### ISSUE TITLE
[Bug]: Channel awaiting payment

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1019]
### Describe the bug

I had a pending transaction. Opened a channel with local balance through a [CPFP transaction](https://mempool.space/tx/1cb023b2e2365654b709e709380e1bb24952bb7830f7695b85031a6b6a0bdd29) using the quick setup. After 36 confirmations, the on-chain funds sent to Blocktank haven't moved, the channel is still "awaiting payment", and the suggestion card doesn't display "Transferring: Ready in ±20 min" anymore.

### Screenshots / Recording

![A9F7605B-316E-4896-807F-D83C533CED7A_1_102_o](https://user-images.githubusercontent.com/93796166/236343375-3567b5f0-6e4c-4c41-8c22-a960d57c2224.jpeg)
![767B3B15-DBAC-4325-AE89-413C5FA57645_1_102_o](https://user-images.githubusercontent.com/93796166/236343422-f85d9969-94fe-4e7d-845f-88d24d07dc6c.jpeg)

### Operating system

iOS 16.5

### Bitkit version

44

**Comment by JeanlChristophe** [comment]
Hi Matt
Which version are you using?

**Comment by mattcrv** [comment]
> Hi Matt Which version are you using?

44

**Comment by pwltr** [comment]
This is a known bug with Blocktank. I think we can close this here or move this to the Blocktank repo?

**Comment by JeanlChristophe** [comment]
I am closing the ticket and moved to Blocktank https://github.com/synonymdev/blocktank-client/issues/35
