### ISSUE TITLE
[Bug]: App crashed when adding/editing/deleting contact

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1020]
### Describe the bug

The app seems to crash in a couple scenarios when dealing with contacts:
- adding a contact makes the added contact's application crash
- editing a contact crashes the app
- deleting a contact crashes the app
- trying to use slashpay crashes the app (maybe also contact's)

Note: remote contact was online while testing

#### Scenario 1:
On two different devices, the application crashed when we tried to delete a contact. After reopening the application, the contact was not deleted. We tried again and the contact was successfully deleted.

Contacts: 
slash:ui5wxjkcynxjqtkyfpjorak717tdppjggyt34meu3eciicy6r4yy
slash:cronhh8adonxidrria9xfzyp7j4zsu8h9jux37n9hdzypartuxeo

#### Scenario 2:
Once contact is imported, we attempt to change the name of the contact manually, then the app crashes either when we attempting to do that (i.e. whilst we are on the contact profile page) or once the new name saved on local app and we were guided back to the Contacts Menu Page.

#### Scenario 1:
1. Go to 'Contacts'
2. Click on 'one of you contact'
5. Deleted your contact
6. App crashes

#### Scenario 2:
1. Go to 'Contacts'
2. Click on 'Edit Name (once imported already)'
3. App crashes

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/8538369/19a9695a-fc72-4e32-ad15-16dabae4d2fa" width="33%" />

### Operating system

iOS & Android

### Bitkit version

51

### Log output

```
Thread 79: "Unhandled JS Exception: TypeError: Cannot read property 'byteLength' of undefined, js engine: hermes, stack:
compare@222136:24
_handleServerConnection@238808:80
emit@46559:18
onConnection@242071:13
onConnection@241217:36
emit@46559:18
recv@231293:38
_recv@231249:34
_decode@231567:23
_ondata@231543:22
emit@46559:18
drain@229411:71
update@229418:18
updateReadNT@229562:15
tryCallOne@53:15
anonymous@139:26
anonymous@14769:25
_callTimer@14699:16
_callReactNativeMicrotasksPass@14721:16
callReactNativeMicrotasks@14881:43
__callReactNativeMicrotasks@4227:45
anonymous@4117:44
__guard@4211:14
flushedQueue@4116:20
callFunctionReturnFlushedQueue@4101:32
```

**Comment by limpbrains** [comment]
I can't reproduce this on the latest Bitkit. I've tested iOS and Android, also tried the Contacts that you provide.
We now have deleting contact in our e2e tests and they are working just fine.
I suggests to re-test this issue

**Comment by pwltr** [comment]
Maybe related to contacts, or more general hyperswarm. Had the app crash in development with the following error:

<img src="https://github.com/synonymdev/bitkit/assets/8538369/19a9695a-fc72-4e32-ad15-16dabae4d2fa" width="33%" />

**Comment by JeanlChristophe** [comment]
The app crashed 10 times today when using contacts or reset the wallet

**Comment by pwltr** [comment]
> Maybe related to contacts, or more general hyperswarm. Had the app crash in development with the following error:
> 
> <img alt="" width="33%" src="https://user-images.githubusercontent.com/8538369/238721443-19a9695a-fc72-4e32-ad15-16dabae4d2fa.png">

Got the above error twice today, fairly sure this would be the cause of the crashes people are seeing in production. As others have said this happens randomly, no real pattern. I only have a profile with a name, no widgets / contacts.

EDIT: tracked down to [this line](https://github.com/holepunchto/hyperswarm/blob/6193265af36dea94af7167446df29ef8a1400eba/index.js#L246)

**Comment by limpbrains** [comment]
@Nuhvi any ideas what could have triggured this?

**Comment by Nuhvi** [comment]
Honestly know, this suggests that somehow, what is supposed to be a private Hyperswarm function was called with a malformed input.

I will double check to see if I called this function or anything upstream manually. 

@pwltr can you share the commit you are working on, and if you have uncommitted changes to yarn.lock?

**Comment by pwltr** [comment]
I'm on master currently, but have not clean installed dependencies, so this could be the issue on my end. Will do that and see if the error pops up again.

**Comment by limpbrains** [comment]
I was able to reproduce this issue. 
I'm on the current master.
I've created a profile on first bitkit instance, then I've tried to add it as a contact on second, at this moment first one throwed 

`Unhandled JS Exception: TypeError: Cannot read property 'byteLength' of undefined`

```
Thread 79: "Unhandled JS Exception: TypeError: Cannot read property 'byteLength' of undefined, js engine: hermes, stack:
compare@222136:24
_handleServerConnection@238808:80
emit@46559:18
onConnection@242071:13
onConnection@241217:36
emit@46559:18
recv@231293:38
_recv@231249:34
_decode@231567:23
_ondata@231543:22
emit@46559:18
drain@229411:71
update@229418:18
updateReadNT@229562:15
tryCallOne@53:15
anonymous@139:26
anonymous@14769:25
_callTimer@14699:16
_callReactNativeMicrotasksPass@14721:16
callReactNativeMicrotasks@14881:43
__callReactNativeMicrotasks@4227:45
anonymous@4117:44
__guard@4211:14
flushedQueue@4116:20
callFunctionReturnFlushedQueue@4101:32
"
```

**Comment by Nuhvi** [comment]
OK, on it.

**Comment by Nuhvi** [comment]
Confirm, at no place do we -at any place in our code base- call `Hyperswarm._handleServerConnection` manually, so the `conn.publicKey` and `conn.remotePublicKey` should be defined by Hyperswarm and its submodules.

on the other hand, I can't replicate this with any Slashtag URL mentioned in this issue, nor with other Slashtags I create on Bitkit (46), and add then delete on IOS simulator (master branch), nor the other way around.

**Comment by JeanlChristophe** [comment]
I replicated it again from another version (v49) and with a new seed. It crashes all the time even after restart my phone, uninstalled Bitkit.

I can share with you me seed.

**Comment by JeanlChristophe** [comment]
slash:qkn8716sumjkxam9dzfy8ytthr5x7cpas9ghojziao4ee7ht6ery

**Comment by JeanlChristophe** [comment]
Fixed with https://github.com/synonymdev/bitkit/pull/1097

**Comment by pwltr** [comment]
@JeanlChristophe Are you sure this is fixed? I don't see how the PR you linked would relate to this issue.

**Comment by JeanlChristophe** [comment]
With the new version, the application no longer bugs on my side. With @Jasonvdb, we were able to identify that this should be due to your fix. If not, can I reopen it so you can keep an eye on it?

**Comment by JeanlChristophe** [comment]
Issue fixed
