### ISSUE TITLE
[Bug]: Price widget not updating

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1021]
### Describe the bug

On two devices, the price does not update, even after 3 min.
Tested with EUR and USD

### Reproduce

1. Go to 'add widget'
2. Click on 'Bitcoin price'
3. See error

### Operating system

IoS, Graphene OS

### Bitkit version

44

**Comment by JeanlChristophe** [comment]
It's updating now. Not sure if I should close this ticket. @Nuhvi could you have a look?

**Comment by Nuhvi** [comment]
@JeanlChristophe I can not replicate neither on 45 Bitkit version (simulator), nor my Android version 43, nor on the [playground](https://slashtags.to/playground/price)

**Comment by JeanlChristophe** [comment]
Thanks.

**Comment by JeanlChristophe** [comment]
With v95 the price widget doesn't update even after 5min. Same for bitcoin Blocks after 20min.

The price is updated only after I force close the app. But the wodget isn't updated.

same for Pav @thisispav

**Comment by JeanlChristophe** [comment]
Fixed
