### ISSUE TITLE
[Bug]: LN Market widget

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1022]
### Describe the bug

I have successfully connected the LNmarket widget from my computer.

However, once the widget is installed and I click on "Sign-In", I get a page redirected to the link https://lnmarkets.com/login/slashtag?token=8AEJ3oKfb9qDLE8kIKMqK4VMtN73MgTNGvL3WdC0QNq6tfrRoFidkw

However the web page is black. Only on GrapheneOS with Vanadium. On IoS it's working perfectly.

### Reproduce

1. Go to 'https://lnmarkets.com'
2. Click on 'Slashtags auth'
3. Accept ToS
4. Go to Bitkit App and LNM Market Widget
5. Clock on "Sign-in"
6 See result

### Screenshots / Recording

![Screenshot_20230505-103700](https://user-images.githubusercontent.com/46056211/236414329-003d51f6-fc77-41fd-8e8e-589ae3990868.png)

### Operating system

GrapheneOS

### Bitkit version

V44

**Comment by JeanlChristophe** [comment]
it's working with Stackernews. Only with LNM doesn't work.

**Comment by pwltr** [comment]
This issue would need to be forwarded to the LNMarkets team. It could be that your browser is blocking something that the website is trying to run.
