### ISSUE TITLE
[Bug]: Slashtags Playground: no data

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1023]
### Describe the bug

I can connect to the Slashtags Playground https://slashtags.to/playground/accounts . However my data does not appear

### Screenshots / Recording

![Capture d’écran 2023-05-05 à 10 51 49](https://user-images.githubusercontent.com/46056211/236416171-489eaf85-4a7d-48bd-8aaf-512b12578876.png)

### Operating system

Graphene OS and iOS

### Bitkit version

V44

**Comment by Nuhvi** [comment]
@JeanlChristophe will be solved by https://github.com/synonymdev/synonym-website/pull/55

**Comment by JeanlChristophe** [comment]
Thanks @Nuhvi
