### ISSUE TITLE
[Bug]: View Private Keys on Address Viewer

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1031]
### Describe the bug

If you click on "View Private Key" and then click on another address or a different address type, it keeps displaying the private key for the address viewed initially. To refresh the displayed private key, it's necessary to click "Hide" and then "View" again.

### Operating system

iOS

**Comment by JeanlChristophe** [comment]
Hi Matt,
No sure I understand the problem.
Can you also indicate how to reproduce the issue and the version used? Don't hesitate to put screen shots if needed.
Thank you

**Comment by coreyphillips** [comment]
Thanks @mattrdec! I'm able to replicate this issue on my end as well. Fix incoming.
