### ISSUE TITLE
[Bug]: Can't open channel: fee error

### ISSUE THREAD

**Issue by raymondclowe** [synonymdev/bitkit-react-native#1050]
### Describe the bug

I tried to open a channel and got this.

```
Unable To Broadcast Transaction

the transaction was rejected by network rules.

min relay fee not met, 79 < 113
```
How do I fix that, and how could the error be easier for a user to understand?

### Reproduce

Any attempt to open a channel does this.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/c8a9ae17-6ca6-46e0-977a-f4faa0dc3031

### Operating system

Android

### Bitkit version

1.0 (46)

**Comment by pwltr** [comment]
This error means that you were unable to afford the transaction fee required for the channel purchase. As of right now the fee for the channel purchase is roughly 5$ (transaction fee + about $0.30 Blocktank fee). You can try opening a smaller channel or add more onchain funds to your wallet. We're working on improving the UX to avoid this case.
