### ISSUE TITLE
[Bug]: Can't retrieve the contact information

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1063]
### Describe the bug

Trying to add this contact but no information is retrieved: slash:wcgdqogzesiuyqtdrj31c5ow88iqbxigo6pexw9ud1dtk3bnwqdo

Tried from different accounts but it worked with v46 not with v47.

### Screenshots / Recording

![File (1)](https://github.com/synonymdev/bitkit/assets/46056211/d1e28d54-2fca-4ddf-aa7d-0a748ae7a360)

<img width="319" alt="Capture d’écran 2023-05-24 à 14 53 50" src="https://github.com/synonymdev/bitkit/assets/46056211/84a7c85b-6950-4309-a1e7-e1325e5579db">

### Operating system

iOS

### Bitkit version

v47

**Comment by Nuhvi** [comment]
Resolved for me just fine, either they had an earlier version of your profile, so they detected a fork (probably you restored bitkit at some point), or your Bitkit was closed, but the seeder detected a fork so it no longer replicate yor drives.

![Screenshot_20230524-163920_Bitkit](https://github.com/synonymdev/bitkit/assets/40009100/1d8921be-374f-4bfc-a164-56a1d68e4cc8)

**Comment by JeanlChristophe** [comment]
Indeed the seeder status is "behind by -9blocks"

**Comment by JeanlChristophe** [comment]
Update. Now the seeder status is "behind by -2blocks".

I can find my profile with the Playground when bikit is open but not when I'm offline.

**Comment by BitcoinErrorLog** [comment]
If the profile is forked, what is the UX for resolving the problem?

**Comment by JeanlChristophe** [comment]
Alas, I'm afraid there's no solution. Once the profile is forked, it's impossible to solve. However, with the new architecture of Slashtags v2, this type of problem should no longer occur.

Unless you have a solution in mind?

**Comment by Nuhvi** [comment]
Same as https://github.com/synonymdev/bitkit/issues/951

**Comment by JeanlChristophe** [comment]
Issue fixed
