### ISSUE TITLE
[Bug]: App freez when reset wallet

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1067]
### Describe the bug

I started a new wallet and backup my seed. When I tried to reset the wallet but the app freez. 
I Needed to close the app and restart it.

### Reproduce

1. Go to 'Setting'
2. Click on '.backup and restore wallet'
3. Click on '.Reset wallet'

### Screenshots / Recording

<img width="323" alt="Capture d’écran 2023-05-26 à 10 27 50" src="https://github.com/synonymdev/bitkit/assets/46056211/78bc0754-88bf-4987-931e-bdfa63c44ee3">

### Operating system

Graphene OS

### Bitkit version

v47

**Comment by pwltr** [comment]
This has been fixed already, see https://github.com/synonymdev/bitkit/issues/937

**Comment by JeanlChristophe** [comment]
@pwltr nope, we tried it again today with le latest version v47

**Comment by pwltr** [comment]
The fix probably didn't make it into the latest build yet. We can leave this open for now but it is most likely [fixed](https://github.com/synonymdev/bitkit/pull/1055).

**Comment by pwltr** [comment]
@JeanlChristophe Can you add a recording of the behaviour you're seeing? Does the application freeze or crash? Here is how it should look:

https://github.com/synonymdev/bitkit/assets/8538369/ef59818f-f3b4-4c6d-aded-8eb00304f408

Can you please confirm you are running the latest version v49?

**Comment by JeanlChristophe** [comment]
Sorry I can't record, I can't use the app due to another bug.
The app freez when at click to "OK" at 0,9"

**Comment by thisispav** [comment]
tested with **iPhone 6S Pro** - after app installation, I went to Settings > Back Up and Restore > Reset Wallet - first time it worked. 

**The 2nd time** I re-tested using the same flow (i.e. create new wallet, go to Settings and Reset wallet - **app crashed**) - **was not prompted** to send a crash report.
**Tested 3rd time** - no issues 
**Tested 4th time** - no issues
**Tested 5th time** - no issues

uninstalled the app, re-installed again
Proceeded to create new wallet and subsequently reset the wallet 
1st attempt - no issues
2nd attempt - no issues

fwiw, in any of the testing attempts, I did **NOT** switch to other tabs, let the app to sit idle etc. 

tested with **Pixel 6A (running on Graphene)** 
1st attempt - no issues
2nd attempt - no issues

uninstalled the app and reinstalled again

3rd attempt - no issues
4th attempt - no issues 

no freezes, crashes or lags. Works pretty smooth
