### ISSUE TITLE
[Bug]: App crashes when attempting to change the name of a contact 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1070]
### Describe the bug

Once contact is imported, we attempt to change the name of the contact manually, then the app crashes either when we attempting to do that (i.e. whilst we are on the contact profile page) or once the new name saved on local app and we were guided back to the Contacts Menu Page. 

Note: remote contact was online (during testing session)

### Reproduce

1. Go to 'Contacts'
2. Click on 'Edit Name (once imported already)'
3. See error

### Operating system

iPhone 6S 

### Bitkit version

v47

**Comment by thisispav** [comment]
[testing session bug - bitkit_ldk_logs_1685093166914.zip](https://github.com/synonymdev/bitkit/files/11573678/testing.session.bug.-.bitkit_ldk_logs_1685093166914.zip)

**Comment by Nuhvi** [comment]
So far I couldn't replicate this bug, however hopefully this [PR](https://github.com/synonymdev/bitkit/pull/1085) will reset the situation enough that all dependencies are updated and we can test again after that.

**Comment by pwltr** [comment]
This seems to be the same issue as https://github.com/synonymdev/bitkit/issues/1020. Updated the description there and closing here.
