### ISSUE TITLE
[Bug]: Spending balance is zero even after receiving sats

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1073]
### Describe the bug

After opening a first channel, I received 2 times 2 sats. But I can't send it back to the sender. When checking into "Lightning connections", spending balance is 0.

Then I received : 
- 1000 sats (and I couldn't send back 2 sats)
- 1000 sats (and I couldn't send back 2 sats)

After that I could send 5 sats with success

[bitkit_ldk_logs_1685102844095.zip](https://github.com/synonymdev/bitkit/files/11575047/bitkit_ldk_logs_1685102844095.zip)

### Screenshots / Recording

![Screenshot_20230526-134920](https://github.com/synonymdev/bitkit/assets/46056211/6481ab2c-8170-45f8-ae9d-6edc4c8dddf1)
![Screenshot_20230526-134103](https://github.com/synonymdev/bitkit/assets/46056211/486fda1d-0fba-4de2-bf34-ac89a8fdfbf3)
![Screenshot_20230526-134119](https://github.com/synonymdev/bitkit/assets/46056211/e12fe1c8-ff27-47ea-a0c9-15911a13c2e5)

### Operating system

Graphene OS

**Comment by JeanlChristophe** [comment]
I think it's because my reserv balance was too small. Could you confirm that's more a UX bug than a LN issue? Thanks

**Comment by pwltr** [comment]
Yes seems likely that this is because of your balance being below reserve amount, we've added a bit of UI to show this a few days ago, see https://github.com/synonymdev/bitkit/pull/1052. Not sure if this made it into the build you are testing.

**Comment by JeanlChristophe** [comment]
thanks
