### ISSUE TITLE
[Bug]: LNM widget missing logo

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1075]
### Describe the bug

After being connected, I can see the widget on Bitkit but the logo is missing

### Screenshots / Recording

![Screenshot_20230526-151335](https://github.com/synonymdev/bitkit/assets/46056211/64f7c6c4-6f48-4d99-902c-f328acc0eb97)

### Operating system

iOS and GrapheneOS

### Bitkit version

v47

**Comment by limpbrains** [comment]
works fine now

**Comment by limpbrains** [comment]
works fine now

**Comment by limpbrains** [comment]
works fine now
