### ISSUE TITLE
[Bug]: Unable to make deposit to LNMarkets 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1076]
### Describe the bug

error occurring whilst attempting to make deposit (1001 sats) to LNMarkets via Bitkit 
please refer to pictures for detailed view of error and Bitkit balance

[pav bitkit_ldk_l
![photo_2023-05-26_16-19-15](https://github.com/synonymdev/bitkit/assets/119061223/d0cd7c89-9acd-43ed-84d6-1433bb2fd1a0)
![photo_2023-05-26_16-19-17](https://github.com/synonymdev/bitkit/assets/119061223/34d64b81-c2d5-49d4-8f04-9f1e465889f5)
![photo_2023-05-26_16-19-18](https://github.com/synonymdev/bitkit/assets/119061223/7520ddd9-ca46-4c8a-84dd-85dd95db2610)
ogs_1685107361265.zip](https://github.com/synonymdev/bitkit/files/11575642/pav.bitkit_ldk_logs_1685107361265.zip)

### Reproduce

1. Go to 'LNmarkets'
2. Click on 'login using Slashtags'
3. Scroll to "Deposits" and try and make a deposit of 1001 sats > request invoice > make payment via Bitkit

### Operating system

iPhone 6S 

### Bitkit version

v47

**Comment by limpbrains** [comment]
[pav bitkit_ldk_logs_1685107361265.zip](https://github.com/synonymdev/bitkit/files/11635203/pav.bitkit_ldk_logs_1685107361265.zip)
