### ISSUE TITLE
[Feature]: repo about section and official link

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#1078]
### Describe the problem

I was sharing the link to the Bitkit repository and I noticed that there was no description in the link embedded in slack. 
When sharing the mempool repository, for example, the correct description of the "about" session appears in the embedded link.
I asked @JWBurgers to write a text for us to put in this "about" section.

There is also an official link that you can add to you repo, we could point that to https://bitkit.to/

### Describe the solution

Here is our suggestion to the about section:

Take charge of your digital life with Bitkit. A non-custodial Bitcoin and Lightning wallet that also supports profiles, contacts, payments to contacts, key-based logins, widgets, and more.

## Preview images (context)

mempool embedded link with description:
![image](https://github.com/synonymdev/bitkit/assets/5798170/210a7616-713c-4af3-94b0-1c5e3bd6a28f)

bitkit embedded link without description:
![image](https://github.com/synonymdev/bitkit/assets/5798170/decb6ead-fd08-4476-89ea-69d818d221c6)

bitkit about section
![image](https://github.com/synonymdev/bitkit/assets/5798170/6516f49c-e697-423f-9565-1a8a64c80e33)

mempool about section
![image](https://github.com/synonymdev/bitkit/assets/5798170/7f826a5b-c6af-4a0d-8ba3-62755b34eebf)

**Comment by Jasonvdb** [comment]
Done 👍

**Comment by MiguelMedeiros** [comment]
@Jasonvdb Thanks!! 👍 

![image](https://github.com/synonymdev/bitkit/assets/5798170/41a22b76-ee87-4960-9a33-89275f3c2fe9)
