### ISSUE TITLE
Swap from saving balance to spending balance

### ISSUE THREAD

**Issue by Chiquiluqui** [synonymdev/bitkit-react-native#1084]
Once the swap has been completed the funds are not shown in the spending balance after the confirmations ![image](https://github.com/synonymdev/bitkit/assets/87268424/1f9a118e-91da-48cd-b443-5f7c58195a64)

**Comment by pwltr** [comment]
Hey, sorry about that. Can you please navigate to `Settings > Advanced > Lightning Connections` and tap on the first item, it will show the status of your channel and at the bottom you can find a 'Support' button. If the status is either 'Awaiting Payment' or 'Order Expired' please use this button to send us an email and you will be issued a refund.

In the case your connection status is 'Open' please let me know so we can debug further.

**Comment by Chiquiluqui** [comment]
Hey, 
Thanks for the reply and the app is great I thought to better bring this to your attention.

In regards to the mentioned: Yes, appears a awaiting payment but the support button does not work when I press it ![image](https://github.com/synonymdev/bitkit/assets/87268424/97930030-8c79-4aff-8475-9a2bc8aa1629)

**Comment by pwltr** [comment]
Thanks yeah looks like we need to fix the button as well here. Do you have an email app installed on your phone? Because this button will open your email app and add a message for you.

In any case if it doesn't work please just send this screenshot to [support@synonym.to](mailto:support@synonym.to) and that will have everything the team needs.

**Comment by Chiquiluqui** [comment]
Great! I have sent the email already thank you.

Just in case yes I do have an apps emails in my mobile phone but the support button didn't do anything tho

Thanks once again for having a look.
