### ISSUE TITLE
[Bug]: Support button not working 

### ISSUE THREAD

**Issue by bonomat** [synonymdev/bitkit-react-native#1095]
### Describe the bug

Under settings->about one can find a support button. 

Unfortunately it’s not doing anything :) 

### Reproduce

1. Go to 'settings' (right top corner)
2. Click on 'About BitKit'
3. Click on ‘Support’
4. Nothing happens 

### Operating system

iOS 16.4.1

### Bitkit version

1.0 (64)

**Comment by coreyphillips** [comment]
Thanks for the issue! PR created [here](https://github.com/synonymdev/bitkit/pull/1102).
