### ISSUE TITLE
[Bug]: Fees only appear in Fiat, not in sats

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1128]
### Describe the bug

It doesn't matter if I select the way I want the amounts to appear (Fiat, Sats or BTC), it appears all the time in Fiat.

Ex: when we look at the activity or in the transaction details.

### Screenshots / Recording

![Screenshot_20230623-133336](https://github.com/synonymdev/bitkit/assets/46056211/9f22f059-a56c-4206-8ca0-d8f9e1ab14f7)
![Screenshot_20230623-133449](https://github.com/synonymdev/bitkit/assets/46056211/0f432bab-171f-4453-9043-9212d3ec9d54)

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v54

**Comment by trigger-xyz** [comment]
Hi,
I was looking for a "good first issue".
This one seems qualified, I'd like to work on it if nobody does!

**Comment by JeanlChristophe** [comment]
Please go ahead, thanks

**Comment by JeanlChristophe** [comment]
Comment: regarding the history, it's not the fees you see below the main value but the conversion to fiat.

Here is the model drawn by our designer for the fees  
![Transaction Lightning](https://github.com/synonymdev/bitkit/assets/46056211/90cf9116-1355-4390-8e7e-63c7e7b9ae63)

**Comment by JeanlChristophe** [comment]
There is no fee anymore

<img width="379" alt="Screenshot 2023-08-04 at 14 19 11" src="https://github.com/synonymdev/bitkit/assets/46056211/cc318f84-78cf-4c64-a40d-79a930751666">

**Comment by JeanlChristophe** [comment]
+ it should be "Explore and not Connection"
![image](https://github.com/synonymdev/bitkit/assets/46056211/42f69758-8a1c-4d5d-847c-6102ef54edef)

**Comment by limpbrains** [comment]
> There is no fee anymore

for old transactions we don't have this information, that is why we are not showing it.

Other issues are fixed in #1194
