### ISSUE TITLE
[Bug]: App crashes when attempting to restore wallet with an open LN channel

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1130]
### Describe the bug

app crashes when I try and restore wallet with an active LN channel. see screenshots and video

### Reproduce

1. Go to 'Settings'
2. Click on 'Back up and Restore Wallet' - make sure you have an open LN channel before you do back up and restore
3. Scroll down to ' Back up wallet ' then reset and try to restore

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/1c356d57-9b0e-4d12-a03c-e7fa69b234d5

https://github.com/synonymdev/bitkit/assets/119061223/bd0c8eff-10d9-4127-a633-b3f18234602e

![photo_2023-06-23_15-40-27](https://github.com/synonymdev/bitkit/assets/119061223/04181286-a695-40f4-b8cd-58e0ee2a1c1b)

### Operating system

iPhone 6S Plus

### Bitkit version

v53

**Comment by JeanlChristophe** [comment]
I have the same issue, After trying to enter my seed, the application crashed everytime it loaded.


https://github.com/synonymdev/bitkit/assets/46056211/5ec5e473-fae2-4017-8cb7-e8ccbf7f978a
