### ISSUE TITLE
[Bug]: Pulsing animation remain displayed

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1162]
### Describe the bug

I carried out two operations: 
1. I transferred my money from Spending to Saving. Everything went smoothly. However, the animation is still displayed (even at +3 days). However, the channel has been closed.

2. After closing my channels, I decided to switch my sats back from Saving to Spending. Once the operation had been carried out successfully, the animation was still displayed, even though I had subsequently been able to send sats via LN to another wallet.

[bitkit_ldk_logs_1689578610751.zip](https://github.com/synonymdev/bitkit/files/12066894/bitkit_ldk_logs_1689578610751.zip)

### Screenshots / Recording

![Screenshot_20230717-091349](https://github.com/synonymdev/bitkit/assets/46056211/cf968250-4bf5-4348-8c97-eb16624a5b36)
![Screenshot_20230715-231905](https://github.com/synonymdev/bitkit/assets/46056211/3cc87929-a112-4120-ab96-0c23e1fdc8fe)
![Screenshot_20230715-231855](https://github.com/synonymdev/bitkit/assets/46056211/dba0ae3f-678a-4e67-8eab-6885d4581552)

https://github.com/synonymdev/bitkit/assets/46056211/7a175be4-6377-4256-baae-fc8422e58e24

### Operating system

GrapheneOS

### Bitkit version

v59

**Comment by JeanlChristophe** [comment]
it will be probably be fixed by https://github.com/synonymdev/bitkit/issues/1007

**Comment by JeanlChristophe** [comment]
I'm reopening this ticket, the pulsing animation remains even though the whole process of creating a channel has been completed.

note: this does not happen every time

![Screenshot_20230817-120201](https://github.com/synonymdev/bitkit/assets/46056211/b30f736f-abdf-4fc7-ab69-283d00599d6b)

**Comment by coreyphillips** [comment]
I'm able to reproduce this when opening a channel as well. Once the channel is fully open the "Setting Up - Opening" block remains. @pwltr 

![Simulator Screenshot - iPhone 14 - 2023-08-18 at 08 42 15](https://github.com/synonymdev/bitkit/assets/8532651/a095ea6a-0bee-4cfb-85e2-8e7aab699a7b)

**Comment by coreyphillips** [comment]
Same thing happens when opening a channel from a personal node as well.

**Comment by pwltr** [comment]
This issue is a consequence of the LDK events sometimes not firing: https://app.asana.com/0/1189635884316057/1204512154618288/f

Bitkit is relying on them so it knows when a channel is in the process of opening or has been closed.
See https://github.com/synonymdev/bitkit/blob/9a15c50fbe57bd5e801089414befc2a1089810d0/src/utils/lightning/index.ts#L352

If we can't rely on those events to fire we need to find a different way to let Bitkit know about channel states. This also goes for force-closes, we need a way to differentiate between coop and force-closes. @Jasonvdb

**Comment by Jasonvdb** [comment]
Yeah these RN events often get missed for some reason still. What about checking all ldk channels and if there are non pending confirmation then remove the animation?

As for force closed channels ldk.claimableBalances(false) can be used. This will list all the funds waiting to be claimable after a channel close. 
[confirmation_height](https://github.com/synonymdev/react-native-ldk/blob/dc345d9bf6741ccfc8c96395d5a264dbd01b37c1/lib/src/utils/types.ts#L407)  can be used to tell the user when they'll get their funds. Would that work or do you need to be able to specifically query which channels were force closed?
