### ISSUE TITLE
[Bug]: Crash when tapping "Receive" on Testnet

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1176]
### Describe the bug

When I change Bitkit to Testnet and tap "Receive", the app crashes. It started working after a while, but still crashes when I switch to mainnet and back to testnet.

### Operating system

iOS 17

**Comment by pwltr** [comment]
Unable to reproduce this so far. At any rate regular users shouldn't be switching networks as this setting is hidden in developer menu.

**Comment by pwltr** [comment]
While hunting down another issue I ran into this now too. On iOS if you try to generate an LN invoice with a note containing an emoji the app will crash. In the current release "Receive" will be broken indefinitely after that. @mattrdec Was that what you were running into as well?

https://github.com/synonymdev/bitkit/assets/8538369/8f960a37-01d4-49ce-9c03-be0efbb4139e

**Comment by mattrdec** [comment]
The app crashes before the receive modal opens, so it's not the same issue as the emoji one. Also, the crash doesn't last indefinitely after it. If I switch networks and wait before pressing receive, the app doesn't crash.

It's a very specific edge case, but I can still reproduce it:

https://github.com/synonymdev/bitkit/assets/93796166/0d61c548-d87c-41ef-9a44-2e551c85ec56
https://github.com/synonymdev/bitkit/assets/93796166/c66f7597-6470-4d1a-952e-03643735841c

**Comment by mattcrv** [comment]
The app crashes before the receive modal opens, so it's not the same issue as the emoji one. Also, the crash doesn't last indefinitely after it. If I switch networks and wait before pressing receive, the app doesn't crash.

It's a very specific edge case, but I can still reproduce it:

https://github.com/synonymdev/bitkit/assets/93796166/53d51acf-0edb-4652-9f45-aeddd78cc8a7

**Comment by Jasonvdb** [comment]
Stripping emojis from iOS invoices temporally until fixed properly in LDK https://github.com/synonymdev/react-native-ldk/pull/159
