### ISSUE TITLE
[Bug]: Activity order wrong when paying w/ Lightning

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1182]
### Describe the bug

Sometimes after sending a transaction with Lightning the transaction is not a the top of the activity list.

### Reproduce

1. Send/receive a few Lightning payments
2. See activity list

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/46056211/5085553f-ec36-4c04-89b3-5aac189b2d29" width="33%" />

### Operating system

Android

### Bitkit version

61

**Comment by JeanlChristophe** [comment]
![Screenshot_20230804-144533](https://github.com/synonymdev/bitkit/assets/46056211/5085553f-ec36-4c04-89b3-5aac189b2d29)

**Comment by JeanlChristophe** [comment]
@pwltr do you still have this issue with v63?
