### ISSUE TITLE
Discrepancy with Lightning State Channel

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1183]
### Describe the bug

I received a notification that the LN channel opening was successful in Bitkit. Tried to send funds from Breez and Phoenix to no avail. There seems to be a discrepancy in Bitkit with regards to the channel state (see screenshots and logs for more info).

**Node ID**
028cd4c1659a94a9f080e5b302a2df78fe9deba9ef15d3c2696421c00778e25b45

**Order ID**
64cccdb70142d40b74f89ae2

### Reproduce

1. Purchase a channel
2. Wait for the process to complete (Notification: "Instant payments ready...")
3. Check if channel is actually open

### Screenshots / Recording

![photo_2023-08-04_14-54-26](https://github.com/synonymdev/bitkit/assets/119061223/54022dc9-d961-4fa5-abfa-9020d926eefe)

[bitkit_ldk_logs_1691150854058.zip](https://github.com/synonymdev/bitkit/files/12260511/bitkit_ldk_logs_1691150854058.zip)

### Operating system

iOS, Android

### Bitkit version

v61

**Comment by thisispav** [comment]
![photo_2023-08-04_15-10-56](https://github.com/synonymdev/bitkit/assets/119061223/5e2cbb8d-06dd-46cc-a680-94c6b22caf6b)

**Comment by thisispav** [comment]
![photo_2023-08-04_15-21-19](https://github.com/synonymdev/bitkit/assets/119061223/32816f60-eaaa-41e3-9af1-ff0d4faf88f9)

**Comment by pwltr** [comment]
Blocktank says the channel is open: https://blocktank.synonym.to/api/v1/channel/order?order_id=64cccdb70142d40b74f89ae2

**Comment by thisispav** [comment]
Upon inspecting the wallet and the channel state - now Bitkit shows that my channel is opened. I was able to send and receive sats using Lightning. Fwiw in the channel history under Lightning Connections there is still a "Closed and Failed" channel with the same spending amount

**Comment by Jasonvdb** [comment]
I think the channel list state might not be updating until app is restarted
