### ISSUE TITLE
[Bug]: Failed payment appearing in the activities

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1186]
### Describe the bug

I made two payment attempts, and both failed. Yet, they're showing up in my activities even though the balance wasn't actually deducted. The payment went through on my first attempt at Phoenix.

### Screenshots / Recording

![IMG_1983](https://github.com/synonymdev/bitkit/assets/93796166/ca7ff8e2-737e-4bcc-a4ac-087a45bfa7d8)
![IMG_1984](https://github.com/synonymdev/bitkit/assets/93796166/f46537ba-01d8-4871-9857-d86845a6987d)
![IMG_1985](https://github.com/synonymdev/bitkit/assets/93796166/abdf1bd5-95f7-47bf-a5d5-ccd7c20ce269)

### Operating system

iOS 17

### Bitkit version

61

**Comment by pwltr** [comment]
Adding a screen recording and some logs here, payment from Bitkit to Bitkit is failing, interestingly it works in the other direction.

https://github.com/synonymdev/bitkit/assets/8538369/1635f14e-dd67-493a-9c26-436a3b553848

```
 LOG  onChannelManagerPaymentPathFailed: {"short_channel_id":"12190285417218048","payment_failed_permanently":false,"path_hops":[{"pubkey":"03b9a456fb45d5ac98c02040d39aec77fa3eeb41fd22cf40b862b393bcfc43473a","cltv_expiry_delta":80,"fee_sat":1,"short_channel_id":"12206778091634688"},{"short_channel_id":"12190285417218048","cltv_expiry_delta":144,"pubkey":"02bfe302bbcb00749efa4e5e478b0e547f2d829960cd1d17bcdccf6a9f9693a1d5","fee_sat":21}],"payment_id":"71e48fcbd0c56395cd505eb49e1b8c282baf1c35a0fb89118c5281e094f728e9","payment_hash":"71e48fcbd0c56395cd505eb49e1b8c282baf1c35a0fb89118c5281e094f728e9"}
 LOG  onChannelManagerPaymentFailed: {"payment_hash":"71e48fcbd0c56395cd505eb49e1b8c282baf1c35a0fb89118c5281e094f728e9","payment_id":"71e48fcbd0c56395cd505eb49e1b8c282baf1c35a0fb89118c5281e094f728e9"}
 LOG  [Error: Payment failed]
```

Should have good liquidity:

<img width="759" alt="Screenshot 2023-08-18 at 12 53 05" src="https://github.com/synonymdev/bitkit/assets/8538369/c844cf99-c542-46a1-af41-bed0ba26c115">

**Comment by mattcrv** [comment]
@pwltr, it looks like there was a regression here, this just happened following a CJIT open:

https://github.com/synonymdev/bitkit/assets/93796166/11b47094-540d-4ff2-9afa-d4834354b1cds
