### ISSUE TITLE
[Bug]: Wrong fee for transactions spent from force-closed channel

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1187]
### Describe the bug

I closed a channel and it resulted in a force-close. After the funds became spendable I wanted to move the coins to another wallet. At this point the internal LDK transaction was still unconfirmed (not sure if relevant). Bitkit showed the fee for this transaction as 6sat/vbyte (ok). Then I checked the tx on mempool.space and it showed an effective fee rate of 3sat/vbyte and flagged the tx as a CPFP (descendant) of an unknown tx (ancestor) that had a fee rate of 1sat/vbyte (will be dropped). Looking closer at the second tx the input was a change address owned by me and outputs also included a change addresses and an address unrelated to my wallet. After rescanning addresses in Bitkit the second transaction also shows up in Bitkit activity.

Effectively both of these transaction will be dropped. Bitkit also doesn't let me boost these transaction any further.

### Reproduce

1. Close a channel (maybe needs to be force-close)
2. After funds become spendable, try to move them
3. Check for correct fees on block explorer

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/8538369/d1559f33-3cec-4e00-b0e7-43509e63b49b" width="33%" />
<img src="https://github.com/synonymdev/bitkit/assets/8538369/a31e8091-40d6-4987-a33c-93ba47271888" width="33%" />
<img src="https://github.com/synonymdev/bitkit/assets/8538369/6b720773-7c11-40a3-9d49-8c46515a51bf" width="33%" />
<img src="https://github.com/synonymdev/bitkit/assets/8538369/b59639ae-c326-41f7-94dc-18ff4813878a" width="33%" />

### Operating system

Android

### Bitkit version

62

**Comment by Jasonvdb** [comment]
@pwltr any chance you still have the tx IDs so I can explore a bit?

**Comment by limpbrains** [comment]
partly was fixed here https://github.com/synonymdev/react-native-ldk/pull/162
