### ISSUE TITLE
[Bug]: LNURL-Pay failed

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1203]
### Describe the bug

I get the following error message when trying to scan LNURLp QRs on [BTC Origin Stories](https://btcoriginstories.com/):

> LNURL-Pay failed
> Got a comment with 16 characters, but can only accept 0

And this when trying to donate to [OpenSats](https://opensats.org/):

> LNURL-Pay failed
> Lightning node could not generate invoice with description hash: The HTTP status code of the response was not expected (500).

Working normally on Phoenix.

### Screenshots / Recording

![IMG_946613D08DD3-1](https://github.com/synonymdev/bitkit/assets/93796166/691fa838-5f60-4259-b1c0-a619e3e0cbe3)
![IMG_41634FA2690B-1](https://github.com/synonymdev/bitkit/assets/93796166/c69ce0cb-e500-45a4-8412-94abcf7a4256)

### Operating system

iOS 17

### Bitkit version

61

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/issues/1205

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/issues/1204

**Comment by limpbrains** [comment]
Where can I fund lnurl on opensats? I can only see bolt11 invoice generated by BTCPayServer

**Comment by mattcrv** [comment]
[https://btcpay0.voltageapp.io/i/HLijYpBaL4eYDMUkywef8](https://btcpay0.voltageapp.io/i/HLijYpBaL4eYDMUkywef8)
![image](https://github.com/synonymdev/bitkit/assets/93796166/3ae94326-e3ae-47d9-9546-b126862b7d91)

**Comment by limpbrains** [comment]
Opensats is working for me. I think issue was on there server (500 error) that they have fixed.

**Comment by JeanlChristophe** [comment]
Doesn't work for 3 peoples

**Comment by limpbrains** [comment]
It is not an LNURL issue, any LN invoice doesn't work outside of our BT node
