### ISSUE TITLE
[Bug]: LNURL-Pay only works on the 2nd attempt

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1204]
### Describe the bug

Paying Bitrefill's LNURL-Pay always fails on my 1st attempt, but always works on the 2nd attempt. Could reproduce 3x (see the 3 videos below). Working on the 1st attempt on Phoenix.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/c7253cba-e83f-4acf-9ac8-7ca79a8c8a85

https://github.com/synonymdev/bitkit/assets/93796166/b8f65eba-b401-40d9-aa2d-67c19a97957d

https://github.com/synonymdev/bitkit/assets/93796166/e1c1e6ec-c696-4647-ad8c-ef27c6fc2ce3

### Operating system

iOS 17

### Bitkit version

61

**Comment by limpbrains** [comment]
This is because LDK is not yet fully started and not connected to any peers.
Need to implement syncing screen
