### ISSUE TITLE
[Bug]: LNURL-Pay: invoice_payment_fail_sending

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1205]
### Describe the bug

LNURL-pay is not working on [Lightning Gifts](https://lightning.gifts/).

Getting the following error:
> Error creating transaction 
> invoice_payment_fail_sending

### Screenshots / Recording

![IMG_124C29EB6742-1](https://github.com/synonymdev/bitkit/assets/93796166/813e420a-0e00-4c0b-a24d-3dfad1f88c28)

### Operating system

iOS 17

### Bitkit version

61

**Comment by JeanlChristophe** [comment]
LNURL Pay has been fixed on v94
