### ISSUE TITLE
[Bug]: Crash when restoring

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1209]
### Describe the bug

I have a wallet with an open Lightning connection. I wiped it through the dev settings, generated a new wallet to test a specific feature, and wiped it again to restore the original wallet. Now, I can't restore it: the app keeps crashing on the "Setting up your Wallet" screen. I tried restoring it on build 60 on an Android device, with no success — with the difference that on Android it doesn't crash, it just stays on the "Setting up your Wallet" screen forever. I haven't force-closed the connection yet. Logs are available below.

### Screenshots / Recording

[bitkit_ldk_logs_1692138052063.zip](https://github.com/synonymdev/bitkit/files/12353518/bitkit_ldk_logs_1692138052063.zip)

### Operating system

iOS 17

### Bitkit version

63

**Comment by JeanlChristophe** [comment]
We've been working on this for several weeks now. I'm closing because of duplication https://github.com/synonymdev/bitkit/issues/1130
Thanks for reporting the issue!
