### ISSUE TITLE
[Bug]: Broken amount sent and fee paid after boosting

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1229]
### Describe the bug

After I boosted a transaction, the amount sent and fee paid have decimals and look broken. Closing and reopening the app didn't fix it (see the two first screenshots below).

After a while, the transaction stopped appearing as a "Transfer" and changed to "Sent" (first issue of the list reported on #1185), and then the issue was fixed (see 3rd screenshot).

### Screenshots / Recording

![IMG_013FBDA81851-1](https://github.com/synonymdev/bitkit/assets/93796166/3709a5d6-8aaa-481f-b269-3e8a882e92da)
![image](https://github.com/synonymdev/bitkit/assets/93796166/1eecad2c-fec8-4928-8b3d-1284196699a3)
![IMG_304D388B0716-1](https://github.com/synonymdev/bitkit/assets/93796166/801d665f-b112-43cd-b900-9981595b5f32)

### Operating system

iOS 17

### Bitkit version

64

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/1816
