### ISSUE TITLE
[Feature]: Effective fee rate

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1230]
### Describe the problem

When CPFP'ing, Bitkit only considers the fee rate of the child, not the effective fee rate of the parent and child transactions together.

I CPFP'd a transaction using Bitkit's recommended fee rate (22 sat/vB), but the fee is still too low to be included in the next block because the effective fee rate is still low (14.5 sat/vB): https://mempool.space/tx/6844140d0262d43f4d171089acbce9be0d5428fd06603b302ca73ac611121f5a

Also, the 10-20 minutes shown here feels misleading because it doesn't seem to take into account the effective fee rate:

![image](https://github.com/synonymdev/bitkit/assets/93796166/83e17a11-b980-4285-8e0e-0e7d0a369f5d)

Finally, I'd like to be able to RBF the child transaction instead of getting the greyed-out "Already Boosted" button. It sucks to have my transaction stuck even though I've boosted it with Bitkit's recommended fee.

**Comment by coreyphillips** [comment]
Adding a third row of text on the boost page that calculates the "Effective Fee Rate" would be a great addition.

**Comment by JeanlChristophe** [comment]
Maybe adding a link to the Mempool for the users that don't know what the current fees? @aldertnl

**Comment by aldertnl** [comment]
The calculated recommended fee should consider the effective fee rate of the parent and child transactions imo. We shouldn't expect anything from the user. The user just should be be able to swipe to boost, have high certainty of this action causing his tx being included in the next block, and be done with it.

**Comment by JeanlChristophe** [comment]
Closing this ticket as we don't use anymore CPFP but RBF. Fees indicated are the effective one.
