### ISSUE TITLE
[Bug]: Link profile

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1232]
### Describe the bug

When the "+Add Link" button is tapped several times, it no longer responds.

### Reproduce

1. Go to 'your profil'
2. Click on '+ Add Link' few time
3. See error

### Operating system

Android, iOS

### Bitkit version

v46

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/assets/46056211/a3216d4f-e90f-4e6d-ad97-382759fefa45

Here a video of the issue. Tested with v89 on GrapheneOS

**Comment by JeanlChristophe** [comment]
Fixed

**Comment by limpbrains** [comment]
Can not reproduce
