### ISSUE TITLE
[Bug]: App crashes on Receive screen

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1235]
### Describe the bug

Sometimes instatly, sometimes when I'm trying to copy the address.
No LN channels, wallet is new.
I have Profile and Contacts

### Reproduce

1. Go to Receive
2. Click on copy

### Screenshots / Recording

[bitkit_ldk_logs_1694163720370.zip](https://github.com/synonymdev/bitkit/files/12557669/bitkit_ldk_logs_1694163720370.zip)

https://github.com/synonymdev/bitkit/assets/155891/7ec20d64-cbe9-4649-9cbb-df866516fb94

### Operating system

iOS

### Bitkit version

64

**Comment by pwltr** [comment]
I'm guessing this a bug that only occurs on iOS release builds? I've never seen this issue on Android or on the simulator when developing.

**Comment by pwltr** [comment]
Found the issue here, fix incoming.
