### ISSUE TITLE
[Bug]: Didn't received proper confetti notification of receipt of funds

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1236]
### Describe the bug

I have send onchain funds from Phoenix and Green Wallet. I didn't received notification or modification of the balance until I actualised myself Bitkit.

### Operating system

GrapheneOS

### Bitkit version

v46

**Comment by limpbrains** [comment]
We need to check if Bitkit resubscribes to addresses on electrum reconnect event

**Comment by pwltr** [comment]
> We need to check if Bitkit resubscribes to addresses on electrum reconnect event

I think that happens [here](https://github.com/synonymdev/bitkit/blob/0b1378a640054e8a35ec459e04ab02a80764a067/src/utils/wallet/electrum.ts#L768). Could be that that's not working , or the issue is somewhere else?

**Comment by JeanlChristophe** [comment]
Couldn't reproduce the issue. Same for Pav.

**Comment by JeanlChristophe** [comment]
This issue has been fixed recently.

**Comment by catch-21** [comment]
On 1e714a948f69789cec42936226bfeb43ac8cf5e6 mainnet
I just saw this when two incoming transactions we received whilst Bitkit was closed. On open I saw no confetti but could see the updated savings balance and the two activities listed. Each activity had 10-20 mins to confirm. No confetti was seen on confirm either.

**Comment by limpbrains** [comment]
Do we still have this issue?

**Comment by catch-21** [comment]
@limpbrains We didn't see any issues with confetti in latest testing session using v130. I also have not seen any problems here for the past month of testing development builds on android.

**Comment by catch-21** [comment]
Closing. Feel free to re-opoen if experienced again.
