### ISSUE TITLE
[Bug]: LNM market logo

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1243]
### Describe the bug

LNM logo don't appear with an iOS phone. Ok with a GrapheneOS

### Screenshots / Recording

![Image from iOS](https://github.com/synonymdev/bitkit/assets/46056211/5b9ff407-bead-436a-b021-d3ea17957f5a)

### Operating system

iOS

### Bitkit version

v64

**Comment by JeanlChristophe** [comment]
Can't reproduce this issue on Android. @thisispav can you tried it on iOS?

**Comment by thisispav** [comment]
Just tried logging in with iOS device - logo appears without a problem 
![photo_2023-10-10_16-34-26](https://github.com/synonymdev/bitkit/assets/119061223/9347b4f2-6742-4f7d-bdb3-df13a817cafa)

**Comment by Nuhvi** [comment]
Couldn't replicate it in IOS simulator.

![Simulator Screen Shot - iPhone 14 - 2023-10-13 at 13 08 51](https://github.com/synonymdev/bitkit/assets/40009100/e70ed13e-f195-4475-8019-a57734447642)

**Comment by JeanlChristophe** [comment]
Fixed
