### ISSUE TITLE
Unable to click on Support button under Advanced Lightning Setting

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1252]
### Describe the bug

Using Graphene OS I was unable to submit a ticket for a expired channel in order to get a refund - perhaps we should rethink the flow if we are unable to open the email client - perhaps a web link or some kind of notification.  

Note I don't have an email app on my Graphene OS. 

### Reproduce

1. Go to 'Settings'
2. Click on 'Advanced'
3. Scroll down to 'Lightning Connections > Closed and Expired > Support '

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v64

**Comment by JeanlChristophe** [comment]
Fixed
