### ISSUE TITLE
Fee for Opening a LN channel does not update properly

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1253]
### Describe the bug

when we try and create a LN channel, I navigate to custom setup > Enter Custom Amount > Continue > When selecting different sizes of channel ($250 / $500 or $990) the Receiving Capacity Fee does not update for ANY of the amounts. If a user clicks continue then they will be presented with a different fee (depending on the size of channel they chose) which will lead to confusion. 

### Reproduce

1. Go to 'Open LN Channel'
2. Click on 'Custom Setup > Enter Amount (make note of the fee displayed) > Click continue (see new fee)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v65

**Comment by thisispav** [comment]
just tested this the fee when selecting different liquidity ($250 / $500 / $996) seem to update sometimes with significant lag - if I go back and forth between the screens to select different liquidity it takes a while before the actual cost updates or it doesn't update for a while ... sometimes it shows the exact same cost irrespective of the selected liquidity amount

**Comment by JeanlChristophe** [comment]
When i try to open a channel, fees are not the same following the two steps @limpbrains 

![Screenshot_20231110-143233 (1)](https://github.com/synonymdev/bitkit/assets/46056211/7142455d-ac60-43fd-b45e-b15cb1dc677e)
![Screenshot_20231110-143241 (1)](https://github.com/synonymdev/bitkit/assets/46056211/65963294-06d4-4a18-a0ea-b974dbe9c7d2)
