### ISSUE TITLE
[Bug] Channel opens/closes only after restart

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1261]
### Describe the bug

tried opening a channel - was waiting for 30 min - the channel state said Connection Open but when I switched on Dev Mode the channel was bot Not Usable and Not Ready.

Order ID - Order ID - 12a83f07-fd31-4d37-be52-5ea8c2668f0c

Sev suggested it is a peer connection issue - I tried to refresh the app multiple times, then closed and opened the app and received notification that the channel was finally opened. 

### Screenshots / Recording

| <img width="315" src="https://github.com/synonymdev/bitkit/assets/119061223/c2797d57-6515-4fdd-ad3b-8c83c847d95d"> | <img width="315" src="https://github.com/synonymdev/bitkit/assets/119061223/dbb543d7-7663-4f65-bce9-8a53594b156d"> |
| - | - |

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v66

### Log output

[bitkit_ldk_logs_1695133081875.zip](https://github.com/synonymdev/bitkit/files/12662001/bitkit_ldk_logs_1695133081875.zip)

**Comment by pwltr** [comment]
Experiencing the same issue on occasion. Have to sometimes restart Bitkit for the channel to be opened, refreshing alone is not enough.

**Comment by pwltr** [comment]
Also an issue when closing channels.

**Comment by ovitrif** [comment]
Couldn't repro yet, will keep trying.

**Comment by ovitrif** [comment]
While I couldn't repro this issue yet I noticed an error that was reported twice in the logs:
```js
2023-09-19 23:12:19 ERROR (LDK): Peer sent channel_ready when we needed a channel_reestablish.
  The peer is likely lnd,
  see https://github.com/lightningnetwork/lnd/issues/4006
  (lightning::ln::channelmanager 7085)
```

Just wanted to add it here, even though I'm skeptical this is the cause of the issue. I mean, I wouldn't expect this error to resolve automatically after restart 🤷

**Comment by JeanlChristophe** [comment]
[bitkit_ldk_logs_1709043704903.zip](https://github.com/synonymdev/bitkit/files/14421055/bitkit_ldk_logs_1709043704903.zip)
 here the logs from Pav. he had the same issue

**Comment by Jasonvdb** [comment]
Latest theory is this was caused by electrum issues and may have been resolved in other updates. Restarting allowed it to reconnect and see the funding tx making the channel usable.

**Comment by pwltr** [comment]
Putting this in the backlog again for now, will keep an eye out for this issue.

**Comment by pwltr** [comment]
Seems to be fixed, closing.

**Comment by Jasonvdb** [comment]
Also think maybe it was caused by dropped peer connections. And now we have a patch that reconnects right away if a peer is dropped.
