### ISSUE TITLE
[Bug]: time displayed in the block widget is not correct

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1263]
### Describe the bug

the time displayed in the widget is 15 minutes behind the current time in several time zones

### Operating system

Android and GrapheneOs

### Bitkit version

v66

**Comment by pwltr** [comment]
@JeanlChristophe The time displayed in the block widget is the time the block was mined, not the current time. Does that clear it up?

**Comment by JeanlChristophe** [comment]
Hey make sens. Thanks
