### ISSUE TITLE
[Bug]: LNURL Withdraw from lnbits doesn't work

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1281]
### Describe the bug

IT says decode error

### Reproduce

go to lnbits, generate qrcode, it doesn't work

### Operating system

iOS, Android

### Bitkit version

v70

**Comment by limpbrains** [comment]
same valid

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/assets/46056211/d6db7c12-78cb-4132-ad0f-372d0f62a554

**Comment by limpbrains** [comment]
I was able to send to LN Markets using LN Address 1000 sats and then, after balance was ~3000 sats withdraw 1000 using LNURL-withdraw
