### ISSUE TITLE
[Bug]: In-flight HTLC

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1288]
### Describe the bug

My channel got force closed while there was an in-flight HTLC. Though the closing transaction has many confirmations, the payment that was in-flight is still showing as pending under the spending balance, and the Lightning suggestion card is still showing "transferring".

![IMG_2230](https://github.com/synonymdev/bitkit/assets/93796166/18c5ac33-250a-4e6d-a1ef-449e88fed1fd)
![IMG_2231](https://github.com/synonymdev/bitkit/assets/93796166/3229d69a-0a6d-44e8-a88f-2a65b7332d73)
![IMG_2232](https://github.com/synonymdev/bitkit/assets/93796166/f742ef48-e956-49ad-af52-197093fe57b0)
![IMG_2233](https://github.com/synonymdev/bitkit/assets/93796166/21f62682-684f-4657-b29e-1d8acf4907cc)

### Screenshots / Recording

[bitkit_ldk_logs_1696301903578.zip](https://github.com/synonymdev/bitkit/files/12788045/bitkit_ldk_logs_1696301903578.zip)

### Operating system

iOS 17

### Bitkit version

72

**Comment by pwltr** [comment]
For coop-closes https://github.com/synonymdev/bitkit/pull/1551 should fix this, for force-closes this needs to be improved still (currently blocked) but tracked [here](https://github.com/synonymdev/bitkit/issues/1338).

**Comment by pwltr** [comment]
https://github.com/synonymdev/bitkit/pull/1551 should improve this, regarding inflight HTLCs some testing will be needed to see how the UI behaves and if we need to do something here.

related: https://github.com/synonymdev/bitkit/issues/1338
