### ISSUE TITLE
[Bug]: App unusable on Android

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1300]
### Describe the bug

A user [reported on Twitter](https://x.com/Stromens/status/1711458199969071242) that they weren't able to click any buttons on the latest public release of Bitkit running on Android 12 on a Nothing Phone 1.

I could reproduce it on build 72 running on Android 11 on a Realme C11 2021, and also had severe performance issues (25 seconds to open the app after a wallet has already been created, receive QR loading forever, etc.).

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/1c31fc5b-bff4-4c28-adf0-a5c3322fd5a0

https://github.com/synonymdev/bitkit/assets/93796166/894409de-48a2-43ba-bfa4-8eba0483ca06

### Operating system

Realme C11 2021

### Bitkit version

72

**Comment by JeanlChristophe** [comment]
Ok with v76
