### ISSUE TITLE
[Bug]: No message confirming when the funds arrived

### ISSUE THREAD

**Issue by flaviomoceri** [synonymdev/bitkit-react-native#1303]
### Describe the bug

I used the function to instantly receive the funds without having LN channels open, it worked because the funds arrived in my account, but I did not see any confirmation message that the funds actually arrived

### Reproduce

1. Go to 'Receive'
2. Click on 'Receive instantly'
3. Insert amount and wait the payment
4. Receive funds without any confirmation message

### Operating system

Android 13

### Bitkit version

1.0 (75)

**Comment by limpbrains** [comment]
The issue is because `EEventTypes.channel_manager_payment_claimed` lnd event is not fired.
100% reproducible. 
 - Create new wallet
 - Receive payment using CJIT
 - no event
 
Also this payment is missed in `lm.getLdkPaymentsClaimed();`

https://github.com/synonymdev/react-native-ldk/issues/179

**Comment by limpbrains** [comment]
I was wrong, this is not an LDK issue. #1304 fixed this for me
