### ISSUE TITLE
[Bug]: Activity item for CJIT channel opening is missing

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1304]
### Describe the bug

For 2 devices activity item is missing. We still have activity items for regular LN payments

### Reproduce

1. crate new wallet
2. do CJIT
3. activity item is missing

### Screenshots / Recording

![telegram-cloud-photo-size-2-5275998480390804686-y](https://github.com/synonymdev/bitkit/assets/155891/4645aefa-9326-492b-afb8-49f185867caa)

### Operating system

iOS, Android

### Bitkit version

v74 / 75

### Log output
[bitkit_ldk_logs_1697027947997.zip](https://github.com/synonymdev/bitkit/files/12869836/bitkit_ldk_logs_1697027947997.zip)

**Comment by coreyphillips** [comment]
Unable to reproduce on my end as of the latest [commit](https://github.com/synonymdev/bitkit/commit/bb5491d04a19bfecf450948e60f95c3d95d2c115). 


![Simulator Screenshot - iPhone 14 - 2023-10-12 at 12 43 32](https://github.com/synonymdev/bitkit/assets/8532651/1e7cad8e-1251-4a8e-9087-e5c6ccbe8a0b)

**Comment by coreyphillips** [comment]
However, it's possible the channel state isn't fully updated when `addCJitActivityItem` is called.

PR with a fix incoming.

**Comment by limpbrains** [comment]
closed in #1316
