### ISSUE TITLE
[Bug]: Show correct error when trying to pay onchain with no onchain balance

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1307]
### Describe the bug

I only have LN funds, when I'm trying to pay onchain bitkit shows me "More sats needed to pay this invoice"

Should be something like "There is no enoght savings balance"

### Reproduce

1. OPen LN channel using CJIT
2. Try to send funds to onchain address
3. see an error

### Operating system

iOS

### Bitkit version

v74

**Comment by JeanlChristophe** [comment]
@pwltr once changed, can you please share it to Aldert in order to have the Figma update.
