### ISSUE TITLE
[Bug]: Awaiting payment channel status

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1308]
### Describe the bug

I've been trying to open channels for several weeks and It didn't worked. I installed the new released (v75) but the status is still "awaiting payment".

Connection 5 order iD
9ffe32c1-9794-4f41-8df2-c9b39d1c1c95

Connection 4 order iD
822aa618-c85a-48bb-82e1-79bc0dd5995c

Tried to opened a new channels few min ago and the order expired
Connection 6 order iD
a27d8f37-677e-4f3d-bfec-853f15dff89c

### Screenshots / Recording
![Screenshot_20231011-184122](https://github.com/synonymdev/bitkit/assets/46056211/94083c99-aa4f-4d03-b8a1-679531650ea6)

### Operating system

GrapheneOS

### Bitkit version

v75

### Log output
[wallet0bitcoinldkaccountv2.zip](https://github.com/synonymdev/bitkit/files/12880598/wallet0bitcoinldkaccountv2.zip)

_No response_

**Comment by limpbrains** [comment]
related #1239

**Comment by JeanlChristophe** [comment]
All my channels never been refunded.

Doesn't work again with UXTO confirmed from Treasure Hunt.

Connection 7
Order 4bec6a5c-2cd4-4363-ba1d-87a5484d3770

**Comment by JeanlChristophe** [comment]
Once I restored, I have lost all the "Awaiting Payment" channels and funds. (v77)
![Screenshot_20231012-125159 (1)](https://github.com/synonymdev/bitkit/assets/46056211/0e5c7671-7cda-453b-9c1d-c9e31f646a8c)

**Comment by limpbrains** [comment]
There are a few different issues here
Orders
9ffe32c1-9794-4f41-8df2-c9b39d1c1c95
822aa618-c85a-48bb-82e1-79bc0dd5995c

Wasn't handled my BT correctly. @SeverinAlexB is aware.

Orders disapeared because of the failed backup, that is another issue

**Comment by SeverinAlexB** [comment]
- [9ffe32c1-9794-4f41-8df2-c9b39d1c1c95](https://api.blocktank.to/api/v2/channels/9ffe32c1-9794-4f41-8df2-c9b39d1c1c95) -> Onchain tx get only watched for 24hrs. Blocktank doesn't show tx correctly that are stuck in the mempool for longer than this timeframe.
- [822aa618-c85a-48bb-82e1-79bc0dd5995c](https://api.blocktank.to/api/v2/channels/822aa618-c85a-48bb-82e1-79bc0dd5995c) -> Same problem.

Will fix (probably after Lugano).
