### ISSUE TITLE
Unable To Save Contact

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1325]
I haven't created a profile and I don't have any contacts. Yet, I'm randomly getting this error toast message on build 79.

![image](https://github.com/synonymdev/bitkit/assets/93796166/1664173a-1236-4938-997b-3845112f6bf4)

**Comment by limpbrains** [comment]
@mattrdec is this an old wallet?

**Comment by mattcrv** [comment]
Yes, as early as August 4. I don't remember ever adding contacts to it. And I don't remember seeing this toast message in past internal versions.
