### ISSUE TITLE
[Bug]: Unresponsive Swipe to Pay

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1334]
### Describe the bug

Sometimes the Swipe to Pay gets unresponsive, though everything else in the UI is still working. Returning to the previous screen always fixes it, no need to close and reopen the app. I have no idea how to reproduce, but it happened randomly a few times.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/e93c7895-d046-4d2e-9bcd-b9ad83208fd3

### Operating system

iOS 17

### Bitkit version

83

**Comment by mattcrv** [comment]
This has not been fixed yet, @JeanlChristophe. Still an issue on 86.

**Comment by pwltr** [comment]
Not able to reproduce this on an iPhone 8 Plus 16.7.2.

**Comment by mattcrv** [comment]
I've just experienced this again. Not sure if related, but apparently my channel got force closed after the Review & Send loaded and before I tried swiping to pay.

https://github.com/synonymdev/bitkit/assets/93796166/a8ef89d4-4d9b-4070-87e1-2bc06718d62f

**Comment by pwltr** [comment]
This is still an issue, not able to find the cause yet.

**Comment by mattcrv** [comment]
It just happened again to me on 118. Copied an invoice from one app, opened Bitkit, quickly tapped send the modal about waiting for the node to sync popped up, and once the review & send screen loaded, slider was unresponsive. As usual, I closed the modal and tried again, without even closing and reopening the app, and the slider worked normally in the next attempt.

**Comment by pwltr** [comment]
Needs to be retested after #1917

**Comment by ovitrif** [comment]
> Needs to be retested after #1917

Putting it to `QA` so we get a fresh new perspective on its staet

**Comment by catch-21** [comment]
https://github.com/synonymdev/bitkit/pull/2018 may address this

**Comment by catch-21** [comment]
I've tried reproducing this in iOS simulator with v126 and v128 but no luck in either.  Tries moving the sheet in different directions and speeds in various combinations with the slider but it always works. Perhaps touch control on a real device has a different effect.  I'll leave this open a short while for iOS users to have a chance at recreating.

**Comment by JeanlChristophe** [comment]
John could reproduce this issue with internal TestFlight version 1.0.4.

**Comment by catch-21** [comment]
This can be reproduced by:
1. Start with Bitkit closed.
2. Open Bitkit
3. As soon as the main wallet page shows, tap QR button at the bottom
4. Scan LN invoice
5. It is not possible to use the slider or press 'Add Tag' button on the 'Review & Send' page

After step 4, you can see the 'Please wait for Bitkit to connect' screen for a short while. This could be a clue.

https://github.com/user-attachments/assets/2a1c9b50-e288-446b-af95-1f0475785af1

**Comment by catch-21** [comment]
Verified using android device only by pressing 'Add Tag' button using e565bd5f24be0a270f23d359127b16dfb27b9fba

**Comment by catch-21** [comment]
Verified using 1.0.5 (137) on iPhone 8
