### ISSUE TITLE
[Bug]: Closing channel with nothing but reserve balance left

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1337]
### Describe the bug

Closing a channel with only the reserve balance left also displays the toast "Transferring back to savings" and shows "354" as pending under "Savings", even though that will just go to mining fees and nothing will actually be transferred back on-chain. 

### Screenshots / Recording

![IMG_2351](https://github.com/synonymdev/bitkit/assets/93796166/c0ce770d-7c4f-4db5-85e0-130f487b7233)

### Operating system

iOS 17

### Bitkit version

83

**Comment by JeanlChristophe** [comment]
Fixed
