### ISSUE TITLE
[Bug]: Force close pending card

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1338]
### Describe the bug

When a channel is force close, the pending card says 60min when it should say 2 weeks.

### Operating system

Android, iOS

### Bitkit version

v83

**Comment by limpbrains** [comment]
https://github.com/synonymdev/bitkit/issues/1296

**Comment by JeanlChristophe** [comment]
Closing this ticket, fixed.

**Comment by pwltr** [comment]
Don't see how this is fixed @JeanlChristophe ?

**Comment by JeanlChristophe** [comment]
isn't it with this fix? https://github.com/synonymdev/bitkit/issues/1288

**Comment by pwltr** [comment]
No that one was about in-flight payments showing in the UI even after the channel was closed.

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/1779
