### ISSUE TITLE
[Bug]: Pending savings balance

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1339]
### Describe the bug

The pending onchain balance from chan close shows as pending spending but should be pending Savings

### Operating system

Android, iOS

### Bitkit version

v83

**Comment by limpbrains** [comment]
Can be done after #1296 is implemented

**Comment by pwltr** [comment]
This was fixed in https://github.com/synonymdev/bitkit/pull/1287
