### ISSUE TITLE
[Feature]: Prevent pasting strings that aren't seed words on the restore screen

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1352]
### Describe the problem

I usually restore my wallet by pasting the 12 words at once, and it works flawlessly. But sometimes, my phone doesn't copy things properly, and I end up pasting the previous thing that was on my clipboard. When that happens, it's a bit of a pain to select and delete whatever was pasted so I can then paste the 12 words properly. So it'd be good to have a way to prevent pasting random data that aren't the seed on the restore screen — or at least make it easy to delete the characters that turn red after being invalidated.

**Comment by limpbrains** [comment]
We already ignore if the string doesn't consist of 12 words. I think it's enough.

**Comment by catch-21** [comment]
You can navigate back and forwards to quickly clear the input fields. Not that anyone would think of that until after pressing backspace 100 times.
