### ISSUE TITLE
[Bug]: Continue button greyed out on profile creation screen

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1353]
### Describe the bug

The user started the profile creation flow but closed the app without finishing it. When the user re-opened the app and clicked on their profile name, the screen below opened with the "Continue" button on the profile screen was greyed out even though the user had filled out their profile name. The user had to click on "AlexSr" to type and delete one character so the "Continue" button became clickable.

### Screenshots / Recording

![IMG_2528](https://github.com/synonymdev/bitkit/assets/93796166/defb21dd-47a3-4d01-865d-ba10910227e9)

### Operating system

iOS 17

### Bitkit version

86

**Comment by pwltr** [comment]
This may be working as expected. The button only becomes active after the user has made changes to avoid redundant saves. If the user can see their profile name after reopening the app that means the profile has already been saved.

**Comment by JeanlChristophe** [comment]
Closing this issue, thanks @pwltr for the answer
