### ISSUE TITLE
[Bug]: Missing icons

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1354]
### Describe the bug

The ⚡ and 👁️ icons weren't displaying on a user's wallet. Everything else seemed to work.

### Reproduce

No idea how to reproduce it, unfortunately.

### Screenshots / Recording

![IMG_2511](https://github.com/synonymdev/bitkit/assets/93796166/161475bd-a162-4758-aa1c-7a1a1fdc2e20)
![IMG_2512](https://github.com/synonymdev/bitkit/assets/93796166/1f20ae21-ecdb-4d7c-b664-68cd02cfb75c)

### Operating system

iOS 17

### Bitkit version

86

**Comment by JeanlChristophe** [comment]
I can't reproduce this issue since Lugano.

**Comment by JeanlChristophe** [comment]
Closing this ticket as we can't reproduce it.
