### ISSUE TITLE
[Bug]: Can't delete widget

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1356]
### Describe the bug

I can't delete the Plan B Forum widget.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/8542b243-7719-49ae-9ded-c8a918990ccc

### Operating system

iOS 17

### Bitkit version

86

**Comment by pwltr** [comment]
@mattcrv How did you manage to have two of the same widget? That's likely the reason why deleting doesn't work.

**Comment by mattcrv** [comment]
Good question, I don't know how there were two widgets. But this got fixed after recent updates, so I'll close it.
