### ISSUE TITLE
[Bug]: Data Connection Issue

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1357]
### Describe the bug

A user reported getting the following error toast on a fresh install.

### Screenshots / Recording

![IMG_2571](https://github.com/synonymdev/bitkit/assets/93796166/3c29ba1a-6280-47e4-b85c-75091e7f434d)

### Operating system

iOS 17

### Bitkit version

86

**Comment by JeanlChristophe** [comment]
Can't reproduce the issue at the moment

**Comment by mattcrv** [comment]
I just saw this notification and realized the #1514 issue I opened yesterday was exactly the same as the one this user from Plan B Forum had. What a coincidence hahaha.

**Comment by JeanlChristophe** [comment]
Duplicated of https://github.com/synonymdev/bitkit/issues/1694
