### ISSUE TITLE
[Bug]: Pending card disapeared

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1371]
### Describe the bug

I tried opening channels twice but it didn't work. I got a Blocktank error.

However, there's a problem in the UI, because the pending card no longer appears after a few hours. But the problem is still there.

[bitkit_ldk_logs_1699437208041.zip](https://github.com/synonymdev/bitkit/files/13295229/bitkit_ldk_logs_1699437208041.zip)

### Screenshots / Recording

![Screenshot_20231108-105653](https://github.com/synonymdev/bitkit/assets/46056211/c764ca4c-49e2-4628-958f-a909485edf3d)
![Screenshot_20231108-110313](https://github.com/synonymdev/bitkit/assets/46056211/ab22162f-9dbf-4023-ad57-2908810c297d)

### Operating system

Android, iOS

### Bitkit version

86

**Comment by pwltr** [comment]
This should be fixed with https://github.com/synonymdev/bitkit/pull/1401, a card will be shown for failed/expired orders.
