### ISSUE TITLE
[Bug]: Warn user if he doens't have enought funds to do a proper ochain transaction

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1384]
### Describe the bug

User have onchain balance that doesn't cover basic onchain fee, for example 50 000 sats.
He tries to send onchain using address on slashpay. 
Bitkit can't create a proper tx and sents fees to default 0.08 cents.
We must warn user about this situation.

### Reproduce

1. Send tx fee with low balance
2. BItkit sends, but it should show a warining

### Screenshots / Recording

![image](https://github.com/synonymdev/bitkit/assets/155891/1eaddba6-bd0c-4ea4-a141-fbf2968362b8)

### Operating system

iOS, Android

### Bitkit version

v87

**Comment by JeanlChristophe** [comment]
Done
