### ISSUE TITLE
[Bug]: Min fee for CJIT isn't respected

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1385]
### Describe the bug

I don not have LN channel. I am trying to receive LN funds by creating a JIT channel.
The min fee on Bitkit is 5000 sats. Nevertheless I am receiving an error message saying that I the min fee should be 10001 sats.

The min should be elastic according to the fees of the network.

+ if someone changes the minimum amount in Blocktank, the information should be given to Bitkit.

### Screenshots / Recording

![Screenshot_20231117-112202 (1)](https://github.com/synonymdev/bitkit/assets/46056211/aaa55cd4-4c52-406a-b6cd-e616af79a0af)

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v87

**Comment by catch-21** [comment]
The error notification is also very quick to disappear. I needed to invoke it 2 or 3 times to read it.

**Comment by JeanlChristophe** [comment]
I can close the ticket
