### ISSUE TITLE
[Bug]: Can't create order with largest spending card

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1394]
### Describe the bug

When choosing the largest predefined amount in the Lightning custom setup I get an error message from BT and can't continue with the order.

### Reproduce

1. Go to Pay Instantly -> Custom Setup
2. Click on card with largest fiat amount
3. Click Continue
4. Click Continue
5. See error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/578b661f-7ec0-4d47-958e-dcc11fa4ae70

### Operating system

iOS / Android

### Bitkit version

master

**Comment by JeanlChristophe** [comment]
@pwltr I can't reproduce this error now. Ca, I close it?

**Comment by pwltr** [comment]
@JeanlChristophe Just checked, issue is still there. Although the inbound amount has to be really high (> 500$) so would consider this low prio.

**Comment by pwltr** [comment]
Seems to have been fixed on BT side.

**Comment by catch-21** [comment]
Seems ok in v128 [e8f5056](https://github.com/synonymdev/bitkit/commit/e8f50564c6b4f471d9a336067fa5d54b4754c2d4)
