### ISSUE TITLE
[Bug]: Edit invoice on "Receive Bitcoin" forces back to "Receive Instantly"

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1407]
### Describe the bug

If a value is entered on the "Receive Instantly" page it is then not possible to create a "Receive Bitcoin" invoice because the UI is stuck trying to produce a lightning invoice.

### Reproduce

1. Open android app at a new wallet (or probably existing wallet too)
2. Tap "Receive" button in bottom right
3. Tap "Receive Instantly" slider to begin producing lightning invoice
4. Input a valid value (e.g. 55555)
5. Tap "Continue"
6. Tap back arrow **twice** to return to view QR
7. Tap "Receive Instantly" again to toggle back to on-chain Bitcoin
8. Tap "Edit" button to create Bitcoin invoice

**Desired Result:**
"Edit Invoice" page is displayed

**Actual Result:**
"Receive Instantly" page is displayed. If I now tap "Continue" I am forced back into "Receive Instantly" mode.

### Screenshots / Recording

https://drive.google.com/file/d/1nSlxYS2M2TpB924xUSorJsl8RFvxHRTc/view?usp=sharing

### Operating system

Android 13

### Bitkit version

V1.0

**Comment by JeanlChristophe** [comment]
Hi @james-iohk, thanks for sharing this issue.
