### ISSUE TITLE
Unable to open LN channel

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1408]
### Describe the bug

tried to open a channel via Quick Setup - 20% allocated to Spending balance and 80% to savings.

got this issue with BT
Channel open failed. {"message":"The operation was unable to achieve a quorum during its retry window.","attempts":[{},{}],"name":"ExecutionError"}

order ID a90b9ad8-682d-4263-ad5d-96f3f0b427b0

### Screenshots / Recording

[bitkit_ldk_logs_1701693771192.zip](https://github.com/synonymdev/bitkit/files/13546036/bitkit_ldk_logs_1701693771192.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v90

**Comment by JeanlChristophe** [comment]
Issue is fixed, closing this ticket
