### ISSUE TITLE
[Bug]: Clipped Text on Welcome Page

### ISSUE THREAD

**Issue by PeteClubSeven** [synonymdev/bitkit-react-native#1423]
### Describe the bug

When running the application for the first time on an iPhone SE 2022 the welcome pages fail to display text correctly

### Reproduce

1. Open Bitkit for the first time
2. See clipped text

### Screenshots / Recording

![Screenshot 2023-12-12 at 16 13 51](https://github.com/synonymdev/bitkit/assets/130258664/92915188-fa50-45d1-88e8-3a25fdcbc5ac)
![Screenshot 2023-12-12 at 16 15 10](https://github.com/synonymdev/bitkit/assets/130258664/c26d3a2d-15b0-4308-885f-a936102c485a)
![Screenshot 2023-12-12 at 16 15 21](https://github.com/synonymdev/bitkit/assets/130258664/9ae45d9b-666b-4de7-9074-9c6840000285)

### Operating system

iOS 17

### Bitkit version

1.0 (92)

**Comment by JeanlChristophe** [comment]
Thanks! Which phone are you using?

**Comment by PeteClubSeven** [comment]
> Thanks! Which phone are you using?

The iPhone SE 2022
