### ISSUE TITLE
[Bug]: Cannot restore the wallet

### ISSUE THREAD

**Issue by jaonoctus** [synonymdev/bitkit-react-native#1424]
### Describe the bug

Cannot restore a wallet.

### Reproduce

1. Accept the terms
2. Skip intro
3. Click on 'Restore'
4. Click on 'Understood'
5. Type the mnemonic
6. Click on 'Advanced'
7. Type the passphrase
8. Click on 'Restore Wallet'

### Screenshots / Recording

![image](https://github.com/synonymdev/bitkit/assets/7918067/76b92301-22df-4877-8bc1-c69a609d8941)

### Operating system

Android 13

### Bitkit version

1.0 (92) [Dec 11, 2023]

### Log output

Cannot get the logs, because There is no menu in this screen. I also clicked on "Try again" 3 times, and after clicking on "Proceed Without Backup", the app crashes.

**Comment by JeanlChristophe** [comment]
Hi @jaonoctus, sorry for this issue.
Do you know what version you were at before updating to v92? 

Can you share your logs with me using this procedure?  Logs contain private information. If you want to send them privately, you can email me: jean@synonym.to

Thanks.

Uploading screen-20231213-101418.mp4…

**Comment by jaonoctus** [comment]
@JeanlChristophe 

> Do you know what version you were at before updating to v92?

I'm honestly not sure. Either v86 or v60

> Uploading screen-20231213-101418.mp4…

?

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/assets/46056211/687a6ace-8401-43f2-b728-177558eb1488

sorry, here the video.

**Comment by jaonoctus** [comment]
@JeanlChristophe I can't find your PGP key. Could you provide one?

**Comment by JeanlChristophe** [comment]
You can email me: [jean@synonym.to](mailto:jean@synonym.to)

**Comment by jaonoctus** [comment]
I just wanted to encrypt the file to your pubkey so the email providers cannot access it.
If you don't have it, that's fine for this test wallet. I'm still sending the file. Thank you 🥂

**Comment by Jasonvdb** [comment]
Strange, looking at your logs you shared and restore seems to be a success as it loaded your channel fine. Not sure why the error happened the first time, consecutive ones might be from failing to override the previous restore. Hard to diagnose the crash though. 

Could you try delete the app completely and just restore again? Unless you've already tried that?

**Comment by jaonoctus** [comment]
@Jasonvdb right? The app just close using this seed.

I've already tried that 😢

**Comment by Jasonvdb** [comment]
We've managed to replicate our side so working on a fix now

**Comment by Jasonvdb** [comment]
@jaonoctus could you please retry now? We've patched the backup server

**Comment by jaonoctus** [comment]
@Jasonvdb it is still closing. I tried from a clean installation.

sending you the logs again

**Comment by jaonoctus** [comment]
Any updates?

**Comment by Jasonvdb** [comment]
We have a fairly large app update we're currently polishing up that may solve a number of these issues. What is the latest version you've recently tried to restore with?

**Comment by jaonoctus** [comment]
Just tried on the [v1.0.0-beta.108](https://github.com/synonymdev/bitkit/releases/tag/v1.0.0-beta.108) and it works.

Closing this issue, ty

**Comment by Jasonvdb** [comment]
Great thanks for the update!
