### ISSUE TITLE
[Bug]: ElectrumConfig - after failure to connect to a server, resetting to default also gives error

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1441]
### Describe the bug

In Settings -> Electrum Server: After failure to connect to a server, resetting to default also gives an error toast even though the connection is working. A restart fixes the UI.

### Operating system

Android, iOS

### Bitkit version

master

**Comment by pwltr** [comment]
@coreyphillips I think this issue might be caused by [this line](https://github.com/synonymdev/react-native-electrum-client/blob/20b93ec5c6d2ef0f1445116b26582a784d78eeb9/helpers/index.js#L266C3-L266C39) in `rn-electrum-client`.

The `mainClient` doesn't have a close method which causes the old connection to linger on and in effect breaking the UI in Bitkit.

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/1731

**Comment by catch-21** [comment]
Verified as part of https://github.com/synonymdev/bitkit/issues/1731
