### ISSUE TITLE
Profile not saved when restarting the app

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1460]
### Describe the bug

I create the profile with the links, I save the profile and when I restart the app, the profile is no longer there (tried this 3 times)

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/177e43fb-f745-4a01-9f8f-78d5c82a472f

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v93

**Comment by ovitrif** [comment]
Happens to me the same with a new profile
Version: 93
OS: Android 14 / Pixel 7 Pro

Didn't happen on previous version (the one from the store)

**Comment by flaviomoceri** [comment]
I'm testing these changes but I still get this error https://github.com/synonymdev/bitkit/issues/1460
