### ISSUE TITLE
Restore Issue

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1461]
### Describe the bug

restoring the app takes a long time - on the first attempt I got an error message (see below)
![photo_2024-01-05_12-38-47](https://github.com/synonymdev/bitkit/assets/119061223/90dde690-9bda-4cde-96fc-19860f8838b4)

note during the process I kept the app open (didn't switch screens or anything)

upon 2nd reattempt the app restored OK 

### Screenshots / Recording

![photo_2024-01-05_12-38-47](https://github.com/synonymdev/bitkit/assets/119061223/38352be1-7473-454b-a5d5-132fc1bc53a9)

[bitkit_ldk_logs_1704451626685.zip](https://github.com/synonymdev/bitkit/files/13841028/bitkit_ldk_logs_1704451626685.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v93

**Comment by ovitrif** [comment]
Had this one time as well:
- **OS** Android 14, Pixel 7 Pr0
- **Bitkit Version** v93

#### Remarks
- On 2nd try it also succeeded.
- Another remove+reinstall app & restore succeeded too.

**Comment by ovitrif** [comment]
I can't repro this on v94, tried 5 times (both with and without spending balance)

**Comment by JeanlChristophe** [comment]
Closing the ticket
