### ISSUE TITLE
Unable to receive CJIT funds (Bitkit <> Bitkit)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1462]
### Describe the bug

tried creating a CJIT invoice for 20500 sats - JC tried to pay via Bitkit and was unable to 

### Screenshots / Recording

<img width="236" alt="cjit error" src="https://github.com/synonymdev/bitkit/assets/119061223/6bbb24b7-b4ae-41dd-b22a-3af0a9c7cd44">

CJitEntry a38dca85-6d09-4a4e-82ef-74aa9ecd50f6

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v93

**Comment by thisispav** [comment]
[bitkit_ldk_logs_1704453854623.zip](https://github.com/synonymdev/bitkit/files/13841392/bitkit_ldk_logs_1704453854623.zip)

**Comment by JeanlChristophe** [comment]
it didn't work also with Phoenix.

**Comment by JeanlChristophe** [comment]
fix. Closing the ticket
