### ISSUE TITLE
[Bug]: Headlines widget isn't synchronized

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1467]
### Describe the bug

Headline from the widget isn't synchronised.

### Reproduce

1. Go to 'add widget'
2. Click on 'bitcoin headlines'
3. Close and reopen the app
4. See error, it's still the same headline

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v93

**Comment by flaviomoceri** [comment]
If we want to show to the user a different headlines every time, this PR implements this
https://github.com/synonymdev/bitkit/pull/1474
