### ISSUE TITLE
[Bug]: Unable to connect to LNM. 

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1468]
### Describe the bug

We are trying to connect to LNM with Slashtags but the screen keep loading after minutes.

### Reproduce

1. Go to 'https://lnmarkets.com/'
2. Click on 'Login'
3. Select 'Slashtags'
4. Scann
5. ee error

### Operating system

Android and GrapheneOs

### Bitkit version

v93

**Comment by pwltr** [comment]
Seems to be working now on Android, closing.
