### ISSUE TITLE
[Bug]: Fees for opening a channel that does not match to Mempool

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1469]
### Describe the bug

I tried to opened a channel with a quick setup and Bitkit tell me that's the network fee will be $15.04. Nevertheless it doesn't match with the current fees : $3,50.

### Screenshots / Recording

![Screenshot_20240105-151524 (1)](https://github.com/synonymdev/bitkit/assets/46056211/080888df-dada-4d57-8ea9-feaa695be1d7)

### Operating system

Graphene OS and iOS

### Bitkit version

v93

**Comment by pwltr** [comment]
Seems to be fixed.
