### ISSUE TITLE
[Bug]: LNURL Withdraw transaction deosn"t show up in the activity

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1470]
### Describe the bug

We did 5 LNURL transaction withdraw and it doesn't shop up in the activity.

### Reproduce

1. Go to '.[..'](https://lnurl.fiatjaf.com/)
2. Scann LNURL withdraws '....'
3. Accept

### Operating system

Android and GrapheneOs

### Bitkit version

v93

**Comment by limpbrains** [comment]
https://lnurl.fiatjaf.com/ is broken
