### ISSUE TITLE
[Bug]: Sending LN transaction to contact failed on my end, recipient received

### ISSUE THREAD

**Issue by ovitrif** [synonymdev/bitkit-react-native#1472]
### Describe the bug

- Attempted to send 1 sat to contact.
- Once sliding, the loader took longer than expected to complete.
- It eventually completed, showing me the transaction failed.
  > **Note** The recipient received the sum.
  > It shows correctly in my activity.

### Screenshots / Recording

<img width="315" src="https://github.com/synonymdev/bitkit/assets/4588074/fcb6a184-a0d1-4990-8365-7c17f45cd384">

### Operating system

Android 14, Pixel 7 Pro

### Bitkit version

v93

### Log output

[bitkit_ldk_logs_1704466100118.zip](https://github.com/synonymdev/bitkit/files/13843395/bitkit_ldk_logs_1704466100118.zip)

**Comment by JeanlChristophe** [comment]
Fixed
