### ISSUE TITLE
[Bug]: lnurl scan channel open failed

### ISSUE THREAD

**Issue by ovitrif** [synonymdev/bitkit-react-native#1473]
### Describe the bug

1. Scanning lnurl for channel, it read the QR code correctly
   Used: https://lnurl.fiatjaf.com/
3. After tap on connect it results in error.

### Reproduce

4. Scroll down to '....'
5. See error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/4588074/f6b980c8-8b58-42ed-a7cb-59b5d44f492e

### Operating system

Android 14, Pixel 7 Pro

### Bitkit version

v93

### Log output

[bitkit_ldk_logs_1704466591433.zip](https://github.com/synonymdev/bitkit/files/13843462/bitkit_ldk_logs_1704466591433.zip)

**Comment by limpbrains** [comment]
Looks like lnurl playground (https://lnurl.fiatjaf.com/) is broken. Node ip/port is not reachable.
I was able to open a channel from our Blocktank using LNURL-channel

**Comment by JeanlChristophe** [comment]
@limpbrains tried today and succeeded after 10 attempts

**Comment by limpbrains** [comment]
Lest just have one ticket - #1490
