### ISSUE TITLE
[Bug]: LN transactions have not been restored

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1475]
### Describe the bug

2 out of 2 users tested v93 and when we restored it, no LN transactions appeared. The onchain ones did.

### Operating system

Android and GrapheneOs

### Bitkit version

v93

### Log output
[bitkit_ldk_logs_1704467670010.zip](https://github.com/synonymdev/bitkit/files/13843628/bitkit_ldk_logs_1704467670010.zip)

**Comment by JeanlChristophe** [comment]
Can't reproduce the error. @pwltr is this issue has been fixe with the old backup issue?

**Comment by pwltr** [comment]
@JeanlChristophe Yes if the backup server is working correctly this should be fixed.

**Comment by ovitrif** [comment]
I couldn't repro this the last 2 days.

**Comment by ovitrif** [comment]
@pwltr Is there a way I could confirm the backup server is working correctly, I mean additional to the manual testing which does confirm LN transactions are no longer lost?

P.S. I'm asking to make sure it's safe closing this issue 🙏🏻 

edit:
Additionally, for my own information, we're speaking about the `LDK Backup server` here, is that correct? Thx!!!

**Comment by pwltr** [comment]
> @pwltr Is there a way I could confirm the backup server is working correctly, I mean additional to the manual testing which does confirm LN transactions are no longer lost?

I don't know backups is not really my area. As to how to check if it's working correctly outside Bitkit, better to ask @Jasonvdb or @rbndg.

**Comment by ovitrif** [comment]
Thanks, since there's a ping already I won't double it for now ;)

**Comment by ovitrif** [comment]
As this issue didn't reproduce in the last 3 internal releases, I'm closing it.
