### ISSUE TITLE
[Bug]: TREASURE_HUNT_HOST not defined

### ISSUE THREAD

**Issue by JijoBose** [synonymdev/bitkit-react-native#1476]
### Describe the bug

I was running bitkit in development mode, found that TREASURE_HUNT_HOST is not defined.

Could anyone explain what needs to be done here?

### Reproduce

1. Clone the repo
2. yarn install
3. npx pod-install // for ios
4. yarn start

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/13100108/06df1a5d-d4d0-4721-89b2-d8e93061be5c" height="500px" />

### Operating system

iOS 17

**Comment by ovitrif** [comment]
Been experiencing the same issue, for the most hacky way to move forward and not get blocked by this I simply entered `localhost` as value.

This should get the app working, except for the treasure hunt functionality.

We'll see how to get this properly fixed, thanks for filing the issue @JijoBose 🙇🏻

**Comment by mattcrv** [comment]
Hi @JijoBose! Thanks for flagging this issue on our Discord server. We're deactivating the help channel on Discord, so I'll reopen this issue so you get replied here.

**Comment by coreyphillips** [comment]
Should be resolved as of this PR:
https://github.com/synonymdev/bitkit/pull/1532

Going to close this issue, but please let us know if you continue to have any issues and we'll re-open it.
