### ISSUE TITLE
[Bug]: Channel closing UX

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1484]
I closed a channel locally, and my reserve was already sweeped to my on-chain wallet, but the sweep is still shown as pending. (ps: channel was opened via the Bitfinex and Blocktank integration).
![image](https://github.com/synonymdev/bitkit/assets/93796166/98ae3670-f291-49f6-817d-72ff540533be)
![image](https://github.com/synonymdev/bitkit/assets/93796166/e84244d9-c70f-4711-bb72-4f860c4e1aa8)
![image](https://github.com/synonymdev/bitkit/assets/93796166/bc85ddc2-84a5-4878-bb04-2c8587da0b6c)
![image](https://github.com/synonymdev/bitkit/assets/93796166/c5c4e5d7-d531-4ebe-99ae-1201403da5b9)

I later opened and closed another channel, and it happened again (fortunately, the 4900 sats sweeped from the previous channel is no longer appearing as "pending"):
![IMG_3C36AE238235-1](https://github.com/synonymdev/bitkit/assets/93796166/fc000506-51b8-43a1-8270-f6cbf21f86fb)

**Comment by pwltr** [comment]
Sweep needs 6 confirmations to become spendable when coop-closing. Currently improving this.
