### ISSUE TITLE
[Bug]: Links no longer appear in profile

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1486]
### Describe the bug

From a new wallet, I wanted to create a profile by filling in all the information including my twitter link. Next time I saved, I saw that it no longer appeared in the profile.

### Reproduce

1. Go to 'create profile'
2. Click on 'add link'
3. Add data
4. Save
5. See error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/a6c5b7fe-9c0c-4ef7-9ea4-646788734eaf

### Operating system

GrapheneOS

### Bitkit version

v94

**Comment by ovitrif** [comment]
~~I wonder if this could have something to do with timing when creating a new profile, because it seems to be working for an existing profile in my case on v94~~
^ mistakenly thought we're speaking about the edit view.

**Comment by pwltr** [comment]
If this is about saving…
Not sure I correctly understand the issue here but if you're looking for the links in your own profile they have been removed for redundancy recently [here](https://app.asana.com/0/1189635884316057/1206202727512780/f)

**Comment by JeanlChristophe** [comment]
you are right, the links has been removed from the design in purpos. it's not a bug, it's a feature.
Closing the ticket.
