### ISSUE TITLE
[Bug]: Problem with the onchain amount

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1487]
### Describe the bug

I have just received EUR 80 from Green wallet. When I click on 80 EUR, the amount is not the same. The error is still the same when I close and reopen the application.

### Screenshots / Recording

![Screenshot_20240112-110759](https://github.com/synonymdev/bitkit/assets/46056211/0e3f2b84-6389-4154-ae44-205c17e22532)
![Screenshot_20240112-110807](https://github.com/synonymdev/bitkit/assets/46056211/4c662bca-558f-4125-95bc-7e2e412b2b3d)

### Operating system

GrapheneOS

### Bitkit version

v94

**Comment by limpbrains** [comment]
The rate is 
```
    {
      "symbol": "BTCUSD",
      "lastPrice": "45862.00",
      "base": "BTC",
      "baseName": "Bitcoin",
      "quote": "USD",
      "quoteName": "US Dollar",
      "currencySymbol": "$",
      "currencyFlag": "🇺🇸",
      "lastUpdatedAt": 1705054400058
    },
```

**Comment by JeanlChristophe** [comment]
Not an issue: the conversion rate changes over time.

**Comment by catch-21** [comment]
imo it is an issue but covered by https://github.com/synonymdev/bitkit/issues/1746

**Comment by JeanlChristophe** [comment]
You receive BTC, not fiat. so the value of fiat change, not the bitcoin's value
