### ISSUE TITLE
[Bug]: the transaction was rejected by network rules: txn-mempool-conflict

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1492]
### Describe the bug

After closing a channel I don't see any confetti notification. In logs I see 
```
{"code": 1, "message": "the transaction was rejected by network rules.

txn-mempool-conflict
"}
```

### Reproduce

I had 3 channels
one CJIT
and 2 from blocktank / lnurl-channel

### Operating system

iOS

### Bitkit version

v94

### Log output

[Kkkk.zip](https://github.com/synonymdev/bitkit/files/13919687/Kkkk.zip)

**Comment by coreyphillips** [comment]
This looks like an on-chain issue. Possible the UTXO's weren't able to be refreshed fast enough from the mempool before one of the closes and attempted to use an already spent UTXO.
