### ISSUE TITLE
Closing Lightning Channel and transferring Spending Balance > Savings Balance - Funds disappeared

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1504]
### Describe the bug

I closed my Lightning channel.
The transaction was pending and was about to receive around $10 worth of btc from my spending balance to savings balance.
I could see that the funds were pending. After a couple of hours in the testing session I opened Bitkit again and the funds were gone.

### Screenshots / Recording

[bitkit_ldk_logs_1705489662486.zip](https://github.com/synonymdev/bitkit/files/13962241/bitkit_ldk_logs_1705489662486.zip)

![photo_2024-01-17_13-06-58](https://github.com/synonymdev/bitkit/assets/119061223/7f3ee6cf-ed0a-40d3-923a-b7c066de3c89)
![photo_2024-01-17_13-06-57](https://github.com/synonymdev/bitkit/assets/119061223/189569ee-f0ba-451a-897a-22f542ca015e)
![photo_2024-01-17_13-06-56](https://github.com/synonymdev/bitkit/assets/119061223/f767674a-e3fe-434b-89b0-07838c6afc5c)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v95

**Comment by pwltr** [comment]
Possible duplicate of https://github.com/synonymdev/bitkit/issues/1484

**Comment by JeanlChristophe** [comment]
Not an issue
