### ISSUE TITLE
[Bug]: Payment page keeps loading indefinitely

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1510]
### Describe the bug

when we try to pay a LNURL Channel, the payment page keeps loading indefinitely. However, the payment is received by the [Blocktank widget ](https://blocktank.to/#widget)and it also appears in the Bitkit transaction history.

it only happened with LNURL channel with Pav and I

### Screenshots / Recording

![photo_2024-01-19_12-17-59 (1)](https://github.com/synonymdev/bitkit/assets/46056211/fcc2a770-b083-44ec-947f-15c44105bdae)

### Operating system

GrapheneOS

### Bitkit version

v97

**Comment by limpbrains** [comment]
#1546
