### ISSUE TITLE
[Bug]: App doesn't load

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1514]
### Describe the bug

Bitkit is being opened for the first time on a new device. No seed was entered and there's no local data saved on this new device.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/f4c485c1-bcbb-4050-83b2-ed373e995e69

### Operating system

iOS 17.3

### Bitkit version

98

**Comment by mattcrv** [comment]
Duplicate of #1357

**Comment by coreyphillips** [comment]
Error is coming from this bit of code [here](https://github.com/synonymdev/bitkit/blob/7386471bd4960772cfd809ce3f91ada6370b6b8a/src/components/SlashtagsProvider2.tsx#L124):
```
const seedHash = useAppSelector(seedHashSelector);
const webRelayUrl = useAppSelector(webRelaySelector);

useEffect(() => {
  if (!seedHash) {
	  return;
  }
  
  (async (): Promise<void> => {
	const primaryKeyRes = await getSlashtagsPrimaryKey(seedHash);
	if (
		primaryKeyRes.error ||
		(primaryKeyRes.data && primaryKeyRes.data.length === 0)
	) {
		showToast({
			type: 'error',
			title: 'Data Connection Issue',
			description:
				'An error occurred: Could not load primary key from keychain.',
		});
		return;
	}
```

Possible it's some type of permission error for the Keychain. Haven't been able to reproduce it at the time of this writing.

**Comment by JeanlChristophe** [comment]
@mattcrv was it a restored wallet or a new wallet?

**Comment by mattcrv** [comment]
The app never loaded on my new phone, so I couldn't even get to the wallet creation/restoration (or any other screen). When I open the app, it shows the Bitkit logo, then the Data Connection Issue toast pops up, and then it just displays the black screen forever (I tried keeping it open for a few minutes to see if something loads, but nothing happens). This is not happening with any other app on my new phone (not even other Bitcoin wallets), so it's a Bitkit-specific issue. I tried installing older builds (87, 92, 97), but the issue persists. This never happened on my old phone.

This looks like an iOS 17.3 issue because I tried opening Bitkit on a different iPhone 15 Pro running iOS 17.3, and the same bug happened. If 17.3 is indeed the reason, it might be a recurring issue with iOS updates considering it also happened back in October (#1357).

**Comment by mattcrv** [comment]
I've just updated to iOS 17.4, and after a reinstall, the app loaded normally. Indeed seems related to 17.3 and the version user #1357 was running. Now that 17.3 is public, it might be good to check if more iOS users are experiencing this bug or if it just affected those on the beta track.

**Comment by JeanlChristophe** [comment]
I'm closing this ticket as we've had no further feedback from users.
