### ISSUE TITLE
[Bug]: Can't open second LN channel

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1536]
### Describe the bug

Custom LN setup is broken. I have 300 USD confirmed onchain balance, but I get "Unable to increase the fee any further. Otherwise, it will exceed half the current sending/output amount." notification

### Operating system

iOS

### Bitkit version

Current master

**Comment by coreyphillips** [comment]
This is something that will happen when the on-chain transaction fee required by Blocktank is 50% or greater than the cost for the channel open sent to Blocktank.

This is tricky. If we wanted to handle this in Bitkit we would need to spam the api to find the lowest channel cost that is greater than 50% of the fee. We could also move the fee safety check up to 80% or 100%, but that makes me feel uncomfortable. If we wanted to handle this on Blocktank's side, Blocktank will only create channel orders where the on-chain transaction fee will never exceed the channel cost by 50%.

**Comment by coreyphillips** [comment]
Actually, we might not have to spam the api anymore. We can call [this](https://api.stag.blocktank.to/blocktank/api/v2/info) and pass Blocktank's expected fee rate to `getFeeInfo` from Beignet and set the result plus a few sats as the minimum client side balance.

**Comment by coreyphillips** [comment]
Actually, we don't have to spam the api anymore. We can call `getInfo` and set the result of `min0ConfTxFee` plus a few sats as the minimum client side balance.

**Comment by limpbrains** [comment]
I think we should disable this warning for amounts smaller than 10 USD or even at all.
What we can do is show additional warning on confirmation screen.

**Comment by limpbrains** [comment]
And I had this error on regtest, with 1 sat/vbyte fees.

**Comment by coreyphillips** [comment]
Unfortunately, the issue isn't limited to Bitkit/Beignet so disabling the warning or bypassing the check will not fully resolve it. Many Electrum servers with defaults set will also refuse to create and/or broadcast transactions with similarly high fee to output ratios. We could implement a minimum client balance amount when creating a channel that helps ensure the user will always send more than 50% of the transaction to Blocktank than fees.

**Comment by limpbrains** [comment]
I also having this issue when doing basic, not BT ochain transaction.
I'm trying to send 547 sats on regtest. 
I errors in logs
```
 LOG  [Error: New total amount exceeds the available balance. Unable to update the transaction fee.]
 LOG  New total amount exceeds the available balance. Unable to update the transaction fee.
 LOG  [Error: New total amount exceeds the available balance. Unable to update the transaction fee.]
 LOG  [Error: Unable to increase the fee any further. Otherwise, it will exceed half the current sending/output amount.]
 LOG  Unable to increase the fee any further. Otherwise, it will exceed half the current sending/output amount.
 LOG  [Error: Unable to increase the fee any further. Otherwise, it will exceed half the current sending/output amount.]
 ```
 
 Also it doesn't show me fee estimate


![image](https://github.com/synonymdev/bitkit/assets/155891/3339c052-6712-4b6f-bf41-213a733d0de5)

**Comment by JeanlChristophe** [comment]
Enable to reproduce this issue on my side wit Beignet.
