### ISSUE TITLE
Bitkit accounting Ledger

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1550]
A library for keeping track of all transactions, balances within Bitkit. 
The aim is to have clarity on the current state of the users funds within Bitkit, and have a good idea where the funds are at all times.

Integrate a database

> In my opinion key/value db is better. 

Track all incoming and outgoings transactions

> All transactions should have a unique identifier
> Routing fees
> On chain fees

Consolidation system (calculate current final balance)

> Throw errors if numbers don't match up

Exportable for debugging

> Logging. Passing a logger function as a constructor so it works with Bitkit's logger.

Lightning transactions

> Sweeping
> Channel opening/closing
> Track user's node id

Transaction state tracking

> Which block on chain tx is included in.

Multi currency support

> We should expect to not only be used with bitcoin, but also tokens in the future too.

Multi account support

> Assume that we will have many accounts.

Documented API and testable

> We should be able to test the logic of this lib independently of bitkit
> Bitkit various components need to pass data to this component.

- [ ] Define API
- [ ] Implement it
- [ ] Design test
- [ ] Integrate it into Bitkit

**Comment by catch-21** [comment]
Have been using this for a week now whilst testing other stuff. It mostly seems to work find. Still discussing with @limpbrains when unexpected things occur.

**Comment by catch-21** [comment]
Happy enough with how this behaves. Closing.
