### ISSUE TITLE
[Bug]: Balance doesn't update after second incoming tx

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1552]
### Describe the bug

New wallet. I received 2 transactions. First one to bech32, second one to taproot.
I received 2 notifications, I see 2 items in activity list, but balance only reflects first transactions

### Reproduce

1. Create new wallet
2. receive 0.001 BTC
3. switch to taproot addresses
4. receive 0.002 BTC
5. balance is still 0.001 BTC

### Operating system

iOS

### Bitkit version

master

**Comment by limpbrains** [comment]
Also balance is resets to first tx ( 0.001 BTC ) when I send more funds.
At the video I'm sending new tx with 0.00111 BTC, see balance goes to 0.001

https://github.com/synonymdev/bitkit/assets/155891/e3c69710-f66d-49ef-b6a7-24cc82a07402

**Comment by limpbrains** [comment]
tested v106 the issue is still here.
I've sent myself 3 tx
- Legacy
- Nested segwit
- Taproot

First one even had one confirmation but overall balance was still 0

**Comment by limpbrains** [comment]
I don't think this is related to taproot. First two tx was not for Taproot and still balance is missing

**Comment by JeanlChristophe** [comment]
Any update about this issue?

**Comment by coreyphillips** [comment]
This issue should be resolved as of #1573
