### ISSUE TITLE
v41 Prototype

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1556]
https://synonymworkspace.slack.com/archives/C01H106JRQB/p1689252457318469

Bitkit Mobile Prototype v41 (HANDOFF):
- These changes are ready to be implemented in the frontend and backend.
- Not all changes are visible in the prototype flows. Therefore, please also refer to the static Figma frames.
- Ongoing experimental design work is not included in this version.
New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=19188%3A288539&type=design&node-id=19188-288550&viewport=25%2C126%2C0.06&t=1Wlu0CbctJRNaoeU-8&scaling=min-zoom&starting-point-node-id=19188%3A293542&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=19188%3A288539&type=design&node-id=19188-293547&viewport=25%2C126%2C0.06&t=1Wlu0CbctJRNaoeU-8&scaling=min-zoom&starting-point-node-id=19188%3A293547&show-proto-sidebar=1&hide-ui=1

**What’s new?**
A key objective of this prototype update was to ensure the transactions displayed in the activity overview add up to the total balance (as requested by multiple team members). To achieve this, several design decisions and changes were made. Please note, these changes and solutions are significantly different from those shown in the [recent video](https://synonymworkspace.slack.com/archives/C01H106JRQB/p1688474247224739). Following careful consideration, some of these previous changes have been reversed. For more information, please refer to the new video below.

**Balance, Activity, Transaction & Amounts Logic:**

- [x] Activity: Activity rows will now reflect the total amount of sats leaving the wallet (payment amount + fee) to ensure total wallet balance is accurate.
- [x] Transaction Details: The Sent Transaction Details view has been updated to clearly communicate the total outgoing amount, as well as the transaction specifics (payment amount + fee amount).
- [x] Transfer Activity: Copy and logic for transfer activity rows have been updated. Each transfer action results in two activity updates:
          - [ ] The on-chain transaction for moving funds from or to the Savings Balance.
          - [ ] An activity update that communicates the change in the Spending balance.
These two activity updates also serve to assist users in verifying the successful completion of a transfer. Users can do this by checking the status of both sides of the transaction—this includes a 'pending' summary displayed inline (or completed state), and slightly more detailed status information found within the Transfer Details view.
- [x] Transfer Activity icon color: Transactions related to/from the savings balance (on-chain txs) will always be orange, reflecting their on-chain nature. Activity updates related to the Spending Balance (linking to Transfer Details) will be purple.
- [x] Transfer Details: Specific designs have been added for on-chain transfer actions and for the activity related to mutations in the spending balance.
- [ ] Self Send Activity: The activity row for self-sends has been updated to display only the fee as the total for the activity row. The amount sent to self is shown in the description line.
- [ ] Self Send Activity: Self-send activity has been updated to include the fee for the outgoing amount. Two activity rows are displayed for a Self-Send; 1) the outgoing amount + fee, 2)  the incoming amount.
- [ ] Self Send Details: Added a specific design for the outgoing Self Send Transaction Details (with split amount to self / fee).
- [x] Bitcoin Asset Overview: The ‘On-chain BTC’ label has been renamed to 'BTC' to be more noob-friendly. The distinction is now between BTC & Instant BTC.
- [x] Bitcoin Asset Overview: A dollar conversion element has been added to the header, allowing users to see the dollar value of their Bitcoin balance.
- [x] Settings > General > Bitcoin Unit: The 'Bitcoin unit' setting has been renamed to 'Default unit' setting, with USD (or other local currency chosen by user) added as an option below Bitcoin and Satoshis. The user can also still cycle through units—BTC, Satoshis, and Dollars—or any other currency chosen as the local currency, simply by tapping on the total wallet balance. This changes the balance denomination on the fly. In the event that the user doesn't discover this tapping behavior, this setting offers a manual method to alter the balance denomination.

**Other Updates:**

- [x] Settings > Privacy: 'Require PIN when idle' has been added to the Figma to reflect the feature added in build 53.
- [x] LN onboarding intro: The copy for the instant payments onboarding frame for residents of the United States and Canada has been updated.
- [ ] LN manual channel with external node: A flow has been added to allow users to manually open a channel to a remote node, using only a spending balance (local balance).
- [x] LNURL-channel: This has been moved to a different part of the Figma board. The frames have been updated to better reflect the spec.
- [x] Closed channel event: The copy for this frame has been updated. A modal popup will appear each time a channel is closed by the peer (not initiated by the user).
- [ ] LN onboarding: The 80% cap has been removed. The slider behavior has been updated to snap to 80% when less than 90% and snap to 100% when more than 90%.
- [x] LN quick onboarding: The same button for custom amount input is now used as in the Custom Setup (renamed to 'Enter Amount').
- [x] LN setup time out: The heading has been changed to 'Please keep Bitkit open' (from ‘Timed Out’).
- [x] LN Channel overview: Minor visual changes have been made to connection states for clearer distinction.
- [x] Beta risk warning: The specific guidance amount ($10) has been removed, instead the advice is more generic ‘We recommend using only small amounts while Bitkit is in beta'.
- [x] Enter PIN: A button has been added to force a retry of Face ID or other biometrics after a failed scan (for example when the fingerprint reader was dirty).
- [x] Send/receive flow: Users can now also tap the amount in the send flow or receive flow to quickly change to USD/BTC/sats (For demonstration purposes, for the prototype this feature is only available in the on-chain send flow. To activate the on-chain send flow within the prototype, tap the paste button in the send flow).
- [x] User offline: The custom offline error message row has been replaced by a regular toast message.

**Comment by pwltr** [comment]
For the open items:

> LN onboarding: The 80% cap has been removed. The slider behavior has been updated to snap to 80% when less than 90% and snap to 100% when more than 90%.

@ovitrif is working on this afaik

> LN manual channel with external node: A flow has been added to allow users to manually open a channel to a remote node, using only a spending balance (local balance).

This is blocked, see https://app.asana.com/0/0/1205862969450147/f

> Self Send Activity: Self-send activity has been updated to include the fee for the outgoing amount. Two activity rows are displayed for a Self-Send; 1) the outgoing amount + fee, 2)  the incoming amount.

@coreyphillips @aldertnl I need some info on this, if I remember correctly there was some discussion on this, what was the outcome? @coreyphillips any progress on this, maybe also something in beignet?

**Comment by aldertnl** [comment]
The topic of self-sends has been discussed at length (a year ago), and as far as I can remember, and as has been approved,  everyone involved was eventually onboard with this solution: 
<img width="345" alt="image" src="https://github.com/synonymdev/bitkit/assets/81586998/29dc2a8a-e17b-4bfd-bae2-ce0b2ba39a2d">
<img width="831" alt="image" src="https://github.com/synonymdev/bitkit/assets/81586998/ba9be90f-66ae-4ba7-817c-d9bacd0abc71">

**Comment by coreyphillips** [comment]
@pwltr @aldertnl This has been discussed. On multiple occasions. Self-send should not appear as a separate transaction. 
1. It is confusing for the user as it will appear that more than one transaction has occurred. This breaks the consistency of the app's current activity feed.
2. It breaks external wallets that were imported into Bitkit that may contain transactions with several outputs.

The previous solution discussed was to include one activity row. If a certain amount in the tx was a self-send we include that fact in the tx detail view. If we want that information included in the activity row itself I recommend including that value in a smaller font, in parentheses, beneath the existing larger font value. Ex: (Self-Send: 5000)

**Comment by ovitrif** [comment]
> For the open items:
> 
> > LN onboarding: The 80% cap has been removed. The slider behavior has been updated to snap to 80% when less than 90% and snap to 100% when more than 90%.
> 
> @ovitrif is working on this afaik
> 

This was put **on hold** for the time being, we've discussed last week and concluded to address this flow with on-chain swap via Blocktank, which is still to be prioritized.

**Comment by aldertnl** [comment]
Regarding self-sends, the pros and cons of each approach were discussed in a UX call in the summer of 2023 on July 17. It appears the decision was made to go for the above solution (see screenshots), as it was included in prototype handoff v41 and the ticket was closed. https://github.com/synonymdev/bitkit/issues/1071

**Comment by coreyphillips** [comment]
Having it approved during a meeting I was absent from does not nullify the items I mentioned above.

**Comment by aldertnl** [comment]
As mentioned in that previous ticket: 
> While it's technically a single transaction, conceptually and mentally it's understood as two parts by regular joe. When a user sends funds, they naturally anticipate a decrease in their wallet balance. And when it concerns a self send, they also expect these funds to re-enter their wallet. This interpretation aligns with the handling of self-sends by most wallets and resonates with conventional transactional concepts. If needed, we can delve deeper into this topic during a UX call, should you believe this design decision could benefit from a broader range of perspectives.

Its seems odd that you were not in the call where this specific topic was discussed and a decision was made. If you feel the need to reopen this discussion, I guess we can.

**Comment by pwltr** [comment]
> It is confusing for the user as it will appear that more than one transaction has occurred. This breaks the consistency of the app's current activity feed.

I don't think we need to hold on to the 1-to-1 mapping in the activity necessarily, if it makes it clearer to the user what happened, see also the transfer activity items:

![transfer](https://github.com/synonymdev/bitkit/assets/8538369/35a0bbd8-ee23-4ec1-8e8c-e6c58c78c764)

> https://github.com/synonymdev/bitkit/issues/1071

Thanks forgot there was an issue already. @JeanlChristophe I think we can close this and continue discussion in https://github.com/synonymdev/bitkit/issues/1071 if needed.

**Comment by coreyphillips** [comment]
I would argue the following activity log and overall balance situation is confusing, which is why I'm pushing back against separate activity row entries such as this:

Balance: 30000

Activity Log:
- Sent To Self: 9,500
- Sent: -5000
- Received: 15,000
- Received: 20,000

Adding sent-to-self values as a sub-entry of the single activity item is more consistent with the current design of the activity list and doesn't make it look like a separate/additional transaction has occurred.

**Comment by JeanlChristophe** [comment]
Closing this ticket, let's continue here #1071
