### ISSUE TITLE
Look up output index when force closing

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1561]

**Comment by JeanlChristophe** [comment]
that's the address index fix for react-native-ldk. I'm holding onto that until we publish the next release since it will require more internal testing.

**Comment by JeanlChristophe** [comment]
LDK should give us the ouput @Jasonvdb / What do you think of?

**Comment by Jasonvdb** [comment]
I might be missing some context here about the original discussion?

**Comment by JeanlChristophe** [comment]
already merge
