### ISSUE TITLE
Data Backup failed toasts

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1566]
we keep getting Backup Failed toasts when i switch back to the app, these toasts should only show when there is a real problem, not because the app resumed faster than the underlying service.

(John, v101)

![Image](https://github.com/synonymdev/bitkit/assets/46056211/46317410-1bb1-44a7-b1b4-3d76a801ee08)

**Comment by pwltr** [comment]
I can't find this toast anywhere in the code, @limpbrains has this already been removed?

**Comment by limpbrains** [comment]
It is a Figma screenshot

**Comment by BitcoinErrorLog** [comment]
Correct, the screenshot is not accurate to the toast I saw, I think it says "backup failed"

**Comment by pwltr** [comment]
While I can reproduce this on the latest public release it doesn't seem to happen anymore on master. Needs to be retested with next release.
