### ISSUE TITLE
[Bug]: onchain funds has disapeared

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1573]
### Describe the bug

I had 210665 sats when I created a transaction for myself of 547 sats.
The onchain amount has disappeared. Now I only have offchain funds.

![Screenshot_20240221-120059](https://github.com/synonymdev/bitkit/assets/46056211/1a0f7c02-c07c-4916-98c9-e307d9000fb7)

### Operating system

GrapheneOS

### Bitkit version

V106

**Comment by JeanlChristophe** [comment]
![Screenshot_20240221-121307](https://github.com/synonymdev/bitkit/assets/46056211/5e1a2ef9-0977-4ff0-9f21-493d98b4daa3)

**Comment by JeanlChristophe** [comment]
Once I r"Rescan adresses", My funds have been found

**Comment by coreyphillips** [comment]
Looking into it. Potential duplicate of #1552.

**Comment by coreyphillips** [comment]
Unable to reproduce on my end at the moment.

**Comment by coreyphillips** [comment]
I have not been able to reproduce this issue on my end. I'm assuming it has been resolved. Will close unless someone reports that we're still having issues here.
