### ISSUE TITLE
[Bug]: Bad UX when trying to send amounts simular to fee

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1574]
### Describe the bug

After enter amount, next screen doesn't show me the amount, I can't adjust fee, I can't send it

### Reproduce

Try to send 700 sats onchain

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/155891/a4e7fce3-437c-4e0d-b52e-ba7fbd9d3103

https://github.com/synonymdev/bitkit/assets/155891/08d1efec-948d-45b8-9fe8-b622cc11b716

### Operating system

iOS

### Bitkit version

v106

**Comment by limpbrains** [comment]
Same thing happens even for 20 000 sats.
UTXO: 1500, 40 000, 20 000 (unconfirmed)

**Comment by coreyphillips** [comment]
Can reproduce for small amounts. Working on a potential fix.

**Comment by coreyphillips** [comment]
Resolved by #1585
