### ISSUE TITLE
[Bug]: When I get to the confirmation page, I no longer have an amount.

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1575]
### Describe the bug

When I get to the confirmation page (ochain tx), I no longer have an amount. And it doesn't matter what the amount was.

### Reproduce

1. Go to 'scan an invoice'
2. Insert an amount
3. See error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/a61d463b-0cf6-40cd-a777-af1ef2612668

### Operating system

GrapheneOS

### Bitkit version

v106

**Comment by JeanlChristophe** [comment]
Same issue for Pav and Ivan

**Comment by coreyphillips** [comment]
Potentially resolved as of [this PR](https://github.com/synonymdev/bitkit/pull/1585).

**Comment by JeanlChristophe** [comment]
Tested and Ok. Closing the ticket.
