### ISSUE TITLE
[Bug]: Duplicated onchain receive notification

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1577]
### Describe the bug

After creating a fresh wallet I received onchain funds and the notification for it. After the next block it shows another notification for the same transaction.

### Reproduce

1. Receive onchain tx
2. Hide receive notification
3. Wait for next block
4. See duplicated receive notification

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/378c8090-be43-4eb7-a90a-dd2c9b2c1e2b

### Operating system

iOS

### Bitkit version

106

**Comment by pwltr** [comment]
@coreyphillips It looks like `transactionReceived` message is sent twice: once when seen in the mempool and another time when confirmed.

**Comment by coreyphillips** [comment]
Should be resolved as of [this PR](https://github.com/synonymdev/bitkit/pull/1610).

**Comment by pwltr** [comment]
Looks good, closing here.
