### ISSUE TITLE
Unable to send funds / manual coin selection 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1578]
### Describe the bug

tried sending 20k sats and tried to select "Normal Fees" since the default was at 1/sat vbyte. 
I then turned on Manual coin selection, selected the biggest UTXO which was more than half of the amount I was trying to send - still was unable to proceed

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/4ff458a9-f593-4d98-ae1d-d289e89125d0

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v106

**Comment by coreyphillips** [comment]
Unable to reproduce on my end at the moment on live Android device using v106. The uploaded video seems to not show the coin selection screen in the tx flow which is something that should appear if coin selection is enabled.

**Comment by JeanlChristophe** [comment]
@coreyphillips can you ask pav seed and test it? Thanks

**Comment by JeanlChristophe** [comment]
#1586

**Comment by coreyphillips** [comment]
May be resolved as of [this PR](https://github.com/synonymdev/bitkit/pull/1585). May ask to try again during next testing session.

**Comment by JeanlChristophe** [comment]
Tested and Ok. Closing the ticket.
