### ISSUE TITLE
[Bug]: LN payment showed as received in bitkit, but Failed in WOS

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1580]
### Describe the bug

I was paying from WOS to bitkit. Both apps are on my phone. WOS showed that payment Failed (55 sats). But I can see it in activity list in bitkit. But invoice is different. It is the same as another successfull payement (12 sats).

Both was 0 amount invoices

### Reproduce

1. pay from WOS 
2. see error

### Screenshots / Recording

![photo_2024-02-21 13 54 22](https://github.com/synonymdev/bitkit/assets/155891/8926ab53-cd30-43f4-b57f-f208ff0e206e)
![photo_2024-02-21 13 54 21](https://github.com/synonymdev/bitkit/assets/155891/64f3c735-f09d-498e-bafc-a44ff1a95d75)
![photo_2024-02-21 13 54 20](https://github.com/synonymdev/bitkit/assets/155891/acf9f19b-7688-457c-84ba-05263839eae6)
![photo_2024-02-21 13 54 19](https://github.com/synonymdev/bitkit/assets/155891/0153892b-429c-4ef8-8ed1-bb825243707a)
![photo_2024-02-21 13 54 17](https://github.com/synonymdev/bitkit/assets/155891/a224611b-a456-40d7-92d5-1006cec8d484)

### Operating system

iOS

### Bitkit version

v106

### Log output

[bitkit_ldk_logs_1708523707503.zip](https://github.com/synonymdev/bitkit/files/14360316/bitkit_ldk_logs_1708523707503.zip)

**Comment by Jasonvdb** [comment]
Fix [here](https://github.com/synonymdev/react-native-ldk/pull/236). Any 2nd attempt at paying a bitkit invoice would overwrite the first payment even if it had a different received amount. This PR blocks duplicates.
