### ISSUE TITLE
[Bug]: 0 amount LN invoices doens't always work on Android

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#1581]
### Describe the bug

bitkit ios -> bitkit android, 0amount - works
bitkit android -> bitkit ios, 0mount - doesn't work
bitkit android -> bitkit ios, 1 satoshi - works
bitkit android -> WOS, 0 amount - doesn't work
bitkit android -> WOS, 5 sats - works
bitkit android -> phoenix, 0 amount - works
bitkit android -> clightning, 0 amount - doesn't work

### Reproduce

see above 

### Operating system

Android

### Bitkit version

v106

### Log output

[bitkit_ldk_logs_1708524918614.zip](https://github.com/synonymdev/bitkit/files/14360593/bitkit_ldk_logs_1708524918614.zip)

**Comment by JeanlChristophe** [comment]
@Jasonvdb did you had time to have a look?

**Comment by Jasonvdb** [comment]
I think this might be resolved in LDK 121. Almost done with the [android update](https://github.com/synonymdev/react-native-ldk/pull/226) and then will confirm.
