### ISSUE TITLE
[Bug]: Onchain balance incorrect after wallet restore having LN funds

### ISSUE THREAD

**Issue by ovitrif** [synonymdev/bitkit-react-native#1584]
### Describe the bug

Restoring wallet with LN funds doesn't show correct onchain balance.

### Reproduce

1. Need a wallet with onchain funds and recent LN channel funding transaction
2. Make sure to backup your wallet, then delete app & reinstall it
3. On startup, restore using your mnemonic
4. ❌ Notice onchain balance is incorrect
5. 🏥 Can be fixed with 'rescan addresses', but after reinstall same problem occurs

_always repros on my end_

### Screenshots / Recording

| Freshly restored                   | After 'rescan addresses' |
| ------------------------ | ------------------------ |
| <img width="300" src="https://github.com/synonymdev/bitkit/assets/4588074/6b5c85cc-4b60-4b49-b631-094deb2bdaa6"> | <img width="300" src="https://github.com/synonymdev/bitkit/assets/4588074/6a8721bb-3a1c-4c12-90bc-2a1ef4cfc24a"> |

### Operating system

Android 14

### Bitkit version

v106

**Comment by ovitrif** [comment]
After sending all LN funds to savings, the total balance showed again the wrong `144 899`.
A pull-to-refresh fixed it.

**Comment by JeanlChristophe** [comment]
#1586 ?

**Comment by coreyphillips** [comment]
This should be resolved as of the latest commits. Will close shortly unless others are still reporting this as an issue.
