### ISSUE TITLE
Send amount too small (unable to send sats) 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1601]
### Describe the bug

when trying to send onchain tx Bitkit to Bitkit via Native Segwit - I ge an error of "send amount too small" - my onchain balance is 50k sats, I am trying to send 20k sats. 

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/e72dd404-d0a7-44f9-a20d-cafb1e5e05b0

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v110

**Comment by JeanlChristophe** [comment]
Update: it doesn't work while scanning the QR code but worked with the adress string
