### ISSUE TITLE
Replace nodejs-mobile-react-native functions with Rust functions via UniFFI

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1617]

**Comment by coreyphillips** [comment]
Replace `nodejs-mobile-react-native` functions with Rust functions via UniFFI using the following:

- [Android](https://forgen.tech/en/blog/post/building-an-android-app-with-rust-using-uniffi)
- [iOS](https://forgen.tech/en/blog/post/building-an-ios-app-with-rust-using-uniffi)
