### ISSUE TITLE
[Bug]: Fees indication

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1619]
### Describe the bug

I'm trying to make an onchain transaction of 10,000 sats, and it says that the fees will be $0.15, but when I continue, the correct fees are charged.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/95ce5e7b-2ce0-44e2-bc92-1392b6ca92ec

### Operating system

GrapheneOS

### Bitkit version

v111

**Comment by coreyphillips** [comment]
To reproduce:

- Create a transaction for 5000 sats.
- Tap "Continue". In a high fee environment the fee should get set to "Custom" at a lower sat per vByte.
- Navigate Back.
- Tap "Continue" again without adjusting the sat amount.
- Observe that "Custom" is now "Normal", but at the same fee rate.

**Comment by catch-21** [comment]
I currently see $0.11, which appears to be the value for 1sat/vB. For some reason it displays the custom value which defaults to 1sat/vB.

**Comment by catch-21** [comment]
Tested on 658b9f2bd22d2ca63893a89dc56f47a054546d79
I'm no longer able to reproduce the original issue 👍 
I am seeing what JC described in their last comment, 'Normal' when it should be 'Custom' 👎  see vid:

https://github.com/synonymdev/bitkit/assets/74595920/a12ac82e-5b23-4551-b253-b92309cdbfe2

Current fees are Slow=5 Normal=18 Fast=21

@coreyphillips Do you consider this related here or a separate UI bug?

**Comment by coreyphillips** [comment]
This would be a new issue.

**Comment by catch-21** [comment]
Raised https://github.com/synonymdev/bitkit/issues/1896
