### ISSUE TITLE
[Bug]: Restored backup not including all data

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1620]
### Describe the bug

I restored a backup made on v108 (Android) onto v111 (iOS) and it worked mostly fine but some data was missing:
- some (LN) transactions missing in activity
- currency preference was not backed up/restored (€ -> $), maybe all settings(?)
- news widget not restored, other widgets ok
- Contacts not always restored

### Operating system

iOS

### Bitkit version

v111

**Comment by Jasonvdb** [comment]
Some new backup labels were added to the backup server and pushed to staging but not production yet. I can point Bitkit to my own backup server and restore everything without issue. 

Will close once prod server is up to date.

**Comment by Jasonvdb** [comment]
This should be fixed now

**Comment by catch-21** [comment]
Tested on ae82edd7a3ab8ff771cbf945729e41c43c5ed1f2 mainnet
All appears to be working now. Closing.
