### ISSUE TITLE
Wrong confetti when sending sats via LN

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1621]
### Describe the bug

tried sending funds via LN from Bitkit to Bitkit (value was 5 sats) - got green confetti indicating that it was sent on chain, but the tx history shows correctly that it was indeed a LN transaction. 

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v 111

**Comment by thisispav** [comment]
[bitkit_ldk_logs_1711549021013.zip](https://github.com/synonymdev/bitkit/files/14774600/bitkit_ldk_logs_1711549021013.zip)

**Comment by JeanlChristophe** [comment]
Looked on figma and it is the correct behaviour. Closing it
