### ISSUE TITLE
[Bug]: Send: "not enough funds" when trying to pay onchain address with LN funds only

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1626]
### Describe the bug

A user can find themselves in a state where they only have funds in spending (LN) but no balance on savings (onchain). When trying to pay an onchain only address the wallet will show a non-descriptive error of  "Not enough funds - You need xxx more to pay this invoice".

### Operating system

Android, iOS

### Bitkit version

latest

**Comment by JeanlChristophe** [comment]
This is the expected behaviour. if a user want to pay with onchain founds, he can move his LN founds to onchain.

**Comment by JeanlChristophe** [comment]
update: The error message says "Not enough funds" even though the user has funds. Can be confusing to noobs. This issue was raised from a developer in Viareggio

**Comment by aldertnl** [comment]
We should be more descriptive and specific here. 'Not enough funds in savings' or 'Not enough funds in spending balance'.

**Comment by pwltr** [comment]
Can't reproduce this, the toast message is accurate: "Insufficient Savings" - "More ₿ needed to pay this Bitcoin invoice."

**Comment by catch-21** [comment]
Verified in v124. 'Insufficient Savings' message now displayed in this scenario.
