### ISSUE TITLE
[Bug]: Restoring your seed is very slow

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1634]
### Describe the bug

This error has occurred several times with John, me, Aldert, etc. When I tried to restore my seed, I had a black screen for more than 10 seconds and then the rocket arrived.
Normally I should not have a black screen.

### Operating system

Graphene OS and iOS

### Bitkit version

v113

**Comment by pwltr** [comment]
This was just a UI issue of the loading screen being hidden. 10 seconds sounds normal for a backup restore. Fixed in https://github.com/synonymdev/bitkit/pull/1696

**Comment by JeanlChristophe** [comment]
not fix

**Comment by pwltr** [comment]
This needs https://github.com/synonymdev/bitkit/pull/1748 and then a couple more changes.

**Comment by JeanlChristophe** [comment]
@catch-21 can you please have a look?

**Comment by catch-21** [comment]
@pwltr please let me know when all the potential fixes are in the release branch so I can verify

**Comment by catch-21** [comment]
It's kinda worse with the new design because it first shows the rocket that doesn't get to 100%, then black screen (15s for me), then rocket again to 100% (sits at 100% for 10s before proceeding)...


https://github.com/synonymdev/bitkit/assets/74595920/babc6da6-729e-45ac-8537-a16961f1d1ef

**Comment by ovitrif** [comment]
@limpbrains and @catch-21 , what do you think of this small fix to mitigate this issue?

> As we discussed the issue to fix here is not showing the rocket screen twice restarting from 0%, with a black screen between it.

A more-polished fix could still be done, but as pointed out earlier this week by @limpbrains it would need a big-enough refactoring of the restore flow which we postponed to the 2nd half of next month for stability reasons of the upcoming release.

https://github.com/synonymdev/bitkit/assets/4588074/223ab314-7b2d-45f6-a4b3-602f24d410f5

**Comment by ovitrif** [comment]
Opened PR #1836 with the proposal from above.

**Comment by catch-21** [comment]
Tested on 9e848b8443daa828ad40fc6822640fcd013bf39f.
Although the is no change in the time taken to restore, we no longer have any long periods of black screen. This is much improved UX and satisfactory to the original problem highlighted by this issue.
