### ISSUE TITLE
Testing on Regtest - Updated Balance but no confetti

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1637]
### Describe the bug

Testing on regtest - my balance updated but there was no confetti, only after 7-8 seconds did I receive confetti (not sure if it's a different environment but there is a substantial lag between the two)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v113

**Comment by JeanlChristophe** [comment]
I can't reproduce it. Closing it.
