### ISSUE TITLE
[Bug]: Confetti screen when sending doesn't display details

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1638]
### Describe the bug

After sending BTC onchain a "Bitcoin Sent" confetti screen is displayed but without any transaction details, the "Details" button is also disabled. Waiting does not display the information. If app is minimised and reopened then the information is correctly displayed. It should display the information asap or at least indicate that it is still loading.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/cc1d7813-8b16-494b-8d87-9ed3565396f2

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v1.0.0-beta.113

**Comment by catch-21** [comment]
It does eventually show. This is probably timing-related and can potentially occur in production environment if electrum is slow to respond with these details.

**Comment by pwltr** [comment]
We should show the amount since we do know it but for the 'Details' to be available we need to wait for the transaction to be in the mempool.

**Comment by catch-21** [comment]
Tested on 2c5b07726fd35cb796a9566c47d0f6c36fda4ef4
Although the 'Details' button can take a bit of time to enable, showing the amount sent makes this screen immediately useful. An acceptable solution to this issue.
