### ISSUE TITLE
Channel Open Failed 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1642]
### Describe the bug

https://synonymworkspace.slack.com/archives/C02MYL829U0/p1712917304271619
link to the internal slack Bot 

### Screenshots / Recording

[bitkit_ldk_logs_1712917639692.zip](https://github.com/synonymdev/bitkit/files/14957541/bitkit_ldk_logs_1712917639692.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v113

**Comment by thisispav** [comment]
Received funds onchain, tx was confirmed, tried opening a channel via the Quick Setup, got Payment Successful (Paid) but then got the error

Order ID - a0655d03-c838-40b0-8258-e07363021462

**Comment by JeanlChristophe** [comment]
Fixed.
