### ISSUE TITLE
Discrepancy with balance received when opening a CJIT

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1644]
### Describe the bug

I couldn't open a normal channel so I tried CJIT instead (using Phoenix)
Got notification about how much I am going to be charged in fees as well as the amount I will receive 14 471 (shown on the image) but instead I received 12919.
This will be confusing to users. 

### Screenshots / Recording

![photo_2024-04-12_14-51-04](https://github.com/synonymdev/bitkit/assets/119061223/8cfd082f-9c5d-4d67-842f-623e881f4a12)
![photo_2024-04-12_14-51-05](https://github.com/synonymdev/bitkit/assets/119061223/aab73326-4464-46d7-aa73-a57abc9b2f81)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v 113

**Comment by thisispav** [comment]
Logs attached 
[bitkit_ldk_logs_1712923251893.zip](https://github.com/synonymdev/bitkit/files/14958396/bitkit_ldk_logs_1712923251893.zip)

**Comment by thisispav** [comment]
again discrepancy between an amount a user is shown in Bitkit prior to paying CJIT and after (different amount received) 
![photo_2024-04-19_12-49-48](https://github.com/synonymdev/bitkit/assets/119061223/4ede608d-5304-4ab0-b033-4e232ed2aae5)
![photo_2024-04-19_12-49-50](https://github.com/synonymdev/bitkit/assets/119061223/a48b8d2e-ac0a-4499-a357-264484b2264b)
![photo_2024-04-19_12-49-49](https://github.com/synonymdev/bitkit/assets/119061223/0049d01a-c120-4814-b252-8f6f2edc9354)

**Comment by catch-21** [comment]
Tested on b47d58d89e810df89be21509462b8e22490d7c0a
LGTM.
