### ISSUE TITLE
Unable to pay using SlashPay despite having LN funds (via CJIT)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1647]
### Describe the bug

Trying to pay a contact but payment defaults to on-chain payment despite me having LN balance via CJIT. 

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/1d303ce0-652b-4fb8-aac7-bb42c6eb420d

![photo_2024-04-12_15-49-32](https://github.com/synonymdev/bitkit/assets/119061223/631d9aaf-de97-4621-a107-b572e9070139)
[bitkit_ldk_logs_1712926465393.zip](https://github.com/synonymdev/bitkit/files/14958980/bitkit_ldk_logs_1712926465393.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v113

**Comment by JeanlChristophe** [comment]
is working now.
