### ISSUE TITLE
[Bug]: Zero fee for ln address payment

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1648]
### Describe the bug

When sending payment to a bitfinex LN address for 123 sats I was charged 0 fees. This happened twice. Fee should always be at least 1 sat.

### Screenshots / Recording

![image](https://github.com/synonymdev/bitkit/assets/74595920/6ed8a41a-0333-4f40-abc7-c913c8eee90a)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v1.0.0-beta.113

**Comment by pwltr** [comment]
> Fee should always be at least 1 sat.

Fees can be 0 on LN, for your route Bitkit -> Blocktank -> Bfx that is very likely the case. I don't think there is an issue here, you could confirm by checking If the full amount of 123 arrived at the recipient. Then there was no routing fee.
