### ISSUE TITLE
[Bug] Bitcoin headlines

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1649]
### Describe the bug

We need to change our sorce feed for Stackernews. Stacker news changed to be topic based, we need to change our source feed to their bitcoin topics

### Operating system

Graphene OS, Iphone, Android

**Comment by pwltr** [comment]
This needs to be changed in the config file on the server.

`"https://stacker.news/rss"` -> `"https://stacker.news/~bitcoin/rss"`

**Comment by pwltr** [comment]
Can see the feed here:
https://webrelay.slashtags.to/tdm8gwcuh6nfw4w8remadpzid9cff4tpoyazeokzbrfnjrxyf9ho/Bitcoin%20Headlines/feed/headlines

**Comment by catch-21** [comment]
Tested on 8de4fa74f41be7613c28bbcd36be93d50948aa74

The feed looks correct although now we don't link directly to the Stacknews article. Instead on tap it navigates straight to the source. This raises concerns that we are now delegating trust to StackerNews to immediately filter all malicious content. It would be best if we only ever link to Stacker News article and let the user decide whether to proceed to the embedded link having seen the url and comments first.

See discussion: https://synonymworkspace.slack.com/archives/C01H106JRQB/p1713167737483979?thread_ts=1712927784.334309&cid=C01H106JRQB

<img src="https://github.com/synonymdev/bitkit/assets/74595920/c52b49e4-965a-4686-9887-f50ba2754a23" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/296ca658-14c4-46f0-948e-785efe3004c1" width="300">

**Comment by pwltr** [comment]
Stacker news is not the only source of articles, you can see a list of default rss feeds [here](https://github.com/synonymdev/slashtags-widget-news-feed/blob/master/config/config.example.json). 

I think you mean to reopen this one: https://github.com/synonymdev/bitkit/issues/1711. But in my opinion it is fine since these links are curated by the chosen blogs.

**Comment by catch-21** [comment]
No, it's fine. I have only seen StackerNews articles in the widget so assumed that was the only source.
