### ISSUE TITLE
[Bug]: Missing details when closing a channel

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1651]
### Describe the bug

I've just closed my channel and I don't have any information. 
Is missing:

- Transfering card
- transaction history
- Ln balance that is getting closed

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/3764e5d0-facb-4cb8-9653-12971f97c14b

### Operating system

GrapheneOS

### Bitkit version

v113

**Comment by pwltr** [comment]
I will take this one @coreyphillips

**Comment by pwltr** [comment]
@JeanlChristophe Can you post a screenshot of detail page for the channel in the settings?

**Comment by JeanlChristophe** [comment]
Missed the notification, sorry @pwltr . I do not have access to the seed, sorry.

**Comment by pwltr** [comment]
I think we have some other open issues similar to this, so I'm closing this. Can't track funds without any details.
