### ISSUE TITLE
[Bug]: Restoring using a seed with no backup displays successful wallet restored from backup message

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1683]
### Describe the bug

When restoring wallet using a newly generated seed, or a seed that has never been used with Bitkit before, the "Wallet Restored." screen is displayed stating "You have successfully restored your wallet from backup".

Unless our intention is for "backup" to mean anything derived from the seed, which could be on-chain data only, or in combination with profile, lightning, contacts etc., It could be useful to inform the user when a profile backup did not exist and therefore has not been restored; perhaps they were expecting one (e.g. forgot to use passphrase).

### Reproduce

1. With a clean Bitkit install (wiped)
2. Restore using a newly generated seed phrase
3. Observe "Wallet Restored." screen, same as attached screenshot.

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/65d02a29-f3d4-4765-a913-f6b27a74db6a" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v1.0.0-beta.113

**Comment by JeanlChristophe** [comment]
Expected behaviour. Closing the ticket.
