### ISSUE TITLE
"Reconnecting To Electrum" msg error

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1688]
The message is currently very intrusive and we have seen it too many times. See the internal discussion[ here](https://synonymworkspace.slack.com/archives/C01H106JRQB/p1713366664542869). 

![Image](https://github.com/synonymdev/bitkit/assets/46056211/1d622796-313f-44fe-88d5-4c462bee18d7)

@coreyphillips [recommends not triggering the message](https://synonymworkspace.slack.com/archives/C01H106JRQB/p1713367605674729?thread_ts=1713366664.542869&cid=C01H106JRQB) with a delay but after a certain number of times when the connection fails to connect. 

- [ ] Identify the time between each reconnection attempt.

- [ ] Identify[ the delay before it takes to give up](https://synonymworkspace.slack.com/archives/C01H106JRQB/p1713368648449139?thread_ts=1713366664.542869&cid=C01H106JRQB). #1686 

- [ ] Once the delay are known, use @JeanlChristophe  and @aldertnl  to identify the number of attempts to define before triggering the error message.

- [ ] Integrate the solution.

**Comment by catch-21** [comment]
LGTM in `master` and `release-115`
