### ISSUE TITLE
[Bug]: Data connection issue

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1694]
### Describe the bug

A user shared on twitter this error msg.

https://twitter.com/steepdawn974/status/1779115637870150015

From @Nuhvi: "This error tells me that Bitkit, couldn't decrypt the Slashtags primary key from the OS's keychain. That key should always be easy to calculate on the fly from the Bitcoin master key, but that too is probably encrypted on the keychain."

### Screenshots / Recording

![GLCwMDNWoAAha6i](https://github.com/synonymdev/bitkit/assets/46056211/1520eddb-0d12-4e8a-bf95-42bdd6c4d49e)

### Operating system

Android

### Bitkit version

n/a

**Comment by JeanlChristophe** [comment]
@catch-21 it's been a long time that I didn't see this issue. can I put it in pause?

**Comment by catch-21** [comment]
I've never seen this or heard anyone else mention this issue. We can close.
