### ISSUE TITLE
[Bug]: Error msg: Unable To Save Profile when uploading image

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1695]
### Describe the bug

When I try to modify my profile (text or picture), I get the error message 500, but when I next come back to my profile, the modification has occurred.

Same issue from a old profile or a new one.

### Reproduce

1. Go to 'your profile'
2. Modify your profile
3. Save

### Screenshots / Recording

![Screenshot_20240419-100423](https://github.com/synonymdev/bitkit/assets/46056211/7f766786-c40a-4c71-adfc-b1d8095d46bc)

https://github.com/synonymdev/bitkit/assets/46056211/d3ee9f5b-6ab2-49b4-a324-49993ece3779

### Operating system

Android and GrapheneOs

### Bitkit version

v113 and v114

**Comment by catch-21** [comment]
Although the profile updates are stored locally on the device, the changes are not updated for your profile on other people's devices. This tells me that the update has not been stored in slashtags.

**Comment by pwltr** [comment]
Will be fixed server-side.

**Comment by JeanlChristophe** [comment]
It's look like the same issue here with v144

![Screenshot_20241227-102117](https://github.com/user-attachments/assets/8aa2bf46-23f1-4d2a-81fc-eab59fd5bb56)

**Comment by catch-21** [comment]
This is a long-running issue we've had on and off over the months.
See internal discussions: https://synonymworkspace.slack.com/archives/C01H106JRQB/p1717746445437739

My experience with this today captures in a few videos (note that the image only updates temporarily locally, not being backed up)

<img src="https://github.com/user-attachments/assets/cc53edf3-d275-4a3a-bb79-0417f2c63787" width="300">

https://github.com/user-attachments/assets/d06ff04e-92cc-4b0f-b057-fcfec86f836e

https://github.com/user-attachments/assets/29a231db-23c8-48c5-83d8-c5e6828f51eb

**Comment by catch-21** [comment]
This has been resolved by storage cleanup, see https://synonymworkspace.slack.com/archives/C032C8X4JGL/p1735291260929509
