### ISSUE TITLE
Fee estimation in Bitkit is incorrect (we are potentially overpaying x3 the current market rate)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1698]
### Describe the bug

when we try and send funds (20,000 sats) to each other via contact payment feature - we get either $0.14 to $0.18 cents potentially overpaying up to x3 ($11 or 18,000) the current market rate (currently below $6) - please see video below.

JC and Pav experience this issue. 

### Screenshots / Recording

![fee estimation currently in mempool](https://github.com/synonymdev/bitkit/assets/119061223/be81326a-eec8-425f-8410-0b3984da4e27)

https://github.com/synonymdev/bitkit/assets/119061223/4b5f2950-1e28-458e-b13f-a1f905ebf150

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v114

**Comment by JeanlChristophe** [comment]
I overpaid x3 when closing a channel
https://mempool.space/tx/808520f7ecf2ccd9d46c3d0011fcd04eea6aaa691592cc4752cf0619ce9ffb34

**Comment by catch-21** [comment]
> we get either $0.14 to $0.18 cents

This issue is separate and covered by https://github.com/synonymdev/bitkit/issues/1619

**Comment by thisispav** [comment]
I try and send 20k sats back to JC - current fee rate is around 47 sats / vbyte, I tried setting up a custom amount of 50 sats /vbyte but instead of $4.40 I get almsot $13 bucks (20k sats or so)  

https://github.com/synonymdev/bitkit/assets/119061223/72756fce-44ed-423f-bde5-21676b5301e8

**Comment by JeanlChristophe** [comment]
Same for boosting a transaction, the fee estimation is wrong.

![Image](https://github.com/synonymdev/bitkit/assets/46056211/861e7daa-1cb9-45b4-a105-cf877877eb05)

**Comment by catch-21** [comment]
Pav and I just experienced BT overpaying by x8 for closing LN channel. We are both using V115 https://github.com/synonymdev/bitkit/commit/9ff423802faacd24a2e5f8fac7e31edd381c5ba6.

<img width="298" alt="Screenshot 2024-04-26 at 15 54 00" src="https://github.com/synonymdev/bitkit/assets/74595920/0870095e-3586-4a9b-811f-48e0a88af258">

<img width="298" alt="Screenshot 2024-04-26 at 15 54 31" src="https://github.com/synonymdev/bitkit/assets/74595920/e9bc9431-f0f4-4c3f-852f-aaca279811d8">

**Comment by coreyphillips** [comment]
Can you please check and relay what your fee estimates are in Settings?

**Comment by catch-21** [comment]
@coreyphillips my Default Transaction Speed is set to Normal.
The values in "Override Fees" are:
Minimum 6
Slow 33
Normal 37
Fast 41
Override is disabled.

**Comment by coreyphillips** [comment]
Thanks! That looks about right. I'm going to look into how we pass these fees off to LDK to ensure we're doing it correctly. It is possible that LDK determines this regardless of what we provide. If that's the case we'll need to look into if there's a way to override that behavior in order to bring these channel close fees down.

**Comment by coreyphillips** [comment]
@Jasonvdb, think we could be overpaying due to [this](https://github.com/synonymdev/bitkit/blob/11bff79a5b8fb57dd4d89e0083ad40c91fbfc48e/src/utils/lightning/index.ts#L221C1-L221C5) setting? If I remember correctly, don't we have that one configured quite a bit higher to ensure it doesn't cause a force close?

**Comment by Jasonvdb** [comment]
@coreyphillips no that setting is for regular channels which we don't use anymore. The setting below is for the anchor channels. Maybe the tx there is the sweeping which is the fast fee that might have been briefly very high?

**Comment by catch-21** [comment]
Why should the client be allowed to determine the price the LSP has to pay for a channel closure?
