### ISSUE TITLE
[Bug]: Custom fee too low required "5 bitcoin/vbyte" is not a useful suggestion

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1699]
### Describe the bug

When sending an onchain transaction with custom low sats/vbyte (e.g. 1) I see a "Fee is potentially too low" "current network conditions require that your fee should be greater than 5 bitcoin/vbyte" message.
Two issues here:
1. "5 bitcoin/vbyte" means something different to 5 sats/vB
2. 6 sats/vB is still way too low for current network conditions, would need at least 60 sats/vB (right now). Is this hard coded?

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/174e47fb-b2b7-401a-a296-11b4278d8d72" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

114

**Comment by JeanlChristophe** [comment]
@coreyphillips can you please change the bitcoin/vbyte for sats/vbyte, please?

**Comment by coreyphillips** [comment]
Looks like it was already adjusted:
https://github.com/synonymdev/bitkit/blob/0eb32fa15728c888fab03d4b915f56ac1061ed45/src/utils/i18n/locales/en/wallet.json#L33
