### ISSUE TITLE
[Bug]: Instant Payments Setting Up page displays ±10 minutes when it will actually take much longer

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1701]
### Describe the bug

When creating a self-funded LN channel, usually BT will use a fast fee rate but when it doesn't the transaction can take much longer than 10 minutes. After 30+ minutes I am still seeing this same message. Much like the inbound onchain transaction activities, it would be good if it adjusted this estimate to manage expectations.

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/114a7786-1f82-42c5-95f9-98b11e4d9c8d" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

114

**Comment by JeanlChristophe** [comment]
Cette estimation est donnée au moment de la création de l'ordre. Un block doit-être toutes les 10 min. 
- Des fois nous avons de sblocks toutes les 30 min, ce qui est pas possible à prévoir.
- Dans beaucoup de cas, les frais augmentent entre le moment où l'ordre a été créé et le prochain block. Ce qui n'est pas possible à prévoir de notre côté également.
