### ISSUE TITLE
Paykit payments issue - I received confetti for a tx and now there is no history of this tx in my Bitkit

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1707]
### Describe the bug

We were mayking paykit payments - I successfully sent to James and JC and vice versa. I received a confetti for 6 sats (see image from James's Bitkit below) but now I don't have a history of receiving this transaction. 

### Screenshots / Recording

![james to pav](https://github.com/synonymdev/bitkit/assets/119061223/55f8da44-fd47-4c8f-afd6-c95a4874dd56)
this is James screen from Bitkit

This is my screen with no history of this tx 
![photo_2024-04-19_15-38-55](https://github.com/synonymdev/bitkit/assets/119061223/74cf833e-6948-44ee-983e-fc404b382944)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v114

**Comment by JeanlChristophe** [comment]
fixed
