### ISSUE TITLE
[Bug]: Bitcoin Blocks widget hash text can fall out of view

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1708]
### Describe the bug

Bitcoin Blocks widget Merkle Root and Hash text can fall out of view to the right (see screenshot)

### Screenshots / Recording
<img src="https://github.com/synonymdev/bitkit/assets/74595920/d59706a2-2c67-4688-8e9c-3a5c9416d3dd" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

114

**Comment by pwltr** [comment]
This is an [upstream issue](https://github.com/facebook/react-native/issues/37511).
