### ISSUE TITLE
Bitcoin Headlines widget should only link to the article

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1711]
The Bitcoin Headlines widget can contain two links, one for the article (blue) and one to the reference link in the article (red). Given the reference link in the article could be anything (potentially malicious) we should not go directly to it from Bitkit. Instead we should make all hit areas in the widget link to the article itself.
![image](https://github.com/synonymdev/bitkit/assets/74595920/83477866-7aea-4a45-a1bf-91164be93594)

**Comment by JeanlChristophe** [comment]
duplicated https://github.com/synonymdev/bitkit/issues/1711

**Comment by catch-21** [comment]
Verified in v118
