### ISSUE TITLE
[Bug]: Transaction stuck pending with status "Payment canceled" with no indication how to resolve 

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1722]
### Describe the bug

Last week, I attempted to open a self-funded channel. The sent on-chain transaction didn't confirm and channel didn't open. I suspect this is because fees spiked and didn't come back down, and BT didn't use a high-enough fee or attempt to replace the transaction. After realising my channel wouldn't open anytime soon, I opened a CJIT channel and used that for some LN transactions. After a few days, the home screen still displays "transferring" balance (see first screenshot) although the self-funded channel has the status "Payment canceled", so the transfer will never complete. The on-chain transaction remains unconfirmed.

At this stage there is no indication to the user what to do. Can I get a refund? What if the transaction eventually confirms?

### Reproduce

The reproduction of this depends on how BT handles a volatile fee environment and channel setup transactions that haven't confirmed.

### Screenshots / Recording

1
<img src="https://github.com/synonymdev/bitkit/assets/74595920/64dfc31a-3edf-48af-9bde-ba661c920999" width="300">
2
<img src="https://github.com/synonymdev/bitkit/assets/74595920/82de207c-46d5-40e7-8306-f36d22fc993a" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

114

**Comment by JeanlChristophe** [comment]
there is a new status now: Refund available.

thanks
