### ISSUE TITLE
Upon locking the phone and unlocking it Bitkit doesn't require a pin (eventhough the security feature is enabled)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1738]
### Describe the bug

When I lock the phone and re-open it again, Bitkit doesn't require a PIN, even though the security feature is ON so the wallet is wide open.

### Screenshots / Recording

[bitkit_ldk_logs_1714118631573.zip](https://github.com/synonymdev/bitkit/files/15127268/bitkit_ldk_logs_1714118631573.zip)

https://github.com/synonymdev/bitkit/assets/119061223/22d58485-9305-4ae2-8315-d1f3c55dc805

### Operating system

Graphene OS Pixel 6S

### Bitkit version

V115

**Comment by catch-21** [comment]
I think this issue is just when resuming the app from minimised (whether the phone is being unlocked or not). It is probably best that the pin is required whether being opened fresh or being resumed.

**Comment by pwltr** [comment]
This is what the 'Require PIN when idle' feature is for. I don't think the app should behave this way, most banking apps don't.

**Comment by catch-21** [comment]
Some other wallets also don't lock on minimise, only when phone is locked or the app starts (not restores).
crypto.com app is aggressive, also requests auth each time the app is restored.

**Comment by JeanlChristophe** [comment]
Closing this ticket if it's the expected behaviour;
