### ISSUE TITLE
Fees options are missing

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1739]
When I create an onchain transaction with $10 (Bitkit to Bitkit), I'm missing the "Fast", "Normal" or "Slow" fee options. However, when I enter $20 with the same receiving address, I have all the options.
Current Mempool fees: 46sat/vb

v115

https://github.com/synonymdev/bitkit/assets/46056211/98fbd2af-a6bd-45ed-94ee-b710c918bcfc

**Comment by catch-21** [comment]
They show when trying to send a larger amount. There appears to be a cap on the amount the fee rate can be set depending on the amount being sent. For example, if I try and send 5_000 sats I am limited to just 9 sats/vB, which is way below market rate.

**Comment by coreyphillips** [comment]
This is expected behavior if the wallet is unable to pay the fee for a given fee tier.

**Comment by catch-21** [comment]
It might be better to disable (grey out) them rather than hide.

**Comment by JeanlChristophe** [comment]
duplicated of https://github.com/orgs/synonymdev/projects/12/views/1?sliceBy%5BcolumnId%5D=75809336&sliceBy%5Bvalue%5D=_noValue&pane=issue&itemId=61092105

**Comment by catch-21** [comment]
That duplicate link is a circular reference. I will reopen this issue, feel free to close if it is a duplicate of an other issue.

**Comment by pwltr** [comment]
I think this was fixed in https://github.com/synonymdev/bitkit/pull/2134. Feel free to reopen.
