### ISSUE TITLE
Change `Share button` message.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#174]
Change `Share button` message.

https://user-images.githubusercontent.com/5798170/177656367-8174037b-159d-455e-9f69-729ff4c2a0fd.mp4

https://user-images.githubusercontent.com/5798170/177656369-6881a218-4dd0-4407-b45c-28ef45a3c762.mp4

**Comment by BitcoinErrorLog** [comment]
Grammatically, it should be "Who will you orange-pill?" no extra caps, and the added hyphen :)
