### ISSUE TITLE
Some transactions created with Bitkit do not appear in mempools

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1741]
Some transactions made in Bitkit are not making it into the mempools:

**Orignal transaction with 1 sat/vB fee** 256 sats fee
https://mempool.space/tx/132b8d647f81b6d205487024f3664da901656778702e7a3fc2033f5bcd2b18dd
or
https://www.blockchain.com/explorer/search?search=132b8d647f81b6d205487024f3664da901656778702e7a3fc2033f5bcd2b18dd

**CPFP (boosted) transaction** 7304 sats fee
https://mempool.space/tx/7c9e9f338ce24b45a4e87df6ac4454880de25d415d21f40cacbc81940f19d80d

**Self-funded LN channel opening** 7304 sats fee
https://mempool.space/tx/c06be127dde280e617c8e055ac2fc49e64acf6d75c52ab896c708a16861be70b

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

V115 https://github.com/synonymdev/bitkit/commit/9ff423802faacd24a2e5f8fac7e31edd381c5ba6

**Comment by JeanlChristophe** [comment]
Same issue when we are trying to to open a channel (basic).

**Comment by catch-21** [comment]
It is likely that the first transaction was correctly purged from mempools (purge limit 5 sats/vB).
It seems likely that the subsequent transactions were consequentially affected by this, resulting in them too to be purged from mempools. The CPFB would to purged because it cannot replace a transaction that isn't in the mempool. The self-funded LN channel could have been attempting to use an output from one of the purged transactions as an input, resulting in it being invalid.

**Comment by catch-21** [comment]
@JeanlChristophe Closing this issue. Reopen if there's any suspicion the cause is not related to the above.
