### ISSUE TITLE
[Bug]: Fiat value of past transactions change each time Bitkit is opened

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1746]
### Describe the bug

When the wallet has a few transactions listed in Activities it displays both the BTC and chosen fiat value. Normally when viewing historical transactions in wallets or on exchanges the fiat value is displayed is calculated at the time the entry is created and remains constant. It is useful for auditing purposes and determining taxes. Bitkit calculates the fiat value for all historical transactions each time the app loads. It would be good to store the original value, at least locally.

### Reproduce

1. Bitkit has some historical transactions
2. Observe the fiat value of each transaction
3. Fully close Bitkikt
4. Restart Bitkit
5. Observe newly calculated fiat values for each historical transaction

### Screenshots / Recording

Before
![Screenshot 2024-04-26 at 13 15 07](https://github.com/synonymdev/bitkit/assets/74595920/9f804df2-9383-4314-bb05-e468bbd4200b)

After
![Screenshot 2024-04-26 at 13 15 43](https://github.com/synonymdev/bitkit/assets/74595920/1cb0065e-0902-453d-a9f9-4bdd9f95ca36)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

V115 https://github.com/synonymdev/bitkit/commit/9ff423802faacd24a2e5f8fac7e31edd381c5ba6

**Comment by JeanlChristophe** [comment]
Not an issue: this is the expected behaviour. You receive BTC, not fiat. so the value of fiat change, not the bitcoin's value
