### ISSUE TITLE
[Bug]: Toast can get stuck displaying at top of the screen

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1747]
### Describe the bug

It is possible to get the custom toast that drops down from the top of the app stuck so it won't go away. App restart required to reload without it.

### Reproduce

Not entirely sure how I managed it. If there's nothing obvious in the implementation then I can timebox recreating it. I may have done something with manually reconnecting from Electrum Server screen or minimise the app whilst toast was being displayed.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/ef55a7ef-8418-496f-9228-28391225bb20

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

c55c045f58b7e76ee82acdc1419bccf9db8490ae

**Comment by pwltr** [comment]
This happens when you tap & hold the toast when it's showing, preventing it from auto-hiding. Upstream issue here: https://github.com/calintamas/react-native-toast-message/issues/531

**Comment by catch-21** [comment]
Tested using 0d67faa2509b1ec083d475abc80e90802f8d7d28
I've not been able to reproduce this. Will keep an eye on it and try different things to provoke it. Closing/
