### ISSUE TITLE
LNmarkets successful notification in Bitkit - but no sign in

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1750]
### Describe the bug

I was able to login successfully using ST to LNMarkets on my desktop. I receive a notification in Bitkit that the attempt was successful but when I check the widget I am not logged in.
Subsequent login does not work. Only upon removing the widget and using it again to authenticate I am able to login to LNMarkets via desktop, still receive the notification but I am not logged into LNMarkets with Bitkit

### Screenshots / Recording

[bitkit_ldk_logs_1714143941464.zip](https://github.com/synonymdev/bitkit/files/15132239/bitkit_ldk_logs_1714143941464.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v115

**Comment by catch-21** [comment]
No longer crashing. @slashtag is deprecated" message is shown. Closing.
