### ISSUE TITLE
[Bug]: Fee amount restriction forces small onchain transactions to use below market fee rate

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1751]
### Describe the bug

When sending an onchain transaction there is a maximum limit on what the fee can be set to which is relative to the amount being sent. As a result, when sending a small amount (e.g. 10_000 sats) the fee rate to capped at 14 sats/vB which is too low for current fee market conditions to make it into a block. Need to spend over 25_000 sats today to have a chance of being included in a block.

This is also the cause of https://github.com/synonymdev/bitkit/issues/1739. The "Fast", "Normal" and "Slow" fee options are not being displayed if they are above the limit.

### Reproduce

1. Go to pay an on-chain address
2. Input a low amount (e.g. 10_000 sats)
3. Observe the fee is using Custom
4. Tap to change the fee
5. Observe that "Fast", "Normal" and "Slow" are not displayed. Only Custom is.
6. Attempt to increase the custom fee rate
7. Fee rate is capped at a maximum of 14 sats/vB when sending 10_000 sats. The maximum increases relative to the sending amount. 20_000 sats is capped at 29 sats/vB which is roughly double.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/ed1e5360-caec-4fe0-9af6-00942cbce576

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

V115 https://github.com/synonymdev/bitkit/commit/9ff423802faacd24a2e5f8fac7e31edd381c5ba6

**Comment by JeanlChristophe** [comment]
see issue #1739

**Comment by coreyphillips** [comment]
Addressed in [this PR](https://github.com/synonymdev/bitkit/pull/1765).

**Comment by catch-21** [comment]
Tested in b47d58d89e810df89be21509462b8e22490d7c0a
This was tested by overriding the current market rates (slow, normal, fast)
We still cap the amount, preventing smaller transactions that could be possible.
For example, I want to send 10_000 sats and I am limited to 18 sat/vbyte. 19 sat/vbyte would cost 3971 sats, not even half the amount sent.

**Comment by catch-21** [comment]
I think we just accept that small onchain tx are a no.
