### ISSUE TITLE
[Bug]: Change PIN & App Status page headings are not displayed correctly "Cha...IN" & "A...s"

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1758]
### Describe the bug

Change PIN page heading is "Cha...IN" and App Status page heading is "A...s" even though there is enough space to fit the whole heading in.

### Reproduce

Go to Change PIN screen and observe the heading.

### Screenshots / Recording

![Screenshot 2024-04-29 at 16 00 08](https://github.com/synonymdev/bitkit/assets/74595920/192ea0c6-ad6d-4a44-97c2-f755e8140018)

![Screenshot 2024-05-06 at 16 25 55](https://github.com/synonymdev/bitkit/assets/74595920/f74e39fc-f22b-4edf-b70f-5ebe51baa888)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

5cb45a6b2b23936d8d4037525e5b5792180847b7

**Comment by JeanlChristophe** [comment]
![Screenshot_20240528-103811](https://github.com/synonymdev/bitkit/assets/46056211/331ebb7a-d01c-4d64-b4c2-c49fe90aeaf9)
no fix :)

**Comment by catch-21** [comment]
@JeanlChristophe it isn't the case for every device so please share the affected device details.

**Comment by catch-21** [comment]
I believe the above screenshot was taken on v116, pre-fix. Closing. Feel free to reopen with details on how to reproduce on the current build.
