### ISSUE TITLE
[Bug]: Sent transactions that are immediately purged from mempool get stuck with "Confirming" status

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1759]
### Describe the bug

When a transaction is immediately pruned from the mempool then Bitkit doesn't recognise it as such. Instead, it shows the transaction is "Pending". I have seen Bitkit notify the user with a toast and highlighting the activity red when transactions that have later been removed from mempool, therefore the same should happen here.

### Reproduce

This is a certain way to reproduce (provided it remains possible to send transactions with very low fee rate)
1. Send an onchain transaction using a very low fee rate that is certain to be immediately purged from the mempool (1 sats/vB)
2. Observe the activity status is "Confirming" even after leaving for a long time (days)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

5cb45a6b2b23936d8d4037525e5b5792180847b7

**Comment by JeanlChristophe** [comment]
Fixed: This is not possible anymore to send too minimal fees.
