### ISSUE TITLE
[Bug]: Transferring Funds spending to savings doesn't account for fees at its 20% limitation

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1763]
### Describe the bug

When using the Transferring Funds screen to choose how much to move from spending to savings there is a 20% limit imposed and the reason given is so there is enough savings to pay for returning the spending back to savings. Although, it does not take fees into account. As a result:
1. It is possible to see an ugly error when the chosen amount cannot be used to balance the transaction.
2. After guessing an amount less to send you are left with a very small amount of savings.
3. The LSP pays for the channel close so you don't actually need any savings to move the funds back from spending.

### Reproduce

1. With roughly 70_000 sats in savings and nothing in spending
2. Attempt to move 80% of balance into spending
3. Observe error if fees cannot be covered by the remaining balance
4. End up with nearly nothing left in savings account

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/040d8f98-3974-4ab9-9c76-888397c69643

This leaves me with 1822 sats (not enough to do anything with)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

f231fea3e5128f9a577ecde3fec53c44c61bccff

**Comment by JeanlChristophe** [comment]
It is very difficult to predict in advance the exact fees required to complete a transaction. Even more so when it involves a channel.

**Comment by catch-21** [comment]
The next page tells you the fees (in $), so they are being requested/determine after the arbitrary 20% limit is imposed.
At least, this messaging is incorrect/misleading: "You need to keep funds in reserve to move this bitcoin back to savings" (unless you're anticipating to fund a force closure with whatever the absolute amount of 20% is)
