### ISSUE TITLE
[Bug]: Suggested fee to boost is well bellow market rate

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1777]
### Describe the bug

When boosting a transaction the suggested fee rate isn't suitable to produce an effective fee rate for current market conditions (not current volatile). Once boosted, a transaction cannot be boosted again so it gets stuck in the mempool and the user has no way to take action in Bitkit.

**Update: Due to the error seen when trying to increase the boost tx fee being "Unable to increase the fee any further. Otherwise, it will exceed half the current sending/output amount." this could be a manifestation of https://github.com/synonymdev/bitkit/issues/1751.**

### Reproduce

See recording section

### Screenshots / Recording

This is a long video so here's the breakdown:
1. Construct and submit an onchain transaction with 10 inputs (I don't know for sure if the tx size causes/exacerbates the issue but this is the condition where I first witnessed it) using a fee rate lower than market rate to ensure the transaction doesn't immediately confirm
2. Check the mempool sees the transaction with 6sat/vB fee rate
3. Boost the transaction using the suggested fee
4. Observe that the effective fee rate is still far too low
5. No option to boost again so now stuck.

https://github.com/synonymdev/bitkit/assets/74595920/0b8499cc-59a6-43c0-a48b-f745b855f9d5

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

20c194faaf1dc812c806fd7b47730f35a4c94286

**Comment by catch-21** [comment]
Tried this again sending a smaller transaction. This time instead of the boost transaction's fee being limited by the output amount it is limited by the input amount (same as https://github.com/synonymdev/bitkit/issues/1704). This results in the effective fee rate falling short of market rate.

<img width="250" alt="Screenshot 2024-05-03 at 07 26 15" src="https://github.com/synonymdev/bitkit/assets/74595920/bc1e92c8-26cd-4d97-9c39-5e7304750ec5">

<img width="250" alt="Screenshot 2024-05-03 at 07 26 24" src="https://github.com/synonymdev/bitkit/assets/74595920/970cb476-34f4-4a7e-9482-3f3b53d9eb3f">

**Comment by coreyphillips** [comment]
Will get back to this issue in a bit, but to resolve this I'll update `setupBoost` [here](https://github.com/synonymdev/bitkit/blob/2336e54f2712b5025f7d3a121fee028ae69b3797/src/utils/wallet/transactions.ts#L948) to call `wallet.getFeeInfo();` and pass the highest allowable fee preference as `satsPerByte` to `setupCpfp`.

**Comment by catch-21** [comment]
Boost does the best it can with the current constraints. Usually this works well but smaller spend amounts do limit the fee rate (and therefore effective fee rate). Closing.
