### ISSUE TITLE
[Bug]: Impossible to choose a custom fee rate for onchain transactions due to mix and max restriction

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1778]
### Describe the bug

When attempting to override the fee rate for an onchain send the UI prevents me from entering any value due to either exceeding the max or not satisfying the min condition. See videos for details. I suspect the changes in https://github.com/synonymdev/bitkit/commit/a93048d212f1c359d044a8c82ccc9353151f742c have causes this behaviour.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/aa11f75b-82d6-4318-9da5-8153c88351ee

https://github.com/synonymdev/bitkit/assets/74595920/16cb2c59-7629-4fa3-8afb-32f33dfce069

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v116 https://github.com/synonymdev/bitkit/commit/af77c19f9476e16fb489b63f8651f228d40e6b95

**Comment by JeanlChristophe** [comment]
it also telling me that the min fee is 3 sat:vb while I am trying with 200 sat/vb



https://github.com/synonymdev/bitkit/assets/46056211/f0e93026-9c00-4340-95b6-fedb41693d05


https://github.com/synonymdev/bitkit/assets/46056211/f120eaf8-79a8-41f2-a62e-0be82ff097a4

**Comment by coreyphillips** [comment]
These are extreme cases on either end of the spectrum and is expected. We just might want to more clearly relay these limits to the user. There's nothing we can do about spending below the current fee threshold and spending above a given limit may not even get successfully broadcasted or even properly relayed to our peers so a limit has to be imposed.

We could improve visibility into these extreme limits further by updating Bitkit's Send flow to use Beignet's updated api. This would take some time and testing to ensure everything is working properly so I propose we schedule this refactor for after launch so we have more time to test it.

**Comment by catch-21** [comment]
The 200sats/vB examples are extreme cases but the ones provided in the description are not.

**Comment by coreyphillips** [comment]
Percentage-wise it is the same and will be handled similarly when broadcasted and getting relayed. On-chain is non-optimal for these types of small spends.

**Comment by JeanlChristophe** [comment]
<img width="300" alt="Screenshot 2024-05-03 at 07 26 15" src="https://github.com/synonymdev/bitkit/assets/46056211/720c1f90-201b-487f-951e-75ba9092e403">

It doesn't work either with 30 sat/vb

**Comment by JeanlChristophe** [comment]
it's only the custom flow which is broken

**Comment by catch-21** [comment]
Tested in 898a58a42979ef8bee906b10182c8a12399e1d16
No longer blocked using custom fee option. There is still the limitation wihen sending smaller onchain amounts but this appears to be an expected limitation.
