### ISSUE TITLE
[Bug]: Show pending balance for force closes

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1779]
### Describe the bug

Bitkit needs to show pending transfer UI when a channel is force closed. 

pending balance, card, activity item

https://app.asana.com/0/1189635884316057/1205269092901302/f
https://app.asana.com/0/0/1204208728352470/1206703239419962/f

### Reproduce

1. Open a channel
2. Either force close from client or LSP
3. Should see pending transfer UI

### Operating system

Android, iOS

### Bitkit version

116

**Comment by catch-21** [comment]
I think this also affects mutual channel close

**Comment by catch-21** [comment]
This might also affect mutual close channel because I just witnessed Bitkit not realising it had received a channel close tx until I restored the wallet.

**Comment by catch-21** [comment]
Tested on 658b9f2bd22d2ca63893a89dc56f47a054546d79
The transferring suggestion displays with correct expected time to wait. The balance activity doesn't show
![image](https://github.com/synonymdev/bitkit/assets/74595920/6735888e-f514-44a3-9560-38161a3ddd00)
The incoming transfer text shows upcoming new balance
![image](https://github.com/synonymdev/bitkit/assets/74595920/d8972e5a-fff4-4a7b-a0de-ce844918f8db)
The activity appears after 6 blocks once seen in mempool.
LGTM.
