### ISSUE TITLE
[Bug]: Android splash screen header/footer

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1782]
### Describe the bug

The top and bottom colors for the splash screen (and the home screen after) are inconsistent. It should be all orange and then all black.

### Reproduce

1. Launch app
2. The top of the screen is black (should be orange)
3. Sometimes after the splash screen the bottom stays orange

### Screenshots / Recording

I don't have screenshots right now.

### Operating system

Android (on device)

### Bitkit version

master

**Comment by catch-21** [comment]
Verified in v118
