### ISSUE TITLE
[Bug]: Onchain receive sheet flashes purple color

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1783]
### Describe the bug

See screen recording

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/551bb8b3-4a71-4cbb-90a4-cd3d0289e990

### Operating system

Android/iOS

### Bitkit version

master

**Comment by catch-21** [comment]
Tested on 898a58a42979ef8bee906b10182c8a12399e1d16
Unable to reproduce on android emulator or own android device.
