### ISSUE TITLE
[Bug]: Orange flash when enabling keyboard for recovery input on Android

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1788]
### Describe the bug

The orange theme shows up when revealing the keyboard at the seed-phase input screen on Android (not iOS afaict). This feels unintentional and looks garish against the dark theme. It doesn't behave this way when opening the keyboard at other screens such as manual address input.

### Reproduce

1. On an Andriod device
2. Start clean Bitkit
3. Restore wallet
4. Display device's software keyboard
5. Observe temporary bright orange background in the area where the keyboard is expanding

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/ff0a924e-67e7-49ae-88f3-120a1b308489

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

**Comment by ovitrif** [comment]
@pwltr In answer to our chat from yesterday, I have a native solution in this patch:
[fix.patch](https://github.com/synonymdev/bitkit/files/15245667/fix.patch)

Download to the root dir of your local Bitkit and run in a shell:
```sh
git apply fix.patch
```


https://github.com/synonymdev/bitkit/assets/4588074/1f24be72-b9cc-43f5-b117-9dcc6f58598e

**Comment by catch-21** [comment]
Verified in v118
