### ISSUE TITLE
[Bug]: Tapping on value at Receive Bitcoin screen for spending doesn't toggle currency

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1790]
### Describe the bug

On the 'Receive Bitcoin' screen, that's shown when requesting spending balance, tapping on the bitcoin/fiat value does not toggle between the two (need to use the dedicated button). On other screens such as the main wallet view, 'Transfer Funds' and  'Edit Invoice' for onchain, tapping the value does toggle.

### Reproduce

1. Go to input an amount to receive for spending balance
2. Tap on the value
3. Value does not toggle between bitcoin and fiat

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/9c8c7a77-6aef-4a45-bbc8-4e6a04c7ec3e

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

**Comment by limpbrains** [comment]
Can't reproduce. Works for me on iOS and Android

**Comment by catch-21** [comment]
Hmm, I still see this on android and iOS. Just checked with 3aa7c764.
@limpbrains are you definitely on the Receive Bitcoin screen for requesting instant lightning payment?

**Comment by limpbrains** [comment]
You are right, I was testing the wrong screen

**Comment by catch-21** [comment]
Tested on b47d58d89e810df89be21509462b8e22490d7c0a
LGTM.
