### ISSUE TITLE
[Bug]: Tapping 'spending balance' on Transfer Funds pages doesn't react as defined in design spec

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1792]
### Describe the bug

Our design spec shows a transition when tapping 'SPENDING BALANCE' on **all** the Transfer Funds 'PLEASE CONFIRM', 'SPENDING BALANCE' and 'Receiving Capacity' pages. Tapping here does nothing in the app.

### Reproduce

See screengrab

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/3d3a5fc2-88fc-484d-863d-c922172423bf

https://github.com/synonymdev/bitkit/assets/74595920/2bb9e047-cba2-4646-aca2-d3d73d48cbe0

https://github.com/synonymdev/bitkit/assets/74595920/0abd21fc-64c5-4de2-8afb-e22e44d716c0

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

**Comment by catch-21** [comment]
Tested on v128 [e8f5056](https://github.com/synonymdev/bitkit/commit/e8f50564c6b4f471d9a336067fa5d54b4754c2d4)
Tapping on these now convert between unit type. The design (v49) defines it as transitioning to 'Spending Balance screen' but what you've done may be better. @limpbrains let's check this and request design change if needed.

**Comment by aldertnl** [comment]
Tapping amount should always result in converting to unit type. It may be an error in the Figma.
