### ISSUE TITLE
[Bug]: Facts and Headlines widgets are missing Widget Feed settings

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1798]
### Describe the bug

Both the Bitcoin Facts and Bitcoin Headlines widgets have nothing in their Widget Feed page. Our design spec defines the desired options for both.

### Reproduce

1. Go to customise widgets
2. Look at the Widget Feed page for Bitcoin Facts and Bitcoin Headlines

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/490bf5a4-a343-4221-bf13-c28cff5bd122" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/ed04c3eb-da74-4065-ab3b-8cad22171ddb" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

**Comment by pwltr** [comment]
Removed the ability to edit options for these two widget types for now. https://github.com/synonymdev/bitkit/pull/1851

**Comment by catch-21** [comment]
Verified in v118
