### ISSUE TITLE
[Bug]: Continue button can be pressed at invalid position on the Transfer Funds slider page

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1800]
### Describe the bug

When moving the slider position, it is possible to tap Continue to continue to the next page with invalid values. It doesn't change the action, just looks wrong and could be confusing.
To resolve, the Continue button could either be disabled until slider gets into valid position or apply the value that the slider is snapping to rather than what it is currently at.

### Reproduce

1. With some spending balance and inbound capacity at its limit (create a LN channel with $999 inbound capacity)
2. Go to Transfer Funds page with the slider
3. Move the slider to an invalid location and quickly tap Continue button before it has time to position itself to the closest valid location
4. The 'Please Confirm' page shows the correct description text (for me it is transferring all funds back to savings) but the percentage values and spending balance amount are wrong and misleading.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/158d4317-2040-4f95-a919-6df2541fd827

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

**Comment by limpbrains** [comment]
fixed

**Comment by catch-21** [comment]
Verified in 63a4dd6db6064916773e1b7983f5192a95b78899
LGTM. Nice.
