### ISSUE TITLE
v47 design differences

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1805]
Here's a list of differences spotted between the design specification and implementation in 2c5b07726fd35cb796a9566c47d0f6c36fda4ef4. Attached zip contains screenshots as evidence.

- [ ] 1: 'bitcoin' is on new line
- [ ] 2: 'bitcoin' is not capitalised, 'instant' is on new line, text is different 'and cheap payments'
- [ ] 3: text is narrower, "Don't store all your money in Bitkit" is on a single line (more readable and looks better)
- [ ] 4: 'your' is on new line
- [ ] 5: text is narrower, bold texts are all on the same line
- [ ] 6: text is narrower, 'and' after comma is on new line
- [ ] 7: text is narrower, 
- [ ] 8: value is located under the text rather than above the input buttons (I actually prefer the implementation but the design shows otherwise)
- [ ] 9: 'able' on new line
- [ ] 10: 'or' after comma is on new line
- [ ] 11: 'experiencing is on new line
- [ ] 12: 'overwrite' on new line
- [ ] 13: everything (header, text and buttons) is centarlised
- [x] 14: (removed)
- [ ] 15: 'able' on new line
- [ ] 16: actual has typo: "fees  fees"
- [ ] 17: different text on 'In Transfer' page
- [ ] 18: everything (header, text and buttons) is centarlised
- [ ] 19: 'display' on new line
- [ ] 20: 'display' on new line
- [ ] 21: 'display' on new line
- [ ] 22: 'display' on new line

[design_delta.zip](https://github.com/synonymdev/bitkit/files/15249115/design_delta.zip)

**Comment by JeanlChristophe** [comment]
Can we close this ticket?

**Comment by catch-21** [comment]
I spoke to @aldertnl and most of the differences are related to screen proportions and are acceptable. The others were addressed in v48.
