### ISSUE TITLE
[Bug]: Deep link to BIP21 Payment URI fails without error

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1807]
### Describe the bug

Due to slow initialisation of the wallet deep linking to a BIP21 payment URI (unified QR) doesn't work. The wallet isn't ready yet to process the input.

Related to https://github.com/synonymdev/bitkit/issues/1650

### Reproduce

1. With an onchain and/or lightning balance
2. Close the app completely
3. Scan a BIP21 unified payment URI
4. Send flow doesn't open and no error

On the simulator can test with by running the command:

```
npx uri-scheme open "bitcoin:bcrt1q5dncl8axehjrz6flztjmtsq0z8ut94hecaa4nc?amount=0.0002&lightning=LNBCRT200U1PNRK7VNDQQNP4QVJH6RYKVW2HLDANDVSJTEZ4PKW2JLPNMH89H5V0LFZDNJUKNJN2SPP5KYGURHUN7PD3SEDGAZYQDMSRRE7HLZ2ZUQNUA5WLURTHP3TXAMNSSP5YW2DSEM4LQMC3XUG67P6WDC0FQA4LATX0JT7GZ39YNYU70H2C8US9QYYSGQCQPCXQRRSSRZJQWU6G4HMGH26EXXQYPQD8XHVWLARA66PL53V7S9CV2EE808UGDRN4APYQQQQQQQY3QQQQQLGQQQQQQGQ2QFKMXTK280FAXLKVYNPRRZETAWE0E5N0PF063WZFDCP5LRLAWK7THV6R4MKSL5AK57F9Y8CKJ97DYQ2NH89UJZH8SCUT4EQTH4CY9WZGQ2QRVMJ" --ios
```

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/3fae25d7-c3f1-4bd7-b4aa-491ecc7980d3

### Operating system

Android/iOS

### Bitkit version

898a58a4

### Log output

```shell
LOG  [TypeError: Cannot read property 'transaction' of undefined]
LOG  [Error: Cannot read property 'transaction' of undefined]
LOG  Syncing Wallet...
```

**Comment by catch-21** [comment]
Tested on 127 [9855fe5](https://github.com/synonymdev/bitkit/commit/9855fe5f6c350c163483aa140e427f27f396de59) best I could on a real (slow) device and the invoice always got handled correctly.
