### ISSUE TITLE
[Bug]: Fraction of sat can be temporarily shown in onchain send details

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1816]
### Describe the bug

After onchain send, the amount of sats can be displayed as a fraction, although it will probably correct itself within a few seconds.

### Reproduce

1. Send an onchain transaction (this happened to me with a boost transaction)
2. When send confetti, view the details page
3. If the bug doesn't occur immediately, wait for a short while because it might happy within a minute or two

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/c63dbb3a-f6f9-46d8-b590-d3b038eea7c9" width="300">
->
<img src="https://github.com/synonymdev/bitkit/assets/74595920/9718ff0a-d842-47d1-8c27-8107485a6336" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v117 ae82edd7a3ab8ff771cbf945729e41c43c5ed1f2

**Comment by coreyphillips** [comment]
I think I came across this last week and know where it is coming from. Will assign to myself.

**Comment by catch-21** [comment]
Not seen in v118 whilst boosting. Will keep an eye on this in future.
