### ISSUE TITLE
[Bug]: No constraints or retry attempt when failing to obtain price data for conversion resulting in error when interacting with Blocktank

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1833]
### Describe the bug

If Bitkit starts without being able to retrieve price data (has happened to me a few timesunder normal conditions) and it doesn't have past data to use then it displays a dash for the dollar value (see first screenshot). From then on it does not attempt to fix this state even if network conditions are good. As a result, there is no price data for creating a LN channel (see second screenshot).

It would be good to prevent access to any action that requires live price data on the client side.
It would be good to retry obtaining price data if it has been unsuccessful.

### Reproduce

1. With no network (aeroplane mode)
2. With a new instance of Bitkit
4. Create a new wallet
5. Allow network access (disable aeroplane mode)
6. Tap the 0 bitcoin balance to display dollar
7. Observe a dash for dollar price instead of 0 (this is probably an ok representation but there are no attempts to update live price data, even with a manual pull-down to refresh)
8. Tap Receive at the bottom
9. Tap Receive on Spending Balance
10. Input valid amount and Continue
11. Observe 'Undefined' fiat amount in description
12. Tap Continue
13. Observe CJIT Error and no progression to create invoice

### Screenshots / Recording

Dollar value displays with a dash when there is no price conversion info
<img src="https://github.com/synonymdev/bitkit/assets/74595920/e13e28a2-2db5-46ae-9bb1-64cf6d5df7e5" width="300">

Attempting to create CJIT channel displays 'undefined' and produces error
<img src="https://github.com/synonymdev/bitkit/assets/74595920/183f0fe7-0c74-4246-bc0b-f88a22057d09" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

d710a89144ec9b15fb03e41c1d08f51b0aae12cd

**Comment by catch-21** [comment]
Tested on v118
This is much improved. I see that the price data is updated automatically and correctly.
However, I did notice that the $0 service provider fee and `CJIT Error: init_channel_manager` can be provoked when attempting to receive spending balance with no network.
@limpbrains would you suggest addressing here or in new issue?

**Comment by limpbrains** [comment]
definetly a new issue

**Comment by catch-21** [comment]
Raised https://github.com/synonymdev/bitkit/issues/1898
