### ISSUE TITLE
[Bug]: Wallet balance can be persistently incorrect on restore

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1841]
### Describe the bug

When attempting to recreate https://github.com/synonymdev/bitkit/issues/1806, which I couldn't, I got into the state where the wallet's balance was incorrect given the current transaction history. This can be seen in the Ledger view. In this state, some things such as the transfer slider do not work at all (slider wont move).

I suspect one of the black screen fixes combined with [bitkit/pull/1773](https://github.com/synonymdev/bitkit/pull/1773) may have caused this.

I suspect that during restoration, the wallet can proceed to calculate the balance before it has all the necessary data.

**Please retest https://github.com/synonymdev/bitkit/issues/1806 once fixed**

### Reproduce

1. ~~With slow network (e.g. HSDPA on android emulator)~~ This is now happening for two of my wallets with fast network
2. Restore a wallet that has onchain funds and a few historical onchain transactions
3. Wait for main screen to load and display some balance
4. Observe to see if balance is correct. Historical transactions may or may not load. ~~I needed to set my network back to faster (LTE)~~. The balance never corrected itself automatically. Needed to manually 'Rescan Addresses' from Advanced settings to set the balance correct.

### Screenshots / Recording

<img width="300" alt="Screenshot 2024-05-16 at 17 01 27" src="https://github.com/synonymdev/bitkit/assets/74595920/4d248dd2-e23d-4afc-a8fd-19cc0db13f3d">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/67cb8112-5529-4a6a-9d8c-0a5d224ef2c4" width="300">

-----

Wallet 1

[bad_restore.webm](https://github.com/synonymdev/bitkit/assets/74595920/c9565e33-c487-417b-ad49-12901b58e5ff)

-----

Wallet 2

[bad_restore_2.webm](https://github.com/synonymdev/bitkit/assets/74595920/169dd0f9-623d-45f6-9424-dab4fbefc359)

### Operating system

Android 14

### Bitkit version

2336e54f2712b5025f7d3a121fee028ae69b3797

**Comment by coreyphillips** [comment]
Potentially due to throttling from the Electrum server given it's current `bitcoind_throttle` config setting of `50 20 5 `. Will retest once the server's config has been updated. [Thread for reference.](https://synonymworkspace.slack.com/archives/C01H106JRQB/p1715170139659419)

**Comment by catch-21** [comment]
This is very similar and fully reproducible on v118. I'm on a fresh VPN to reduce the chance of throttling.

https://github.com/synonymdev/bitkit/assets/74595920/ad00f7f5-5134-46c6-b997-33c8c0174e85

**Comment by coreyphillips** [comment]
Retest this once the mainnet server has been updated to where it won't throttle you upon restore. Again, please [see thread](https://synonymworkspace.slack.com/?redir=%2Farchives%2FC01H106JRQB%2Fp1715170139659419%3Fname%3DC01H106JRQB%26perma%3D1715170139659419). For context, the current config throttles at 50 and a restored wallet needs to make ~160 queries.

**Comment by catch-21** [comment]
>once the mainnet server has been updated

Any idea when this might happen?

**Comment by coreyphillips** [comment]
If the app is getting throttled by the Electrum server (its data source for everything), it will not be able to retrieve the current balance/transaction info for a given set of addresses.

**Comment by JeanlChristophe** [comment]
When Fulcrum on Mainnet? @dzdidi

**Comment by dzdidi** [comment]
@JeanlChristophe , it was there since a year, I think. The lates config update was done on 13:20 (UTC+1), May 28th 2024

**Comment by dzdidi** [comment]
@JeanlChristophe as @coreyphillips  mentioned https://github.com/synonymdev/bitkit/issues/1841#issuecomment-2129543285

**Comment by coreyphillips** [comment]
@catch-21, if you're still experiencing this issue after retesting please DM me your testing mnemonic phrase so I can attempt to reproduce it on my end.

**Comment by catch-21** [comment]
Checked on three of my and I don't think I am seeing this anymore 🙌
Although, the main screen does display before all balances have been determined so I'd like to track that separately: https://github.com/synonymdev/bitkit/issues/1934
