### ISSUE TITLE
[Bug]: Profile and Contact names display all-caps when heading only

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1852]
### Describe the bug

The wallet's profile name and all added contacts name display using the actual case (lower or upper) in most places, but when a heading (Profile or Contacts pages) it is all-caps. This fits with the new branding but I don't think it is suitable for profile names because case is a means of personalisation. We should always display profile names using the chosen character cases.

### Reproduce

1. Edit your profile name
2. View it on the Profile page
3. Observe it is all-caps on one screen only (see video for details)

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/b31e8a0f-7b1d-47a2-acc6-0d27cd0c1fd7

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

9e848b8443daa828ad40fc6822640fcd013bf39f

**Comment by JeanlChristophe** [comment]
From Aldert "The user name will just display differently based on the context and I would prefer for it to match the new brand visual identity."
