### ISSUE TITLE
[Bug]:Load Screen goes to 29-32% and then straight to wallet Home Screen 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1872]
### Describe the bug

When setting up a new wallet, the screen loads very fast but it goes to 29% - 32% and then straight to home screen.

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v118

**Comment by thisispav** [comment]
https://github.com/synonymdev/bitkit/assets/119061223/93a15fb1-e201-4cee-b318-c2ce56258bf2

video of the screen

**Comment by catch-21** [comment]
My opinion is that this is fine. The alternative being we make the animation faster for new wallet, or force the user to wait for the animation to complete which means waiting longer to use the new wallet.

**Comment by catch-21** [comment]
Verified in 63a4dd6db6064916773e1b7983f5192a95b78899
Although now my restore also doesn't get to 100%. I suppose that's just faster than avg.
