### ISSUE TITLE
[Bug]: Slow / Buggy Unlocking of the app

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1873]
### Describe the bug

the unlocking screen gets stuck - maybe I entered the pin too quick since it's the same numbers / characters. I tried to backtrack or erase the characters but nothing happened - had to close and reopen the app, re-enter the pin for it to work. 
Happened a few times already during the testing session

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/7c54baf7-f61a-4580-9ee9-e124728ff1f7

[bitkit_ldk_logs_1716539033809.zip](https://github.com/synonymdev/bitkit/files/15430361/bitkit_ldk_logs_1716539033809.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v118

**Comment by catch-21** [comment]
I input the correct PIN but tap more than 4 times (8). At this stage the app doesn't unlock until I backspace 4 times so the input is equal to 4 numbers.

https://github.com/synonymdev/bitkit/assets/74595920/fcbc8b2f-af08-4f8a-8751-34ba25eb4564

**Comment by catch-21** [comment]
Tested on 8de4fa74f41be7613c28bbcd36be93d50948aa74 in a few places where PIN entry happens. LGTM.
