### ISSUE TITLE
[Bug]: Transfer / Opening a channel doesn't show estimate

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1877]
### Describe the bug

made a transfer from savings to spending - got the tx marked under the activity section of Bitkit with the correct amount, but there is no time estimate given (instead it says +NaNm) 

### Screenshots / Recording

![regular channel (transfer)](https://github.com/synonymdev/bitkit/assets/119061223/2cb3bc11-9e7d-40c7-a876-d58cdbfc26ea)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v118

**Comment by catch-21** [comment]
Tested in 5dee7d29d2cc891d52d97475de4180e020278a01
Unable to reproduce, although I never saw it before. Will keep an eye out.

**Comment by catch-21** [comment]
@pwltr back again https://github.com/synonymdev/bitkit/issues/1952
