### ISSUE TITLE
[Bug]: Unable to open CJIT LN Channel

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1879]
### Describe the bug

I just tried multiple times to pay a CJIT LN invoice for 12_500 sats from Pheonix and it failed every time. Two orderIds are 1b75a644-8723-49b6-9782-2c34332600cb and cacbcf68-8f18-4e85-877e-ddf289ff7302 and BT logs show `"message":"Channel capacity must be >= 20000sat.","type":"CHANNEL_REJECTED_BY_LSP"`

BT error: https://synonymworkspace.slack.com/archives/C0726U60V6Y/p1716545752789479

### Reproduce

1. With onchain funds but no LN connections
2. Create a 'spend instantly' cjit invoie
3. Attempt to pay from Pheonix (not sure if source is relevant)
4. Fail to spend message in Pheonix
5. CHANNEL_REJECTED_BY_LSP in BT logs
6. No spending balance in Bitkit

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v118

**Comment by JeanlChristophe** [comment]
MinChannelSize is always at least 20k sat

**Comment by pwltr** [comment]
Fixed on BT side

**Comment by catch-21** [comment]
Verified in v118 with the fix in BT
