### ISSUE TITLE
[Bug]: Channel is not usable despite me using the channel multiple times 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1882]
### Describe the bug

this is the status for both CJIT and Regular channels 

JC mentioned that it can be due to my connection, since some of the paykit payments we did (to contacts) didn't work from the first time 

### Screenshots / Recording

[bitkit_ldk_logs_1716548147054.zip](https://github.com/synonymdev/bitkit/files/15433267/bitkit_ldk_logs_1716548147054.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v118

**Comment by thisispav** [comment]
![photo_2024-05-24_13-57-16](https://github.com/synonymdev/bitkit/assets/119061223/1d5c5914-14d1-4942-b5a9-a47dfa6c3de4)

**Comment by limpbrains** [comment]
[bitkit_ldk_logs_1716911604567.zip](https://github.com/synonymdev/bitkit/files/15472846/bitkit_ldk_logs_1716911604567.zip)

**Comment by JeanlChristophe** [comment]
Note: This error also appears when Bitkit isn't into the background.

**Comment by Jasonvdb** [comment]
Chatting to spiral about this. Peer is not connected which makes the channel unusable. Trying to debug that/

**Comment by JeanlChristophe** [comment]
Can't reproduce it with new fix
