### ISSUE TITLE
[Bug]: Transaction suggested fee rate can display Custom when current fee rate allows for Normal

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1896]
### Describe the bug

Minor UI bug.

When sending a transaction, it is possible for the fee rate to display as 'Custom' when it is actually using the Normal value. First mentioned here: https://github.com/synonymdev/bitkit/issues/1619#issuecomment-2022813353.

### Reproduce

1. Begin constructing a transaction where the sent amount is high enough that the Normal fee rate can be used (it could matter if it is close to not being allowed, or maybe it was recently not allowed)
2. View the suggested fee rate is Custom
3. Tap on Custom
4. Observe that only Custom is seen even though the Normal fee rate is being applied

### Screenshots / Recording

see https://github.com/synonymdev/bitkit/issues/1619#issuecomment-2122994907.

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v118

**Comment by JeanlChristophe** [comment]
Missing: Fast normal and slow

![Image](https://github.com/synonymdev/bitkit/assets/46056211/b505c70e-8144-4782-adba-5d2f7d417da8)


See Figma
![Image](https://github.com/synonymdev/bitkit/assets/46056211/00c7c167-0c8f-4565-a52a-43de39bc8283)

**Comment by catch-21** [comment]
>Missing: Fast normal and slow

@JeanlChristophe This is expected when the options are not made available to the user. That is decided by beignet and depends on the current fee amount relative to input and output amounts of the transaction. I proposed we grey them out instead of hiding, see https://github.com/synonymdev/bitkit/issues/1739#issuecomment-2082574495

**Comment by JeanlChristophe** [comment]
I still don't understand the issue here

**Comment by JeanlChristophe** [comment]
If its follow the Figma, it's not a bug. Any UI improvement need to be done on Figma please.

**Comment by catch-21** [comment]
@JeanlChristophe The issue is that 'Normal' is displayed at the 'Review & Send' page but 'Normal' is not actually an available option on the 'Speed' page. See from the 7th second in video here: https://github.com/synonymdev/bitkit/issues/1619#issuecomment-2122994907.

**Comment by catch-21** [comment]
[not_normal.webm](https://github.com/synonymdev/bitkit/assets/74595920/9de26d9c-1acf-4d34-bc20-d13ce31a168d)

**Comment by limpbrains** [comment]
I am unable to replicate this issue. I've tested various on-chain balances similar to the value you had, along with different fee rates. Whenever BitKit allows me to choose Normal, it is available. Next time this occurs, please note the on-chain amount, the value you are sending, and on-chain fees from [mempool](https://mempool.space/api/v1/fees/recommended). Thank you.

**Comment by catch-21** [comment]
@limpbrains with v131

https://github.com/user-attachments/assets/11f03d1a-f27f-42aa-b937-d5b956d3d760

**Comment by catch-21** [comment]
Verified in v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914
Perfect 👍
