### ISSUE TITLE
[Bug]: No minimum receive amount or LSP fee, and CJIT Error when attempting to receive spending balances when network is down

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1898]
### Describe the bug

Created off the back of https://github.com/synonymdev/bitkit/issues/1833#issuecomment-2133657792

$0 receive minimum, $0 LSP fee and `CJIT Error: init_channel_manager` or `CJIT Error: Failed to create cjit entry. undefined` toast is displayed when attempting to receive spending balance without an existing LN connection. We should handle this better in the UI, perhaps preventing progression when unable to contact LSP.

### Reproduce

This is easy to reproduce in aeroplane mode but it can also occur when network is down or restricted
1. With no existing LN connection
2. Enable aeroplane mode to stop network
3. Attempt to receive lightning funds
4. Observe $0 minimum
5. Continue
6. Observe $0 LSP fee
7. Continue
8. Observe cjit error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/1acec51b-0dd3-4b36-90d6-82aece234fc9

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

5dee7d29d2cc891d52d97475de4180e020278a01

**Comment by JeanlChristophe** [comment]
Normaly you received a notification saying "network issue", right?

**Comment by catch-21** [comment]
>Normaly you received a notification saying "network issue", right?

Yes, but still...

-----

Minimum is wrong and misleading.
![Screenshot 2024-06-21 at 11 13 02](https://github.com/synonymdev/bitkit/assets/74595920/bed8143a-d40e-4d98-9ce6-360830081d97)

-----

Service provider fee is wrong and misleading.
![Screenshot 2024-06-21 at 11 13 36](https://github.com/synonymdev/bitkit/assets/74595920/54a1e00d-8313-41f4-8000-3056ae32badd)

-----

"Wtf is CJIT" - User, probably.
![Screenshot 2024-06-21 at 11 14 05](https://github.com/synonymdev/bitkit/assets/74595920/55a46ef7-3d80-4827-a890-c39e1ad35ffb)

**Comment by limpbrains** [comment]
In flight mode it is now impossible to strart CJIT flow.
The "Spending Balance Initializing" spinner will never end

<img src="https://github.com/user-attachments/assets/9db04853-6994-4e59-a217-d7007fdf41d7" width="300" />

**Comment by catch-21** [comment]
Tested on v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

>In flight mode it is now impossible to strart CJIT flow.
The "Spending Balance Initializing" spinner will never end

True, but if aeroplane mode (or network drop probably) after bitkit has already initialised it's same behaviour as before with the zero values.

https://github.com/user-attachments/assets/a490eee0-e0a3-44f9-8984-1c7805f5afff

If we don't care enough then feel free to close off.

**Comment by catch-21** [comment]
Tested on v1.0.6 (138)
I'd say the original bug is fixed but now I get an error containing 'undefined'

<img width="300" alt="Screenshot 2024-11-04 at 17 21 04" src="https://github.com/user-attachments/assets/a53751fa-04b1-49ff-983a-e34e0e91adc4">

https://github.com/user-attachments/assets/0bfe935a-733d-426d-a22b-e9d97653ecbe

Raised https://github.com/synonymdev/bitkit/issues/2330
