### ISSUE TITLE
[Bug]: Tx indicated in "Open Block Explorer" is not the correct one

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1902]
### Describe the bug

I've just closed a channel with the slide bar by going from Savings to Spending. The transaction is completed. When I look for information on this transaction, I click on "Open Block Explorer" and I see that the transaction is not the right one and that it indicates a tx confirmed 14 days ago.

### Reproduce

1. Go to 'ACTIVITY'
2. Click on 'Transfer' tx
3. Click on 'Open Block Explorer'

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/4ac3046d-0896-435f-bf33-e2cbb96df00c

### Operating system

GrapheneOS

### Bitkit version

v118

**Comment by catch-21** [comment]
@pwltr  It could be that https://github.com/synonymdev/bitkit/pull/1866 only fixed the displayed txid and not the link?

**Comment by JeanlChristophe** [comment]
I think this is a different issue than https://github.com/synonymdev/bitkit/pull/1866. here the tx id indicated is good. But the one on mempool isn't

**Comment by catch-21** [comment]
Verified in 63a4dd6db6064916773e1b7983f5192a95b78899 on a transfer from spending tx.
