### ISSUE TITLE
[Bug]: Unable to increase spending balance

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1908]
### Describe the bug

I currently have a LN connection and wish to increase my spending balance. I am unable to continue from the transfer funds quick setup or advanced lows

[bitkit_ldk_logs_1716990999808.zip](https://github.com/synonymdev/bitkit/files/15485466/bitkit_ldk_logs_1716990999808.zip)

### Reproduce

1. With an existing LN connection that has some spending balance
2. Attempt to increase the amount of spending balance
3. Tapping 'Continue' button on the Transfer Fund's Quick Setup flow does nothing
4. Following the Advanced flow results in a 'Instant Payments Setup Failed' 'You need $x more to complete this transaction' error 

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/3a468d45-1ce5-4363-bc18-83c99e60503a

<img src="https://github.com/synonymdev/bitkit/assets/74595920/c90d5469-80e6-4333-b445-f660dd818d38" width="300">

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

d6166eaa68f9fb95e9f4d6db4941e9c726280a80

**Comment by JeanlChristophe** [comment]
do you still have the issue? I can't reproduce it

**Comment by catch-21** [comment]
@JeanlChristophe  Yes, on two wallets. You must ensure to not be at max inbound capacity.

**Comment by catch-21** [comment]
Verified in 6c75bd068c9bac72cc488c52e78f3ef7bba8a4ba

**Comment by pwltr** [comment]
@catch-21 Can we close here?
