### ISSUE TITLE
[Bug]: Send max spending doesn't use the max, repeated use results in payment routing error

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1909]
### Describe the bug

When sending from spending balance the max option doesn't use the actual maximum. After sending the suggested max amount it is then possible to send from spending balance again for a much smaller max. On the third attempt an ugly routing error is displayed. Max should mean you cannot send from spending balance a second time.

### Reproduce

1. Send all your available spending using 'max' option 
2. Do it again
3. Do it again
4. Observe 'invoice_payment_fail_route_found' error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/73222ace-626d-42c7-aefa-23927b48f14f

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

d6166eaa68f9fb95e9f4d6db4941e9c726280a80

**Comment by pwltr** [comment]
Max amount for LN payments is only an estimate for now, see https://github.com/synonymdev/bitkit/issues/1422
