### ISSUE TITLE
[Bug]: Hot reloading on Android broken

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1916]
### Describe the bug

https://synonymworkspace.slack.com/archives/C01H106JRQB/p1714631786516419

Development issue only, low prio

### Operating system

Android

### Bitkit version

04959b72

## Preview
![Image](https://github.com/user-attachments/assets/0a1834d3-3e86-4b08-ab71-22cba7ecee91)

**Comment by ovitrif** [comment]
@pwltr seems to work fine for me on the last changes to react-native-keychain fork 🎉 

Tested with update in `package.json`:
```
"@synonymdev/react-native-keychain": "github:synonymdev/react-native-keychain#refactor/android-data-store",
```

https://github.com/user-attachments/assets/b7720059-69e7-4b0f-b1ab-091c1af24484



Please give it a check as well and we should have this working nice again after @limpbrains approves the PR in the fork 🙏🏻

**Comment by ovitrif** [comment]
FYI had to re-remove `PrefsStorageBase.java`, pushed again to fork, now it actually builds and works.

Probably it was a merge issue on the private fork that the file wasn't gone.
