### ISSUE TITLE
[Bug]: CJIT Error init_channel_manager

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1921]
### Describe the bug

Not the first time this has happened, but isn't the same as recent issues (#1898, #1833). Unsure if related, but this occurred ~2 hours after [high mempool delay warning](https://synonymworkspace.slack.com/archives/C02MYL829U0/p1717167114717689).

### Reproduce

I could reproduce this multiple times when speedrunning from wallet creation to first receive.

1. Reset wallet
2. Close and reopen the app
3. Create wallet
4. Quickly try to receive to spending balance

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/542b8adf-43f9-4619-935f-ee8b8d2db348

### Operating system

iOS 17.5

### Bitkit version

49d1359

**Comment by JeanlChristophe** [comment]
Thanks Matt for your feedback. You need to wait until you're properly connected, you're moving too fast between creating the wallet and initiating the request to open the channel.
To find out the status of the wallet: Settings > Support > App Status

The error msg has been updated.
