### ISSUE TITLE
[Bug]: QR centre logo doesn't change to orange when invoice generation falls back to onchain

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1923]
### Describe the bug

When setting an invoice amount to be larger than the receiving capacity, the "Receive on Spending Balance" toggle stays on, and the half-orange, half-purple Bitcoin logo is still shown despite the QR containing no Lightning invoice.

### Reproduce

1. Edit invoice amount to be larger than receiving capacity

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/9b60964b-e693-49a9-977a-67701fbd2ca6

### Operating system

iOS 17.5.1

### Bitkit version

49d1359

**Comment by catch-21** [comment]
Verified in v127 [9855fe5](https://github.com/synonymdev/bitkit/commit/9855fe5f6c350c163483aa140e427f27f396de59)
Works well.
