### ISSUE TITLE
Instant Payments  denomination in sats or fiat.

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1926]
All units on the same screen would change once user taps balance or amount anywhere

![Image](https://github.com/synonymdev/bitkit/assets/46056211/8508ac4d-1553-4a65-91fc-7da3275b3ae2)

**Comment by catch-21** [comment]
Verified in v128 [e8f5056](https://github.com/synonymdev/bitkit/commit/e8f50564c6b4f471d9a336067fa5d54b4754c2d4)
