### ISSUE TITLE
[Bug]: Back-up buttons can stop working

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1927]
### Describe the bug

I got myself into a situation where it's not possible to display the back up seed phrase. Not sure if this is possible with other modals bottom sheets.

### Reproduce

1. Go to 'Back Up Or Restore' settings page
2. Tap 'Back up your wallet' quickly a few times
3. If fast enough, the bottom sheet will stop displaying and app restart is required to fix

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/db20e4fb-01db-440b-8801-b1b8e60452d3

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

162d75166e3331dbdbbf6272c156b15ae4e80544

**Comment by coreyphillips** [comment]
Similar bug to [this](https://github.com/synonymdev/bitkit/pull/1829).

Bug can be partially addressed by swapping `showBottomSheet('backupNavigation');` to `toggleBottomSheet('backupNavigation');`. We still need to find a way to respond to interrupted open/close animations from the bottom-sheet wrapper.

**Comment by catch-21** [comment]
Verified in v122
