### ISSUE TITLE
[Bug]: LN send fee way higher than expected

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1928]
### Describe the bug

Every LN payment I am making is expected to be approx $0.01 but in reality much higher, observed $0.07 to $0.11.

### Reproduce

1. Go to send a LN payment from one Bitkit wallet to another Bitkit wallet
2. Expected fee shown before making the payment is around $0.01
3. Actual fee paid was $0.11

### Screenshots / Recording

[ln_bad_fee_estimation.webm](https://github.com/synonymdev/bitkit/assets/74595920/3e665a3e-fa04-4e99-86ed-219944d49971)

Payment hash: 74bd4449508720457a3f9cb14b3d457ddff6d9c817651a1812ef954c74b65041
Invoice: lnbc1004920n1pn9my03dqqnp4q0zn09gvdcdk9sxw0y3lfyea3xve898detq0ft9gwlx4el9wextvjpp5wj75gj2ssusy273lnjc5k0290h0ldkwgzaj35xqja725ca9k2pqssp5e2j06k28alp34hudkzfskcand7yj6eh94zch5kd3pyfdasa7u06q9qyysgqcqpcxqrrssrzjqv6zatycmrq84j9y7vpm9tgf5d9nx5p4wucqz02nf5zn0fx3mzs5mapyqqqqqqqqpqqqqqlgqqqq86qqeqmjupm4005kne48qslkcdeva9zxycuf8xyvytsuqufmy6cq332za5q9eup54smarkxpjxhwg9mar2w3jfza60xa8899mwndupmyaps3qpm0ntf6

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

1e714a948f69789cec42936226bfeb43ac8cf5e6

**Comment by Jasonvdb** [comment]
No way to know the LN payment fee prior to actually attempting the payment. We have previously discussed probing as the invoice is pasted to better give an estimate but currently we don't have that feature. I suspect the fee you're seeing is a hard coded guess.
