### ISSUE TITLE
[Bug]: Invoice QR centre-icon indicates onchain and LN when chosen amount exceeds receiving capacity

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1936]
### Describe the bug

When creating a receive invoice that exceeds the inbound capacity for LN an error is displayed and the invoice produces is onchain only. The icon shown still indicates the invoice is for both onchain and LN.

### Reproduce

1. With an existing LN connection
2. Receive with an amount greater than the connection's inbound capacity
3. Observe the 'Insufficient receiving balance." error
4. Observe the QR for the invoice is only for onchain but the icon in the centre remains indicating both onchain and LN

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/fef11935-cbb5-41d0-b767-f7dd0edc0460

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

1e714a948f69789cec42936226bfeb43ac8cf5e6

**Comment by JeanlChristophe** [comment]
Duplicated from https://github.com/synonymdev/bitkit/issues/1923
