### ISSUE TITLE
Update Bitkit ToS on Website

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1957]
https://docs.google.com/document/d/15L_3YegLmsuixRfGT23bhO2Mm1gPEabz/edit?usp=sharing&ouid=108976799534797215192&rtpof=true&sd=true

Place: https://bitkit.to/terms-of-use

**Comment by MiguelMedeiros** [comment]
We will publish the new website soon. 
Here is the PR that fixes this:
https://github.com/synonymdev/synonym-website/pull/128
