### ISSUE TITLE
[Bug]: Unable to pay Fountain LN Address

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1960]
### Describe the bug

Attempting to pay a Fountain LN Address `brown@fountain.fm` results in 'Unable To Pay (LNURL)' error.
I can successfully pay this way from Pheonix.

I also cannot pay an LNbits LN Address (e.g. catsbro@demo.lnbits.com) but I am also unable to pay that from Pheonix at this time.

### Reproduce

1. Send to brown@fountain.fm from Bitkit
2. Observe 'Unable To Pay (LNURL)' toast error

### Screenshots / Recording

![image](https://github.com/synonymdev/bitkit/assets/74595920/21bf862f-3ccc-4540-a4ba-55aafdc3f138)

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v122 01b96914b84df3a2584c71bd9fb6ca5f143709e0

**Comment by JeanlChristophe** [comment]
@catch-21 I don't have Fountain LN adress. Do you still have this issue?

**Comment by catch-21** [comment]
>Do you still have this issue?

Issue still exists.

**Comment by JeanlChristophe** [comment]
True. Doesn't work from Bitkit but worked from Phoenix

**Comment by limpbrains** [comment]
fountain.fm doesn't follow lnurl specification
https://github.com/lnurl/luds/blob/luds/06.md
Quote:
```
LN Service takes the GET request and returns JSON response of form:

{
    pr: string, // bech32-serialized lightning invoice
    routes: [] // an empty array
}
```

This is the answer I received from there server:
```
{"pr": "xxxxx", "successAction": {"description": "You sent @brown 1 sats on Fountain!

See their profile at fountain.fm/brown", "tag": "url", "url": "https://fountain.fm/brown"}}
```

It laks `routes` field.

I think we can ignore it, but if you know whom to send this bug report, please do

**Comment by catch-21** [comment]
I'll let them know. Thanks @limpbrains

**Comment by MerryOscar** [comment]
@catch-21 @limpbrains this should be fixed on Fountain's side now - thanks for flagging.

**Comment by catch-21** [comment]
Verified in v127
