### ISSUE TITLE
[Feature]: Show Channel Point in Channel List

### ISSUE THREAD

**Issue by SeverinAlexB** [synonymdev/bitkit-react-native#1974]
### Describe the problem

When I try to debug, I don't have an easy way to access the channel point (funding tx + vout) in the app. That would help a lot tho.

### Describe the solution

Add channel point to the channel in the Lightning Connections list.

**Comment by catch-21** [comment]
Verified in 2e3cf89d424d3f05fe5c2727ab02b3c9f318454a
