### ISSUE TITLE
+v0.01 Bitkit update

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1996]
**LN URL Modal:** 

- [ ] Interface bug where scanning a Lightning Network (LN) URL consistently opens the modal popup twice. It briefly appears, closes (200ms), and then reopens with LN URL Payment UI details. We should ensure it opens correctly on the first attempt.

**Contact List Scrolling:** 

- [ ] We should ensure the send modal contact list is always scrollable, especially when use user has ±>10 contacts. Currently, on first attempt scrolling is not possible. Closing and reopening the modal sometimes resolves this. We should make scrolling work consistently.

**LN Loader on Receive:**

- [ ] We should show the same payment network loader animation when the user immediately hits “Receive” after opening the app as is currently done for the “Send” flow. The problem is that currently, initially only the Bitcoin on-chain address is shown, because the Lightning Node isn’t ready. If the user has an active spending balance (channel), we should display the LN loading animation until the Lightning Node finishes loading and Bitkit is able to generate the unified QR.

**Send to Contact (unified QR):**

- [ ] Balance Toggle Functionality: It would be nice to allow the sender to switch between “Savings” and “Spending” after scanning a unified QR code (see mockup video)
- [ ] Fixed States for Toggle:

	•	For On-chain-only QR codes, the toggle will be set to a fixed “Savings” state (see mockup video).
	•	For Lightning-only invoices, the toggle will be set to a fixed “Spending” state.

**Comment by pwltr** [comment]
Split into different tasks
