### ISSUE TITLE
Can't close channel

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1999]
Trying to close channel in beta results in this screen on infinite wait.

<img width="215" src="https://github.com/synonymdev/bitkit/assets/46056211/7ef76671-c6e3-45c4-b856-7f6b76da26a7">

**Comment by JeanlChristophe** [comment]
Here logs

[bitkit_ldk_logs_1718782536830.zip](https://github.com/user-attachments/files/15897369/bitkit_ldk_logs_1718782536830.zip)

**Comment by ovitrif** [comment]
30 errors logged from LDK saying:

```js
ERROR (LDK): Got non-closing error: 
Got a message for a channel from the wrong node!
No such channel for the passed counterparty_node_id
0296b2db342fcf87ea94d981757fdf4d3e545bd5cef4919f58b5d38dfdd73bf5c9
(lightning::ln::channelmanager 8839)
```

Could this be an attempt to close with the beta app a channel that was originally opened using the stable app?

I'm expecting this not to work currently, would need @Jasonvdb confirmation to be 💯 certain.
@JeanlChristophe Do we even want to do an effort to enable such compatibility?

**Comment by ovitrif** [comment]
> Could this be an attempt to close with the beta app a channel that was originally opened using the stable app?

It's not, as discussed internally with John. Everything is beta app.
