### ISSUE TITLE
[Bug]: LNURL bottom-sheet opens twice

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2000]
### Describe the bug

Interface bug where scanning a Lightning Network (LN) URL consistently opens the modal popup twice. It briefly appears, closes (200ms), and then reopens with LN URL Payment UI details. We should ensure it opens correctly on the first attempt.

### Operating system

iOS

**Comment by JeanlChristophe** [comment]
Can reproduce it also

**Comment by catch-21** [comment]
Bottom sheet opens once in v131
