### ISSUE TITLE
[Bug]: LN Loader on Receive

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2002]
### Describe the bug

We should show the same payment network loader animation when the user immediately hits “Receive” after opening the app as is currently done for the “Send” flow. The problem is that currently, initially only the Bitcoin on-chain address is shown, because the Lightning Node isn’t ready. If the user has an active spending balance (channel), we should display the LN loading animation until the Lightning Node finishes loading and Bitkit is able to generate the unified QR.

### Operating system

iOS

**Comment by catch-21** [comment]
See https://github.com/synonymdev/bitkit/pull/2010#issuecomment-2202960590 for testing notes.
