### ISSUE TITLE
[Bug]: Transfer activity has not moved to 'Confirmed' status even after new LN connection is established

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2026]
### Describe the bug

Transfer activity list entry and details page remain stuck showing "Transfer (± 10m)" long after transaction is confirmed.
Manual refresh does not resolve.

### Reproduce

1. Transfer from Savings to Spending
2. Wait for confirmation
3. Observe Transfer activity's status does not move to 'Confirmed'

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/497ea751-426e-48ab-acf8-83167d0dea3e

<img src="https://github.com/synonymdev/bitkit/assets/74595920/30df8d52-1ae1-4026-8087-43e57793c811" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/193967bf-0b06-4cea-9400-5c9b6392a5d4" width="300">

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v127

**Comment by catch-21** [comment]
I attempted to recreate this twice just now.  First attempt did not recreate the issue.  Second attempt did recreate the issue.

One difference between the two was that for the second attempt I tapped on the activity to view it, I did not do this for this first.
The other difference to note with the second attempt is the tx had an unconfirmed parent, although I don't believe that to be the case with the original occurrence detailed in the issue description.

**Comment by catch-21** [comment]
On further testing, it is possible that chained transitions could be the cause of this. Raised https://github.com/synonymdev/bitkit/issues/2036.

**Comment by limpbrains** [comment]
fixed in #2047

**Comment by catch-21** [comment]
Verified in v130 d8f96e7d6475d2eef04ae08f9d9dd2c8894a8218
Status in Activity list items and detail pages updated instantly and correctly.
