### ISSUE TITLE
[Bug]: Unable to pay contacts via LN despite having a channel already (v127) 

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2027]
### Describe the bug

both James and JC had opened LN Channels - tried sending funds via "pay a contact" feature - wasn't able to send via LN - only got the option for on-chain for some reason despite having enough funds.

I had to pay an LN invoice (from Bitkit) first before I was able to send funds via LN to contacts in Bitkit ... prior to that despite all 3 of us having channels (mine being CJIT) I was unable to (see video

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/a300bcdb-afce-47a2-b862-0d8dcfe298e6

[bitkit_ldk_logs_1719842144119.zip](https://github.com/user-attachments/files/16053901/bitkit_ldk_logs_1719842144119.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v127

**Comment by catch-21** [comment]
No issues with LN payment in v130 testing session. No issues with my testing over the past weeks.
Closing as verified.
