### ISSUE TITLE
[Bug]: No indication in 'Transfer From Spending' Activity list entry that it is unconfirmed

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2035]
### Describe the bug

After sending funds back from spending to savings, the activity card appeared without any indication that it is unconfirmed. Usually we see something like `(± 10m)`.

### Reproduce

1. Transfer all funds from spending balance to savings
2. Observe "Transfer From Spending' activity list item doesn't indicate the estimated duration to confirmation

### Screenshots / Recording

In this video, it is the "Transfer From Spending" activity for `+79 682`

[Transfer_from_spending_no_duration.webm](https://github.com/synonymdev/bitkit/assets/74595920/4d381d8e-99ad-4e94-929f-e2b2bf0a79a4)

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v128 e8f50564c6b4f471d9a336067fa5d54b4754c2d4

**Comment by limpbrains** [comment]
Philipp said because it is a coop close, funds are available immediately. So this is expected behaviour
