### ISSUE TITLE
[Bug]: Advanced transfer "you need more" error

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2041]
### Describe the bug

I already have a LN connection and when using the Advanced flow to transfer funds I get an error due to the spending balance amount being invalid. 

### Reproduce

1. With an exiting LN connection (and potentially affected by the amount I have in savings)
2. Go to Transfer Funds
3. Using the Advanced flow, attempt to use the maximum amount ($12 in my case)
4. A "you need more to complete this transaction" error toast is shown regardless of chosen receiving capacity

### Screenshots / Recording

[advanced_transfer_amount_err.webm](https://github.com/synonymdev/bitkit/assets/74595920/d6d4f589-c531-4725-a99e-2ab4e666c9be)

Existing LN connection details:

<img src="https://github.com/synonymdev/bitkit/assets/74595920/0ab96678-8862-43b0-9c79-12f0e9faeb9b" width="300">

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v128 e8f50564c6b4f471d9a336067fa5d54b4754c2d4

**Comment by JeanlChristophe** [comment]
@catch-21 I'm not sure I understand the problem. Can you elaborate?

here you are trying to open a new channel and you do not have enough onchain funds for it.

**Comment by catch-21** [comment]
@JeanlChristophe I would say the problem is that the only option I have in the Advanced flow is a value that is too high. At that time I had 27_597 savings and go to open a channel of 22_078 ($12), which leaves me with 5,519 to satisfy fees. If that it not enough for fees then I should be given the option to open using less than $12.

Feel free to close if this is not a valid or important issue.

**Comment by catch-21** [comment]
This flow has been replaced in favour of one with granular choice spending balance and therefore this issue is no more. Closing.
