### ISSUE TITLE
Android UI performance

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2052]
Try to improve performance on Android:
- setup basic performance profiling (CI)
- improve startup time
- fix lag on initial load and when putting app to foreground
- fix navigation lag

**Comment by pwltr** [comment]
Closing here, I think we're in a good place wrt performance now. Boot time is tracked separately [here](https://github.com/synonymdev/bitkit/issues/2014)

**Comment by catch-21** [comment]
Tested on v130 d8f96e7d6475d2eef04ae08f9d9dd2c8894a8218
The performance of the android app does seem improved. There are still times that UI is unresponsive but that can also be the case on iOS.
