### ISSUE TITLE
Redesign network and service fees

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2054]
It's critical to revamp networking and service fees to improve transparency and affordability for users during Savings to Spending transfers. Currently, our approach lacks clarity on aggregated networking fees and needs adjustment to make service fees more competitive.

**Network fees**
We have two on-chain transactions : 
- opening fees
- closing fees

**LSP fees**

Please find the full discussion here https://synonymworkspace.slack.com/archives/C01J0QPPV08/p1719909742092599?thread_ts=1719841046.874069&cid=C01J0QPPV08

**Comment by JeanlChristophe** [comment]
@SeverinAlexB from Blocktank we need to know what's the closing fees?

**Comment by SeverinAlexB** [comment]
Blocktank needs to distinguish this first.
https://github.com/orgs/synonymdev/projects/17/views/1?pane=issue&itemId=74424595

**Comment by catch-21** [comment]
We still need to do the "Attach refund address directly to the LN connection order" https://github.com/synonymdev/bitkit/issues/2043
