### ISSUE TITLE
[Feature]: Open Channel to any node 

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#2057]
### Describe the problem

While Bitkit does support LNURL-channel, there is no way to connect to nodes that do not generate such a QR. 

### Describe the solution

Need an Advanced Feature for manually entering the connection data and initiating a chan.

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/1972
