### ISSUE TITLE
[Feature]: Stealth Mode

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2059]
### Describe the problem

**Bitkit Mobile Prototype v49**

🔢 Settings > Privacy > Stealth Mode: Introducing Stealth Mode, turning Bitkit and its icon into a (non-functioning) calculator for privacy.
🔢 Launch > Stealth Mode: Users can enter their PIN on the calculator to access their Bitkit wallet, with the entered numbers not appearing on the display for added security. (edited)

**Comment by JeanlChristophe** [comment]
The stealth mode should work as a calculator and numbers should be be visible. People need to press the correct code and enter =
But people can also use it as calculator.

ex: Hide IT, vaulty, etc.
Ex video: https://x.com/anoneroio/status/1783913550991266030

**Comment by JeanlChristophe** [comment]
@pwltr what do you think of https://github.com/MrCyjaneK/libstealth_calculator ?

**Comment by catch-21** [comment]
This feature has been scrapped and in v1.0.4 it's not in the Security and Privicy settings.
