### ISSUE TITLE
[Feature]: Add more fiat currencies

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2061]
### Describe the problem

Some users ask us for more currencies (fiat). Some companies in the sector use Radyo instead of Coingecko.

### Describe the solution

We need :

**Step1**
- [ ] Identify and list Radyo's currency
- [x] Identify and list Coingeko's currency
- [ ] Analyse the prices offered compared to Coingecko

**Step 2**
- [ ] Look at exactly where Coingeko is used in Bitkit / Blocktank.

if approved
- [ ] Use Radyo
- [ ] check whether Coingeko is used in ToS @JeanlChristophe

**Comment by dzdidi** [comment]
The service responsible to pulling exchange rates is https://github.com/synonymdev/blocktank-fx-service
It uses two sources for corresponding quotes:
**Bitfinex**:
-  USD - US Dollar
-  EUR - Euro
-  GBP - Pound Sterling
-  JPY - Jananese Yen
-  USDT - Tether
-  EUT - Euro tether

The only fiat currency among supported by bitfinex which we do not use is Chinese Yuan [see https://support.bitfinex.com/hc/en-us/articles/360010505034-Fiat-on-Bitfinex-Frequently-Asked-Questions-FAQ] , is instead, retrieved from Coingeko

**Coingeko**:
- CAD - Canadian Dollar,
- AUD - Australian Dollar,
- MYR - Malaysian Ringgit,
- CHF - Swiss Franc,
- SGD - Singapore Dollar,
- AED - United Arab Emirates Dirham,
- HKD - Hong Kong Dollar,
- INR - Indian Rupee,
- CNY - Chinese Yuan Renminbi,
- KRW - South Korean Won,
- BRL - Brazilian Real,
- TRY - Turkish Lira,
- IDR - Indonesian Rupiah,
- NZD - New Zealand Dollar,
- ZAR - South African Rand,
- RUB - Russian Ruble,
- SEK - Swedish Krona,
- THB - Thai Baht,
- NOK - Norwegian Krone,
- HUF - Hungarian Forint,
- MXN - Mexican Peso,
- DKK - Danish Krone,
- ILS - Israeli Shekel,
- ARS - Argentine Peso,
- UAH - Ukrainian Hryvnia,
- PLN - Polish Zloty

Other currencies supported by Coingeko [see https://support.coingecko.com/hc/en-us/articles/4538839949081-Which-currencies-are-supported]  but not exported by our service are:
- BDT - Bangladesh Taka
- BHD - Bahraini Dinar
- BMD - Bermudian Dollar
- CLP - Chilean Peso
- CZK - Czech Krone
- GEL - Georgian Lari
- KWD - Kuwaiti Dinar
- LKR - Sri Lanka Rupee
- MMK - Myanmar Kyat
- PHP - Philipine Peso
- PKR - Pakistan Rupee
- SAR - Saudi Riyal
- TWD - New Taiwan Dollar
- VEF - Venezuela Bolivar
- VND - Vietnam Dong
- XDR - IMF Special Drawing Right

Adding them will simply require to add corresponding codes into config.

May somebody share link to Radyo? I can not find this service

**Comment by BitcoinErrorLog** [comment]
This, i think https://yadio.io/

**Comment by dzdidi** [comment]
additional currencies provided by Yadio, on top of those provided by coingeko are:
- NGN - Nigerian Naira
- ZAR - South African Rand
- KZT - Kazakhstan Tenge
- UGX - Uganda Shilling
- CFA - West Africa (?)
- TZS - Tanzanian Shilling
- MAD - Morrocan Dirham
- EGP - Egyptian Pound
- COP - Colombian Peso
- TND - Tunisian Dinar
- UZS - Uzbekistan Sum
- CRC - Costa Rica Colon
- BYN - Belorussian Ruble
- ALL - Albanian Lek
- KES - Kenyan Shilling
- GHS - Ghana Sedi
- XAF - Central African Frank
- ZMW - Zambian Kwacha
- BWP - Botswana Pula
- PEN - Peru, Nuevo Sol
- RON - Romanian Leu
- XCD - East Caribean Dollar (Dominicana)
- ETB - Ethiopean Birr
- BOB - Bolivia Boliviano,
- UYU - Peso Uruguay
- GTQ - Quetzal Guatemala
- PYG - Guarani Paraguay
- ISK - Icelandic Krone



On the moment of writing price difference of BTC/USD pair between Coingeko and Yadio is `0,061307342 %`  between Bitfinex and Yadio is `0,17258099 %` 


Coingeko - price is calculated in real-time by aggregating the latest data across 222 exchanges and 4890 markets, using a global volume-weighted average formula [ see https://www.coingecko.com/en/methodology ]

Yadio - use public data, so it is easily verifiable by anyone at anytime. We get the weighted average price of bitcoin in dollars using data from exchanges around the world, while simultaneously pulling data directly from multiple local bitcoin exchanges to calculate the price of bitcoin in local currency. [see https://yadio.io/info.html] - no specific number or sources except for p2p exchanges with which they are integrated

Bitfinex - order book

**Comment by dzdidi** [comment]
blocktank does not use coingeko at all, only bitfinex

**Comment by dzdidi** [comment]
@JeanlChristophe , it looks like FX and Blocktank parts are done. Now it is up to Bitkit and you to decide if adding Yadio is desired

**Comment by JeanlChristophe** [comment]
@dzdidi none of them are listing the Bulgarian Lev (BGN)](https://x.com/MadGrowr/status/1734639788152537221)?

Can you please add in the first place the others currencies supported by Coingeko?

    BDT - Bangladesh Taka
    BHD - Bahraini Dinar
    BMD - Bermudian Dollar
    CLP - Chilean Peso
    CZK - Czech Krone
    GEL - Georgian Lari
    KWD - Kuwaiti Dinar
    LKR - Sri Lanka Rupee
    MMK - Myanmar Kyat
    PHP - Philipine Peso
    PKR - Pakistan Rupee
    SAR - Saudi Riyal
    TWD - New Taiwan Dollar
    VEF - Venezuela Bolivar
    VND - Vietnam Dong
    XDR - IMF Special Drawing Right

@BitcoinErrorLog what do you think about the additional currencies listed by radio?

**Comment by dzdidi** [comment]
@JeanlChristophe yadio seem to have Lev (BGN) to USD exchange but not to BTC . 

> Can you please add in the first place the others currencies supported by Coingeko?


Yeah, will do.

@pwltr  may you please confirm that adding new currencies will not break anything on bitkit?

**Comment by pwltr** [comment]
@dzdidi Should be fine as long as all the currencies have the same format as in https://blocktank.synonym.to/fx/rates/btc/

**Comment by dzdidi** [comment]
@pwltr thanks, will test on staging first

**Comment by JeanlChristophe** [comment]
For the time being, we're not going to add currencies linked to Radio.
Once the all currencies from Coingeko are on production, we can close this ticket and reopen it if needed later @dzdidi

**Comment by catch-21** [comment]
Beware values in VND may get very long in the UI.

**Comment by dzdidi** [comment]
@pwltr I've added requested currencies on staging (available via API call) but do not see them on my regtest connected bitkit. Please have a look

**Comment by pwltr** [comment]
I can see them on the development build. I think we had requests for Bulgarian Lev and Polish Zloty which are not included but the ones listed in https://github.com/synonymdev/bitkit/issues/2061#issuecomment-2309664706 are there.

**Comment by dzdidi** [comment]
@pwltr ok, thank you. I went to `settings` > `general` > `local currency` and could not see them there, while in `settings` > `general` > `default unit` it is only `USD` or `Bitcoin`. Anyway... I'll update production tomorrow

**Comment by dzdidi** [comment]
Updated production with 
```
BDT - Bangladesh Taka
BHD - Bahraini Dinar
BMD - Bermudian Dollar
CLP - Chilean Peso
CZK - Czech Krone
GEL - Georgian Lari
KWD - Kuwaiti Dinar
LKR - Sri Lanka Rupee
MMK - Myanmar Kyat
PHP - Philipine Peso
PKR - Pakistan Rupee
SAR - Saudi Riyal
TWD - New Taiwan Dollar
VEF - Venezuela Bolivar
VND - Vietnam Dong
XDR - IMF Special Drawing Right
```

**Comment by catch-21** [comment]
Philippine*

**Comment by dzdidi** [comment]
@catch-21 thanks you, fixed

**Comment by JeanlChristophe** [comment]
Thanks. Closing it for the moment and we will reopen it if the marketing team want to add more currencies or if it's requested my users.
