### ISSUE TITLE
Testing Pipeline Bitkit

### ISSUE THREAD

**Issue by SeverinAlexB** [synonymdev/bitkit-react-native#2067]
@pwltr?

**Comment by pwltr** [comment]
What? :)

**Comment by SeverinAlexB** [comment]
Sorry, this is for the new DevOps. A task to look into the Bitkit Testing to see if there is anything he can improve. Probably should have tagged James not you. @catch-21

**Comment by catch-21** [comment]
At this stage, we're not in a bad place wrt Bitkit test pipelines.
Things will get more complicated over time, such as there could be a requirement for external trigger events for the system-level tests when new versions of Blocktank are deployed into production.
For now, prioritise Pubky and Blocktank over Bitkit and leave it with me to identify anything we need in the near future.

**Comment by SeverinAlexB** [comment]
Do you want me to close this issue?

**Comment by catch-21** [comment]
Closing due to no immediate tasks required.
