### ISSUE TITLE
Wallet loading (v50)

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2082]
This new feature is part of the v50 [#2084 ](https://github.com/synonymdev/bitkit/issues/2084)

New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228002&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228002&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228007&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228007&show-proto-sidebar=1&hide-ui=1

Wallet Loading: Added spinning loading indicators for Total balance, Spending, and Savings balances.

**Comment by JeanlChristophe** [comment]
Please update #2084 when it's done

**Comment by JeanlChristophe** [comment]
![Image](https://github.com/user-attachments/assets/666f136b-ca1b-4b69-985d-34d8377936e9)

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/1934
