### ISSUE TITLE
Minor changes (v50)

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2083]
v50 [#2084 ](https://github.com/synonymdev/bitkit/issues/2084)

New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228002&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228002&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228007&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228007&show-proto-sidebar=1&hide-ui=1

- [x] :art: Transfer to Savings Progress Card: Changed color to #FF4400 for moving funds back to savings (channel closures) for consistency.
- [x] :moneybag: Spending Balance Details: Added amount to incoming transfer indicator.
- [x] :jigsaw: Add Widget Button: Updated appearance to match the ‘Show All Activity’ button.
- [ ] :construction: New Toast Message: To prevent users from opening a new CJIT channel while another is closing.
  - Title: ‘Transfer in Progress’
  - Message: ‘Please wait for the transfer from your spending balance to your savings to be completed.’
- [x] :wrench: Numpad Actions: Improved alignment and spacing.
- [x] :writing_hand: Connection Closed Modal: Updated paragraph copy.

**Comment by JeanlChristophe** [comment]
Please update #2084 when it's done

**Comment by pwltr** [comment]
'New Message Toast' is tracked separately here: https://github.com/synonymdev/bitkit/issues/1910
