### ISSUE TITLE
[Bug]: Restoring wallet shows incorrect savings and spending balances for a long time (also lightning error)

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2091]
### Describe the bug

Coming from v128, restoring my wallet on the latest build from default branch took a very long time to get my savings and spending balance (over 3 minutes). A lightning sync error was displayed in the process. See attached video, which is very long so here is the breakdown:

- 0:17 - Wallet is restored with incorrect spending balance of `0` and savings balance of `534 712` (correct value).
- 0:20 - Savings balance changes to `534 416` (incorrect value).
- 0:25 - Savings balance changes to `0`. All balances are no `0`. Historical spending activities can be seen.
- 0:35 - Historical spending activities still displayed.
- Long wait...
- 0:56 Tap on "Show All Activity", nothing happens.
- 1:07 Tap on "Show All Activity" again, nothing happens.
- Long wait...
- 2:07 'All Activity' page loads. Correctly showing historical savings and spending activities.
- 2:13 Close 'All Activity' page. Savings balance has returned to `534 416` (incorrect value).
- 2:33 'Lightning Sync Error' toast is displayed
- 3:02 Manual refresh (swipe down)
- 3:03 Savings balance changes back to `534 712` (correct value).
- 3:17 LN suggestion changes to "READY". Spending balance changes to `136 495` (probably correct).

### Reproduce

On a fresh install of bitkit, restore wallet that has both savings and spending balance. Wait for balances to display correctly.

### Screenshots / Recording

https://github.com/user-attachments/assets/ee2b651e-9606-48f8-9493-57d75060aa7c

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

e0693f04d1fecab16f23a14a1cc98015c6cac4f5

### Log output

[bitkit_ldk_logs_1721898297202.zip](https://github.com/user-attachments/files/16373360/bitkit_ldk_logs_1721898297202.zip)

**Comment by catch-21** [comment]
In an attempt to break this down, here are some already existing issues related to this wallet recovery experience:
- https://github.com/synonymdev/bitkit/issues/1729
- ...

**Comment by JeanlChristophe** [comment]
@Jasonvdb 
 Can you give me an at-a-glance estimate of the complexity of the task?

**Comment by JeanlChristophe** [comment]
Jay: "You have like 9 past channels I think it is still requesting block data for. Wondering if that plus the on chain rescan might be causing electrum to shit the bed"

James: "Not 9. I distinctly recall 3 in recent week but this wallet is months old."

**Comment by Jasonvdb** [comment]
@catch-21 will you retest with matching env? 99% sure this solves all the weirdness related to the lightning balance

**Comment by catch-21** [comment]
Yeah, restoring lightning is working fine with v130.
All this all occurred with the wrong env. I'll trash this ticket and raise any issues separately.
