### ISSUE TITLE
Local notification to open Bitkit

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2094]
**Description**

When a user makes a request to open a channel, the user must come back to the app in between the time the channel is ready to be opened and before channel expiry. However, since the transaction can take several hours or even several days some users may forget and miss the time window, ending up with an expired channel order.

The problem is that the BT order is only valid for 2 days. We therefore need to warn the user to open Bitkit.

Ex: https://synonymworkspace.slack.com/archives/C0726U60V6Y/p1721769530317439

**Solution**
Schedule local notifications telling the user that he must open Bitkit in order to continue the channel opening process.
- First notification after 24 hours
- Second notification after 40 hours (this notification will not be shown if the channel was opened before then)

Note:
We don't check if the channel purchase transaction actually got confirmed (will be solved with wakeToOpen), so there can be the case where fees are spiking and the transaction doesn't confirm before order expiry. In this case the notifications will still (falsely) appear.

**Comment by aldertnl** [comment]
![image](https://github.com/user-attachments/assets/5a048c0b-df44-40e1-8353-69e78b4542e6)

**Comment by JeanlChristophe** [comment]
First: after 24h
Second: After 40h

**Comment by pwltr** [comment]
Updated description to better explain the problem and implementation

**Comment by JeanlChristophe** [comment]
I received a notification 24h after on my phone. But Once I clicked on it, nothing happened. I needed to open myself Bitkit.

**Comment by pwltr** [comment]
The changes from the stealth mode feature did break this on Android. If we end up reverting that feature this will be resolved.

**Comment by JeanlChristophe** [comment]
Yes, during the dev call Johna said we were killing this feature, right?
