### ISSUE TITLE
[Bug]: Lizard emoji changes to brown heart in profile bio

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2096]
### Describe the bug

When I use the lizard emoji in my profile bio, after saving it changes to a brown heart 🤷‍♂️ 

### Reproduce

1. Go to edit your profile
2. Insert the lizard emoji
3. Save Profile
4. Leave profile page
5. Return to profile page
6. Observe brown heart instead of lizard

### Screenshots / Recording

https://github.com/user-attachments/assets/831dc719-8634-4a2e-99c1-1718e49c673d

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v130 d8f96e7d6475d2eef04ae08f9d9dd2c8894a8218

**Comment by JeanlChristophe** [comment]
Also here
<img src="https://github.com/user-attachments/assets/46afb0fd-a2c1-41f8-b9c8-81250babf759" width="300">
-----
<img src="https://github.com/user-attachments/assets/06d3cf67-afcd-4963-907e-2eaddc584be0" width="300">

**Comment by catch-21** [comment]
Verified with 033edb4a46ff8d407baa25587cd5d86f6fc9c6c3 on mainnet
