### ISSUE TITLE
[Bug]: currency denomination of fees

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2097]
### Describe the bug

When I want to make an onchain tx, I've set up my parameter so that sats are displayed. However, the fees are in euros. The fees should be in the type of denomination/currency chosen.

### Screenshots / Recording

![Screenshot_20240726-102613 (1)](https://github.com/user-attachments/assets/78608e4c-9956-4430-83c0-ef3c38cc9b53)

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v130

**Comment by limpbrains** [comment]
Fees are alywas in fiat as per design.
Fee will not fit if it will be in BTC classic denomination, and will break the UI
