### ISSUE TITLE
[Bug]: 'Sent Bitcoin' screen shows wrong address 

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2098]
### Describe the bug

The address shown in the 'Sent Bitcoin' activity page is not the address sent to, it is my address from the previous transaction.

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/65463c4e-c178-4b4e-b9d7-1fedf2cb3a7e)

txid: b9cc7d252ec52c3371637ca34faff3deab3a2a9eb627c5ed7c19ad2b07a37011

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v130 d8f96e7d6475d2eef04ae08f9d9dd2c8894a8218

**Comment by pwltr** [comment]
UI needs to respect the CPFP here and not update the output address, I can take this.

**Comment by limpbrains** [comment]
This address field comes from beignet and has wrong value without any CPFP

**Comment by pwltr** [comment]
> This address field comes from beignet and has wrong value without any CPFP

I can't reproduce this with a normal transaction (without CPFP)

**Comment by limpbrains** [comment]
Nope, it is mine

**Comment by catch-21** [comment]
Verified with 033edb4a46ff8d407baa25587cd5d86f6fc9c6c3 that the address field has now been removed.
