### ISSUE TITLE
Could Bitkit show the EUR equivalent

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2101]
From a user

![Image](https://github.com/user-attachments/assets/ed8992a2-6289-4ece-b1da-2cf1ffd5ecb8)

**Comment by aldertnl** [comment]
Please see a proposed solution in our internal Slack channel.

**Comment by JeanlChristophe** [comment]
https://synonymworkspace.slack.com/archives/C01H106JRQB/p1724232490247799

**Comment by aldertnl** [comment]
added to prototype v51

**Comment by pwltr** [comment]
This was implemented in https://github.com/synonymdev/bitkit/pull/2337
