### ISSUE TITLE
Adding channel with external node/LSP

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2118]
A user should have the possibility to connet channels from others LSP or nodes.

**Example or the process:**

- Get start with Spending balance

![Image](https://github.com/user-attachments/assets/13041ee5-cb3d-4845-96d8-d3b5a5691cb4)

- Select "External node"

![Image](https://github.com/user-attachments/assets/4d757d02-934e-46cf-b8cd-acad9114519f)

here external node is a bit mislanding: users could think they can use a remote node with Bitkit. maybe here we can say External channel?

- LNURL Channel or Connected Manually
                               - LNURL chanel
                               - Manual https://github.com/synonymdev/bitkit/issues/1972

**Comment by Jasonvdb** [comment]
PR with instructions on how to implement in LDK are here https://github.com/synonymdev/react-native-ldk/pull/268
