### ISSUE TITLE
background receiving from Blocktank

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2124]
- [x] synonymdev/bitkit-android#8
- [ ] synonymdev/bitkit-android#12

**Comment by ovitrif** [comment]
@JeanlChristophe Is this about registering for push notifications from Blocktank?

**Comment by JeanlChristophe** [comment]
Yes, you are right @ovitrif

**Comment by ovitrif** [comment]
> Yes, you are right @ovitrif 

Perfecte, thank you. Means I'm working on the right thing 😅
