### ISSUE TITLE
[Feature]: Use higher than 'fast' fee rate for channel opening transaction

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2139]
### Describe the problem

Bitkit uses the 'fast' fee rate provided by mempool.space for channel opening transactions. In times of low network activity, fee rates are stable but can be subject to small spikes in the market fee rate that can push the transaction out of the next block, or several. One example that can cause this is when block discovery has slowed.

### Describe the solution

For the sake of a few sats the UX may be improved by Bitkit preemptively applying a 'surplus' to the fee used for channel opening transactions to beat the market if the real fee rate increases before the transaction confirms. For example, add 5sat/vb to 'fast' for channel opening transactions only.

### Additional context

See internal discussion for more details https://synonymworkspace.slack.com/archives/C01H106JRQB/p1723550212066839

**Comment by pwltr** [comment]
When fees are below ~10sats/vbyte always use a higher fee rate (5sats/vbyte) to avoid the tx not confirming in fee spike environment.

**Comment by catch-21** [comment]
Verified on v1.0.8
Observed higher fee rate used in recent channel opening.
