### ISSUE TITLE
[Bug]: Receive button on Spending page always performs CJIT onboarding

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2140]
### Describe the bug

If the wallet already has a lightning channel and user is on the 'Spending' page, if the Receive button is pressed then the CJIT flow is triggered. It should only do this when the wallet has no LN channel.

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v130

**Comment by catch-21** [comment]
Tested on v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

@pwltr is it intentional that when there are historical spending activities it goes straight to CJIT flow? I ask because the "send Bitcoin to your SPENDING BALANCE" message and arrow are not displayed anymore.

https://github.com/user-attachments/assets/d5bccaf9-c2f9-4474-8261-4efc450e921b

**Comment by pwltr** [comment]
No you're right this probably should only go to CJIT when there is no receiving capacity. Right now it checks whether spending balance is 0.

**Comment by catch-21** [comment]
Verified in v134
Now the only time it goes straight to CJIT on the Receiving page is when the onboarding text and arrow are shown. All other times it behaves the same as home page but showing the QR. Nice and simple.
