### ISSUE TITLE
[Bug]: Duplicate Activity item for transfer to spending

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2147]
### Describe the bug

Sometimes the activity item for transfers to spending is duplicated in the list. One for the transfer and one normal send. Not sure about the exact steps to reproduce yet.

### Screenshots / Recording

https://github.com/user-attachments/assets/5ffb8c21-749c-4869-9b34-834c9b798abe

### Operating system

Android

### Bitkit version

afd07c52

**Comment by catch-21** [comment]
To reproduce, you initiate a transfer from savings and then send a new tx before that transfer confirms.

https://github.com/user-attachments/assets/dbdf2f82-3526-4422-8148-5c09c00176e8

**Comment by catch-21** [comment]
Verified in b3f9f30dd56e4a1666492c3219f352d2bcd77086 on Android 14
The first activity shows "Transfer From Savings" and the second shows "Sent", to do not change after confirmation. All good.
