### ISSUE TITLE
[Bug]: Problem with scanning a contact

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2157]
### Describe the bug

When I want to add a new contact, I have to click repeatedly on the scan icon for it to open it.

### Reproduce

1. Go to 'Contacts'
2. Click on 'Add contact" icon "+"
3. Clock on Scan icon

### Screenshots / Recording

https://github.com/user-attachments/assets/1369ac10-b593-4d55-be94-71a37af68cff

### Operating system

GrapheneOS

### Bitkit version

v132

**Comment by pwltr** [comment]
See https://github.com/synonymdev/bitkit/issues/1635
