### ISSUE TITLE
[Bug]: Contact doesn't update

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2158]
### Describe the bug

My contact changed his name and profile picture. Nothing change.
I rescanned his QR, the photo changed but not the name.
I deleted the contact. Rescaned his QR and names and Profile picture were good.

### Operating system

GrapheneOS

### Bitkit version

v132

**Comment by limpbrains** [comment]
Name should not change.
Image should.
I can't reproduce this issue. Trying iOS/Android and dev/production builds

**Comment by limpbrains** [comment]
fixed, there was an issue with ST storage
