### ISSUE TITLE
[Bug]: Max channel duration 52 weeks (instead of 12)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2159]
### Describe the bug

Max duration for a LN channel on Bitkit is 52 weeks, instead of 12 weeks (as stated in ToS)

### Reproduce

Go to Settings > Advanced > Lightning Connections > try setting up a normal channel, select amount and size of channel then adjust channel duration. According to the ToS the max term should be 12 weeks. On v 132 I am able to set it up to 52 weeks (the maximum allowed on Bitkit in this current version) 

### Screenshots / Recording

https://github.com/user-attachments/assets/3699d68c-1f2b-4417-9c3b-32307e724072

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v132

**Comment by pwltr** [comment]
The new transfer UI will remove the ability to configure channel duration, but 52 is still the max duration allowed by Blocktank. Leaving to @SeverinAlexB whether it needs to be changed there.

**Comment by SeverinAlexB** [comment]
Max duration was always 52 weeks. 12w was usually the default Bitkit purchased a channel for. I think you guys decreased that to 6w. If not legally required, I don't see why I should reduce the 52w.

**Comment by JeanlChristophe** [comment]
This must be 12 for the Bitkit purchase, because that's what we say in our ToS. However we don't usually close them, so yes we can keep 52 weeks for Blocktank.

**Comment by catch-21** [comment]
Tested on 2e3cf89d424d3f05fe5c2727ab02b3c9f318454a
In the new transfer flow, duration is fixed to 6 weeks. Need to increase to 12.

![Image](https://github.com/user-attachments/assets/a8357f7f-34b6-4bbf-b2fa-eb97e58fe582)
