### ISSUE TITLE
[Bug]: The loading wheel during a boost does not work properly

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2162]
### Describe the bug

I am boosting the transaction and the loading wheel doesn't load properly.

### Operating system

GrapheneOS

### Bitkit version

v132

**Comment by limpbrains** [comment]
What is wrong with it? Can you please post screenshot or something?

**Comment by JeanlChristophe** [comment]
https://github.com/user-attachments/assets/6047a58f-b50c-49e3-a925-a784ec79e729

**Comment by catch-21** [comment]
Verified in v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914
Boost swipe is working just fine.
