### ISSUE TITLE
[Bug]: Activity list isn't accurate

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2170]
### Describe the bug

Today I created a transaction (onchain) but it's listed on "this month"

### Screenshots / Recording

https://github.com/user-attachments/assets/da55dab8-4064-4f7d-ba07-7f2bcbd67c63

### Operating system

GrapheneOS

### Bitkit version

v133

**Comment by pwltr** [comment]
I see that this is the same transaction as in https://github.com/synonymdev/bitkit/issues/2171. There are several things wrong if I understand correctly:
- It's marked as a transfer even though it should be a normal send (to self)
- the fees are wrong
- it's grouped in 'This Month' even though it was sent 'Today'

Could be related to https://github.com/synonymdev/bitkit/issues/2147

**Comment by catch-21** [comment]
Tried to reproduce this with 1.0.5 (137) by creating send to self around the same time as a transfer. Never did I see an activity duplicated or have wrong information.
