### ISSUE TITLE
[Bug]: Fees are incorrect when sending to oneself

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2171]
### Describe the bug

I carried out a transaction on my own but it was the wrong fees. However, those in the same on Mempool are correct.
https://mempool.space/tx/469cdcb4c02acb09c54498f07b0200b6d9cc75158d7fa854b0ca6778a37f9e84?mode=details

### Screenshots / Recording

https://github.com/user-attachments/assets/568ca7dc-4f36-4295-8371-276660c7e7af

### Operating system

GrapheneOS

### Bitkit version

v133

**Comment by limpbrains** [comment]
This is BT channel opening, so fee contains BT fee as well

**Comment by JeanlChristophe** [comment]
Nope, BT channel isn't 35k sats.
The amount sent (996) indicated is in fact the onchain fees here.

**Comment by JeanlChristophe** [comment]
I can't reproduce it at the moment

**Comment by catch-21** [comment]
I have been unable to reproduce this using 1.0.5 (137)
@JeanlChristophe are you happy for this to be moved to Done or would you like to attempt to recreate?

**Comment by catch-21** [comment]
I think this was simply due to CPFP fee calculation
