### ISSUE TITLE
[Bug]: Wrong amount for channels when I want to close them

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2174]
### Describe the bug

You can see that there are schannels with the amount 0 when I want to close them, but I don't really have any with 0.

### Screenshots / Recording

![Screenshot_20240830-113220](https://g

https://github.com/user-attachments/assets/7e4ce881-73f3-4a27-a1ad-dfb6a0109bdc

ithub.com/user-attachments/assets/0d754d2f-3af3-449a-9867-8dcdd863262e)

### Operating system

GrapheneOS

**Comment by pwltr** [comment]
@JeanlChristophe Post LDK logs please

**Comment by JeanlChristophe** [comment]
Error on my side. Nothing wrong here.
