### ISSUE TITLE
[Bug]: When I want to close a channel and I select one, Bitkit deselects all the channels.

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2175]
### Describe the bug

When I want to close a channel and I select one, Bitkit deselects all the channels. It doesn't reproduce all the time.

### Screenshots / Recording

https://github.com/user-attachments/assets/a244ac4e-dc92-43c0-b351-ca85824c8641

### Operating system

GrapheneOS

### Bitkit version

v133

**Comment by pwltr** [comment]
I can't reproduce this one.

**Comment by JeanlChristophe** [comment]
On tesnet or production?

**Comment by pwltr** [comment]
> On tesnet or production?

Regtest, although network shouldn't really matter in this case.

**Comment by JeanlChristophe** [comment]
I can't reproduce it also now.

**Comment by pwltr** [comment]
Fixed in https://github.com/synonymdev/bitkit/pull/2305
