### ISSUE TITLE
Missing coins image on transfer to spending PLEASE CONFIRM page

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2181]
### Description

Design: Image of three coins above the Swipe To Transfer slider that is animated to tilt as slider is used

Actual: No image

<img src="https://github.com/user-attachments/assets/0b889e33-9385-46cd-81c6-7b5529b09b5b" width="200">

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

**Comment by pwltr** [comment]
Please check revised layout in the Figma

**Comment by pwltr** [comment]
Missing animation: https://github.com/synonymdev/bitkit/issues/2207

**Comment by catch-21** [comment]
Tested on v134
Coins are there but the animated tilt is missing. We can address this later, see https://github.com/synonymdev/bitkit/issues/2207
