### ISSUE TITLE
[Bug]: Custom receiving capacity different to value shown once applied

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2184]
### Describe the bug

If custom receiving capacity is set then the value differs on the PLEASE CONFIRM and LIQUIDITY & ROUTING pages, the latter is slightly lower. They should match.

### Reproduce

1. Go to RECEIVING CAPACITY page
2. Override the value to something other than default
3. Observe the receiving capacity value in the bar-view is slightly lower than the value chosen, it should be the same.

### Screenshots / Recording

https://github.com/user-attachments/assets/5e0ebcf8-044d-42c1-af78-bfc50d31d8a6

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/2183, see comment https://github.com/synonymdev/bitkit/issues/2183#issuecomment-2328884123

**Comment by catch-21** [comment]
Verified in v134
