### ISSUE TITLE
[Bug]: "Channel size too big" error can occur on the TRANSFER TO SPENDING page

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2185]
### Describe the bug

"Channel size too big" error can occur on the TRANSFER TO SPENDING value input page. I suspect this is only when max is selected and Blocktanks maximum changes. Seeing the whole capacity value in the error isn't useful to the user as they only have control of the spending balance here. We could reset the max or improve the error when this occurs.

### Reproduce

1. Go to transfer from savings to spending
2. On the TRANSFER TO SPENDING value input page, select max value
3. Wait a while for exchange price to change in the backend
4. Try to proceed
5. Observe "Channel size too big" error

### Screenshots / Recording

https://github.com/user-attachments/assets/24dbcfb0-e5bf-45fc-b39e-b87e8e538696

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

**Comment by pwltr** [comment]
Fixed [here](https://github.com/synonymdev/bitkit/pull/2197) by adding a 10% buffer to account for fluctuations while making the order.

**Comment by catch-21** [comment]
>Fixed https://github.com/synonymdev/bitkit/pull/2197 by adding a 10% buffer to account for fluctuations while making the order.

I appreciate this will almost always avoid this issue, but 10% is quite a big sacrifice for a scenario that most will never encounter. 

It may also be causing this problem when I select Max and get an error (need to test with other balances)

<img src="https://github.com/user-attachments/assets/a490585c-56b8-4e19-8042-366fedf0838a" width="300">

**Comment by catch-21** [comment]
Tried again just now and got a different error. Would be good to try this more and see if it is related to this or a new issue.

<img src="https://github.com/user-attachments/assets/587fb696-daaa-4138-b1e7-9e3eb02e110d" width="300">

**Comment by catch-21** [comment]
Tested on 1.0.6 (138)
10% has been applied, unable to reproduce issue.
