### ISSUE TITLE
[Bug]: Possible to pay channel order after expiry

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2187]
### Describe the bug

It is possible to create the channel order and swipe to pay after the order has expired (30 minutes). The onchain transaction is still broadcast but channel fails with status 'Order expired'. Can we check the invoice has not expired with a sensible tolerance before broadcasting?

### Reproduce

1. Go to transfer from savings to spending
2. Once the channel order has been made, wait 30 minutes
3. Swipe to pay
4. Onchain tx is broadcast but channel creation immediately fails

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

**Comment by pwltr** [comment]
Order expiration on production/mainnet is 2 days. I don't think this is worth fixing. Closing.

**Comment by catch-21** [comment]
@pwltr The initial offer (before tx is broadcast) is only valid for 30 minutes. I was imagining if someone left the offer open and came back after 30 minutes and swiped to pay, it would broadcast the tx to an expired offer. It still may not be worth fixing but wanted to clarify.

**Comment by pwltr** [comment]
I wasn't aware that offers can expire, but makes sense. @SeverinAlexB Can you confirm this 30m window for order payment? Do you think it makes sense to expose this via `/info`?

**Comment by SeverinAlexB** [comment]
On staging, the offer is only valid for 30min. On mainnet, it is 48hrs. Can you elaborate how this info would help in the `/info` endpoint? It is already in the individual order.
![CleanShot 2024-09-03 at 13 48 45@2x](https://github.com/user-attachments/assets/6aea10d1-661c-48aa-89b4-305a6a6f5c02)

**Comment by catch-21** [comment]
Ah, I would have been on staging when I noticed this short duration. It is unlikely someone will keep the app open for over 48 hours without paying an order. Although a possible situation, it's probably not worth fixing.

**Comment by SeverinAlexB** [comment]
I can increase the order duration on staging too if you want. Should I?

**Comment by SeverinAlexB** [comment]
Done. Extended to 48hrs on staging.
