### ISSUE TITLE
Update Bitkit ToS

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2189]
Current Bitkit ToS on the website are:

"The minimum configurable Connection Duration shall be four weeks and maximum configurable Connection Duration shall be 12 weeks, subject to the rights of Synonym to extend or reduce such maximum or minimum Connection Duration at any time, without notice to you and to otherwise close a Blocktank Connection pursuant to these Terms."

Please modify this secton for:
"The configurable Connection Duration shall be 6 weeks, subject to the rights of Synonym to extend or reduce such maximum or minimum Connection Duration at any time, without notice to you and to otherwise close a Blocktank Connection pursuant to these Terms."

**Comment by catch-21** [comment]
Verified in v134
