### ISSUE TITLE
UI crash: Error: Cannot read property 'getBoostedTransactionParents' of undefined > >

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2202]
> > Error: Cannot read property 'getBoostedTransactionParents' of undefined
> >

> > Component Stack:
> > in OnchainActivityDetail
> > in RCTView
> > in Unknown
> > in RCTScrollView
> > in ScrollView
> > in ScrollView
> > in RCTView
> > in Unknown
> > in StyledNativeComponent
> > in Unknown
> > in ActivityDetail
> > in StaticContainer
> > in EnsureSingleNavigator
> > in SceneView
> > in RCTView
> > in Unknown
> > in DebugContainer
> > in MaybeNestedStack
> > in RCTView
> > in Unknown
> > in RNSScreen
> > in Unknown
> > in Suspender
> > in Suspense
> > in Freeze
> > in DelayedFreeze
> > in InnerScreen
> > in Screen
> > in SceneView
> > in Suspender
> > in Suspense
> > in Freeze
> > in DelayedFreeze
> > in RNSScreenStack
> > in ScreenStack
> > in NativeStackViewInner
> > in RCTView
> > in Unknown
> > in SafeAreaProviderCompat
> > in NativeStackView
> > in PreventRemoveProvider
> > in NavigationContent
> > in Unknown
> > in NativeStackNavigator
> > in EnsureSingleNavigator
> > in BaseNavigationContainer
> > in ThemeProvider
> > in NavigationContainerInner
> > in StyledNativeComponent
> > in Unknown
> > in RootNavigator
> > in RCTView
> > in Unknown
> > in InactivityTracker
> > in AppOnboarded
> > in SlashtagsProvider
> > in RNCSafeAreaProvider
> > in SafeAreaProvider
> > in StyledNativeComponent
> > in Unknown
> > in ThemeProvider
> > in App
> > in PersistGate
> > in Provider
> > in ErrorBoundary
> > in Root
> > in RNGestureHandlerRootView
> > in GestureHandlerRootView
> > in gestureHandlerRootHOC(Root)
> > in RCTView
> > in Unknown
> > in AppContainer
> >

> > Stack: TypeError: Cannot read property 'getBoostedTransactionParents' of undefined
> > at getBoostedTransactionParents (address at index.android.bundle:1:2635725)
> > at anonymous (address at index.android.bundle:1:4206459)
> > at useMemo (address at index.android.bundle:1:474645)
> > at anonymous (address at index.android.bundle:1:201125)
> > at OnchainActivityDetail (address at index.android.bundle:1:4201755)
> > at renderWithHooks (address at index.android.bundle:1:430297)
> > at beginWork (address at index.android.bundle:1:478353)
> > at performUnitOfWork (address at index.android.bundle:1:464633)
> > at workLoopSync (address at index.android.bundle:1:463763)
> > at renderRootSync (address at index.android.bundle:1:463594)
> > at flushSyncWorkAcrossRoots_impl (address at index.android.bundle:1:419984)
> > at batchedUpdatesImpl (address at index.android.bundle:1:478728)
> > at batchedUpdates$1 (address at index.android.bundle:1:411251)
> > at _receiveRootNodeIDEvent (address at index.android.bundle:1:411536)
> > at receiveTouches (address at index.android.bundle:1:473690)
> > at apply (native)
> > at __callFunction (address at index.android.bundle:1:144176)
> > at anonymous (address at index.android.bundle:1:142615)
> > at __guard (address at index.android.bundle:1:143557)
> > at callFunctionReturnFlushedQueue (address at index.android.bundle:1:142573)
> >

> > Platform: android 14
> > Version: 1.0.4 (133)
> > LDK version: ldk-v0.0.123-36-g1027b935fb92b924 c_bindings-v0.0.123.1)

**Comment by catch-21** [comment]
Tested on [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [f0cde24](https://github.com/synonymdev/bitkit/commit/f0cde24a9f71cabb4c6f1887eeb4b070ab19c904)
Tried combinations of new transactions, transfer, boosting; restarting the app and quickly viewing each of these. No problems.
