### ISSUE TITLE
[Bug]: Keyboard can cover comment box in 'Pay Bitcoin' screen

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2204]
### Describe the bug

On a device with a smaller display, such as iPhone8, the keyboard can cover the comment box and make it hard to know what is being typed. This isn't helped by the Swipe To Pay slider being pushed up either.

### Reproduce

1. Go to pay a LN invoice
2. At the 'Pay Bitcoin' screen, tap the comment box to input a message
3. Observe keyboard mostly covers the comment box input area

### Screenshots / Recording

https://github.com/user-attachments/assets/b549b61d-3fdd-4ee4-8e85-785c91d26947

### Operating system

iPhone8 (iOS16)

### Bitkit version

v134

**Comment by limpbrains** [comment]
Fixed in #2318

**Comment by catch-21** [comment]
Verified in v1.0.8
