### ISSUE TITLE
[Bug]: Sent transaction can show as duplicated Transfer Activity

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2217]
### Describe the bug

After making a transfer to Spending, sending funds to a different wallet showed up as a duplicate Transfer Activity.

### Reproduce

1. Receive some funds for 19_000 (127ef60cdcd16be2ee87943f8f151351d98089faed0f74e7e51e8061a8647cbd)
2. Whilst previous tx is unconfirmed, transfer 25_000 to spending (cost 26_836 in total) (8ea066a512324b86e014f7a07a0b5efe1d9463c35509ea6f29ffbd6d859dcae2)
3. Whilst previous tx is unconfirmed, send 26_000 to a different wallet.
4. Observe the latest tx is represented as aTransfer activity, a duplicate of the previous transfer. Even the txid is the same.

### Screenshots / Recording

https://github.com/user-attachments/assets/1a80f1c8-90d6-40e2-b6fe-cdb125b155cd

### Operating system

Android 14

### Bitkit version

1.0.4 (135)

**Comment by limpbrains** [comment]
2218 is not related, I've linked it by mistake

**Comment by pwltr** [comment]
Sounds like duplicate of https://github.com/synonymdev/bitkit/issues/2147

**Comment by catch-21** [comment]
Yep, duplicate.
