### ISSUE TITLE
[Bug]: Skip Transfer Intros after first time

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2222]
### Describe the bug

These intros have to appear only the first time but at the moment it keeps popping up each time.

- [ ] Spending balance

<img width="375" alt="Lightning onboarding Intro" src="https://github.com/user-attachments/assets/d80f663b-a8a7-467a-8435-fa87a08bee10">

- [ ] Transfer to savings
<img width="375" alt="Transfer to savings" src="https://github.com/user-attachments/assets/47967544-66c3-43dd-87ba-a71e4d562131">

https://www.figma.com/design/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?node-id=25792-117980&t=ZykrpdwwKyziDYc1-4

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v135

**Comment by catch-21** [comment]
Verified on v1.0.6 (138) both ways (to spending and to saving)
