### ISSUE TITLE
[Bug]: Min spendable used as default value for LNURL Pay can prevent proceeding if fiat value is zero

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2239]
### Describe the bug

I was testing my qr code on a video I’m about to publish found another bug!
Notice how I cannot spend the £ amount, But I can spend in the btc denomination.

For reference: https://lightningdecoder.com/LNURL1DP68GURN8GHJ7AMPD3KX2AR0VEEKZAR0WD5XJTNRDAKJ7TNHV4KXCTTTDEHHWM30D3H82UNVWQHK5MM9DESKKCTDDA6X7UFLY66

### Screenshots / Recording

[bitkit_ldk_logs_1726576205816.zip](https://github.com/user-attachments/files/17028438/bitkit_ldk_logs_1726576205816.zip)

https://github.com/user-attachments/assets/b371d327-e70f-4f84-b05a-e7ba8f487512

### Operating system

iOS

### Bitkit version

v135

**Comment by catch-21** [comment]
Suggestions:
- Keep the default value being set as min spendable in the invoice but allow proceeding even when fiat value is zero
- Don't use the min spendable value from the invoice as the default value (but still validate against using a lower value)

**Comment by catch-21** [comment]
Verified in 1.0.5 (137)
The minimum value is no longer used so this invoice is now easily payable.
