### ISSUE TITLE
[Bug]: Advanced Manual Setup for LN channel can result in crash

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2253]
### Describe the bug

Bitkit crashes if the Manual Setup flow form is not filled in and the Continue button is pressed.
(This may have persistently broken ldk, need to test more)

### Reproduce

1. Go to Advanced settings -> Lightning Connections -> Add Connection
2. At Manual Setup page, tap 'Continue'
3. App crashes
4. On restarting Bitkit the LDK node never starts correctly (wallet restore required)

### Screenshots / Recording

https://github.com/user-attachments/assets/16a55c09-859a-456a-a216-5bfa49a2a463

https://github.com/user-attachments/assets/df133def-72c0-4f85-bdc1-5d945cce034b

### Operating system

iOS / Android

### Bitkit version

1.0.5 (136)

### Log output

[crash-report.txt](https://github.com/user-attachments/files/17155798/crash-report.txt)

**Comment by pwltr** [comment]
Can confirm, the app is crashing when trying to add a peer with an invalid pubkey. I can add validation to check for correct length but that's not enough to prevent this. @Jasonvdb FYI

https://github.com/user-attachments/assets/16a55c09-859a-456a-a216-5bfa49a2a463

[crash-report.txt](https://github.com/user-attachments/files/17155798/crash-report.txt)

**Comment by pwltr** [comment]
Crashing on Android  as well:

https://github.com/user-attachments/assets/df133def-72c0-4f85-bdc1-5d945cce034b

**Comment by JeanlChristophe** [comment]
it's weird it didn't crash for me

**Comment by Jasonvdb** [comment]
Yeah length check doesn't seem like enough here. Needs proper validation.

**Comment by Jasonvdb** [comment]
This should do the trick: https://github.com/synonymdev/react-native-ldk/pull/274

I'm testing with `0000000000000000000000000000000000000000000000000000000000000000`

**Comment by catch-21** [comment]
@pwltr It's interesting you get a crash on android because I see a toast (real device)
<img src="https://github.com/user-attachments/assets/760025a2-2570-407b-8a60-cc02320fe88c" width="300">
**A fix must be tested on both platforms**

**Comment by Jasonvdb** [comment]
Still strangely stopped being able to replicate the crash since Friday but I believe this does the trick: https://github.com/synonymdev/bitkit/pull/2275

Using the actual curve to validate the public key.

**Comment by catch-21** [comment]
Unable to reproduce crash on android using 0d67faa2509b1ec083d475abc80e90802f8d7d28
- The form validation now prevents proceeding without inputting a valid node id, and something for host and port.
- If an node id is used that cannot be connected to then an appropriate toast error is displayed

-----

Tested again on Android and iOS using release 1.0.5 (137)
