### ISSUE TITLE
[Bug]: Unable to check status of tx

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2254]
### Describe the bug

I am on the homescreen and I want to check the status of my onchain tx - the moment I click on that I am prompted with this screen 

### Reproduce

1. Go to homescreen
2. Click on latest onchain tx
3. See error

### Screenshots / Recording

![photo_2024-09-27_11-37-09](https://github.com/user-attachments/assets/fc46ea8c-a111-412f-9647-bf4bca1284ea)
[bitkit_ldk_logs_1727426351930.zip](https://github.com/user-attachments/files/17161448/bitkit_ldk_logs_1727426351930.zip)

### Operating system

Android

### Bitkit version

v136

**Comment by catch-21** [comment]
@thisispav  Was it a send or receive? Do you have the txid?

**Comment by pwltr** [comment]
@coreyphillips Looks like this error is coming from the wallet not being instantiated for a couple of seconds after app start. Changing the type to`let wallet: TWallet | undefined;` gives a lot of type errors. Any ideas how we can correct this?

![image](https://github.com/user-attachments/assets/df31f1d5-5f00-4e5d-b9dd-8a123e3f7c40)

**Comment by coreyphillips** [comment]
We could add logic on-start to restrict certain views or only pass the user off to the main wallet view once `setupOnChainWallet` has completed [here](https://github.com/synonymdev/bitkit/blob/f35c52e5b4138e681ff017a8ca2db2c706eceb24/src/utils/wallet/index.ts#L1164).

**Comment by pwltr** [comment]
Related: https://github.com/synonymdev/bitkit/issues/2202

**Comment by catch-21** [comment]
Tested on [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [f0cde24](https://github.com/synonymdev/bitkit/commit/f0cde24a9f71cabb4c6f1887eeb4b070ab19c904)
Tried combinations of new transactions, transfer, boosting; restarting the app and quickly viewing each of these. No problems.
