### ISSUE TITLE
[Bug]: scan or paste a bitcoin address when sending shows me a toast notification of insufficient funds

### ISSUE THREAD

**Issue by weedcoder** [synonymdev/bitkit-react-native#2255]
### Describe the bug

i click the send button, it shows me the menu "send bitcoin"
when i scan a bitcoin address or i paste a bitcoin address in format bitcoin:bc1xxx
it displays a toast notification of insufficient funds

context : i received only 1 transaction of 30k sats, it's confirming
[bitkit_ldk_logs_1727427327007.zip](https://github.com/user-attachments/files/17161669/bitkit_ldk_logs_1727427327007.zip)

### Reproduce

i click the send button, it shows me the menu "send bitcoin"
when i scan a bitcoin address or i paste a bitcoin address in format bitcoin:bc1xxx
it displays a toast notification of insufficient funds

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/4d2306ba-901b-439d-87da-3d0171457ad1)

### Operating system

android 13

### Bitkit version

1.0.5 (136)

**Comment by JeanlChristophe** [comment]
He closed Bitkit and then it worked.

**Comment by catch-21** [comment]
Attempting to send before initial confirmation should be covered in the e2e tests.

**Comment by pwltr** [comment]
Looks like this is this old issue: https://github.com/synonymdev/bitkit/issues/1602
