### ISSUE TITLE
[Bug]: Unable to pay contact via paykit (both have LN channels opened)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2256]
### Describe the bug

tried paying a contact via LN and I got an error.
I tried closing and reopening the app, after which I clicked on the button, it was loading for about 15 sec and then I was presented with the same issue. Julien tried paying to JC and had the same result (all 3 of us have LN Channels)
Bitkit was opened during the entire time 

### Screenshots / Recording

[bitkit_ldk_logs_1727433118367.zip](https://github.com/user-attachments/files/17162888/bitkit_ldk_logs_1727433118367.zip)
![photo_2024-09-27_13-33-07](https://github.com/user-attachments/assets/4b14a929-77fc-40b0-bc5c-687c3f8e7942)

### Operating system

Android

### Bitkit version

v136

**Comment by limpbrains** [comment]
I did a few regtest and a few mainnet payments without any issues. If you still can reproduce this, please share the details

**Comment by limpbrains** [comment]
Contact slashpay profile was empty.
