### ISSUE TITLE
[Bug]: Advanced Manual Setup: Unable to establish a new LN connection with Regtest Blocktank

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2259]
### Describe the bug

I always see an error when attempting to use the advanced manual setup flow with our Regtest Blocktank.
I have tried manually entering and pasting this uri 03b9a456fb45d5ac98c02040d39aec77fa3eeb41fd22cf40b862b393bcfc43473a@35.233.47.252:9400

### Reproduce

0. Configure Bitkit to use Regtest network
1. With an onchain balance
2. Go to Advanced settings -> Lightning Connections -> Add Connection
3. Enter the Regtest Blocktank details
4. Proceed to Swipt to Transfer

### Screenshots / Recording

<img width="391" alt="Screenshot 2024-09-30 at 11 13 06" src="https://github.com/user-attachments/assets/53f9e731-63da-4aa1-b653-39aa43daedf9">

https://github.com/user-attachments/assets/d3b3c658-f35f-4e06-86fa-d52e404c49d3

### Operating system

Android 14

### Bitkit version

1.0.5 (136)

**Comment by Jasonvdb** [comment]
Not sure if regtest is setup the same as mainnet but I don't think we accept channels from random peers or at least we have a limit on the channel size of ones opened to us. Can you share logs with this and I'll confirm?

**Comment by catch-21** [comment]
@Jasonvdb 
[bitkit_ldk_logs_1727689485253.zip](https://github.com/user-attachments/files/17187706/bitkit_ldk_logs_1727689485253.zip)

**Comment by Jasonvdb** [comment]
`2024-09-30 09:44:36 UTC DEBUG (LDK): Finishing closure of channel due to Channel closed because counterparty force-closed with message: funding failed due to internal error with 0 HTLCs to fail (lightning::ln::channelmanager 3245)`

Seems like a counterparty node issue, we might have to check Blocktank LND server logs for this one. Have you tried at all with a random node that hasn't been setup with any custom rules?

**Comment by catch-21** [comment]
@Jasonvdb  Do we have other nodes on our regtest network?

**Comment by Jasonvdb** [comment]
Not that I know of. Not sure if you have polar setup but I use that with our regtest. If you open the bitcoin core terminal and use `bitcoin-cli addnode 35.233.47.252:18433 "onetry"` it will sync to our network and then any LND node you add to that polar network will be usable with Bitkit

**Comment by catch-21** [comment]
This works if I use a different Regtest wallet. For some reason the one i had been using is in a bad way.
