### ISSUE TITLE
[Bug]: Transfer to savings flow can auto-deselect connections, ignore user-selected connections and force to close all connections

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2262]
### Describe the bug

With two LN connections, proceeding to transfer from spending to saving automatically deselected all available connections but still applied the sum of all as the total. When manually enabling one back to enabled the sum of all is still applied.

I don't believe there is a valid reason for this, it shouldn't happen under any circumstance.

### Reproduce

Steps from the attached screen recording
- 0:00 to 0:24  Shows current two LN connections (one is from a regular BT order and the other is a manually set up connection). The latest manual transfer activity is also shown.
- 0:27 begins the Transfer to Savings flow
- 0:32 tap 'Advanced' button to choose connection to close, it automatically deselects and changes the order of the two listed connections
- 0:38 I navigate back but the total is still sum of both connections (115_063)
- 0:42 tap 'Advance' button again, it automatically deselects both connections again
- 0:46 I select one of them (56_565) and tap 'Continue
- 0:51 the total is still sum of both connections (115_063). I swipe to transfer.
- 1:11 Two 'Transfer from Savings' Activities appear

### Screenshots / Recording

https://github.com/user-attachments/assets/571dacf5-acc9-4f28-b214-12b5ef18c99a

### Operating system

Android 14

### Bitkit version

1.0.5 (136)

### Log output

[bitkit_ldk_logs_1727676385522.zip](https://github.com/user-attachments/files/17187917/bitkit_ldk_logs_1727676385522.zip)

**Comment by pwltr** [comment]
Having a hard time reproducing this. Any additional steps that could lead to this? I tested on iOS simulator, Android emulator and on my mainnet Android build.

**Comment by catch-21** [comment]
@pwltr Yes, I think it happens if you leave it long enough, try leaving it for 2-3 minutes. Perhaps there is a background refresh occurring that causes it. If so, it could happen shortly after arriving at this page by chance. This was on my android device:

https://github.com/user-attachments/assets/35cea4a1-1f14-42c4-b12d-584ea480e424

**Comment by catch-21** [comment]
Verified on 1.0.6 (138) by waiting on the 'Select funds to transfer' page for 3 minutes. Toggles never move by themselves and always work as intended.
