### ISSUE TITLE
[Feature]: Allow custom fees for Advanced Manual Setup of LN connection

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2266]
### Describe the problem

Using the Advanced Manual Setup to add a new LN connection, there is no way to choose the channel opening fee. It appears to use 'normal'.

### Describe the solution

Given this is an advanced feature, why not let the user decide if they want to override the suggested fee, as we do for regular onchain transactions?

If not, it might be a good idea to default to 'fast', as bitkit does for its channel openings with blocktank.

**Comment by aldertnl** [comment]
added to prototype v52

**Comment by pwltr** [comment]
Implemented in https://github.com/synonymdev/bitkit/pull/2349
