### ISSUE TITLE
Advanced Manual Setup flow for LN channel isn't available for US/Canadia

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2269]

**Comment by dzdidi** [comment]
I assume this is related to creating connection with non-blocktank nodes, right? If so it needs to be adjusted on bitkit end.

**Comment by pwltr** [comment]
Duplicate of https://github.com/synonymdev/bitkit/issues/2252

**Comment by catch-21** [comment]
already tested in #2252
