### ISSUE TITLE
[Bug]: No longer able to add LN node peer

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2272]
### Describe the bug

It used to be possible to QR Scan or paste a LN node connection string in the format `nodeId@ip:port` into Bitkit to ass a new peer. Now this triggers the Manual Setup flow for a Lightning connection.

I don't think there is an other way to add a lightning peer. If there isn't, perhaps it should be added in a menu.

### Reproduce

1. Go to https://lnbig.com
2. Scan one of the QR codes
3. Observe Manual Setup flow
4. If you want to simply add a peer, there is no option.

### Operating system

Android 14

### Bitkit version

1.0.5 (136)

**Comment by pwltr** [comment]
@catch-21 What's the use case for this? I assume if you want to add a LN peer it's to open a channel to them?

**Comment by catch-21** [comment]
@pwltr I don't know, but we had it before so I wanted to raise the point. I am happy to see this one closed if it is/was a  useless feature.

Edit:  It was useful for me when my peer was not backed up and restored, which was due to a bug that existed at the time. Something like this could happen again.

**Comment by catch-21** [comment]
@Jasonvdb?

**Comment by pwltr** [comment]
For simply adding a peer you can use the debug feature by navigating to DevSettings -> LDK.

**Comment by catch-21** [comment]
I missed that. Ok, we can close this.
