### ISSUE TITLE
[Bug]: Manual Setup channel doesn't produce receive invoice

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2287]
### Describe the bug

After manually setting up a channel with LND3 I have a spending balance and the connection has usable status but when I tap 'Receive' no lightning invoice is created. I only see onchain address. It is still possible to pay a lightning invoice.

[bitkit_ldk_logs_1728135915812.zip](https://github.com/user-attachments/files/17266446/bitkit_ldk_logs_1728135915812.zip)

### Reproduce

1. Go to Advanced -> Lightning Connection -> Manual Setup
2. Establish a connection with LND3 `03816141f1dce7782ec32b66a300783b1d436b19777e7c686ed00115bd4b88ff4b@34.65.191.64:9735`
3. When the channel is successfully opened and spending balance is shown, tap 'Receive' button on home page
4. Observe no lightning invoice is generated. Only the onchain address is shown. The toggle for CJIT flow is displayed and the wallet behaves as if there is no existing lightning connection.

### Screenshots / Recording

https://github.com/user-attachments/assets/5b2a15ee-fa09-49d5-98ac-44b88078f1ae

### Operating system

Android 14

### Bitkit version

0d67faa2509b1ec083d475abc80e90802f8d7d28

**Comment by Jasonvdb** [comment]
Not sure what the order of events here was exactly, in the logs the channel is Usable: no mostly until right at the end. Maybe funding tx wasn't confirmed yet? Do you remember how long you waited from opening to trying to create an invoice?

2nd theory is we have some check on receiving balance before showing invoices. And locally funded channels have zero receiving balance.

**Comment by catch-21** [comment]
@Jasonvdb I am able to pay invoices but unable to produce one, even after hundreds of confirmations. Your 2nd theory is more likely and actually the correct behaviour, although I had forgotten I had no inbound so perhaps we should add a message when tapping Receive to indicate there is not enough inbound to produce LN invoice.
[bitkit_ldk_logs_1728279997215.zip](https://github.com/user-attachments/files/17273697/bitkit_ldk_logs_1728279997215.zip)

**Comment by pwltr** [comment]
There is a check for whether the user has inbound before generating a LN invoice [here](https://github.com/synonymdev/bitkit/blob/master/src/screens/Wallets/Receive/ReceiveQR.tsx#L121), so this is expected.
