### ISSUE TITLE
[Bug]: Manual Setup: Connection doesn't open after boost

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2291]
### Describe the bug

After using the Manual Setup flow to create a new lightning connection but before the channel opening transaction has confirmed, if the Transfer activity is boosted then once the transaction confirms the activity changes to 'Sent', the Transfer suggestion card remains, and the lightning connection doesn't proceed from 'Opening connection' status. Effectively, the funds were sent onchain but no channel was opened.

[bitkit_ldk_logs_1728213363388.zip](https://github.com/user-attachments/files/17269058/bitkit_ldk_logs_1728213363388.zip)

### Reproduce

1. Go to Advanced -> Lightning Connection -> Manual Setup
2. Establish a connection with a LN node (I used https://1ml.com/node/0296b2db342fcf87ea94d981757fdf4d3e545bd5cef4919f58b5d38dfdd73bf5c9)
3. Once the transfer is processing, boost the Transfer activity (RBF)
4. Wait for the new transaction to confirm
5. Observe the Transfer activity has changed to 'Sent'
6. Observe the Transfer suggestion card is still displayed
7. Observe the lightning connection is stuck with 'Opening connection' status

### Screenshots / Recording

[boosted_manual_transfer.webm](https://github.com/user-attachments/assets/2cd621b6-5a79-48e9-b825-0ae832cd3b9e)

### Operating system

Android 14

### Bitkit version

0d67faa2509b1ec083d475abc80e90802f8d7d28

**Comment by pwltr** [comment]
Split into separate issues: https://github.com/synonymdev/bitkit/issues/2295

**Comment by catch-21** [comment]
@pwltr Ok, so this issue is tracking now just the connection not opening bug?

**Comment by pwltr** [comment]
> @pwltr Ok, so this issue is tracking now just the connection not opening bug?

Yes sorry forgot to update title/description on this one.

**Comment by catch-21** [comment]
Verified in b3f9f30dd56e4a1666492c3219f352d2bcd77086
Connection now opens after a manual setup transfer activity is boosted (CPFP).
