### ISSUE TITLE
[Bug]: Boosted Transfer activity changes to 'Sent' once confirmed

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2295]
### Describe the bug

After transferring funds to spending, if the Transfer activity is boosted the activity changes to 'Sent'.

### Reproduce

1. Make a transfer to spending
2. Once the transfer is processing, boost the Transfer activity (CPFP)
3. Wait for the new transaction to confirm
4. Observe the Transfer activity has changed to 'Sent'

### Operating system

Android / iOS

### Bitkit version

0d67faa2509b1ec083d475abc80e90802f8d7d28

**Comment by catch-21** [comment]
Verified in 0fbc9c371d86e642fbf4276f4473f4e5203963ea on staging
