### ISSUE TITLE
[Bug]: Unexpected Error (crash) as savings balance went to 0

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2297]
### Describe the bug

A few minutes after initiating a Manual Setup transfer and boosting the transaction (CPFP), I was sitting on the home page waiting for the transaction to confirm and for my new spending balance to be available when my savings balance went from positive value 384k to 0 (see screenshot 1). I then tapped the savings balance and the 'Unexpected Error' page displayed (see screenshot 2) with the following report:

```
Error: Text strings must be rendered within a <Text> component.
Component Stack:
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in StyledNativeComponent
    in Unknown
    in ActivitySavings
    in StaticContainer
    in EnsureSingleNavigator
    in SceneView
    in RCTView
    in Unknown
    in DebugContainer
    in MaybeNestedStack
    in RCTView
    in Unknown
    in RNSScreen
    in Unknown
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in InnerScreen
    in Screen
    in SceneView
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in RNSScreenStack
    in ScreenStack
    in NativeStackViewInner
    in RCTView
    in Unknown
    in SafeAreaProviderCompat
    in NativeStackView
    in PreventRemoveProvider
    in NavigationContent
    in Unknown
    in NativeStackNavigator
    in WalletsStack
    in StaticContainer
    in EnsureSingleNavigator
    in SceneView
    in RCTView
    in Unknown
    in DebugContainer
    in MaybeNestedStack
    in RCTView
    in Unknown
    in RNSScreen
    in Unknown
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in InnerScreen
    in Screen
    in SceneView
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in RNSScreenStack
    in ScreenStack
    in NativeStackViewInner
    in RCTView
    in Unknown
    in SafeAreaProviderCompat
    in NativeStackView
    in PreventRemoveProvider
    in NavigationContent
    in Unknown
    in NativeStackNavigator
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner
    in StyledNativeComponent
    in Unknown
    in RootNavigator
    in RCTView
    in Unknown
    in InactivityTracker
    in AppOnboarded
    in SlashtagsProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in StyledNativeComponent
    in Unknown
    in ThemeProvider
    in App
    in PersistGate
    in Provider
    in ErrorBoundary
    in Root
    in RNGestureHandlerRootView
    in GestureHandlerRootView
    in gestureHandlerRootHOC(Root)
    in RCTView
    in Unknown
    in AppContainer
Stack: Error: Text strings must be rendered within a <Text> component.
    at completeWork (address at index.android.bundle:1:454493)
    at completeUnitOfWork (address at index.android.bundle:1:471571)
    at performUnitOfWork (address at index.android.bundle:1:470872)
    at workLoopSync (address at index.android.bundle:1:469967)
    at renderRootSync (address at index.android.bundle:1:469799)
    at flushSyncWorkAcrossRoots_impl (address at index.android.bundle:1:423743)
    at batchedUpdatesImpl (address at index.android.bundle:1:482345)
    at batchedUpdates$1 (address at index.android.bundle:1:416457)
    at _receiveRootNodeIDEvent (address at index.android.bundle:1:416745)
    at receiveTouches (address at index.android.bundle:1:479907)
    at apply (native)
    at __callFunction (address at index.android.bundle:1:144401)
    at anonymous (address at index.android.bundle:1:142840)
    at __guard (address at index.android.bundle:1:143782)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:142798)
Platform: android 14
Version: 1.0.5 (136)
LDK version: ldk-v0.0.123-36-g1027b935fb92b924 c_bindings-v0.0.123.1)
LDK node ID: 03c537950c6e1b62c0ce7923f4933d89999394edcac0f4aca877cd5cfcaec996c9
```

### Reproduce

I'm unsure whether the manual setup and boost are relevant here but this is what I did

1. Scan lightning node https://1ml.com/node/0296b2db342fcf87ea94d981757fdf4d3e545bd5cef4919f58b5d38dfdd73bf5c9 and initiate a new channel with just spending balance, no inbound liquidity.
2. Once Transfer activity is visible, tap it and boost (CPFP)
3. Once activity is boosted, leave the wallet open on home page to wait for confirmation
4. After 5-10 minutes the savings balance went from 384k to 0
5. Tapping the savings balance showed Unexpected Error (crash) page

### Screenshots / Recording

Screenshot 1
<img src="https://github.com/user-attachments/assets/071b7f93-aa61-4b3c-be3f-2d5d32988325" width="280">

Screenshot 2
<img src="https://github.com/user-attachments/assets/238aae75-d350-4194-8d90-e6cb81be4684" width="280">

### Operating system

Android 14

### Bitkit version

b3f9f30dd56e4a1666492c3219f352d2bcd77086

### Log output

[bitkit_ldk_logs_1728449292551.zip](https://github.com/user-attachments/files/17302188/bitkit_ldk_logs_1728449292551.zip)

**Comment by catch-21** [comment]
I was unable to reproduce by letting a manual setup transfer confirm whilst watching the main wallet page.
I tried twice, one without boost and one with. Both times behaviour was as desired.

**Comment by pwltr** [comment]
No idea why the balance would be wrong but the uncaught error is fixed with https://github.com/synonymdev/bitkit/pull/2307

**Comment by catch-21** [comment]
@pwltr  We've seen the 0 balance a few times recently.  @SeverinAlexB reported it happening after initial funding of new wallet via CJIT.

Sev and I also witnessed something that could be related: the double-counting of savings balance after a transfer to spending.  It feels to me like sometimes an address/output is either not being included in the balance or is being double-counted. Could this could be the result of simultaneous refreshes occurring, potential race condition?

tracked by #2301 

A manual refresh always corrects the balances.

**Comment by catch-21** [comment]
This issue is for the uncaught error crash, not zero balance.

**Comment by pwltr** [comment]
JS uncaught error was fixed [here](https://github.com/synonymdev/bitkit/pull/2307)

**Comment by catch-21** [comment]
Tested on v1.0.6 (138)
Not seen this in our testing session today. Everyone will regularly perform the action of opening Savings activity so no further testing needed. Closing.
