### ISSUE TITLE
[Bug]: Calculate the number of invalid PIN attempts during the Send flow

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#2308]
### Describe the bug

It is currently possible to have unlimited attempts to enter the PIN during the Send flow. 
This should be limited to 10 attempts, as it is in the Start flow.

### Reproduce

1. Setup PIN
2. Enable PIN for Send
3. Try to enter wrong PIN 10 times 

### Operating system

iOS, Android

**Comment by limpbrains** [comment]
fixed in #2311

**Comment by catch-21** [comment]
Verified in v1.0.8
Wipes data after 8 unsuccessful pin attempts on send
