### ISSUE TITLE
Quick Pay

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2316]
Please integrate the Quick pay feature

Figma: https://www.figma.com/design/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?node-id=26618-123731&t=4hOCLdZm39Z3FrKz-4

**Comment by catch-21** [comment]
We already have https://github.com/synonymdev/bitkit/issues/2058

**Comment by pwltr** [comment]
Closed in favor of https://github.com/synonymdev/bitkit/issues/2058
