### ISSUE TITLE
[Feature]: v52 MINOR Changes

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2319]
### Describe the problem

- These changes are ready to be implemented in frontend and backend.
- Please check the interactive prototype for user experience and interactions
- Please check the static frames in Figma for design nuances and edge cases
- This version excludes ongoing experimental design work.	
New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=26999%3A127282&node-id=26999-132385&node-type=canvas&viewport=97%2C-174%2C0.06&t=Mezz22lLvIviLzJ6-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=26999%3A132385&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=26999%3A127282&node-id=26999-132389&node-type=canvas&viewport=97%2C-174%2C0.06&t=Mezz22lLvIviLzJ6-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=26999%3A132389&show-proto-sidebar=1&hide-ui=1

### Describe the solution

**MINOR CHANGES:**

- [x] Receive > Switch apps edge case: Added toast warning (triggered when switching between apps while trying to receive).
- [x] Receive > NFC Card Campaigns: Extended UI views for Bitkit NFC Card campaigns to cover edge cases and errors.
- [x] Receive > CJIT > Geoblock: Introduced a geoblock view in the CJIT receive flow with a link for manual setup.
- [x] ~~Send > Contact/Lightning > Geoblock: Added a geoblock view in the Send flow for transaction failures due to geoblock policies.~~
- [x] Advanced Lightning Onboarding > Manual Setup > Confirm: Enabled custom fee setting for manual Lightning setup (accessible via pencil icon on network fee overview).
- [x] Profile > Edit: Added a button to delete profile information.
- [x] :Changed payment animation, reused part of the LN sync animation. (Quickpay is accessible in the prototype by using the Active user link, by tapping the big central [ ] scan QR button in the footer, right from the wallet overview)

**Comment by pwltr** [comment]
":Changed payment animation, reused part of the LN sync animation. (Quickpay is accessible in the prototype by using the Active user link, by tapping the big central [ ] scan QR button in the footer, right from the wallet overview)" -> Part of https://github.com/synonymdev/bitkit/issues/2058

**Comment by limpbrains** [comment]
"Send > Contact/Lightning > Geoblock"
I don't think we need to show geoblock here. We only check during LN channel openning, right @pwltr ?

**Comment by pwltr** [comment]
> "Send > Contact/Lightning > Geoblock"
> I don't think we need to show geoblock here. We only check during LN channel openning, right @pwltr ?

Agree

**Comment by catch-21** [comment]
Tested on [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [3b9a833](https://github.com/synonymdev/bitkit/commit/3b9a8334d29899ace50749a3233f2b09733b2d13)
LGTM 👍
