### ISSUE TITLE
[Feature]: (51) MINOR CHANGES

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2322]
### Describe the problem

New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=26618%3A121070&node-id=26618-121071&node-type=FRAME&viewport=252%2C96%2C0.13&t=3a2PIK7WZzp5LAls-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=26618%3A126150&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=26618%3A121070&node-id=26618-126158&node-type=FRAME&viewport=252%2C96%2C0.13&t=VzG6WKLC255EAc0M-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=26618%3A126154&show-proto-sidebar=1&hide-ui=1

### Describe the solution

- [x] Stealth Mode: Removed from the prototype, due to product decision (Calculator UI).
- [x] Layout: Optimized layout for better compatibility across screen sizes and languages (Implemented Philipp’s suggestion).
- [x] Transfer > Confirm > Learn More: Updated copy (Implemented John’s suggestion).
- [x] CJIT Receive > Fee Confirmation > Learn More: Updated copy (Implemented John’s suggestion).
- [x] Send Flow: Fees are now displayed in ₿ when Bitcoin is selected as the display denomination.
- [x] Send Flow > MAX button: Removed MAX button from the prototype due to screen size constraints.
- [x] Send Flow > Available: Tapping ‘Available’ balance element now serves MAX button function. Added toast for informing user about the maximum spendable amount is a bit lower due to a required reserve balance.

### Additional context

See: https://synonymworkspace.slack.com/archives/C01H106JRQB/p1726065889623369

**Comment by catch-21** [comment]
Tested in [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [3b9a833](https://github.com/synonymdev/bitkit/commit/3b9a8334d29899ace50749a3233f2b09733b2d13)
LGTM 👍
