### ISSUE TITLE
[Bug]: Bitkit crashes if i tap on Savings card on home page

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#2323]
### Describe the bug

Bitkit crashes if i tap on Savings card on home page with "Unexpected Error ... Text strings must be rendered within a <Text> component"

### Reproduce

1. Go to home page
2. Click on Savings card below the master balance
3. Crash window pops up

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/963fbbb0-f7b9-45cf-b495-b0ffcb357396)

### Operating system

iOS

### Bitkit version

1.0.5 137

**Comment by catch-21** [comment]
Marking as duplicate of https://github.com/synonymdev/bitkit/issues/2297
