### ISSUE TITLE
[Bug]: No LN invoice found in order to pay contact in Bitkit (after opening a CJIT channel)

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#2325]
### Describe the bug

both myself and Ivan opened CJIT channels (channels are open and usable).
For some reason I am unable to pay him via slashpay 
this is his ID - g3j6o95a7ar165hcfxx568fk8rfaps67ycgkgj1wgwaqewkn89co/slashpay.json (only has onchain address)
no LN invoices on slashpages on file 

### Operating system

Android (Graphene Pixel 6S)

### Bitkit version

v138

**Comment by catch-21** [comment]
This also affected me after creating my only LN channe lvia CJIT. I have onchain balance and have had regular lightning channels in the past.

**Comment by catch-21** [comment]
Verified on [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [3b9a833](https://github.com/synonymdev/bitkit/commit/3b9a8334d29899ace50749a3233f2b09733b2d13)
On iPhone, with no spending balance, already have contact spending enabled, unable to receive via contact, CJIT to receive 25k spending balance, immediately able to receive via contact.
