### ISSUE TITLE
[Bug]: Do not show green notification during LNURL withdraw

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#2326]
### Describe the bug

When trying to withdraw from LNmarkets you have green notification which is confusing. 
We need to change it to yellow and change the text, mention that payment is still in process and we are waiting for it.

### Reproduce

1. Go to lnmarkets withdraw
2. withdraw using LNURL-withdraw
3. See Success notification but not the confetty 

### Operating system

iOS, Android

**Comment by catch-21** [comment]
This is the current notification
![Screenshot_20241104_103401](https://github.com/user-attachments/assets/27a55af6-e826-42c0-bf21-ff845297b285)

**Comment by catch-21** [comment]
Verified in [release-v1.0.7](https://github.com/synonymdev/bitkit/tree/release-v1.0.7) [f0cde24](https://github.com/synonymdev/bitkit/commit/f0cde24a9f71cabb4c6f1887eeb4b070ab19c904)
