### ISSUE TITLE
[Bug]: Pay to contact can take a long time to show payment flow

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2377]
### Describe the bug

Most times when I tap the pay to contact button, the button turns into a spinner for longer than usual (10-50seconds).
This happens for contacts with both onchain and lightning, and for those with just onchain capability.

### Reproduce

1. With a contact that has payments enabled
2. Tap the button to pay the contact (coins icon button in their contact page)
3. Wait a long time, up to nearly 1 minute for the payment flow to display

### Screenshots / Recording

https://github.com/user-attachments/assets/a473ed32-20b4-4e7b-a00b-cc307101c5bf

### Operating system

Android 14

### Bitkit version

release-v1.0.7 3b9a833

**Comment by catch-21** [comment]
<img src="https://github.com/user-attachments/assets/948c0c15-0763-433a-8209-4c09dc16ff80" width="300">
<img src="https://github.com/user-attachments/assets/320dc41c-40c2-4bea-915a-59b2c1013945" width="300">
<img src="https://github.com/user-attachments/assets/dc12d6e2-8617-462c-b080-f229c976d815" width="300">
<img src="https://github.com/user-attachments/assets/620e33c4-ae00-4552-8135-d6e517765713" width="300">

[bitkit_ldk_logs_1732880263542.zip](https://github.com/user-attachments/files/17958591/bitkit_ldk_logs_1732880263542.zip)

**Comment by limpbrains** [comment]
The problem is that the wallet LDK startup is slow, probably because it is old and has a lot of transactions. We should probably show the same Lightning starting animation as we do for the send flow. After LDK is started, everything works fine.

https://github.com/user-attachments/assets/447f632c-3bce-42db-b007-d0dbf18f3381

**Comment by catch-21** [comment]
This is surprising to me because I am able to pay an invoice after starting the wallet from cold without delay, but the slashpay option still takes a long time to get to the payment flow.

https://github.com/user-attachments/assets/8c7e0909-689c-4a0a-8b9b-f530465b45e3
