### ISSUE TITLE
[Feature]: Only use confirmed inputs when transfer to spending 

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2397]
### Describe the problem

When attempting to transfer to spending I am blocked by a small unconfirmed UTxO even though I have three other confirmed unspent outputs that could be used instead. 

![Screenshot_20241211_131832](https://github.com/user-attachments/assets/c23a2ce9-752c-410d-857c-d7af16917905)

https://github.com/user-attachments/assets/0ad95eab-5cd4-4503-a840-9500aaef5d78

The fee market has spiked and I am unable to boost the transaction, so even though I have the funds available in confirmed unspent outputs I must wait potentially hours before I can transfer to spending balance.

### Describe the solution

The transfer flow should ignore the unconfirmed UTxOs and proceed without them if possible.
Also consider letting the user decide which inputs to try when in manual coin selection mode.

**Comment by pwltr** [comment]
There is no requirement for these order payment transactions to use confirmed UTXOs. Are you sure you've not reached the node capacity limit as the error suggests?

**Comment by catch-21** [comment]
Ah, probably. I cannot see my old 600 sat spending channel anymore but it may well have had a very large receiving capacity.
