### ISSUE TITLE
[Feature]: upgrade to `@bitcoinerlab/secp256k1@1.2.0`

### ISSUE THREAD

**Issue by landabaso** [synonymdev/bitkit-react-native#2405]
### Describe the problem

`@bitcoinerlab/secp256k1` internally uses the audited Noble libraries. The author of Noble has recommended upgrading to the latest version for enhanced security.

For more details, see the related discussion and PR: [[bitcoinerlab/secp256k1#10](https://github.com/bitcoinerlab/secp256k1/pull/10)](https://github.com/bitcoinerlab/secp256k1/pull/10)

**Comment by pwltr** [comment]
@landabaso Thanks for letting us know, PR to upgrade [here](https://github.com/synonymdev/bitkit/pull/2407)
