### ISSUE TITLE
Onboarding: add terms of service screen

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#250]
**Describe the bug**
`Terms of service` information are missing.

**To Reproduce**
1. Open Bitkit app for the first time (or wipe your wallet)
2. Swipe right to all the onboarding screens.
3. Try to click on `terms of service` - nothing happens

**Expected behavior**
Should show the `terms of service`.

**Screenshots**

https://user-images.githubusercontent.com/5798170/184369577-9c7734e3-0f57-4f54-9c84-d94b48c2723c.mp4

**Smartphone (please complete the following information):**
 - OS: Android - Pixel 2

**Comment by limpbrains** [comment]
It works for me on both Android and iOS

[tos.webm](https://user-images.githubusercontent.com/155891/184835966-ebb70655-3429-439b-a5c1-cdd6bf14df2b.webm)
