### ISSUE TITLE
Error: Could not invoke Ldk.updateFees

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#251]
**Describe the bug**
Error shows up after loading the app: `Could not invoke Ldk.updateFees`

**To Reproduce**
1. Open the app
2. Wait a little bit and the error will show up automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/184379605-af6048b9-86e9-436e-9cb2-9d859435e55a.png)

https://user-images.githubusercontent.com/5798170/184380095-4dd18d8a-945b-41b2-94a4-d75bc63f8754.mp4

**Smartphone (please complete the following information):**
 - OS: Android Emulator - Pixel 2

**Comment by Jasonvdb** [comment]
Hopefully new LDK version solves this. If not unfortunately we'll be stuck testing lightning on real devices.

**Comment by MiguelMedeiros** [comment]
I cleaned my android emulator data and rebuilt it with the latest master branch version and it worked without errors. So I'm going to close this PR for now.

**Comment by Jasonvdb** [comment]
Not sure why LDK is flakey on emulators but I've updated it [here](https://github.com/synonymdev/react-native-ldk/pull/41) so it'll be in Bitkit soon and hopefully that fixes it.
