### ISSUE TITLE
Non circular app icons

### ISSUE THREAD

**Issue by Nuhvi** [synonymdev/bitkit-react-native#252]
**Describe the bug**
The Android app icon looks weird with non-circular app logos!

**To Reproduce**
Install the app on Samsung??

**Screenshots**
![Screenshot_20220815-124827_One UI Home (1)](https://user-images.githubusercontent.com/40009100/184614943-e450d228-ea88-4750-b0dc-ce7d647ed47f.jpg)

**Smartphone (please complete the following information):**
 - OS: Android (Samsung)

**Comment by Jasonvdb** [comment]
Used an online tool to make these app icons quickly. Aldert gave me the proper ones I need to use though. Just very time consuming making [all these sizes](https://github.com/synonymdev/bitkit/tree/master/android/app/src/main/res) but will have to before public testing.

**Comment by BitcoinErrorLog** [comment]
I had suggested to Aldert to remove the circle in the past, since it will be hard to manage. Is that we he passed to you Jay?

**Comment by Jasonvdb** [comment]
This is the latest [figma for icons](https://www.figma.com/file/NEZo9dUyBC4822RIdxC1W0/Icon-Mobile-Wallet?node-id=0%3A121) I'm aware of.

**Comment by BitcoinErrorLog** [comment]
Aldert will provide a new set this week, without circles

**Comment by Jasonvdb** [comment]
Updated in #260 but on a Pixel that icon is cut off. Maybe we need to make it smaller for Android.
![Simulator Screen Shot - iPhone 12 Pro - 2022-08-18 at 10 28 30](https://user-images.githubusercontent.com/5300488/185358268-bc0d5efc-fce0-45ac-954c-b17ecda8cdc8.png)


![Screenshot_20220818_111049](https://user-images.githubusercontent.com/5300488/185358237-eb49a10d-e998-4e75-8517-27812b7c6ebb.png)

**Comment by BitcoinErrorLog** [comment]
Something seems off here, why would android crop the icon so much to make a circle?

**Comment by Jasonvdb** [comment]
Yeah I don't know why the Pixel is doing this (possibly other devices as well). You can see the [file changes here](https://github.com/synonymdev/bitkit/pull/260/files) are all fine but this OS is obviously cropping more than we expect.

**Comment by Jasonvdb** [comment]
Fixed in #260 
![Screenshot_20220818_122333](https://user-images.githubusercontent.com/5300488/185450865-b0215c7a-edb0-4d73-a34c-c601a6e3fa3f.png)
