### ISSUE TITLE
App Icons: Non-standard shapes

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#264]
**Describe the bug**
Some flavors of Android will allow non-standard app icon shapes

**Expected behavior**
BitKit icon should respect the custom shape set by the OS

**Screenshots**
![Screenshot_20220819_102938_com huawei android launcher](https://user-images.githubusercontent.com/8538369/185583294-012e8f68-d624-4596-8de7-0748e2bee33d.jpg)

In the screenshot the shape is set to something like "rounded"
- correct: Zap, Muun, Blixt, Blue
- incorrect: Samourai, bitrefill, Breez, BitKit

**Smartphone (please complete the following information):**
 - OS: EMUI 9 (Android 9 based)

**Comment by MiguelMedeiros** [comment]
Fixed here: https://github.com/synonymdev/bitkit/pull/260

**Comment by Jasonvdb** [comment]
I don't think this is fixed. @pwltr can you confirm the latest test app fixed this on your phone?

**Comment by pwltr** [comment]
No it still looks the same.

**Comment by JeanlChristophe** [comment]
Can we close the ticket?
It's fixed on my side

**Comment by pwltr** [comment]
No, it's still an issue on my testing phone.
