### ISSUE TITLE
Lightning onboarding: Crashed trying to set up lightning

### ISSUE THREAD

**Issue by instabot42** [synonymdev/bitkit-react-native#265]
**Describe the bug**
The "Spending and saving" page crashes on iOS and is non-functional. Need to kill the app to get out of it.
I submitted 2 crash reports following this sequence

**To Reproduce**
Tapped the 'Pay Instantly' suggestion, then 'Quick Setup' on the Instant Payments into page.
Arrive at crashed page.

**Expected behavior**
to not crash and let me slide the slider around :-)

**Screenshots**
na

**Smartphone (please complete the following information):**
 - iOS 15.6

**Additional context**
none

**Comment by limpbrains** [comment]
Can't reproduce this issue. Works for me with development or production build.
I think it was related to swipe-to-go-back issue. Please, test again on latest build

**Comment by instabot42** [comment]
Re-tested and it is fine now (no crash anyway)
Resolved
