### ISSUE TITLE
Sent some on chain bitcoin to myself. Activity log stuck on "Sending..."

### ISSUE THREAD

**Issue by rbndg** [synonymdev/bitkit-react-native#269]
**Describe the bug**
Create a new receive address and send some bitcoin to yourself. After the transaction being confirmed, the activity log still shows "Sending...", next to the transaction.

Clicking Boost transactions shows, "Cannot read property 'message' of undefined"

**To Reproduce**
1. Create a receive address
2. Send some bitcoin to the address generated in step 1
3. Mine some blocks.
4. Transaction is stuck in "Sending..."

**Expected behavior**
Should we prevent self sends in general?

**Screenshots**

![image](https://user-images.githubusercontent.com/5121169/185596701-fbee9a8f-6340-4627-b136-2745612fcace.png)
![image](https://user-images.githubusercontent.com/5121169/185596785-92b92ae5-32a5-43d1-93d2-eeebacebfb17.png)

**Smartphone (please complete the following information):**
 - iOS

**Comment by aldertnl** [comment]
No I don't think we should not prevent self-sends, as some people will try out the app with their own funds, sending and receiving from and to themselves. So I guess this bug needs fixing.

**Comment by JWBurgers** [comment]
In addition, people will want to consolidate their UTXOs from time to time.

**Comment by pwltr** [comment]
This doesn't seem to be an issue anymore, but much room to improve UX if we do want to make self sends more of a standard feature (e.g. don't show receive tx modal, transaction amounts, separate icon in activity...)
