### ISSUE TITLE
Keyboard lagging when entering payment amount

### ISSUE THREAD

**Issue by instabot42** [synonymdev/bitkit-react-native#271]
**Describe the bug**
When trying to enter the amount to pay (Bitcoin payment, in sats), there is a delay from typing before the number updates.

**To Reproduce**
Press Send from the home screen
Normal
Try and type an amount.
Notice how long it takes for numbers to update

**Expected behavior**
instant

**Screenshots**
na

**Smartphone (please complete the following information):**
 - iOS

**Comment by limpbrains** [comment]
fixed in #283
