### ISSUE TITLE
Camera isn't always disabled when done

### ISSUE THREAD

**Issue by instabot42** [synonymdev/bitkit-react-native#273]
**Describe the bug**
While using the app I noticed that the iOS 'Camera is on' indicator was enabled. The app was not actively using the camera at the time. I had used it earlier, but did not notice when it went wrong.

**To Reproduce**
Used the camera at some point. Camera stayed on.

**Expected behavior**
Camera should be off when not in use.

**Screenshots**
na

**Smartphone (please complete the following information):**
 - iOS

**Comment by limpbrains** [comment]
Tried to reproduce this, but looks like we are fixed it during bottom-modal refactoring
