### ISSUE TITLE
Toggling Bitcoin Network Requires App Restart

### ISSUE THREAD

**Issue by coreyphillips** [synonymdev/bitkit-react-native#288]
**Describe the bug**
When toggling networks from "Settings->Advanced->Dev Settings->Bitcoin Network Selection" the app requires a full restart for the change to take effect.

**To Reproduce**
1. Navigate to Settings->Advanced->Dev Settings->Bitcoin Network Selection.
2. Toggle to a new Bitcoin network.
3. Attempt to retrieve an address for the new network.
4. The address is either empty or returns the old network's address.

**Expected behavior**
The address for the new network appears.

**Smartphone**
 - OS: iOS & Android

**Comment by JWBurgers** [comment]
I was not able to reproduce this issue in Android.

**Comment by coreyphillips** [comment]
This was resolved as of #362.

Closing now.
