### ISSUE TITLE
Allow for detaching inactive screens (iOS)

### ISSUE THREAD

**Issue by Jasonvdb** [synonymdev/bitkit-react-native#293]
Temp crash/hanging fix [here](https://github.com/synonymdev/bitkit/pull/291) but once issue is properly fixed in [@react-navigation/native-stack](https://github.com/react-navigation/react-navigation/issues/9015#issuecomment-828700138) we should remove `detachInactiveScreens={false}`

**Comment by pwltr** [comment]
Fixed in https://github.com/synonymdev/bitkit/pull/1391
