### ISSUE TITLE
Settings: add `Leave a review` screen

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#306]
**Describe the bug**
Add `Leave a review` screen.

**To Reproduce**
1. Go `Settings` > `About Bitkit` > `Leave Review`

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/187768432-68e91193-fb80-4a19-a7f7-b5a2184ccda0.png)

**Comment by BitcoinErrorLog** [comment]
I think the Leave Review button would just take the user to the OS's App Store review for our and we probably do not need anything interstitial, right?

**Comment by aldertnl** [comment]
Correct
