### ISSUE TITLE
Settings: share message and link

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#307]
**Describe the bug**
Change share message and link

**To Reproduce**
1. Go Settings > About Bitkit > Share Bitkit with a friend.

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/187771727-9d0913b0-85c6-47ba-bcb5-f1dd4c6ff96d.png)

**Comment by aldertnl** [comment]
For now: 'Download Bitkit, Your Ultimate Bitcoin Toolkit. Handing you the keys to reshape your digital life.'
