### ISSUE TITLE
Image covers controls when sending a transaction

### ISSUE THREAD

**Issue by instabot42** [synonymdev/bitkit-react-native#315]
**Describe the bug**
When sending a transaction, the stack of coins image ends up covering the Notes field, making the screen look confused.

**To Reproduce**
1. Send a payment
2. Ask to specify the amount and notes.
3. Add an amount
4. Tap in the Note field
5. The keyboard will open and cause hte image to slide up

**Expected behavior**
Maybe the keyboard should cover the image. It shouldn't end up on top of the notes field though :-)

**Screenshots**

![image](https://user-images.githubusercontent.com/35345644/188142827-5b5366eb-8bd5-4e94-b5e5-d014ede8ff9a.png)

**Smartphone (please complete the following information):**
 - OS: iOS

**Comment by limpbrains** [comment]
fixed in #371
