### ISSUE TITLE
Wallet: Missing the activity log after restore wallet.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#330]
**Describe the bug**
Missing the activity log after restore wallet.

**To Reproduce**
1. Go to `settings` > `advanced` > `dev settings` > `wipe wallet data`
2. Go through the start screens and click on the `restore wallet` button.
3. Paste your seed and restore wallet
4. You balance will show up after refreshing the wallet, and the activity log is empty.

**Expected behavior**
The activity log should show up with your recent transactions.

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/188762469-06254535-fe38-4659-a565-0cfc9cc160f2.png)

**Smartphone (please complete the following information):**
 - OS: [Android]

**Comment by pwltr** [comment]
I've not been able to replicate this yet. Maybe it's solved or an edge case? @MiguelMedeiros Can you try again and see if it's fixed?

**Comment by JWBurgers** [comment]
After extensive yesterday, this was not an issue with Android restores. We had too many issues restoring with IOS to see whether there was any specific issue with activities.

**Comment by MiguelMedeiros** [comment]
I could not replicate this issue anymore. Will close this issue.
