### ISSUE TITLE
Send/Receive: Remove coins graphic, tags and buttons when editing note.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#335]
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/188897139-befdd2a6-1dee-48e4-86f5-1e9c27627c43.png)

**Comment by pwltr** [comment]
@limpbrains Are you already on this? I didn't see you were assigned and started working on a fix.

**Comment by limpbrains** [comment]
@pwltr Yeah, I'm on this

**Comment by limpbrains** [comment]
fixed in #371
