### ISSUE TITLE
UI: Add retry button to the connectivity issue warning.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#341]
**Describe the bug**
Add retry button to the connectivity issue warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/188911229-a411752c-dea4-46b8-9d32-0a32aa298857.png)

**Comment by aldertnl** [comment]
After a short discussion with Philipp, we decided this action is redundant, the app can automatically try to reconnect (no action from user required)
