### ISSUE TITLE
Contacts: review contact list

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#350]
**Describe the bug**
- [ ] Bug: contact keys without contact info
- [ ] Bug: ‘undefined’‘ 
- [x] Check size of [+] button (should be same height as search bar)

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/189012170-fb601d5e-b105-455e-b016-f20f6d0fbfbd.png)

**Comment by limpbrains** [comment]
Fist two was discussed in call, will be fixed later
