### ISSUE TITLE
Contacts: click on coins icon

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#351]
**Describe the bug**
Bug: empty alert when tapping the coins icon to send some funds (probably not implemented yet)

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/189012349-dd3bcaac-ea63-4bbc-aaa5-1d19b078bdb9.png)

**Comment by limpbrains** [comment]
Added in #367
