### ISSUE TITLE
Improve Electrum Connection toasts

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#363]
**Describe the bug**
Currently the toasts relating to the user's Electrum connection show up too often.

**To Reproduce**
1. Open up the app
2. Minimize the app
3. Open app again
4. Notification pops up

**Expected behavior**
Toast should only appear when there is an unexpected connection issue. It should not appear when:
- the app starts up normally (Android)
- the app is in the foreground again after being minimized
- etc.

**Comment by JWBurgers** [comment]
Most people don't know what an Electrum server is and such a message will probably just cause confusion. What about replacing the electrum server messages as follows?

- "Bitkit is reconnecting"
- "Bitkit connection restored"

Furthermore, we should only bug the user after a certain amount of time with these messages. It now seems they are constantly popping up as soon as connection is lost. What about a 5 to 10 second lag?
