### ISSUE TITLE
Send: change boosting and sending swipe loading animation.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#366]
**Describe the bug**
Change loading animation when swiping to send/boosting tx.

**Screenshots**

https://user-images.githubusercontent.com/5798170/189798453-b9f82e73-9449-4afb-92e3-cad48d185f74.mp4

**Comment by limpbrains** [comment]
If you find this animation confusing, please discuss it with Aldert, he purposed it. Currently it woks as expected - 1 second delay before showing spinner

**Comment by pwltr** [comment]
Currently the "delay" is not 1 second as the UI is freezing for ~3 secs and only then shows the spinner. Closing here as this issue is a duplicate of https://github.com/synonymdev/bitkit/issues/364.
