### ISSUE TITLE
(Android) react-native-ldk v0.0.53 Does Not Init On First Launch

### ISSUE THREAD

**Issue by coreyphillips** [synonymdev/bitkit-react-native#372]
**Describe the bug**
As of `react-native-ldk` v0.0.53, LDK does not seem to be able to init after first creating the wallet. Restarting the app after first creating the wallet resolves the issue.

**To Reproduce**
1. Go through the onboarding flow and create a wallet for the first time.
2. After creating a wallet and directed to the home screen the user will see a notification explaining that LDK was unable to start.

**Expected behavior**
After creating a wallet and directed to the home screen LDK inits as expected without having to restart the app.

**Smartphone:**
 - OS: Android

**Comment by pwltr** [comment]
Can this be closed @coreyphillips ? Haven't seen this error notification in a while.
