### ISSUE TITLE
Send/Receive: Hiding Balance also makes send/receive flow unusable

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#376]
**Describe the bug**
After hiding balance on Wallet screen the amounts in send & receive flows are also hidden, making them unusable.

**To Reproduce**
1. Go to Wallet/Home screen
2. Swipe to the side on the balance
3. Go to Send or Receive flow
4. Try to use UI

**Expected behavior**
Amounts are not hidden, only the user's balance and tx history. 

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-09-16 at 11 18 30](https://user-images.githubusercontent.com/8538369/190604050-56d86ba8-e302-4a08-a297-55df9bb9e786.png)

**Comment by limpbrains** [comment]
Old discussion for the context:

> **Ivan**

> If the balance sheet is hidden, how far should this logic extend? What if the user tries to send some of the funds? Or look at the wallet details?
> Maybe this should only be applied on the home screen?

> **Aldert**

> I would suggest implementing the  hiding balance functionality only for the home screen, maybe the asset overview screens (as these are similar to the home screen) and probably also (always) hide the balance during the receive flow, especially once a QR is presented, as at that time you likely don't want the paying / scanning counterparty to see your balance in the background.
