### ISSUE TITLE
Disallow adding your local slashtags as contacts

### ISSUE THREAD

**Issue by Nuhvi** [synonymdev/bitkit-react-native#378]
**Describe the bug**
It is possible to add your self as contact, but not delete that contact later.

**To Reproduce**
1. Copy your own slashtag url and add it as a contact.
2. Try to delete that account.

**Expected behavior**
Check if the url is already one of your local slashtags (easiest way is to check the profiles in the SlashtagsProvider), and if so, just navigate to that profile page instead of adding it as a contact.

**Screenshots**

![Screenshot_20220916-133936_Bitkit](https://user-images.githubusercontent.com/40009100/190621857-049d4158-9ba0-48b2-93ee-1d8264e19d6a.jpg)

**Smartphone (please complete the following information):**
 - OS:  Android

**Comment by JWBurgers** [comment]
From a UX perspective, this is low priority. Few people will try this kind of thing.
