### ISSUE TITLE
Suggestions: gap space after closing suggestions cards

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#385]
**Describe the bug**
There is a gap space after closing suggestions cards

**To Reproduce**
1. close all the cards at the homepage.

**Screenshots**
![image](https://user-images.githubusercontent.com/5798170/190636101-09a49433-7e2d-4c19-8149-db74c63a6506.png)

**Comment by pwltr** [comment]
I'm not able to reproduce this, can you try again or provide more details as to the device you were testing on? I tested on iOS Simulator and Android 12 Emulator.

https://user-images.githubusercontent.com/8538369/190991602-f40266d4-34ee-4484-bbae-c1b12e57ad5e.mp4

**Comment by limpbrains** [comment]
same, can't reproduce

**Comment by pwltr** [comment]
Was able to reproduce, the cards are off-screen to the left. Investigating...
