### ISSUE TITLE
Slashtags profile link's value is not visible.

### ISSUE THREAD

**Issue by Nuhvi** [synonymdev/bitkit-react-native#387]
**Describe the bug**
Slashtags profile link's value is not visible.

**To Reproduce**
Seems to only happen on my Android phone! But create a link and go to links in your profile page.

**Expected behavior**
It should be visible in white text.

**Screenshots**
![Screenshot_20220916-132255_Bitkit](https://user-images.githubusercontent.com/40009100/190640666-a98487d9-eeaa-41c7-862a-096c1eb84670.jpg)

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by pwltr** [comment]
Most likely has been fixed by https://github.com/synonymdev/bitkit/pull/401
