### ISSUE TITLE
useSlashtags() doesn't return contact name if it is not custom one.

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#396]
**Describe the bug**
I'm adding 2 contacts. For the first one I'm providing custom name. For the second I don't and name get retrieved from slashtags.
Now when I use `useSlashtags` hook it gives me 2 contacts, but the second one doesn't have a name.

<img width="300" alt="изображение" src="https://user-images.githubusercontent.com/155891/191028718-8ed690e9-2228-467a-a397-e5e894a93a7b.png">

**Comment by Nuhvi** [comment]
I think it will be solved by this commit https://github.com/synonymdev/bitkit/pull/394/commits/4ee9f4f296a038e324c51089c08f9886e2633d57
