### ISSUE TITLE
Do not show contacts/profile onboarding if wallet was recovered from a backup

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#398]
**Describe the bug**
I wave a wallet with slashtags profile and a list of contacts. When I recover it from a seed it gets my profile and contacts list just fine. But when I click on a contacts button, it shows contacts onboarding screens. Same for Profile.
I think this can be skipped.

**Comment by Nuhvi** [comment]
Hmmm, I will test this again after Bitkit backpack backup is in place, it should be how this problem is solved! (restoring Redux state)

**Comment by BitcoinErrorLog** [comment]
This seems to have gotten a little bit worse. In a restored wallet, you can no longer see your normal profile screen. It always forces you into the Edit mode, with no way to close the editor.
![telegram-cloud-photo-size-1-5118492709567441594-y](https://user-images.githubusercontent.com/18273620/217013440-6c01f399-dc72-48cd-9e68-e626d0ec7784.jpg)

**Comment by Nuhvi** [comment]
@BitcoinErrorLog I think this is a separate error, which has to do with the fact that having many links push the save button too low. opened https://github.com/synonymdev/bitkit/issues/879

But yes you shouldn't go through the onboarding anyway if you are restoring from Bitkit.

The question is, how can we till if the restored wallet _was_ indeed made in Bitkit previously?
The best I can do here is either:
1- Make the assumption and never show the onboarding to anyone restoring a wallet.
2- If they are restoring online, and they created profile / added contacts, and the seeder has their data, and they got it fast enough, then I shouldn't show the onboarding.

Any ideas?

**Comment by Nuhvi** [comment]
Apparently, https://github.com/synonymdev/bitkit/issues/706 should solve this!
