### ISSUE TITLE
Backup: Add "Enable Biometric" OS prompt

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#431]
### Tasks
- Add a prompt to ask the user to enable biometric in OS settings if it's available but disabled

**Comment by limpbrains** [comment]
It seems react-native-biometrics doesn't tell if biometric is unavailable or disabled on the device. May be we can just change text mention this?

**Comment by aldertnl** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/81586998/195574792-f5c90345-3f3a-4e66-9097-e81fec1f7d36.png">


'Looks like you haven’t set up biometric security for your device yet (or it is not supported). You can try to enable biometric security in the phone settings.'
