### ISSUE TITLE
New wallet when re-installing app on iOS

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#459]
**Describe the bug**
I 

**To Reproduce**
Have a wallet on a iphone
Reinstall the app
Launch it, now I have new wallet with NEW SEED

**Expected behavior**
Should be a wallet with an old seed

**Smartphone (please complete the following information):**
 - iOS

**Comment by aldertnl** [comment]
Is this about reinstalling or restoring? A reinstall after deleting the app will usually start with a fresh set of data, and therefore a new seed, no? This is default behavior in iOS I think.

**Comment by limpbrains** [comment]
This is about reinstalling. We have 2 storages for data in Bitkit. Main one and one for wallet seeds. Wallet seeds are stored in the Keychain and remains there after app get removed.
I'm too find this confusing, I think if app gets removed, all wallets should be gone forever

**Comment by coreyphillips** [comment]
Not sure there's a way to force the app to remove or delete the keychain data when uninstalling. We will need to find a way to detect a fresh install and initiate a wallet/keychain wipe prior to the creation and setup of a new wallet in the onboarding flow.

**Comment by limpbrains** [comment]
Related #503
