### ISSUE TITLE
Send: Improve max. amount validation feedback

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#467]
There is no feedback when entering an invalid amount in the NumberPad in the Send flow.

https://user-images.githubusercontent.com/155891/194560264-49023b38-d65c-4556-990d-1a4d6bbfbc03.MP4

**Comment by aldertnl** [comment]
Ideally the user should be able to rotate between USD/BTC/SATS in every numpad of the app

**Comment by limpbrains** [comment]
This is how our keyboard works. It prevents user to enter amount higher, than he have.
If he have 0.01, he have to enter 0 dot 0 1, other variants will be ignored.

**Comment by aldertnl** [comment]
Can we flash the numbers orange #ff6600 for 0.5 sec or so when the amount is higher than a user has in his wallet?

**Comment by limpbrains** [comment]
> Can we flash the numbers orange #ff6600 for 0.5 sec or so when the amount is higher than a user has in his wallet?

Should we flash possible variants or impossible?

**Comment by aldertnl** [comment]
I was thinking just flash whatever their input is, with the orange color briefly indicating that this is not possible, and resetting again to 0.000000000

**Comment by coreyphillips** [comment]
These limits will also be made clearer in the next version of the app as it will indicate what the available max amount is.
