### ISSUE TITLE
After paying someone on chain the view transaction details button goes to the previous screen where swipe to pay is located.

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#471]
https://user-images.githubusercontent.com/155891/194560957-f0c0b068-b1c4-47dc-8f28-c7f6b5fb1eef.MP4

**Comment by aldertnl** [comment]
Correct, this button should lead to the transaction overview page, the same view that opens when you tap a transaction in the activity list view. This is pretty high priority, as this bug may currently cause people to pay twice(?) 

Also please change the label of the button to a shorter 'Show Details' (will be reflected in a prototype update as well)
