### ISSUE TITLE
Pre-Launch Tasks

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#502]
Things to do before publishing Bitkit to the App Store.

### Tasks
- update AppleID in `About` and `EasterEgg` screens
- update About screen links
- remove `usesCleartextTraffic` from `AndroidManifest.xml`

**Comment by Nuhvi** [comment]
should we close this now @pwltr?

**Comment by pwltr** [comment]
No, these are tasks for when we do a full launch, meaning moving from Testflight to App Store. We also use some non TLS endpoints currently that we should swap at some point.
