### ISSUE TITLE
Hide dev setting

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#509]
- tap 5 times somewhere ( on an orange pill, probably ? )
- same for lightning connections, add pull-to-refresh

**Comment by coreyphillips** [comment]
Started work on this and never created a branch. Added it [here](https://github.com/synonymdev/bitkit/tree/toggle-dev-settings) for reference if needed. Only thing it doesn't have is pull-to-refresh on the Lightning Channel list. It's currently set up to require 5 taps on the bottom of the the initial Settings view to enable/disable the new `enableDevOptions` variable in the `settings` store.
