### ISSUE TITLE
Swipe back from settings screens sometimes throws you to main screen. iOS

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#526]
On the 2nd or 3rd layers swipe to go back gesture sometimes works incorrectly. Instead of going back, it goes all the way to the top route. Feels like a bug in react-navigation. I've tried to upgrade to the latest version, but that didn't help.

iOS

https://user-images.githubusercontent.com/155891/196403032-46823ddd-e16f-432e-8a1e-4bd2e8f44bc2.mp4

**Comment by pwltr** [comment]
Can we just disable `react-navigation` gestures? I have native swipe gestures enabled on my Android too so for me there are two swipe handlers which leads to bad UX (have to be precise where to start the swipe).

**Comment by limpbrains** [comment]
I don't know, will it break gestures on iOS ? I really like them

**Comment by limpbrains** [comment]
I think I found a solution for my issue with swipe to go back issue. 
Just replacing react-navigation/native-stack with react-navigation/stack for settings

**Comment by pwltr** [comment]
Need to check if performance is still okay with the non-native navigator.

**Comment by limpbrains** [comment]
We are using it for root navigation. It is fine.
