### ISSUE TITLE
Can't fetch all transactions when recovering wallet from seed

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#535]
**Describe the bug**
BIP84 wallet has 146 transactions. When I'm trying to recover it in Bitkit, it only shows me 40.

**To Reproduce**
1. recover famous `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about` in bitkit
2. go to actions. there should be more than 100 transactions, starting from 2 years ago

**Comment by coreyphillips** [comment]
This appears to be resolved while testing as of version v1.0.0-beta46.

@limpbrains can you confirm?

**Comment by limpbrains** [comment]
I've tested it once again, works fine now
