### ISSUE TITLE
Receiving QRCode with no address

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#536]
**Describe the bug**
Sometimes Bitkit shows qrcode with no bitcoin address in it `bitcoin:?amount=0`

**To Reproduce**
1. Create new wallet
2. Go to settings -> General -> Bitcoin address type
3. Switch to Legacy
4. Go to main screen, tap receive
5. Check the qrcode

**Expected behavior**
QRcode should have legacy bitcoin address in it, it has none.

**Comment by limpbrains** [comment]
I can see a typo here
https://github.com/synonymdev/bitkit/blob/master/src/utils/wallet/index.ts#L2439
```diff
- getStore().wallet[selectedWallet].addresses[selectedNetwork][addressType];
+ getStore().wallet?.wallets[selectedWallet].addresses[selectedNetwork][addressType];
```

But the issue still exists, because there are no generated addresses in wallet.addresses index

**Comment by pwltr** [comment]
Seeing this issue with default address type (Bech32) as well. Not able to get an address.
