### ISSUE TITLE
add to Bitkit LNURL Open channel

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#569]

**Comment by coreyphillips** [comment]
LNURL Open Channel added as of [this](https://github.com/synonymdev/bitkit/pull/846) commit.

**Comment by JeanlChristophe** [comment]
I successfully opened channel but had not notification. It should be like this:
![image (2)](https://github.com/synonymdev/bitkit/assets/46056211/d3eb8d6c-c433-4c3c-8cb4-fda17e3abd91)

Phil tried but couldn't opened channel.
![Screenshot_20230804-145208](https://github.com/synonymdev/bitkit/assets/46056211/427ff818-0a5b-4d4d-ad1f-32cb3c1743f4)
