### ISSUE TITLE
Balance refreshing, but no notification of transaction

### ISSUE THREAD

**Issue by JWBurgers** [synonymdev/bitkit-react-native#602]
**Describe the bug**
An incoming transaction will be added to the balance, but no notification of the transaction is seen and it there is no record in activities list. Requires refreshing the wallet for the notification and to be recorded in activities.  

**To Reproduce**
Just continue sending small payments to a wallet and it will pop up eventually. It seems to happen more often when payment are sent at the same time. 

**Expected behavior**
Notification of payment, updated activities, and refreshing of balance. 

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by limpbrains** [comment]
If there are a few simulations incoming transactions, bitkit will show notification only for the last one.

**Comment by JWBurgers** [comment]
Tested extensively today. All transactions on mainnet received notifications within the wallet, both on Android and iOS. Closing this for now.
