### ISSUE TITLE
[Bug]: Selecting Contact/Slashtag to Send Funds to Fails

### ISSUE THREAD

**Issue by mchapiro1** [synonymdev/bitkit-react-native#624]
After adding a couple contacts, I was able to send one on-chain payment. After putting half my funds on Lightning, I was not able to make any further payments to a Slashtag/contact by any method. After entering a payment amount, I would click on a contact and it would do nothing. Pasting a slashtag in also failed in enable continuing. Ordinary addresses do not have issues.

It is also not possible to pay a contact by going to the contact directly and hitting any of the icons.

Just added another contact that fails differently: it now throws "unable to pay invoice" error when trying to send funds.

Weirdly, when I enter my own slashtag, I am able to hit continue and slide to confirm a transaction, which then fails by informing me I cannot generate a route to myself.

I have attempted adjusting in settings whether Ln or onchain is the first choice and this does not seem to fix things.

I am on Android. A couple other people had similar issues, one of whom is on iOS, but was eventually able to get one transaction through to me. Overall, reliability is far too low as this makes the wallet largely unusable when it comes to the major feature innovation of push payments with nice UI.

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/744
