### ISSUE TITLE
[Feature]: PLN missing as local currency

### ISSUE THREAD

**Issue by jesterhodl** [synonymdev/bitkit-react-native#626]
**Describe the bug**
Local currency list is missing PLN - Polish Zloty

**To Reproduce**
1. Go to Settings
2. Click on General
3. Type PLN
4. See no PLN is listed

**Expected behavior**
PLN listed as local currency to choose

**Screenshots**
![86D1876C-B20A-46C7-B41D-F5FA4F701CA2](https://user-images.githubusercontent.com/103882255/198884641-6847cd2a-520f-44fc-a04d-5365169409d4.png)

**Smartphone (please complete the following information):**
 - OS: iOS

**Additional context**
Using version in testpilot: 1.0.0

**Comment by limpbrains** [comment]
Fixed
