### ISSUE TITLE
[Bug]: PIN UI responsiveness

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#632]
### Describe the bug

Apparently the PIN flow or PIN check screens are a bit slow to respond to user input

### Reproduce

Taken from Twitter. Need to try to reproduce.

### Operating system

Android

### Bitkit version

v1.0.0

**Comment by mchapiro1** [comment]
Can confirm. About 3 second lag for me on Android. Some of the other button clicks are also slow throughout the app, but not all.

**Comment by Nuhvi** [comment]
Is this still true? we got a report that it is working great now. @pwltr
