### ISSUE TITLE
[Feature]: Improve UI/UX On Finishing Entry of Send Amount

### ISSUE THREAD

**Issue by mchapiro1** [synonymdev/bitkit-react-native#637]
### Describe the problem

Currently, after you enter a number of sats to send, there is a small "done" button to go back to the main send screen. This is slightly awkward, and for someone new to bitcoin might be unintuitive. Added to this problem is the fact that if you miss the Done button and try to swipe away from the main screen, it is likely to just lead to closing out the send screen altogether.

### Describe the solution

I'm not entirely sure how to solve since I am not a designer. I'm not sure if there is a more intuitive gesture solution. It is possible that moving the Done button to the bottom right, and making it bigger, so more like a standard send/finish button. My keyboard retraction button within Android is on bottom left so maybe look at what typical keyboard/keypad retraction UIs look like in different apps.

**Comment by imacfan** [comment]
Does sending funds actually work for you ? My funds are stuck in the app for 2 months. Anyway to send them?

**Comment by mchapiro1** [comment]
I ended up getting funds back directly from them, at least within LN
channel. Haven't tried latest version of app for weeks.
