### ISSUE TITLE
[Bug]: Restore Flow Error Handling

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#651]
### Describe the bug

There are cases when Bitkit is unable to restore from the remote backup and the app gets stuck on "Setting Up Wallet". Exact reasons yet unclear but we need to handle all the error cases and give the user the possibility to "Try again" or "Cancel" the remote restore process while letting them know the implications (no Lightning channel restore).

### Operating system

Android, iOS

### Bitkit version

v1.0.0

**Comment by limpbrains** [comment]
How to reproduce:
Try to recover `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`
It fails with unhandled exception
