### ISSUE TITLE
[Bug]: Unable to open a channel

### ISSUE THREAD

**Issue by grunch** [synonymdev/bitkit-react-native#655]
### Describe the bug

I am trying to open a channel, I received two onchain payments, so I have two utxo, then I'm trying to open a channel, I tried with the quick way and the advance way, both I get the same error.
```
Unable to create transaction
Outputs are spending more than inputs
```

### Reproduce

Receive two onchain payments, one with amount o 200k and the other one 400k.
Then try to open a channel
I tried to open a channel with 100% on the quick way but also I tried to open a channel of 400k, I have 600k so it should open but is not

### Screenshots / Recording

![photo_2022-11-03_16-43-15](https://user-images.githubusercontent.com/228364/199819620-09f7edf5-61fb-413b-b450-9200e3690d14.jpg)

### Operating system

Android 13

### Bitkit version

v1.0.0

**Comment by coreyphillips** [comment]
Thanks for opening this issue @grunch. Looks like the calculation for sending the max amount when opening a lightning channel isn't properly accounting for one of the channel open fees in this instance.

Have you had any luck opening a channel at a lower percentage? 95% or 90%?

**Comment by grunch** [comment]
hi @coreyphillips  I tried with 50% and I still get the same error

**Comment by coreyphillips** [comment]
I see the issue and will have a fix ready for the next release.

The issue stems from this bit of logic [here](https://github.com/synonymdev/bitkit/blob/45a9738b254ab0ec676bb399504d79659d0fcf54/src/store/actions/wallet.ts#L817) that tries to retain any previously selected inputs for a given transaction. So when we setup the transaction for a channel open it's not pulling in any new utxo's as inputs that may have arrived between previous transaction attempts. To fix this, we just need to call `resetOnChainTransaction` when navigating directly to any channel-open view.

As a quick fix, you should be able to open the "Send" view from the main screen, close/swipe down from the "Send" view (this will trigger `resetOnChainTransaction`) and then re-attempt to open a channel.

**Comment by grunch** [comment]
Thanks for the quick response, I tried the quick fix and it works, the channel is being open
