### ISSUE TITLE
[Bug]: Balance not adding up, too-high Blocktank fees, Blocktank takes many attempts

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#659]
### Describe the bug

A few possibly related bugs:

Part 1 - "It looks like 14,793 Sats have gone missing somehow in setting up lightning. These numbers don't add up. I sent myself (received) 57,840. Then set up lightning. Now I only have 43,047 left. Where is the other 14,793 sats? If they went for fees then it needs to explain that somewhere. "

Part 2 - "Note: It costs $123 to add $2 to my lightning channel."

Part 3 - "It took 9 attempts over 2 days to get the Lightning channel open. It kept throwing an error about outputs exceeding inputs." 

### Screenshots / Recording

![image](https://user-images.githubusercontent.com/18273620/200113366-40465319-3e3f-48e2-a7d5-c7c14f64e705.png)

![image](https://user-images.githubusercontent.com/18273620/200113401-da86d2d3-8b17-4fee-b5e5-ae721924a7bb.png)

![image](https://user-images.githubusercontent.com/18273620/200113445-d642a938-b43e-47e3-912a-c7f3c3d84be4.png)

### Operating system

Android?

**Comment by coreyphillips** [comment]
- Part 2 was fixed [here](https://github.com/synonymdev/bitkit/pull/657).
  - Until the next release, tapping the "Transfer" icon in the wallet details view will navigate to the incorrect lightning onboarding view.
- Part 3 is being addressed [here](https://github.com/synonymdev/bitkit/issues/655#issuecomment-1304550218). Fix incoming.
  - Quick fix until then: You should be able to open the "Send" view from the main screen, close/swipe down from the "Send" view (this will trigger resetOnChainTransaction) and then re-attempt to open a channel.
