### ISSUE TITLE
[Feature]: Document pending time for channel 

### ISSUE THREAD

**Issue by louneskmt** [synonymdev/bitkit-react-native#704]
### Describe the problem

When I set up my first channel, I had to wait for it to be opened and usable (obviously, no problem here). However, it was unclear how much time it will take and when I will be able to use that channel to send/receive payments. 

The average user might ask theirselves why is their balance "pending", and why they get errors trying to pay invoices or receive payments. 

### Describe the solution

At the end of the setup, there could be a small text explaining that it could take up to X minutes for the channel te become usable (6 blocks, right?), or similar helper text. 

The balance is "pending" but nowhere it is explained what "pending" means, it might confuse users.

**Comment by JeanlChristophe** [comment]
![Capture d’écran 2023-04-20 à 11 11 51](https://user-images.githubusercontent.com/46056211/233318723-0112a78b-10f7-42da-8cab-f03bd862383f.png)

We have added this information to the UI. Thanks for you help Lounes.
Close the ticket.
