### ISSUE TITLE
[Bug]: Stuck in 'awaiting payment'

### ISSUE THREAD

**Issue by mindrunner** [synonymdev/bitkit-react-native#705]
### Describe the bug

I created a channel about a week ago. The Blocktank Order is stuck in 'Awaiting Payment' Status. Transaction was confirmed already 7 days ago. It is unclear what I have to do now to get either my money refunded or the channel opened.

### Reproduce

-

### Screenshots / Recording

-

### Operating system

Android 13

### Bitkit version

1.0.0

**Comment by pwltr** [comment]
Please navigate to `Settings -> General -> Blocktank Orders -> Your Order -> Contact Support` to send us an email. The team will look into it and you will get a refund if eligible.
