### ISSUE TITLE
[Feature]: Perform full backup

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#706]
### Describe the problem

Bitkit currently does not save all of the user's data to the remote backup.

### Describe the solution

Should save/restore all (useful) user data:

- [x] Lightning backup
- [ ] Profile
- [ ] Contacts
- [x] Widgets
- [x] Tags
- [x] Preferences

**Comment by BitcoinErrorLog** [comment]
okay, but we do need to make sure states are both saved and checked when restored thoughtfully. We have more than one onboarding frame (Profile, Pay to Contacts, Dynamic Contacts, Suggestion Cards State, etc) @coreyphillips

**Comment by coreyphillips** [comment]
I'll bring this up in the next dev call as well. Based on the work completed on backups so far, when restoring non-critical/user-convenience items such as settings or widgets the app will check the shape of the backup and compare it to the app's currently expected default shape for that item. If the items do not match, we simply discard the backup for that specific item to prevent importing an invalid/unexpected shape. This will allow us to adjust the shape/structure of the settings, widgets or suggestion cards without worrying about failing a restore attempt.

**Comment by JeanlChristophe** [comment]
the fix will also solve this issue #398

**Comment by pwltr** [comment]
This doesn't seem to be done yet. When restoring from remote backup the profile and contacts are still fetched from the seeder as far as I can tell. Can you confirm @coreyphillips ?
