### ISSUE TITLE
[Bug]: Funds lost after channel close

### ISSUE THREAD

**Issue by steepdawn974** [synonymdev/bitkit-react-native#713]
### Describe the bug

After having closed a Lightning connection, the funds that were in the channel never reappear in the on-chain wallet.  

Under Networks > Ligthning Connections the channel is under "Closed Connections", so it appears it has properly closed. 
I imported the seed words into a third-party wallet to double-check, and can confirm that the funds never arrived.

Where can I provide further info (channelId etc) to help troubleshoot?

### Reproduce

1. Open a LN channel (Blocktank) with wallet on-chain funds
2. LN Balance appears
3. Close this Lightning Connection
4. Channel is closed, but Funds are lost

### Operating system

CalyxOS 4.3.0 (Android13)

### Bitkit version

v1.0.0

**Comment by Jasonvdb** [comment]
Can you please confirm the version in the app? Go to Settings -> About Bitkit. It should be version `1.0 (19)` for the latest. 

We just added a pending balance to your total so you should see that there for a while after the channel closes. It's likely a mutual close didn't happen resulting in a force close and the funds could take 2 weeks to be claimable. You won't see it in your onchain wallet even if you import it elsewhere until the outputs become spendable again so the wallet can claim it.

If you're on the latest version and not seeing a pending balance above your total on the home screen then send us your channel ID or Blocktank order ID (Settings -> General -> Blocktank Orders) to `support@synonym.to` and we can check on our side what the status is.

**Comment by steepdawn974** [comment]
It reads: 
`Version: 1.0.0`  


EDIT: I see a new update just dropped. Installing `1.0 (19)` now

**Comment by Jasonvdb** [comment]
Cool let me know if you see a pending balance now?

**Comment by steepdawn974** [comment]
Negative. Still no pending balance on `v1.0 (19)`.   Will engage support@synonym.to now.

**Comment by Jasonvdb** [comment]
@steepdawn974 just confirming you didn't try restore your wallet into Bitkit? It's still the original one you created on your device? Just want to rule out a bug in the backup method.

**Comment by steepdawn974** [comment]
Correct- It was a first-time fresh install of 1.0.0 back then. Create a fresh wallet, transferred some sats, opened a channel, then two weeks later closed the channel --> remaining channel balance is not showing up in the on chain wallet, also not a pending. 
Then upgraded to 1.0 (19) as suggested on Github --> still no fund pending. 

SD 

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Nov 21, 2022, 20:37 by ***@***.***:

**Comment by steepdawn974** [comment]
Any updates for me in this?

Still waiting for my funds...


Rgds,
SD974
Nov 22, 2022, 21:13 by ***@***.***:

**Comment by JWBurgers** [comment]
@rbndg ?

**Comment by Jasonvdb** [comment]
@steepdawn974 do you still have the Bitkit wallet installed with the original seed? Could you please check if funds from the closed channel ever returned? Could have taken +-2 weeks if the channel was force closed.

**Comment by steepdawn974** [comment]
@Jasonvdb Yes, I still have the wallet and no, the funds have not shown up.

Note: I did receive an out of band refund via Customer Support though.

**Comment by steepdawn974** [comment]
There might be another related issue though: Moved a coouple of days ago some 20k sats from Savings to "Spending balance" (Lighning), and the funds never showed up in Lightning. the tx is confirmed for several days. 

I dont actually know if the LDK node changed from then to now; but if it remained the same then it could mean that this node is somehow "broken" and funds disappear in it.

**Comment by JeanlChristophe** [comment]
Hi @steepdawn974 

Could you please try with the latest version and let me know if it's not fixed. Thanks and sorry.

**Comment by JeanlChristophe** [comment]
@steepdawn974 Were you able to try again with the latest version?

**Comment by JeanlChristophe** [comment]
Closing this issue
