### ISSUE TITLE
[Bug]: `Payment Received` screen is not showing the amount. (Regtest only)

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#731]
### Describe the bug

The `Payment Received` screen it is not showing the amount.

### Reproduce

1. Click on Receive Button
2. Pay the invoice
3. Wait for the receive payment screen

### Screenshots / Recording

![image](https://user-images.githubusercontent.com/5798170/203985696-7a0a41ef-f382-4527-89aa-63b083b7de81.png)

### Operating system

Android 12

### Bitkit version

v1.0(20)

**Comment by pwltr** [comment]
Should be fixed by https://github.com/synonymdev/bitkit/pull/796
