### ISSUE TITLE
[Bug]: Paying to Contacts functionality broken

### ISSUE THREAD

**Issue by aldertnl** [synonymdev/bitkit-react-native#744]
### Describe the bug

The 'Pay to Contacts' functionality seems to be broken in v1.0 (21) and v1.0 (22). A user cannot select a contact from the contact list in the send flow. Also, tapping the [coins] button while viewing a contact profile will not activate the 'send to contact' modal.

This is an important issue to fix in my opinion, as sending to contacts is one of the most important use cases within Bitkit. 

### Reproduce

1. Go to [Send]
2. Click on [Contacts icon]
3. Select a contact from the contacts list
4. Nothing happens

1. Go to [Contacts]
2. Tap on a contact 
3. Tap on the [coins] button
4. Nothing happens

### Operating system

iPhone 11, iOS 16.1.1

### Bitkit version

1.0 (22)

**Comment by Bitc0indad** [comment]
![image](https://user-images.githubusercontent.com/105452033/205090540-512461fd-5b8f-4ea0-bb06-7d57f501957d.jpeg)

I ran into this issue as well

**Comment by aldertnl** [comment]
This is a different issue (but related). Some team members encountered the same error as you. @Nazeh @BitcoinErrorLog

**Comment by BitcoinErrorLog** [comment]
This may be the same issue, as at first I thought I also only could not tap on any contact, but then I realized this error started showing and that was why.

This could be because have bad handling of the fallback, a missing fallback, or failed replacement processes. Needs more attention and testing of fixes.

**Comment by Nuhvi** [comment]
This is either `slashpay.json` wasn't resolved (seeder didn't have the data, and the user is offline), or the user didn't allow `slashpay` at all... either way there is no way to tell which.

However we can add an error message if that was the case, so it is a bit distinct from this generic error that is thrown at the end of the code path (that is common with scanning normal bitcoin/lightning QR)

**Comment by BitcoinErrorLog** [comment]
It is probably something broad, as it happens for all my contacts the same way. Something is broken. Please test using the app in two phones across the team, and with team members that are having the issue. Also test while app is closed vs open, etc. Generally Slashtags Profiles, Contacts, and Slashpay are not reliable yet.

**Comment by aldertnl** [comment]
Tested this feature again today with @pwltr, we had varying experiences (v1.0 (23)).

- I couldn't select any of the contacts in my contacts list (mostly team members), except for a newly generated profile by Philipp and a test profile.
- Philip could select most contacts in his contact list, and it would default to the on-chain Pay to Contacts flow (expected behavior).
- Using his new profile, I was able to successfully send an on-chain transaction to Philipp using the Pay to Contacts flow.

Some current presumptions based on these and previous observations:
- This issue seems to affect 'older' contacts more than recently created ones.
- This issue seems to mostly affect users that simply updating the app instead of deleting, reinstalling and restoring their wallet.

We couldn't test the LN instant payment variant of the Pay to Contacts flow, as Philipp had an issue with setting up a new instant spending balance (looks like a Blocktank issue).

**Comment by aldertnl** [comment]
Update: The Pay to Contacts feature is still not working for me 90+ % of the time (can't be the only one). Getting a spinner for almost every contact that I select from the contact list (Send Flow, build v31). Can someone confirm this?

![5F9AC607-E6A7-4EBB-AA11-EB4A580D9993_1_102_o](https://user-images.githubusercontent.com/81586998/215553683-1845306c-a166-44b2-ac75-2ace1ed6aa98.jpeg)

**Comment by Nuhvi** [comment]
@aldertnl the internal bulid is disabling the Hyperswarm connection to the seeder, I am trying to add a stopgap WebSocket connection to that seeder, and it should be there in the next internal build.

**Comment by aldertnl** [comment]
Did this change make it into our new internal build 33? I am not seeing any improvements, still getting the spinner when selecting a contact.

**Comment by Nuhvi** [comment]
@aldertnl we will see in today's internal build, it should work nicely *fingers crossed* #870

**Comment by Nuhvi** [comment]
should we close this issue already?

**Comment by BitcoinErrorLog** [comment]
Please test after the next release with Pav/Jan and confirm all test cases work (new user payments, onchain/offchain, replacement invoices)

**Comment by Nuhvi** [comment]
https://synonymworkspace.slack.com/archives/C01H106JRQB/p1676540215532869?thread_ts=1676526564.246289&cid=C01H106JRQB
