### ISSUE TITLE
[Bug]: Adding Slashtag Contact then viewing Contacts has interrupted flow initially

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#765]
### Describe the bug

Just tried the iOS version again and noticed a bug with the contact list view. If I start by scanning someones Slashtag and then save it … Then enter the Contact list .. it will always just show a splash screen with “add your first contact!” .. Which is false because it’s already added, and I don’t see how I can actually just list the contacts,, eventually it worked after getting past that one

### Operating system

iOS

**Comment by BitcoinErrorLog** [comment]
"I tried scanning the contact and save it .. but every time I went to check the contact list I just got this splash screen so I thought it was never saved"

**Comment by pwltr** [comment]
Fixed in https://github.com/synonymdev/bitkit/pull/788
