### ISSUE TITLE
[Bug]: Lightning send issues

### ISSUE THREAD

**Issue by nbourbon** [synonymdev/bitkit-react-native#785]
### Describe the bug

Can’t send Lightning. I tried sending to Muun and then to my node.. and it’s not working 
![142E41CF-0303-4B13-BA90-AB9D5372FB45](https://user-images.githubusercontent.com/6254963/208219790-9e31722b-f6c5-480e-b7e4-bd330397ab95.png)

### Screenshots / Recording

![FBCDEDCE-B9E9-4040-AA86-BEFF5A349A22](https://user-images.githubusercontent.com/6254963/208219805-8c970136-78f7-4528-8879-8976a08ac7f0.png)

### Operating system

IOS 16.2

**Comment by nbourbon** [comment]
I think I had wallet connectivity issue before, yet, after fixing it now it’s telling me this.. and I tried sending it to Muun and also to my node only few sats
![ACB0B0B1-D59D-4A17-84D8-E93FC6A20D44](https://user-images.githubusercontent.com/6254963/208221429-799e8845-8043-492a-b701-328ff680617b.jpeg)

**Comment by nbourbon** [comment]
and finally then I got a problem with my node connectivity for lightning probably triggering the problem above and after making sure I was properly connected.. it simply never send the sats... it went into a loop.. making me wait and wait and never confirming the delivery of the sats over lighting

So I tried closing my lightning channel and is not allowing me to. Is throwing and error so it's not closing that channel so I can't get my money back. let me know how can we fix this. thanks

**Comment by JWBurgers** [comment]
We've been working on a lot of upgrades to Lightning and performance should significantly improve in the next release.

If you're funds are stuck, please send an e-mail to support@synonym.to so we can help you retrieve your funds.

**Comment by coreyphillips** [comment]
@nbourbon, this issue should be resolved as of the latest build if you would like to update and try again. Going to close this issue for now, but if you're still having issues please feel free to comment and we'll reopen it or send us an email at support@synonym.to
