### ISSUE TITLE
[Bug]: 'Pay instantly' suggestion before user has funds

### ISSUE THREAD

**Issue by vforvilela** [synonymdev/bitkit-react-native#800]
### Describe the bug

The wallet suggest the user to 'pay instantly' before it has any funds, just to inform him that he has no funds.

### Reproduce

1. Create a wallet.
2. Click in 'pay instantly'

### Screenshots / Recording

<img src='https://user-images.githubusercontent.com/80433106/209882633-a48b6a61-2c2f-4a62-843a-00cd434152f5.png' width=400>
<img src='https://user-images.githubusercontent.com/80433106/209882636-d068661a-517b-4e35-a379-7cc73b5b0133.png' width=400>

### Operating system

iOS 16.1.2

### Bitkit version

v1.0 (23)

**Comment by pwltr** [comment]
Hi and thanks for opening these issues, we'll be going over all of them in a bit (PRs welcome!). In this particular case it was an intentional design decision to make the user aware of the feature.
