### ISSUE TITLE
[Bug]:  Excessive data/resource usage while on mobile connection

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#805]
### Describe the bug

![image](https://user-images.githubusercontent.com/18273620/210311481-c2c909c8-783d-4269-8702-3fa431037c92.png)

User reports using 1GB of data in 1 hour while using cellular network.

We need to do the following, in some form:

- Add a monitoring & QA workflow to be aware of resource usage in Bitkit
- Reduce overall constant resource usage (likely hyperswarm)
- Add setting & capability to throttle when not on WiFi
- Share reports of other resource usage stats, and compare to prior release, before each new release
- Anything else?

### Reproduce

1. Open Bitkit
2. Turn off wifi, use cellular network
3. Run up large cellular bill
4. Complain to Bitkit team 

### Screenshots / Recording

![image](https://user-images.githubusercontent.com/18273620/210311481-c2c909c8-783d-4269-8702-3fa431037c92.png)

### Operating system

Android?

**Comment by BitcoinErrorLog** [comment]
If the culprit is indeed Hyperswarm, maybe we can limit self-serving of cores by Bitkit users to strictly be for updating our seeder. Then, we can add a way for peers to instigate direct requests or something later. _(like, "John wants to verify your profile, press okay to send him your current version."_

**Comment by Nazeh** [comment]
@BitcoinErrorLog how did you narrow it down to Hyperswarm?

**Comment by Nuhvi** [comment]
@BitcoinErrorLog Not sure what you mean by a way for peers to instigate a direct request.

If it is the conventional way of sending a message to a server/node somewhere that Bitkit is connected to, then that is fine, but now we are talking about client-server architecture, and Hyperswarm in its entirety becomes redundant. I am ok with that as long as we provide a way to hire and fire these nodes/servers in a soverign way.

If however, you mean Bitkit listening on a DHT server, but not upload its profile to anyone (other than trusted seeder) without user consent, then that requires Bitkit listening on a well-known publicKey to get that request directly, but notice that incoming data is paid usage too, and we can't at this case protect a Bitkit user from spammy incoming requests, even if we don't fulfill them.

Also, there is a minimum overhead running a Hyperswarm and announcing yourself, or even trying to connect to another Bitkit, or just joining a topic, all these operations require periodic requests to the DHT, at Hyperswarm level, not by the SDK itself.

**Comment by BitcoinErrorLog** [comment]
While I am not exactly qualified to be designing this, my starting suggestion was simply to rely on our seeder for now, where the user owns the master copy of the Core. And then we can address ways to extend that ownership into self-sovereign means, through notification server, or self-server via a separate "Slash Node" etc. 

Ofc, you already know my intentions to give people ways to hire/fire providers, and leverage Hyper as unwalled CDN garden. 

The immediate problem (which we have not even verified yet) is that Bitkit is using way too much bandwidth, and that the most likely culprit is excessive swarming behavior. Alternatively, maybe you can throttle that, or maybe it is just bugged and actually overactive.

**Comment by Jasonvdb** [comment]
I still haven't been able to reproduce this. @Nazeh how likely is it that it was hyperswarm and it's been fixed in an update?

**Comment by Nuhvi** [comment]
@Jasonvdb I don't think anyone managed to reproduce it, but reports are that disabling connection to the seeder already removed a lot of the performance hit, so it stands to reason that that spike of network traffic was eliminated too.

Let's wait till we reconnect to the seeder with WebSocket instead of Hyperswarm, and test again (working on it).

**Comment by Nuhvi** [comment]
Until further information, I will assume that changes to the seeder fixed this bug, at least as far as Slasthags is concerned!
