### ISSUE TITLE
[Bug]: update nobleSecp256k1Wrapper.js

### ISSUE THREAD

**Issue by landabaso** [synonymdev/bitkit-react-native#813]
### Describe the bug

Hi there.

I noticed that you are currently using an old version of the code that I wrote for [farvault](https://github.com/bitcoinerlab/farvault-lib). The specific file in question is [nobleSecp256k1Wrapper.js](https://github.com/synonymdev/bitkit/blob/master/nodejs-assets/nodejs-project/nobleSecp256k1Wrapper.js)

I have since found and fixed some minor bugs in the code, and have refactored it into a new package called https://github.com/bitcoinerlab/secp256k1. This new package passes all tests against BitcoinJS's tiny-secp256k1 test-suite.

I would suggest either updating your nobleSecp256k1Wrapper.js file with the new code from the [Github repository](https://github.com/bitcoinerlab/secp256k1), or even better using the new npm package I've created and will maintain. Let me know if you need any help or if there's anything else I can do to assist you.

### Reproduce

Nothing to reproduce

### Operating system

Anything related to RN

**Comment by coreyphillips** [comment]
Thanks for creating this issue, @landabaso. Looking into this now.

**Comment by landabaso** [comment]
Great @coreyphillips . Take a look to the comment linked below for more context and let me know if I can help.

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1781#issuecomment-1378315940

**Comment by junderw** [comment]
@landabaso has since made `@bitcoinerlab/secp256k1` and I just released a new asmjs based package that will be released in lock step with WASM.

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1781#issuecomment-1646446257

**Comment by coreyphillips** [comment]
Thanks @junderw and @landabaso!

`@bitcoinerlab/secp256k1` was added as of [this PR](https://github.com/synonymdev/bitkit/pull/1165).

Will look into replacing the old [nobleSecp256k1Wrapper.js](https://github.com/synonymdev/bitkit/blob/master/nodejs-assets/nodejs-project/nobleSecp256k1Wrapper.js) in the nodejs thread with `@bitcoin-js/tiny-secp256k1-asmjs` after some testing.
