### ISSUE TITLE
Unable to send funds

### ISSUE THREAD

**Issue by imacfan** [synonymdev/bitkit-react-native#825]
I have ios beta app. Updated to latest version. 

Not able to make transactions. 

All send transactions are broken. 
Onchain , lightning, nothing works. 

Funds stuck for long time. ![image](https://user-images.githubusercontent.com/54225190/212521442-9ae86361-9b4d-48b6-a662-3aba894654b6.jpeg)

**Comment by JWBurgers** [comment]
We are aware that some people are plagued by the error message in their wallets. We are working on resolving the problem. For now, the best is to use your seed to restore your money in another wallet (e.g., bluewallet).

**Comment by imacfan** [comment]
Yes, I have tried restoring. And that's not working either. Raised the issue here - https://github.com/synonymdev/bitkit/issues/826

**Comment by JeanlChristophe** [comment]
@imacfan I tried to send you an email but there was no reply. Can you have a look? Thanks

**Comment by imacfan** [comment]
> @imacfan I tried to send you an email but there was no reply. Can you have a look? Thanks

Just replied. Still same issue. Not able to send the transaction. You  can check the screenshot I sent in email.

**Comment by JeanlChristophe** [comment]
Hi @imacfan 
I tried to email you few times to follow up our call, but got no reply.

**Comment by JeanlChristophe** [comment]
Issue fixed, closing the ticket
