### ISSUE TITLE
Restore and backup issue

### ISSUE THREAD

**Issue by imacfan** [synonymdev/bitkit-react-native#826]
I backed up seed phrase in ios wallet. 

Then restored bitkit wallet in Android. Public key for username is exactly the same. 

Seed phrase recovery generates entirely new wallet. I have tried it recovering on blue wallet , Nunchuk and bitkit on another device.

All three new recovered wallets are exactly same. Bitkit even has same publicl key for username. But no funds in any of them. Because recovered wallet seems entirely different from original one which still sits on my phone.
Balance still visible but unable to spend 🤦‍♂️

**Comment by imacfan** [comment]
Seed phrase recovery generates entirely new wallet. I have tried it recovering on blue wallet , Nunchuk and bitkit on another device. 

All three new recovered wallets are exactly same. Bitkit even has same publicl key for username. But no funds in any of them. Because recovered wallet seems entirely different from original one which still sits on my phone.

**Comment by limpbrains** [comment]
How do you check if this is a new wallet? Did you send money to ios wallet? Can you spend them?

**Comment by imacfan** [comment]
I had balance in old ios wallet. Still there. 

But balances in new wallet created with same seed in android is zero. Also addresses doesn't seem to match

**Comment by limpbrains** [comment]
Can you please try to send them from ios somewhere else ?

**Comment by imacfan** [comment]
Yes I tried. Send doesn't work. That's why created this issue - https://github.com/synonymdev/bitkit/issues/825

**Comment by imacfan** [comment]
ok, so I used the same seed on a secondary iOS device. Same results as on Android. Entirely new wallet with zero balance. Address do not match the original wallet which sits on first iOS device. Seems my funds are prisoned... didn't expect such a goof up in bitkit. Don't know if these will get recovered at all

**Comment by BitcoinErrorLog** [comment]
Please clarify a few things:
1. How many seeds do you have, one or two? 
2. Did you try both seeds in Blue wallet?
3. Did you use the funds to make a Lightning Channel at any point? (Instant Payments purple area in Bitkit)

**Comment by imacfan** [comment]
> Please clarify a few things:
> 
> 1. How many seeds do you have, one or two? 
> 
> 2. Did you try both seeds in Blue wallet?
> 
> 3. Did you use the funds to make a Lightning Channel at any point? (Instant Payments purple area in Bitkit)


---/

1. I have only one seed phrase. I can see it when I tap on backup money option. 
2. Tried on bluewallet. Shows zero balance. This is what's weird, I am using exactly the Same seed phrase from the wallet which has balance. 
Bluewallet first address is same as any new wallet which I created with bitkit on new devices. 
For some reason original wallet shows same has same seed phrase but different addresses. It also has balances which is unspendable. See screenshot ![image](https://user-images.githubusercontent.com/54225190/213447104-4fc8a28b-8ba9-4931-b453-a6c4c323177c.jpeg)

3. I tried creating creating lightning. But it never worked and alway threw error.

**Comment by BitcoinErrorLog** [comment]
1. Please send the txn id for the deposit shown in your screenshot _(you can email it to support@synonym.to if you do not want it public here)_
2. Please do the same for a screenshot of Settings > Advanced > Blocktank Orders in the wallet that shows a balance.

**Comment by imacfan** [comment]
> 1. Please send the txn id for the deposit shown in your screenshot _(you can email it to support@synonym.to if you do not want it public here)_
> 
> 2. Please do the same for a screenshot of Settings > Advanced > Blocktank Orders in the wallet that shows a balance.

Ok. Just sent an email with screenshots. Thanks !

**Comment by BitcoinErrorLog** [comment]
Team, I reviewed the images and the pubkey shows as still having the sats in it unspent (and of course no spent sats on Blocktank orders).

**Comment by imacfan** [comment]
Hope someone is looking into it. 😀

**Comment by imacfan** [comment]
Any update here. What's going on? Anything I can help with to expedite process?

**Comment by shinycake** [comment]
I am facing the same issue.

but I am a little bit confused, isn't restoring on the protocol level (i.e application independent)?

does that mean the app provides you with the wrong private key? or is there something I am missing?

**Comment by imacfan** [comment]
> I am facing the same issue.
> 
> but I am a little bit confused, isn't restoring on the protocol level (i.e application independent)?
> 
> does that mean the app provides you with the wrong private key? or is there something I am missing?

It is protocol level and application independent. Not sure what's going on here. 

Yes the real private key 🔑 is different than whats coming up in UI. That's the only explanation but I am just guessing. Hopefully someone from dev team gives some insight.

**Comment by shinycake** [comment]
well, that was an expensive lesson...

**Comment by coreyphillips** [comment]
@imacfan, we have a release set to come out this week that includes a number of bug fixes that may address your issue. One of the bugs we found during our troubleshooting sessions was not pulling all of the UTXO's in when calculating the balance. This would explain why your balance isn't getting displayed and why the address is different (It is using the next available address index in your wallet). It's also possible you switched address types.

One of the notable inclusions in the next release is an address viewer that allows you to see and sweep from various addresses associated with your seed. You'll be able to access it by navigating to Settings->Advanced->Address Viewer.

We'll notify you once the new build is available. Please keep your seed phrase safe until then. When the next build is available it is recommended that you uninstall and reinstall Bitkit from your mobile device for a clean restore.

**Comment by imacfan** [comment]
Sure, seed is safe with me. Looking forward for this bug to get resolved in next release. Thanks

**Comment by nym1991** [comment]
I have the exact same problem as imacfan. Tried the new adress-tool, only one of the adresses that has received funds shows in the list. I was able to spend from it (it was also the last adress I received from, and it was the only receive adress that was after the update 13th january. All others were from between december-13th january.

Tried to restore from Bluewallet and only the one adress and transactions shows. In Bitkit the full balance shows, but unable to spend. 

Also checked adresses that I received on and they are unspent obv.

**Comment by nym1991** [comment]
It seems like none of the adresses are (except the one I spent) are associated with the my seed (which has been the same since I started testing). Also, I can restore the Bitkitwallet using the seed on both Android and iOs, and get the same profile etc, but none of the adresses.

**Comment by coreyphillips** [comment]
@nym1991 To make sure we're on the same page for troubleshooting purposes, in the address viewer did you toggle between and inspect each address type (p2pkh, p2sh, p2wpkh) and change/receive addresses using the tabs? I would also recommend tapping "Generate 20 more" once or twice and then "Check Balances".

**Comment by nym1991** [comment]
> @nym1991 To make sure we're on the same page for troubleshooting purposes, in the address viewer did you toggle between and inspect each address type (p2pkh, p2sh, p2wpkh) and change/receive addresses using the tabs? I would also recommend tapping "Generate 20 more" once or twice and then "Check Balances".

Done. Same issue. All receiving addresses are bc1 so should be p2wphk. Cannot find any address with a balance.

**Comment by imacfan** [comment]
I see there is an update of bitkit app. Updated the same. 

Went to Advanced - address viewer. 
Addresses are same as restored blue wallet. 

But none of the address matches with the one that has balance. All addresses show 0 balances. 

The address which received the bitcoin still shows balances and bitcoin stuck with no way to send them. 🤦‍♂️

**Comment by shinycake** [comment]
> I see there is an update of bitkit app. Updated the same. 
> 
> Went to Advanced - address viewer. 
> Addresses are same as restored blue wallet. 
> 
> But none of the address matches with the one that has balance. All addresses show 0 balances. 
> 
> The address which received the bitcoin still shows balances and bitcoin stuck with no way to send them. 🤦‍♂️

same for me.

tried to Install on a different iOS device as well as an Android device, restored from seed.

balance is 0.

went to Address Viewer - all balances are 0 (tried to generate more a few times).

**Comment by imacfan** [comment]
@coreyphillips @BitcoinErrorLog are you able to figure out the root cause of the issue yet? 

Seems the update of app did nothing to resolve the issue. 

I restored wallet in a new device and balance is 0. Original wallet still shows balance.

How come wallet was generating receiving address unrelated to private key. That's question that need to be answered to resolve it.

**Comment by BitcoinErrorLog** [comment]
I'm not an engineer, but I will note two possible factors:
1. The app had/has some issues with not totally clearing the metadata when you delete the app and install it again. This can cause it to show old activity within a new seed. (This aspect might be fixed).
2. If this is your case, the solution would be to have backed up the original seed from the original wallet, and then restore that instead of using the newer seed. If you did not back up your first seed, but then uninstalled the app, then that seed would not be retrievable, despite it appearing like maybe your old wallet (metadata) is there.

**Comment by nym1991** [comment]
> I'm not an engineer, but I will note two possible factors:
> 
> 1. The app had/has some issues with not totally clearing the metadata when you delete the app and install it again. This can cause it to show old activity within a new seed. (This aspect might be fixed).
> 2. If this is your case, the solution would be to have backed up the original seed from the original wallet, and then restore that instead of using the newer seed. If you did not back up your first seed, but then uninstalled the app, then that seed would not be retrievable, despite it appearing like maybe your old wallet (metadata) is there.

I have 100% backed up the original seed, and tested (although regrettably only on Bitkitwallet) and got the same profile restored. So this does not appear to be the case.

Also restored from seed with Bitkitwallet on multiple phones, same profile, but now none of the addresses are retrieved.

**Comment by coreyphillips** [comment]
To add to BitcoinErrorLog, basically if you ever uninstalled and reinstalled the app before this release, it's possible the app may have carried over an address from the unsaved wallet from storage. Meaning, an address from the old state that is not associated with your current, saved wallet may have been used to send funds to. If that's the case, it's possible those funds are lost.

I would be happy to setup a call to perform some additional troubleshooting if you would like. For anyone needing assistance here that would like to troubleshoot this over a call, please reach out to me at corey@synonym.to with times that would work for you this week or in the near future.

**Comment by imacfan** [comment]
> To add to BitcoinErrorLog, basically if you ever uninstalled and reinstalled the app before this release, it's possible the app may have carried over an address from the unsaved wallet from storage. Meaning, an address from the old state that is not associated with your current, saved wallet may have been used to send funds to. If that's the case, it's possible those funds are lost.
> 
> 
> 
> I would be happy to setup a call to perform some additional troubleshooting if you would like. For anyone needing assistance here that would like to troubleshoot this over a call, please reach out to me at corey@synonym.to with times that would work for you this week or in the near future. 

No. Never uninstalled the app. I reached out to you guys long time back when I faced the issue for the first time. I took the seed backup on day one on paper. It is exact same seed which wallet is showing up right now in the app. 

In the meantime more people have reported same issue. 

Transaction can be seen in the wallet. Balance is visible. 
Your wallet is giving us a seed which restores to zero balance. 

Send feature - both lightning and bitcoin don't work. 

Please setup a call I that helps in troubleshooting. I am not a developer though.

**Comment by imacfan** [comment]
> I'm not an engineer, but I will note two possible factors:
> 
> 1. The app had/has some issues with not totally clearing the metadata when you delete the app and install it again. This can cause it to show old activity within a new seed. (This aspect might be fixed).
> 2. If this is your case, the solution would be to have backed up the original seed from the original wallet, and then restore that instead of using the newer seed. If you did not back up your first seed, but then uninstalled the app, then that seed would not be retrievable, despite it appearing like maybe your old wallet (metadata) is there.

1. I have never deleted the app. Seed backup was taken on day one on paper. It matches with current seed shown by the app. However, this seed restores to zero balance. 
2. I am not using any new seed. Had this been the case , I would not have raised the issue in first place.

**Comment by nym1991** [comment]
I would be interested in the outcome of your call with imacfan.

Seems like we got identical issues, and the problem seems to be the receive adresses provided by the wallet? Im not sure how much can be done, but I hope there is something since I got about 3 mill sats stuck on addresses I cant access.

I can also provide a lot of different screenshots if thats helpful in troubleshooting.

**Comment by coreyphillips** [comment]
For those having trouble, could you please provide the following information:

- Date you first installed Bitkit.
- Device you first installed Bitkit on and experienced this issue with? (iOS/Android)

If comfortable providing the following information, please email me the following at corey@synonym.to:

-  Bitcoin Address funds were sent to.

One route we can try is to slightly modify and rebuild Bitkit at the problematic version number in an attempt to recover your funds from that point. I'm not confident this route will lead to the recovery of funds, but it will be worth trying if additional troubleshooting is unsuccessful.

**Comment by imacfan** [comment]
Hi Corey

Please see the details below. Let me know if you need any other information. thanks

> - Date you first installed Bitkit. - November 9th, 2022.
> - Device you first installed Bitkit on and experienced this issue with? (iOS/Android) - iOS (iPhone 14 pro)
> - Bitcoin Address funds were sent to. - address is bc1qwdOpirdv9wdlktmdzqdje0ctja2sqa9jz73khc (see screenshot for transaction details)

[IMG_E512CD7F883D-1.jpeg]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by imacfan** [comment]
> For those having trouble, could you please provide the following information:
> 
> 
> 
> - Date you first installed Bitkit.
> 
> - Device you first installed Bitkit on and experienced this issue with? (iOS/Android)
> 
> 
> 
> If comfortable providing the following information, please email me the following at corey@synonym.to:
> 
> 
> 
> -  Bitcoin Address funds were sent to.
> 
> 
> 
> One route we can try is to slightly modify and rebuild Bitkit at the problematic version number in an attempt to recover your funds from that point. I'm not confident this route will lead to the recovery of funds, but it will be worth trying if additional troubleshooting is unsuccessful.

Sent an email to you. Thanks

**Comment by nym1991** [comment]
Sent as well.

**Comment by imacfan** [comment]
Guys , please check the code of build which had the issue. 

Most probably some code or server side API was doing some funny business to steal the funds.

**Comment by imacfan** [comment]
Another update for devs. 

My original wallet is still generating addresses which doesn't belong to this wallet. 

I clicked receive and the address do not match addresses in advanced settings 

If I go ahead and receive any bitcoin on this address presented by app. Then it will become unrecoverable.

**Comment by coreyphillips** [comment]
The unfortunate news is that this seems to be further confirmation of the memory bug from earlier builds.
When tapping the "Receive" button the address that appears is returned from memory based on the current address index. The address viewer in advanced settings, however, is setup in such a way that it generates all addresses on the fly. This would explain why the addresses returned from the Receive view differ from the Address Viewer.

**Comment by imacfan** [comment]
> The unfortunate news is that this seems to be further confirmation of the memory bug from earlier builds.
> 
> When tapping the "Receive" button the address that appears is returned from memory based on the current address index. The address viewer in advanced settings, however, is setup in such a way that it generates all addresses on the fly. This would explain why the addresses returned from the Receive view differ from the Address Viewer.

So the question remains - is there a way to recover the fund or not? 

If address is being generated from memory then memory must have private key / seed to generate it. Anyway to recover the it?

**Comment by imacfan** [comment]
Further I do not understand how this is memory bug?

Could you please explain in detail?

I created the wallet - it generated some seed/recovery phrase. I noted them on paper. 

After taking backup of recovery phrase. I transferred bitcoin to receiving address. 

I was unable to send bitcoin. It is stuck there from that day. 

I still have the same seed/ recovery phrase on that original wallet. 

What made in that version to generate crazy addresses which are stored in memory till now? 

Can we reverse engineer by restoring into Same build etc ?

**Comment by coreyphillips** [comment]
> > The unfortunate news is that this seems to be further confirmation of the memory bug from earlier builds.
> > When tapping the "Receive" button the address that appears is returned from memory based on the current address index. The address viewer in advanced settings, however, is setup in such a way that it generates all addresses on the fly. This would explain why the addresses returned from the Receive view differ from the Address Viewer.
> 
> So the question remains - is there a way to recover the fund or not?
> 
> If address is being generated from memory then memory must have private key / seed to generate it. Anyway to recover the it?

Only the addresses are stored in memory. Not their private keys. If what I referenced above is the issue, then I'm not confident the funds are recoverable. However, I'm exploring other options/possibilities as well. Will keep this thread updated.

**Comment by imacfan** [comment]
That's interesting that only addresses were stored. 

what logic / code was generating these addresses which were unrelated to the seed/recovery phrase? 
That's the root , I guess. That piece code must be deriving these crazy addresses based off something. 

Sure , I'll wait for further updates from you. Thanks

**Comment by coreyphillips** [comment]
Bitkit automatically generates a set number of addresses (~5-25 per script type depending on the version) when initially creating the wallet. The memory bug being referenced can potentially come into play when a user either installs and uninstalls the app resulting in these initial addresses being saved, but are no longer associated with the new seed after reinstalling the app or, in your case, something may have happened during install that caused similar behavior to occur.

For those having this issue. If you're comfortable with the terminal, I created a library [here](https://github.com/coreyphillips/address-finder) that allows you to search for specific addresses associated with a given mnemonic by iterating over many possible, standard and non-standard address derivation paths. The difference between this and the address viewer in Bitkit is that this also generates addresses from non-standard derivation paths. It's unlikely that this is the cause, but it's worth exploring to eliminate as a possibility. If you would like to setup and run this test, but need help please let me know. I can be available anytime tomorrow (2/19) and Monday (2/20) EST to assist.

I believe the Electrum client also has a fairly in-depth recovery tool if you're more comfortable giving that a try. However, I'm not sure how well it iterates over various non-standard paths.

**Comment by imacfan** [comment]
> Bitkit automatically generates a set number of addresses (~5-25 per script type depending on the version) when initially creating the wallet. The memory bug being referenced can potentially come into play when a user either installs and uninstalls the app resulting in these initial addresses being saved, but are no longer associated with the new seed after reinstalling the app or, in your case, something may have happened during install that caused similar behavior to occur.
> 
> For those having this issue. If you're comfortable with the terminal, I created a library [here](https://github.com/coreyphillips/address-finder) that allows you to search for specific addresses associated with a given mnemonic by iterating over many possible, standard and non-standard address derivation paths. The difference between this and the address viewer in Bitkit is that this also generates addresses from non-standard derivation paths. It's unlikely that this is the cause, but it's worth exploring to eliminate as a possibility. If you would like to setup and run this test, but need help please let me know. I can be available anytime tomorrow (2/19) and Monday (2/20) EST to assist.
> 
> I believe the Electrum client also has a fairly in-depth recovery tool if you're more comfortable giving that a try. However, I'm not sure how well it iterates over various non-standard paths.

Hey Corey, I ran the script. Addresses generated by "Receive" button are **not** found using the seed phrase. Addresses available in Address viewer match perfectly. So , we can rule out the possibility of addresses being generated from some other derivation path of this seed

**Comment by nym1991** [comment]
All coins received to addresses before the january 13th update is unspendable. One address that received after january 13th update is spendable.

**Comment by imacfan** [comment]
> All coins received to addresses before the january 13th update is unspendable. One address that received after january 13th update is spendable. 

For me all address are unspendable. 
Receive button is generating un-spendable addresses.

**Comment by JeanlChristophe** [comment]
Corey sent you an email but got no response. Can you take a look at it? @imacfan

**Comment by imacfan** [comment]
> Corey sent you an email but got no response. Can you take a look at it? @imacfan 

Just replied

**Comment by nym1991** [comment]
No updates for about a month. Tell me if you gonna reimburse the sum I lost because of your faulty wallet or not.

**Comment by BitcoinErrorLog** [comment]
We had to consult with legal to ensure our response does not conflict with our ToS. We will provide a formal response this month.

**Comment by BitcoinErrorLog** [comment]
Thank you for your patience whilst we investigated this matter. As noted in our terms of service (available at [https://bitkit.to/terms-of-use](https://bitkit.to/terms-of-use)), the Bitkit wallet software is still in its Beta testing phase and a primary purpose of this Beta testing phase is to obtain feedback on performance and the identification of defects – we appreciate the time taken to test the Bitkit wallet.

Having reviewed the information available to us, we believe this issue was caused by an initial version of the Bitkit wallet software being downloaded onto an iOS device, recovery phrases being produced, and the software subsequently being deleted and reinstalled. This appears to have caused the device to cache the previous receiving addresses, rather than those produced by the new seed in the reinstalled software.

We expect that funds would be recoverable by restoring the software with the original recovery phrases, rather than those produced by the reinstalled application. Please note that, in line with our terms of service, we do not store users’ recovery phrases and we cannot recover these for you. As noted in our terms, it is important that you record recovery phases and maintain these securely.

We believe that this scenario has been fixed in newer versions of Bitkit. In addition, we have added new features to seek to detect caching errors and, where possible, prevent these. We invite you to continue to test the Bitkit wallet software and, if you are able to reproduce this scenario, we would appreciate you opening a new support ticket or Github issue. We consider this support ticket closed.

**Comment by imacfan** [comment]
Hey , I am able to reproduce the issue even on latest version. 

What should I do ? Open another ticket for the same issue?

**Comment by imacfan** [comment]
It is very frustrating that great minds (working on bitcoin wallet) can't even understand this issue till date. 
Even after sharing screenshots and multiple emails , provided no resolution. 

Issue EXISTS on latest version ... I can not send the funds on your latest version when balance is still visible. 

Do you understand this??

**Comment by BitcoinErrorLog** [comment]
First, please wait for the next release, I made this post a little too early because I thought it was public already. It should be out today I think.

Second, please understand that reproducing the problem and you having lost bitcoin to the problem are not the same thing. If you can install a new instance of Bitkit, and show that it holds deposit addresses for a seed it does not have, that would be reproducing the problem.

**Comment by imacfan** [comment]
> First, please wait for the next release, I made this post a little too early because I thought it was public already. It should be out today I think.
> 
> 
> 
> Second, please understand that reproducing the problem and you having lost bitcoin to the problem are not the same thing. If you can install a new instance of Bitkit, and show that it holds deposit addresses for a seed it does not have, that would be reproducing the problem.

What does next release do? Resolve issue or clear cache so that there is no trace of issue remains ? 

What's the users fault in all this mess?

**Comment by BitcoinErrorLog** [comment]
This release look for address mismatches in the cache compared to the active seed and clears them and replaces them with valid addresses. It similarly checks the history for mismatches.

Bitkit cannot generate addresses for seeds it does not have loaded and backup-able. So the only way to restore badly-cached addresses would be from the original seed that generated them. This means you would have had to have made sure you backed up the seed of any previous install of Bitkit.

**Comment by nym1991** [comment]
Thats not what happened. Same seed phrase on first and every install after.

**Comment by imacfan** [comment]
> This release look for address mismatches in the cache compared to the active seed and clears them and replaces them with valid addresses. It similarly checks the history for mismatches.
> 
> 
> 
> Bitkit cannot generate addresses for seeds it does not have loaded and backup-able. So the only way to restore badly-cached addresses would be from the original seed that generated them. This means you would have had to have made sure you backed up the seed of any previous install of Bitkit.

Come on.. we are back to square one. 

It's the same seed phrase. 

I would not even bother otherwise...

**Comment by BitcoinErrorLog** [comment]
We cannot reproduce such a claim, and it is technically impossible for Bitkit to have produced or used two different seeds within the same installation as far as we know. If you can reproduce such an outcome using the current version, we would love to know the steps to reproduce.

**Comment by imacfan** [comment]
> We cannot reproduce such a claim, and it is technically impossible for Bitkit to have produced or used two different seeds within the same installation as far as we know. If you can reproduce such an outcome using the current version, we would love to know the steps to reproduce.

Your current version is still reproducing bogus addresses on my phone. 

Even today , if I receive any bitcoin at receive addresses produced by your app ... it's lost forever... 

Is this is a serious bug or not? 

Any blind person would see the app would laugh at your defences ...

Anyway .. it's small amount. But I see you guys.What a disappointment

**Comment by BitcoinErrorLog** [comment]
Are you willing to do a live video call where we verify your OS, testflight, version, send a test payment, then try to spend that output?

**Comment by nym1991** [comment]
Im out. 2.5 million sats sacrificed to Satoshi. Will not use more time on this project. Good luck, hope its sorted so no more people lose their funds because of wallet disfunction.

**Comment by imacfan** [comment]
> Are you willing to do a live video call where we verify your OS, testflight, version, send a test payment, then try to spend that output?

Sure ... I can do that. Send me the call details. Thanks

**Comment by imacfan** [comment]
Yes , sure .. I can do it.
