### ISSUE TITLE
[Feature]: User defined relay

### ISSUE THREAD

**Issue by vforvilela** [synonymdev/bitkit-react-native#834]
### Describe the problem

Bitkit's Slashtags functionality fully relies on the `dht-relay.synonym.to` relay, creating a central point of failure and reducing privacy.

### Describe the solution

Replace the [hardcoded relay](https://github.com/synonymdev/bitkit/blob/4bf43d97e3b703444cbec55b14e1136c08b8bcea/src/components/SlashtagsProvider.tsx#L88) with an configurable option, keeping `dht-relay.synonym.to` as default.

**Comment by JWBurgers** [comment]
This is on the roadmap. You will be able to bootstrap from your own relays eventually.

**Comment by BitcoinErrorLog** [comment]
Just some clarification:  we haven't actually discussed the ability to choose your own dht, as this raises some considerations. I defer to @Nazeh on how much hard-coding our relay actually effects privacy, and whether it would be dangerous to allow any relay to be set. 

What we have discussed is giving the user a way to designate a custom *seeding server* and *backup server*, which is on our roadmap.

I am open to also having a DHT setting, but we need to discuss the actual utility and complications of this, as we haven't really, afaik.

**Comment by Nuhvi** [comment]
As we move to the custom runtime, we shouldn't need a relay at all (just use the DHT natively), but if we decided to keep using the `dht-relay` for better privacy, we can make that optional, or if Hyperswarm implemented better more stable solutions for p2p-vpn, then we can add optionality for that too.

In the meantime, I think we should focus on moving to the runtime first.

**Comment by pwltr** [comment]
Closed by https://github.com/synonymdev/bitkit/pull/1276
