### ISSUE TITLE
[Feature]: stop showing qr/address after payment notification received 

### ISSUE THREAD

**Issue by dzdidi** [synonymdev/bitkit-react-native#853]
### Describe the problem

1. Select "receive" from the main screen, the app will show QR code with address;
2. Pay to this address.
3. Within a minute incoming transaction will be recognized and app will pop a persisted notification about incoming payment;
4. Slide to remove notification from the screen (maybe it goes await itself and I was not patient enough);
5. The app now shows the same address which just received payment. 

### Describe the solution

I think that address should not be shown anymore after there was a recognized payment to it (at least by default), as it has potential privacy implications.

### Additional context

Bitkit: 1.0(30)
Phone: Pixel 5
OS: Calyx 4.5.1 (Android 13)

**Comment by pwltr** [comment]
A fix for this has been included somewhere in https://github.com/synonymdev/bitkit/pull/802. Will be included in the next release :)
