### ISSUE TITLE
[Bug]: Text parser showing 0 as amount in LN invoice payment attempts

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#872]
### Describe the bug

If I scan a QR code of a LN invoice, it shows the correct amount and I can attempt to pay it.

If I paste in a text version of the same invoice instead, it shows the amount as zero (amount is also not editable).

### Operating system

iOS

### Bitkit version

33

**Comment by pwltr** [comment]
I'm not able to reproduce this one. Could you do a retest or provide more detail?

https://user-images.githubusercontent.com/8538369/217229939-8b289ab4-d903-4ebb-90e8-385443b96387.mp4

**Comment by BitcoinErrorLog** [comment]
Try generating an invoice from Wallet of Satoshi, that is where Reza was providing the ones that gave me trouble.
