### ISSUE TITLE
[Bug]: LDK node extremely sensitive/unavailable

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#873]
### Describe the bug

LDK seems to close immediately when minimizing Bitkit, and seems to also disconnect sometimes while it is open. 

It also takes a noticeable amount of time to spin up after returning to, or opening, the app. 

I do not know if this can be improved, but it begs for two UX needs if not:

- An indicator and or interstitial frame for LN features that lets the user know when LDK is available/connecting/disconnected
- Support for Jay's waking method for receiving sooner than later...

### Operating system

iOS

### Bitkit version

33

**Comment by Jasonvdb** [comment]
This should be improved significantly since [this PR](https://github.com/synonymdev/react-native-ldk/pull/109). Instead of restarting all LDK services it just restarts what's needed to reset the TCP peer handler which only takes a fraction of a second.

**Comment by coreyphillips** [comment]
@BitcoinErrorLog, have you noticed an improvement as of [v1.0.0-beta46](https://github.com/synonymdev/bitkit/releases/tag/v1.0.0-beta46)?

**Comment by BitcoinErrorLog** [comment]
I will take your word for it and re-open this if it pops up again. Havent had a chance to test it...
