### ISSUE TITLE
[Bug]: App crashes on editing widget

### ISSUE THREAD

**Issue by Nuhvi** [synonymdev/bitkit-react-native#919]
### Describe the bug

Something is going wrong with _at least_ price widget

### Reproduce

1. Go to home screen
2. Add price widget
3. click on gear icon
4. do some edits
5. go back to home screen
6. click gear icon again, it will crash

### Operating system

Android

### Bitkit version

1.0.0-beta.36

**Comment by Nuhvi** [comment]
This seems to be an issue with corestore not being able to open closed drives, which is something that only happens in Bitkit, and was previously solved in a hacky way.

Something was updated and the problem appeared again.

I need to accelerate the runtime efforts, or keep hacking on this in the meantime.

**Comment by BitcoinErrorLog** [comment]
I doubt we can get the runtime in this month. afaik Reza is still prepping it. We still have other notable bugs to fix, and Corey is doing a full RN upgrade. I assume adding the runtime on top of all this would be unwise...
