### ISSUE TITLE
[Bug]: Wiping wallet freezes app

### ISSUE THREAD

**Issue by SeverinAlexB** [synonymdev/bitkit-react-native#937]
### Describe the bug

After clicking `Reset and restore wallet` and confirming `Yes, Reset`, the app freezes. I need to kill the app to continue. The wallet is wiped.

### Reproduce

1. Go to `Settings`, `Back Up Or Restore`, `Reset and restore wallet`.
2. Click on `Yes, Reset`.
3. App freezes.

### Screenshots / Recording

![IMG_1241](https://user-images.githubusercontent.com/8782386/225851812-ebcc76ff-b908-44b7-8773-7fbdbcbc77f4.png)

### Operating system

iOS 16.1.1

### Bitkit version

Build 37

**Comment by JeanlChristophe** [comment]
Reopen the ticket because we can find a bug sometimes.

**Comment by pwltr** [comment]
Issue is likely caused by `RNFS.unlink()`, see https://github.com/itinance/react-native-fs/issues/1174

**Comment by JeanlChristophe** [comment]
Thanks
