### ISSUE TITLE
[Bug]: Change contact information

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#939]
### Describe the bug

When a contact changes information, it changes directly for him. But this is not necessarily visible to other contacts who see his profile:
- the photos are modified directly 
- links are modified directly
- photos are not modified

### Operating system

Graphene OS

### Bitkit version

v37

**Comment by pwltr** [comment]
Closing in favor of https://github.com/synonymdev/bitkit/issues/951
