### ISSUE TITLE
[Bug]: Activity doesnt add up to balance (fees excluded)

### ISSUE THREAD

**Issue by SeverinAlexB** [synonymdev/bitkit-react-native#940]
### Describe the bug

JC had a balance of 44k sats. When he send 10k sat to me, he only had 26,280sats left. When adding up the activities, he should have 34k sat left. This is confusing.

Turns out, the transaction fee is not included in the activity list. So adding them up doesn't result in the final balance. This is kind of a UX bug as we 3 testers (JC,  Pav, and I) got fooled into thinking there is a bug.

Suggestion: Make the UX more clear. Phoenix makes it better IMO.

### Reproduce

1. Send an onchain transaction in a high fee environment.

### Screenshots / Recording

![image](https://user-images.githubusercontent.com/8782386/225879502-2444a18e-7dae-47c7-b293-def44c242951.png)
![image](https://user-images.githubusercontent.com/8782386/225879540-f4d6bd76-1768-4fda-8926-38582953e4a5.png)
![image](https://user-images.githubusercontent.com/8782386/225879650-4822ebeb-dffe-49e1-a357-10f55cb8d2f4.png)

## Phoenix example
![image](https://user-images.githubusercontent.com/8782386/225879749-55d5d9ac-fd2c-40d3-a846-1a5bd3b8fbb4.png)
![image](https://user-images.githubusercontent.com/8782386/225879775-2770c23a-e0d8-4ca5-93f4-fa8540caf493.png)

### Operating system

iOS 16

### Bitkit version

Build 37

**Comment by JeanlChristophe** [comment]
This is an UX improvement. We will soon speak about it with the team. I am closing the ticket.
