### ISSUE TITLE
[Bug]: LNURL Withdrawal not working

### ISSUE THREAD

**Issue by SeverinAlexB** [synonymdev/bitkit-react-native#942]
### Describe the bug

I tried LNURL withdrawal on lnpay.co. After scanning the QR code, Bitkit showed success. The funds never arrived though. I had enough channel capacity. I hope this is not a lnpay issue.

### Reproduce

1. Scan LNURL Withdrawal QR code

### Screenshots / Recording

![IMG_1256](https://user-images.githubusercontent.com/8782386/225922680-23f0372e-e6e0-40cf-b913-7e88b2fabd02.png)

### Operating system

iOS

### Bitkit version

Build 37

**Comment by SeverinAlexB** [comment]
@JeanlChristophe

**Comment by coreyphillips** [comment]
Lets retest this once we upgrade to LDK v114.

Currently Bitkit can only receive < 10% the highest channel capacity in a single lightning invoice. So it's possible the withdraw request exceeded 10% and the lnpay node couldn't find a path as a result.

**Comment by BitcoinErrorLog** [comment]
In v114 is the limit no longer enforced? What can we do to ensure users can send/rec any amount within the available capacity (less 1% reserve or such)

**Comment by coreyphillips** [comment]
It's to do with the node's settings. Specifically `max_inbound_htlc_value_in_flight_percent_of_channel` in `ChannelHandshakeConfig` [here](https://docs.rs/lightning/latest/lightning/util/config/struct.ChannelHandshakeConfig.html#structfield.max_inbound_htlc_value_in_flight_percent_of_channel). You can see that the default value is set to `10` when it should be `100`.

We adjusted this config option in react-native-ldk [here](https://github.com/synonymdev/react-native-ldk/pull/108) and updated Bitkit accordingly, but this node setting won't take properly until v114 of LDK.

**Comment by JeanlChristophe** [comment]
Even with the v114 of LDK we still have the same issue https://github.com/synonymdev/bitkit/issues/972

**Comment by pwltr** [comment]
I was able to withdraw ~120 000 sats from LNMarkets using LNURL with a receiving capacity of ~1 000 000. If payments fail it should be due to routing and not LNURL in Bitkit so I think we can close here.

**Comment by limpbrains** [comment]
Can't withdraw 2000 sats from LNMarkets, will try to debug it

**Comment by pwltr** [comment]
It shows the max amount but not the minimum amount. Can we show something if it is below the minium amount?

![Screenshot_20230804-143106](https://github.com/synonymdev/bitkit/assets/8538369/270af892-db67-4042-80b4-a579d8b8d0c1)

**Comment by pwltr** [comment]
On LNMarkets withdraw doesn't work for me. Maybe issue on their side.

![Screenshot_20230804-143542](https://github.com/synonymdev/bitkit/assets/8538369/87dfd3c8-5c5f-4439-916c-224f027b62c8)

**Comment by pwltr** [comment]
Example how it looks in Phoenix:

![Screenshot_20230804-143951](https://github.com/synonymdev/bitkit/assets/8538369/7e87c635-53f3-4d9e-ac16-0b4d3661a4e9)

**Comment by limpbrains** [comment]
> It shows the max amount but not the minimum amount. Can we show something if it is below the minium amount?

We discussed this with @aldertnl and decided that default value is set to minimum and if user enters less that it, continue button should be inactive
