### ISSUE TITLE
[Bug]: LN Backups

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#944]
### Describe the bug

After going through the mainnet, lightning, and contact payments, as well as profile and contacts sections we deleted the application.

Every single time we attemp to open the app - the app crashes but it didn't crashed when you only used onchain (without LN)

You can ask the testing seed to Sev.

It crashed with two iOS but I LN didn't worked at all with a GrapheneOS. So I couldn't do the backup stage.

### Reproduce

1. Go to 'Back up or restore
2. Click on 'Reset and restore you wallet'
3. Re open the app and enter your seed

### Operating system

iOS

### Bitkit version

v37

**Comment by limpbrains** [comment]
It crashed for me too, when I'm trying to restore wallet on build from the Testflight. But it doesn't if I'm trying building app from master. Both dev and production builds. I think it is releated to LDK, but I'm not sure.
I suggest assign it back to @Jasonvdb, he has better understanding how to debug native code
