### ISSUE TITLE
[Bug]: Bitkit widget playground auth

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#945]
### Describe the bug

I connected to the Playground by scanning the QR code and it works. 

The widget appears on my Bitkit mobile application (iOS and Graphene OS)
However when we  trying to login from BK is where we end up with a 404 error 

### Reproduce

1. Go to '(https://slashtags.to/playground/accounts)'
2. Scann the QR Code
3 Click on 'Sign' from the Bitkit widget 
<img width="323" alt="Capture d’écran 2023-03-17 à 16 08 02" src="https://user-images.githubusercontent.com/46056211/225944109-306d4626-7fca-4d35-a1bd-37bfd3fb48ba.png">

### Operating system

iOS et Graphene OS

### Bitkit version

v37

**Comment by MiguelMedeiros** [comment]
Hey @JeanlChristophe 
I've tested this issue and found the cause.

After you click on the `sign in` button in the bitkit widgets session, the app redirects you to the playground website.
But to the wrong URL, example:
https://www.synonym.to/products/slashtags/playground/accounts?user=r99915xj9c7m11z4xeap3n4oepkur8upwptsdxpohrz9zbre1fzy

The right URL should be something like:
https://slashtags.to/playground/accounts?user=r99915xj9c7m11z4xeap3n4oepkur8upwptsdxpohrz9zbre1fzy

@Nazeh should I re-assign this issue to you?

**Comment by JeanlChristophe** [comment]
@Nuhvi

**Comment by Nuhvi** [comment]
@JeanlChristophe already fixed https://github.com/synonymdev/slashtags-playground-auth-demo/pull/3 @rbndg can you merge and deploy it?

**Comment by JeanlChristophe** [comment]
Thanks, I am cling the ticket
