### ISSUE TITLE
[Bug]: Profiles can't sync with seeder after restoring wallet (potential hypercore forks)

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#951]
### Describe the bug

For some reason bitkit can't push certain profile to seeder. We need to debug why

### Reproduce

1. restore wallet with seed starting with `escape filter estate`
2. wallet should create slashtags `slash:gskitcr5dosftdgiu17qkfb61sghaqfj3zzoa5e4ktadw83n4ksy`
3. edit the profile
4. check if data is saved to seeder
5. wipe the wallet, restore from seed. Profile is empty again

### Operating system

iOS

### Bitkit version

latest master

**Comment by JeanlChristophe** [comment]
Related to issue [#939](https://github.com/synonymdev/bitkit/issues/939)

**Comment by Nuhvi** [comment]
I am working on a fundamental solution to all of this, so I will visit this issue after a week from now

**Comment by JeanlChristophe** [comment]
Hi @Nuhvi , can you make an update about this issue? Thanks

**Comment by Nuhvi** [comment]
@JeanlChristophe Yes, but I think I have a presentation about it (among other challenges) tomorrow where I suggest a few solutions. But I can't ship anything to Bitkit unilaterally, needs internal discussions first.

**Comment by JeanlChristophe** [comment]
Closing this issue, duplicated https://github.com/synonymdev/bitkit/issues/1063
