### ISSUE TITLE
[Bug]: Profil and Contact backup

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#969]
### Describe the bug

On 3 testers: 2 worked (Iphone/GrapheneOS), 1 didn't (Android)

Can I wipe the wallet and restore to retrieve my contacts?

I Cannot see picture and name on home screen, even after restarting; clicking on profile, I go through the setup, but no previous profile exists; no contacts either

You can find the seed on the Bitkit testing framework

### Reproduce

1. Reset wallet
2. Restart the application
3. Backup wallet

### Operating system

Android

### Bitkit version

v39

**Comment by JeanlChristophe** [comment]
Fiex

**Comment by JeanlChristophe** [comment]
It worked for two testers but there were bugs with Jan's phone. Can you check with his seed what the problem is? At first he downloaded a old v32 version, maybe that's where the issue came from.

**Comment by Nuhvi** [comment]
@JeanlChristophe I don't have access to the seeder.

**Comment by JeanlChristophe** [comment]
Hi @Nuhvi, some update.

**Describe the bug**

Can I wipe the wallet and restore to retrieve my contacts? yes

Is the data updated for your contacts: Yes excepted the profil name. Picture profil, bio and links changed

Operating system
Android

Bitkit version
v44

**What i see**
<img width="324" alt="Capture d’écran 2023-05-05 à 09 51 06" src="https://user-images.githubusercontent.com/46056211/236404094-66c7bc54-229a-446e-85e1-be23956cfe5a.png">



**What my contact see**
![photo_2023-05-05_10-46-38](https://user-images.githubusercontent.com/46056211/236404023-56728241-b8f9-4d56-a209-628bcc35e33d.jpg)

**Comment by JeanlChristophe** [comment]
Not a bug, a feature
