### ISSUE TITLE
[Bug]: Slashplay can't pay over LN

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#971]
### Describe the bug

Can I send an amount of money with LN to the contact successfully?

No I can't. We tried with 5,10,10 1000 sats but it doesn't work.

I have an error "Unfortunately contact could not be paid instantly. You can try a regular payment (more expensive, slower).

### Reproduce

1. Go to 'contacts'
2. Select one contact
3. Select pay
4. Select an amount and confirm
5. See error

### Screenshots / Recording

<img width="329" alt="Capture d’écran 2023-04-14 à 15 39 04" src="https://user-images.githubusercontent.com/46056211/232059796-9a1caf98-1e76-4382-85ad-2a3ffe998747.png">

### Operating system

Graphene OS

### Bitkit version

v39

**Comment by Nuhvi** [comment]
@JeanlChristophe Is this a bug? this is expected to happen if the invoice in the user's `slashpay.json` was consumed, and the app wasn't online to update it.

**Comment by Jasonvdb** [comment]
Apps were both online the whole time and it never worked the first time so I don't think the slashpay.json was ever consumed

**Comment by Nuhvi** [comment]
Can you give me the contact's URL?

**Comment by Nuhvi** [comment]
@JeanlChristophe I need to examine the contact to confirm Bitkit is adding invoices in the first place, can you share these contacts you tried to pay?

Here is an example of how you can do the same on your own for future reference:

https://user-images.githubusercontent.com/40009100/232450720-609aa90a-bee5-4c7a-8bd8-085d9e572930.mov

**Comment by JeanlChristophe** [comment]
slash:n49ozyf67rjicjbi1131qahibhygaeozhzmcchtm71uutzmox5wy

slash:idpr8mazg95rmi9hi166zoizkrbjhjj6w3jdp47y7dprwsfh4hbo

**Comment by Nuhvi** [comment]
In here https://github.com/synonymdev/bitkit/blob/master/src/utils/scanner.ts#L457 

I can resolve the `payConfig` for `slash:n49ozyf67rjicjbi1131qahibhygaeozhzmcchtm71uutzmox5wy` to
```json
 [{"type": "p2wpkh", "value": "bc1qke4s0nxtzflph4u4cwe7q2zgdu33kfn3ldyf6s"}, {"type": "lightningInvoice", "value": "lnbc1pjrj3v8dqqnp4q0w5kpp7zud7elwfzead7urh2m58dph5sq9zcswyj2r2847qsld4gpp58n7vqcj2am0f26ervw3950ax7pwruedf2z52m3sec4mncgayfchssp53rpusxrrx4h898v832hxkpp7an8qvgmt6dvgrgjwkn68egvl4a8s9qyysgqcqpcxqyjw5qjhjxynk0vm9n0appnnxygzm69ez4jjdel6rajhqw5cdtwcaqfn2qc8p6q8ctsr6ywduaqn7a2nrfmynw37pd7khwnqwmajtfd6ajncsqs7w5p7"}]
```

**Comment by aldertnl** [comment]
What is the current state of this issue? Could it be that the error lives on the side of Bitkit by defaulting to on-chain, even when there is a LN payment negotiation match?

**Comment by Nuhvi** [comment]
@aldertnl My assessment is that all the contacts where Slashpay reportedly didn't work, are also not resolvable at all, so probably the have been forked while restoring the wallet.

If that is the case, which I believe it is, then this is more of an issue about how to solve Hyperdrive multi-writing.

Otherwise resolvable hyperdrives, return slashpay.json configuration fine, and I haven't got a report that they can't be paid on LN.

**Comment by aldertnl** [comment]
Just tested this on the Slashtags playground with my profile:
- Bitkit open with an active LN channel
- Playground does not push a LN QR for my profile, only on-chain

**Comment by Nuhvi** [comment]
If you mean that the playground only shows an on chain, then that is
expected, the playground was hard-coded to take the onchain address, as LN
wasn't working yet. But if you open the console, you should the entire
slashpay printed, and hopefully you will see a Lightning invoice, as I have
seen examining Jay's Slashtag.

**Comment by BitcoinErrorLog** [comment]
Can you update the Playground to include the multi-QR?

**Comment by Nuhvi** [comment]
Sure.
