### ISSUE TITLE
[Bug]: Lnurl-withdraw success message but never receives

### ISSUE THREAD

**Issue by Jasonvdb** [synonymdev/bitkit-react-native#972]
### Describe the bug

Scanning a LN Markets lnurl-withdraw QR gives a success toast message on Bitkit but the withdraw never happens

### Reproduce

1. Go to Lnmarkets, tap withdraw
2. Scan with Bitkit

### Screenshots / Recording

![IMG_32BE2E20AECF-1](https://user-images.githubusercontent.com/5300488/232064900-27e7fed2-4a5b-48c4-91b0-a3ccb773c6e5.jpeg)

### Operating system

iOS 16

### Bitkit version

v.0.0.1 (39)

**Comment by pwltr** [comment]
Duplicate: https://github.com/synonymdev/bitkit/issues/942
