### ISSUE TITLE
[Bug]: Incorrect spending balance

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#987]
### Describe the bug

Timeline:

1. I created a new wallet on a new device where Bitkit has never been previously installed.

2. I requested a channel through the Blocktank Widget because I wanted to have a channel before depositing on-chain on Bitkit. I claimed it with LNURL.
Order ID: 6441a2f5b36969f4a88242a2
Channel ID: 2ee3b28e16005b4db7956ea346805fbeb1c269c3691765d45c32c0c39a6af899
Local balance: 0
Remote balance: 1,000,000
Funding transaction: ?

3. While the channel from the widget was being opened, I deposited 7,701 sats on-chain to be able to request a channel through Bitkit.
On-chain deposit: https://mempool.space/tx/ae117a9ef08bca234cc6c8aba3f6a02ee806d9826cf862463cb4ee0d021460ae

4. I requested a channel through Bitkit.
Channel payment: https://mempool.space/tx/06ed5a3bb6ea86f614e66f9e2b9aca96e17d9fb6f8718eabe4d1a8e79ca0f0bc
Order ID: 6441a55fb369694a88242a7
Channel ID: c80a751f80130cd269abc66bc0d14d67017049ac4f48eaf778f505e322741ade
Local balance: 0
Remote balance: 1,769,348 ($500)
Funding transaction: https://mempool.space/tx/de1a7422e305f578f7ea484fac497001674dd1c06bc6ab69d20c13801f750ac8

5. I successfully received 997 sats through the 'c80' channel and then 1,000 more through the '2ee' channel.

6. A spending balance of 25,696 appeared out of nowhere. My total balance (21,907) became the difference between my alleged spending (25,696) and my savings balance (3,789).

7. I checked other screens. The quick setup screen shows the correct spending balance (1,997). The Lightning Connections screen shows 0 spending balance on both channels.

8. I started recording, link below. Every time I receive Lightning payments, my spending balance reduces rather than increases, as if my spending balance was negative. I can't spend any of the sats I've received (which might be because it's building up the channel reserve or something, but still, the toast message doesn't make it clear). When I tried to pay a 10,000 sats invoice from Breez, it said I needed 35,696 more sats. To pay 1,000, 26,696 more (even though I already had 1,997 sats in my real spending balance). I later tried smaller invoices, and the pattern repeated, I couldn't pay any of them, no matter how small they were.

9. In the end, after receiving a total of 5,097 sats, I ended up with a "fake" spending balance of 18,807.

### Screenshots / Recording

Recording: [Google Drive](https://drive.google.com/file/d/1ZAnx_-CYpPWFLNa33a6en8Xb70xtp191/view?usp=sharing)
Logs:
[bitkit_ldk_logs_1682036031257.zip](https://github.com/synonymdev/bitkit/files/11291450/bitkit_ldk_logs_1682036031257.zip)

### Operating system

iOS 16.5

### Bitkit version

43

**Comment by rbndg** [comment]
thanks we will look into it
