### ISSUE TITLE
[Bug]: Can't transfer from spending to saving balance

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#991]
### Describe the bug

The user can't transfer from spending to saving balance. He could transfer from savings to spending, but not the other way around. The recording below shows that the spending and saving balance are displayed as "NaN%". He had an ongoing transfer when he recorded the video, but the bug persisted after the transfer was finalized.

Original messages available on Telegram: https://t.me/bitkitchat/985.

### Screenshots / Recording

https://user-images.githubusercontent.com/93796166/233682325-ab80c7de-0a77-403e-b4af-2517e4858fd1.mp4

### Operating system

Xiaomi Redmi 10, Android 12 build SP1A.210812.016

### Bitkit version

43

**Comment by limpbrains** [comment]
fixed at  #1035
